### ISSUE TITLE
gradle project sync failed

### ISSUE THREAD

**Issue by hananabilabd** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#432]
I have done exactly like what you told 

1-Create a new project in Android Studio.
2-Create the jni folder inside the project's folder: app/src/main/jni
3-Copy the contents of the following files from one of the example projects: gradle/wrapper/gradle-wrapper.properties, build.gradle, app/build.gradle, app/src/main/jni/CMakeLists.txt
4-Open build.gradle (Module: app), and change the applicationId

but every time it gives me  error regarding CMake Error at CMakeLists.txt:11 (add_library):
![capture](https://user-images.githubusercontent.com/26032494/36096912-0d9a867c-1001-11e8-9e02-a1b955640f68.PNG)

**Comment by superpoweredSDK** [comment]
Check where it says "syntax error". The path there looks wrong.

Please note, this support is for the Superpowered library, not for generic Android build questions.

**Comment by hananabilabd** [comment]
For God sake Please give us more any explanation I've uninstall and re-install all the android studio ,,, 
U have changed somethings in the Build.gradle and the CMakeList in the last version so  provide us with what to change exactly in those files 
Thanks in advance

**Comment by superpoweredSDK** [comment]
"Check where it says "syntax error". The path there looks wrong."

Check the text on the picture. Find the line with "syntax error". Check the path there. It is wrong. Somewhere you set a wrong path.

**Comment by paschoaletto** [comment]
Had same issue, fixed path, claims "Error:error: linker command failed with exit code 1 (use -v to see invocation)"

Followed exactly like on Readme file. couldn't make any example work, neither a new project. Time to review the instructions for Android Studio 3.0 with newer versions of SDK and NDK?

**Comment by superpoweredSDK** [comment]
The instructions remain the same. See what your build log says, i'm sure it says more than just "linker command failed".

**Comment by hananabilabd** [comment]
Pascha. 
it is resolved with me when i changed the path in CmakeList file
