### ISSUE TITLE
use of digital filters in frequency domain example

### ISSUE THREAD

**Issue by hananabilabd** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#433]
Can i use digital filters in the frequency_domain example exactly in
 (new SuperpoweredAndroidAudioIO(samplerate, buffersize, true,,,,, ); )
so use digital band-pass filter then output the result to the speaker ,, and how to make that ?
Thanks in advance

**Comment by superpoweredSDK** [comment]
If you mean running a filter in the time domain, then i recommend to check out Examples_Windows/SuperpoweredEffect.

Please use GitHub Issues to report serious issues (such as bugs) of Superpowered. We'd like to keep this page for those, not for generic audio programming advice.
