### ISSUE TITLE
Unable to play External Audio Files.

### ISSUE THREAD

**Issue by deepakrokz** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#434]
Hi @superpoweredSDK 
I am struggling with playing an audio file from an external directory using this library. Can you help me with this, because attaching multiple files in a raw folder(Resource directory) of the app will make app size very big. I am trying to play like this: 

`char *musicPath = "/storage/emulated/0/98863862.wav";
player->open(path, musicOffset, musicLength);
player->syncMode = SuperpoweredAdvancedAudioPlayerSyncMode_None;`

**Comment by superpoweredSDK** [comment]
Hi, perhaps "/storage/emulated/0/98863862.wav" is not a valid full file system path or you forget to add the permissions in your app manifest xml?

**Comment by deepakrokz** [comment]
it's right, and I have given permission to read external storage in the app

**Comment by deepakrokz** [comment]
Really thanks for your quick response @superpoweredSDK , It will be very helpful if you can check this at your end. Thanks!

**Comment by superpoweredSDK** [comment]
There is nothing we need to check. The player opens and plays those files it can access via a valid path and valid permissions.
Try to do a simple fopen on that path and see if it works.

**Comment by deepakrokz** [comment]
Let me try.

**Comment by deepakrokz** [comment]
Hi @superpoweredSDK again, 

I tried as you said, this is the code : 
`int i=0;
    char caracteres[100];

    FILE *archivo;
    archivo = fopen("/storage/emulated/0/98863862.wav","r");
    if (archivo == NULL){
        __android_log_print(ANDROID_LOG_ERROR, "SuperpoweredExample", "Dont Work");
    }
    while (feof(archivo) == 0)
    {
        fgets(caracteres,100,archivo);
        i++;
    }
    __android_log_print(ANDROID_LOG_ERROR, "SuperpoweredExample", "Number of lines: %d" , i) ;`

and the output is `SuperpoweredExample: Number of lines: 849490`

**Comment by superpoweredSDK** [comment]
That is great, then check the player callback, what events you get when you try to open that path with Superpowered?

**Comment by deepakrokz** [comment]
In this callback of player 
`playerEventCallback(void *clientData, SuperpoweredAdvancedAudioPlayerEvent event, void *value) {
    if (event == SuperpoweredAdvancedAudioPlayerEvent_LoadSuccess) {
        SuperpoweredAdvancedAudioPlayer *player = *((SuperpoweredAdvancedAudioPlayer **) clientData);
        player->setBpm(126.0f);
        player->setFirstBeatMs(353);
        player->setPosition(player->firstBeatMs, false, false);
    };
}`

SuperpoweredAdvancedAudioPlayerEvent_LoadSuccess is returning false.

**Comment by superpoweredSDK** [comment]
There is no such thing as "SuperpoweredAdvancedAudioPlayerEvent_LoadSuccess is returning false". If the load success event is called, then loading was successful.

**Comment by deepakrokz** [comment]
It's event type in SuperpoweredAdvancedAudioPlayer

**Comment by deepakrokz** [comment]
When I tried playercallback without event check this is what I am getting:

> Fatal signal 11 (SIGSEGV), code 1, fault addr 0x63638ee9 in tid 4688 (AudioFile Read)[ 02-13 17:33:15.685   289:  289 W/         ]debuggerd: handling request: pid=4668 uid=10198 gid=10198 tid=4688

 application crashes on this.

**Comment by superpoweredSDK** [comment]
I can't help you with generic C++ programming issues, sorry.
