### ISSUE TITLE
How to pause audio recording?

### ISSUE THREAD

**Issue by deepakrokz** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#435]
Hi @superpoweredSDK @theyonibomber 
I am unable to pause the audio recoding, as there is no function available to pause the recording. SuperpoweredRecorder only contain start() and stop() functions available. Can you guys help me in this?

I also have another question to hear back instance mic input with effects, currently I am able to hear only voice without any effect. Please help me.

Thanks in advance!

**Comment by superpoweredSDK** [comment]
Pause recording: just don't submit any audio samples to the recorder, meaning don't call recorder->process()

Regarding the other question, check out the SuperpoweredEffects example project in the Windows folder. It will be very similar on all platforms.

**Comment by deepakrokz** [comment]
Okay let me check, thanks for your instance support

**Comment by deepakrokz** [comment]
I checked window's one, there is a file named "MainPage.xaml.cpp". I don't know how it's related to instant  playback of mic input with effects

**Comment by superpoweredSDK** [comment]
Did you try to understand what that file does?

**Comment by deepakrokz** [comment]
Thanks a lot, @superpoweredSDK. I have resolved these issues
