### ISSUE TITLE
Editing the playback sound - anti noise

### ISSUE THREAD

**Issue by ridoyf** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#436]
Hi, 

I'm just trying out the superpoweredsdk and have been playing around with the frequency domain example. My intention is to build an app that is able to record audio and then play back the inverse of the sound it recorded (anti noise). Would you guys be able to tell me how I can use the superpowredsdk to achieve this? 

Thanks

**Comment by ridoyf** [comment]
Hi Thanks for the reply and yes the concept is the same.

**Comment by superpoweredSDK** [comment]
This is something you can't achieve with a mobile or desktop application. Noise-cancelling requires a calibrated microphone+transducer pair, plus ultra-low-latency to play the inverse of the incoming sound. The lowest achievable audio latency of a mobile or desktop application is around 6 ms. That is too high. You need to react in the sub 1 ms region.

**Comment by ridoyf** [comment]
Ok, thats fair enough. Would you still be able to tell me how I can invert the sound?

**Comment by superpoweredSDK** [comment]
If you mean inverting an audio sample, then you simply change it's sign. So 0.5f becomes -0.5f.

**Comment by superpoweredSDK** [comment]
Yes. But instead of multiplying you can also negate, like sample = -sample;

**Comment by ridoyf** [comment]
So is this correct? 

`// This is called periodically by the media server.`
`static bool audioProcessing(void * __unused clientdata, short int *audioInputOutput, int numberOfSamples, int __unused samplerate) {`
`    SuperpoweredShortIntToFloat(audioInputOutput, inputBufferFloat, (unsigned int)numberOfSamples);`
`    for(int i = 0; i < numberOfSamples; i++){`
`        inputBufferFloat[i] = inputBufferFloat[i]==0 ? 0 : -inputBufferFloat[i];`
`    }`

**Comment by superpoweredSDK** [comment]
No need to convert audioInputOutput to floating point... Just iterate over each sample in audioInputOutput and negate them.
