### ISSUE TITLE
iOS, 22050 sample rate files open, but urls don't?

### ISSUE THREAD

**Issue by flagoworld** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#437]
iOS. I stumbled upon this on accident. I've tested this with a few different files. When I provide a URL for progressive streaming, i get the expected "Unknown file format" error. When I download that same file and then provide a path to the file in open(), it loads and plays.

I am told on Android, both error as expected.

Are you able to repro this? If so, what's stopping 22050 and the rest of mpeg2 from working across the board?

**Comment by superpoweredSDK** [comment]
Superpowered has no layer 2 implementation, only layer 3 is supported.
On iOS it turns for the good quality decoders by Apple when a file format is not supported natively by Superpowered.
On Android there are no good quality decoders available by the system.
Use layer 3 if you can. Your users will appreciate the better audio quality.
