### ISSUE TITLE
Superpowered How to save the output from CrossExample example to a file

### ISSUE THREAD

**Issue by ShruAlekha** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#440]
Is there a way to save the processed output buffers to a file in the CrossExample Android project from SuperpoweredSDK? I am unable to save it on a file.

**Comment by superpoweredSDK** [comment]
Use the SuperpoweredRecorder class. In the Examples_Windows folder you can find an example too, which is easily portable into CrossExample on Android.
