### ISSUE TITLE
Band-Pass filter produce noise

### ISSUE THREAD

**Issue by hananabilabd** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#441]
when I implement a low pass filter in real-time the output sound is super clear 

```
filter = new SuperpoweredFilter(SuperpoweredFilter_Resonant_Lowpass, numberOfSamples);
 filter->setResonantParameters(400.0f, 0.1f);
 filter->enable(true);
 filter->process(inputBufferFloat, outputFloatLow, numberOfSamples);
SuperpoweredFloatToShortInt(outputFloatLow, output, numberOfSamples);
```
But when I implement a band-Bass alone , the output sound  comes with a noise when talking although that i implemented the band-pass the same way
```
filter2 = new SuperpoweredFilter(SuperpoweredFilter_Bandlimited_Bandpass, numberOfSamples);
filter2->setBandlimitedParameters(100.0f,2.0f);
filter2->enable(true);
filter2->process(inputBufferFloat, outputFloat, numberOfSamples);

SuperpoweredFloatToShortInt(outputFloat, output, numberOfSamples);
```
So what in your opinion is causing that noise in Band-pass knowing that I defined the 2 buffers as 
```
inputBufferFloat = (float *)malloc(buffersize * sizeof(float) * 2 + 128);
outputFloat = (float *)malloc(buffersize * sizeof(float) * 2 + 128);
```

Regards

**Comment by superpoweredSDK** [comment]
This is not a bug in the Superpowered SDK. Please post SDK bugs to GitHub ("issues"). 
Please post your questions via email as you did before. We will answer if we get there. We receive many questions every day, sorry if you need to wait.
