### ISSUE TITLE
SuperpoweredAdvancedAudioPlayer: How to implement effects to entire audio in realtime

### ISSUE THREAD

**Issue by ShruAlekha** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#442]
I have ported over the CrossExample in Android and added a SupoerPoweredRecorder to record the audioIO from the two players. For example: if I apply a Fx effect at around 18 seconds after the audio starts playing then the recorded wav file also has the effects starting at 18 seconds. Instead I would like to apply the effects to entire audio. Is it possible?

I am also trying to have a UI for the player which will allow for moving the song/audio forward/backward(seekbar). How can I implement this with the SuperpoweredAdvancedAudioPlayer, that is how can I process the audio when user moves the audio backward/forward?

**Comment by superpoweredSDK** [comment]
Yes, this is possible. You have full control over the buffers, apply Fx at the point you want.

SuperpoweredAdvancedAudioPlayer has the setPosition method for seeking.
