### ISSUE TITLE
How to Recreate instance of load library

### ISSUE THREAD

**Issue by deepakrokz** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#444]
Hi @superpoweredSDK @theyonibomber,
I am working on the CrossExample demo with recording feature. What I am trying to achieve is restarting complete instance of SuperpoweredExample CPP file. I tried to reset player, recorder and buffer memories, it's reset on destroying call. When I am starting my activity again after finishing that I am getting these

> APM_AudioPolicyManager: startInput(3038) failed: other input 3022 already started
> 02-23 13:43:48.884 2101-7668/? E/AudioRecord: start() status -38
> AudioProvider: recording stopped, not in RECORDSTATE_RECORDING state
> E/APM_AudioPolicyManager: startInput(3046) failed: other input 3022 already started
> E/AudioRecord: start() status -38
> E/AudioProvider: recording stopped, not in RECORDSTATE_RECORDING state

It seems that nothing is being reinitialized because it's showing the older state of player and recorder. Can you please help me in this to restart the instances completely?
I am seeking for your instance support.

Thanks in advance!

**Comment by superpoweredSDK** [comment]
Seems like you forgot the tear down the audio I/O.

**Comment by deepakrokz** [comment]
what do you mean by teardown Audio I/O? If it's SuperpoweredAndroidAudioIO instance. I would like to know that I am deleting it's instance as well.

**Comment by superpoweredSDK** [comment]
yes, delete SuperpoweredAndroidAudioIO

the error says that you have other SuperpoweredAndroidAudioIO alive

somehow your class is alive or is in multiple instances

**Comment by deepakrokz** [comment]
okay, let me check once again

**Comment by deepakrokz** [comment]
I checked System.loadLibrary("SuperpoweredExample"); is being called on only one screen
