### ISSUE TITLE
Poor audio quality

### ISSUE THREAD

**Issue by petitpre** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#446]
Hi,

I test decoding AAC files with Superpowered on Android. The sound quality seem poor comparing to a desktop ffmpeg decoder. I attach two decoded wav samples from the same original mp4 file: [samples.zip](https://github.com/superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform/files/1751954/samples.zip)

How can we improve sound quality ?

**Comment by superpoweredSDK** [comment]
Can you please include the original AAC file as well?

**Comment by petitpre** [comment]
You can found a sample original mp4 here : [original.zip](https://github.com/superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform/files/1752081/original.zip)

**Comment by superpoweredSDK** [comment]
This file is in HE-AAC format. Superpowered doesn't support the "HE" extensions over AAC yet, that is the reason of the poor audio quality.
You can use "regular", non-HE AAC files, or push us for HE-AAC support.
