### ISSUE TITLE
mp3File.h crash

### ISSUE THREAD

**Issue by flagoworld** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#448]
I get this crash every once in a while during playback. It's persisted through the last few versions at least. I don't have a good repro on it, but here's the stack trace.

```
Crashed: AudioPlayer Read
0  MyApp                     0x102af3314 mp3Decoder::decodeFrame(int*, unsigned char**, int, short*) (mp3File.h:40)
1  MyApp                     0x102af3bc0 mp3File::decodeFrame(short*, unsigned int, bool*, bool*) (mp3File.h:676)
2  MyApp                     0x102af2e9c mp3File::decode(short*, unsigned int*) (mp3File.h:550)
3  MyApp                     0x102aeef00 SuperpoweredDecoder::decode(short*, unsigned int*) (SuperpoweredDecoder.cpp:680)
4  MyApp                     0x102ac77d8 readThreadFunc(void*) (SuperpoweredAdvancedAudioPlayer.cpp:1358)
5  libsystem_pthread.dylib        0x184d942b4 _pthread_body + 308
6  libsystem_pthread.dylib        0x184d94180 _pthread_body + 310
7  libsystem_pthread.dylib        0x184d92b74 thread_start + 4
```

**Comment by superpoweredSDK** [comment]
Please send the mp3 file crashing our decoder. We didn't see a crash in the mp3 decoder for years.

**Comment by superpoweredSDK** [comment]
I will close this if you don't send the file.

**Comment by flagoworld** [comment]
Sorry, I don't actually have a specific file. It comes in seemingly at random on our crash report platform. It appears to happen occasionally with any file, and the rest of the time it will play the file fine.

I will watch the reports a little more closely and report back if I see a pattern.

**Comment by superpoweredSDK** [comment]
I close this for now and please let us know if you have further information.

**Comment by flagoworld** [comment]
I get this crash often enough to be concerned, but there is no pattern that I've seen so far. It's happened to me occasionally, and for users in the field. The same file will play 99% of the time and the crash out of nowhere. Is there any other info I might be able to provide that can shed light on this? I can compile logs of all similar crashes, for instance, and maybe that will help reveal a pattern?

**Comment by superpoweredSDK** [comment]
Since Superpowered runs in the same memory space as the other parts of your application, there is a chance that other parts may corrupt the memory.

**Comment by flagoworld** [comment]
Sure that's possible I guess, but there are no other crashes in our system that are related to memory corruption. They have all been fixable bugs from programmer error. And our user activity logs at the time of the crash show that nothing fancy appears to be happening at the time of the crash...

I just went back and pulled up lists of all the crashes. I think actually the most prominent one is different than this, so I will just post a new issue and we can see if anything comes of it. This specific crash has not yet happened with the latest version of superpowered, I am now seeing, so maybe it was actually fixed...
