### ISSUE TITLE
After opening iOS image picker coreAudioProcessingCallback :inNumberFrames is 1024 

### ISSUE THREAD

**Issue by alexfoxy** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#449]
I'm using super powered within an app that uses the default iOS image picker to import some video.

On some occasions after opening and closing the image picker SuperPowered refuses to render audio. I tracked the issue down to within coreAudioProcessingCallback. See screen shot: 

<img width="956" alt="screen shot 2018-03-03 at 10 54 17" src="https://user-images.githubusercontent.com/151772/36933501-b5a4632c-1ed1-11e8-8c79-ac9462b0fd79.png">

As you can see inNumberFrames is 1024 (normally 512) so audio is never rendered. I am calling stop on the SuperPowered class before I show the image picker and calling start once the imager picker has been dismissed.

This error doesn't occur every time. Do you have any ideas what might be happening? Is there a way to force it to request only 512 samples?

Thanks!

**Comment by superpoweredSDK** [comment]
Please update to the current version of Superpowered or replace 512 with 1024.
