### ISSUE TITLE
sample build error

### ISSUE THREAD

**Issue by teratorrent** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#450]
I want to build android sample projects.
but I got this error.
CrossExample and HLSExample and HLSExample are same.

please help me..

External Native Build Issues
Build command failed.
Error while executing process C:\Users\sungjin\AppData\Local\Android\Sdk\cmake\3.6.4111459\bin\cmake.exe with arguments {-HC:\Users\sungjin\Downloads\Low-Latency-Audio-Platform-master\Examples_Android\HLSExample\app\src\main\jni -BC:\Users\sungjin\Downloads\Low-Latency-Audio-Platform-master\Examples_Android\HLSExample\app\.externalNativeBuild\cmake\release\armeabi-v7a -DANDROID_ABI=armeabi-v7a -DANDROID_PLATFORM=android-16 -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\Users\sungjin\Downloads\Low-Latency-Audio-Platform-master\Examples_Android\HLSExample\app\build\intermediates\cmake\release\obj\armeabi-v7a -DCMAKE_BUILD_TYPE=Release -DANDROID_NDK=C:\Users\sungjin\AppData\Local\Android\Sdk\ndk-bundle -DCMAKE_C_FLAGS=-O3 -fsigned-char -DCMAKE_CXX_FLAGS=-fsigned-char -IC:\Users\sungjin\Downloads\Low-Latency-Audio-Platform-master\Examples_Android\HLSExample\app\..\..\..\Superpowered -DCMAKE_TOOLCHAIN_FILE=C:\Users\sungjin\AppData\Local\Android\Sdk\ndk-bundle\build\cmake\android.toolchain.cmake -DCMAKE_MAKE_PROGRAM=C:\Users\sungjin\AppData\Local\Android\Sdk\cmake\3.6.4111459\bin\ninja.exe -GAndroid Gradle - Ninja -DANDROID_PLATFORM=android-16 -DANDROID_TOOLCHAIN=clang -DANDROID_ARM_NEON=TRUE -DANDROID_STL=gnustl_static -DPATH_TO_SUPERPOWERED:STRING=C:\Users\sungjin\Downloads\Low-Latency-Audio-Platform-master\Examples_Android\HLSExample\app\..\..\..\Superpowered}
-- Check for working C compiler: C:/Users/sungjin/AppData/Local/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe
-- Check for working C compiler: C:/Users/sungjin/AppData/Local/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Users/sungjin/AppData/Local/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe
-- Check for working CXX compiler: C:/Users/sungjin/AppData/Local/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
armeabi-v7a
CMake Error at CMakeLists.txt:12 (add_library):
    C:\Users\sungjin\Downloads\Low-Latency-Audio-Platform-master\Examples_Android\HLSExample\app\..\..\..\Superpowered/AndroidIO/SuperpoweredAndroidAudioIO.cpp
  Invalid character escape '\U'.
-- Configuring incomplete, errors occurred!
See also "C:/Users/sungjin/Downloads/Low-Latency-Audio-Platform-master/Examples_Android/HLSExample/app/.externalNativeBuild/cmake/release/armeabi-v7a/CMakeFiles/CMakeOutput.log".
Build command failed.
Error while executing process C:\Users\sungjin\AppData\Local\Android\Sdk\cmake\3.6.4111459\bin\cmake.exe with arguments {-HC:\Users\sungjin\Downloads\Low-Latency-Audio-Platform-master\Examples_Android\HLSExample\app\src\main\jni -BC:\Users\sungjin\Downloads\Low-Latency-Audio-Platform-master\Examples_Android\HLSExample\app\.externalNativeBuild\cmake\debug\armeabi-v7a -DANDROID_ABI=armeabi-v7a -DANDROID_PLATFORM=android-16 -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\Users\sungjin\Downloads\Low-Latency-Audio-Platform-master\Examples_Android\HLSExample\app\build\intermediates\cmake\debug\obj\armeabi-v7a -DCMAKE_BUILD_TYPE=Debug -DANDROID_NDK=C:\Users\sungjin\AppData\Local\Android\Sdk\ndk-bundle -DCMAKE_C_FLAGS=-O3 -fsigned-char -DCMAKE_CXX_FLAGS=-fsigned-char -IC:\Users\sungjin\Downloads\Low-Latency-Audio-Platform-master\Examples_Android\HLSExample\app\..\..\..\Superpowered -DCMAKE_TOOLCHAIN_FILE=C:\Users\sungjin\AppData\Local\Android\Sdk\ndk-bundle\build\cmake\android.toolchain.cmake -DCMAKE_MAKE_PROGRAM=C:\Users\sungjin\AppData\Local\Android\Sdk\cmake\3.6.4111459\bin\ninja.exe -GAndroid Gradle - Ninja -DANDROID_PLATFORM=android-16 -DANDROID_TOOLCHAIN=clang -DANDROID_ARM_NEON=TRUE -DANDROID_STL=gnustl_static -DPATH_TO_SUPERPOWERED:STRING=C:\Users\sungjin\Downloads\Low-Latency-Audio-Platform-master\Examples_Android\HLSExample\app\..\..\..\Superpowered}
-- Check for working C compiler: C:/Users/sungjin/AppData/Local/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe
-- Check for working C compiler: C:/Users/sungjin/AppData/Local/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Users/sungjin/AppData/Local/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe
-- Check for working CXX compiler: C:/Users/sungjin/AppData/Local/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
armeabi-v7a
CMake Error at CMakeLists.txt:12 (add_library):
    C:\Users\sungjin\Downloads\Low-Latency-Audio-Platform-master\Examples_Android\HLSExample\app\..\..\..\Superpowered/AndroidIO/SuperpoweredAndroidAudioIO.cpp
  Invalid character escape '\U'.
-- Configuring incomplete, errors occurred!
See also "C:/Users/sungjin/Downloads/Low-Latency-Audio-Platform-master/Examples_Android/HLSExample/app/.externalNativeBuild/cmake/debug/armeabi-v7a/CMakeFiles/CMakeOutput.log".

[CMakeOutput.log](https://github.com/superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform/files/1778532/CMakeOutput.log)

**Comment by superpoweredSDK** [comment]
You are on Windows, use double slashes in your path, like C:\\folder\\

**Comment by teratorrent** [comment]
Thank you for your answer. 

Yes, I am on Window 7.

Which file should I change?
