### ISSUE TITLE
SuperpoweredWindowsAudioIO.cpp only supports UWP/WinRT?

### ISSUE THREAD

**Issue by markbeaton** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#451]
It looks like the `SuperpoweredWindowsAudioIO.cpp` class leverages UWP-only classes - `Windows::Media::Devices::MediaDevice` etc. We're keen to use Superpowered in our WPF app (we're already using it on Android), but need to support Windows 7.

Will this be a possibility in the future?

Thanks

**Comment by superpoweredSDK** [comment]
Thank you for the feature request. Honestly, we don't know yet.
