### ISSUE TITLE
SuperpoweredIOSAudioIO samplerate and Synchronize with video file

### ISSUE THREAD

**Issue by temkich** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#452]
I make an application in which audio is recorded via Superpowered and video is recorded using AVCaptureSession only with AVMediaTypeVideo without audio. The processes of recording video and audio start at the same time. In the end, I combine these two files into one video with sound. But I get a problem, there is an audio sync from the video. But this is not always, if I use conventional headphones, without a microphone (sound is written through the microphone of the phone), then everything is fine. If I use the EarPods I get the desync. It seems to me that the problem is in the correct use of the samplerate. 
I tried to put 44100 for all, but this does not always work. For example, on the iPhone 6s, you need set 48000. 
I tried to use this code:
```
AVAudioSession *session = [AVAudioSession sharedInstance];
double mySamplerateWhatIWant = session.sampleRate;
```
But this wrong way...i think.
But I can not find the right solution.
How to find the right way?

**Comment by superpoweredSDK** [comment]
We are not able to provide you generic iOS programming advice, however please note that the sample rate you set with AVAudioSession is only a _preferred_ sample rate, it's not guaranteed that you will get that sample rate all the time, and sample rate may change during the session too (typically when the user connects an audio device).

**Comment by temkich** [comment]
Those. It turns out if I initially set 44100 here:
```
audioIO = [[SuperpoweredIOSAudioIO alloc] initWithDelegate:(id<SuperpoweredIOSAudioIODelegate>)self
                                           preferredBufferSize:12
                                    preferredMinimumSamplerate:44100
                                          audioSessionCategory:sessionCategory
                                                      channels:2
                                       audioProcessingCallback:audioProcessing
                                                    clientdata:(__bridge void *)self];
```
and I will in turn connect different devices, like headphones, a headset, etc.
will the samplerate change?
Why then if I set the value **preferredMinimumSamplerate:44100** and use this code in iPhone 6s, do I get desync? And if I set 48000 it will not be a guarantee?

**Comment by superpoweredSDK** [comment]
iOS can not guarantee the sample rate, regardless 44100 or 48000 or anything else. That's why it's the "preferred" sample rate setting. It's just a preference.

**Comment by temkich** [comment]
Well, how do you get the same result using the same code for iPhone5s and iPhone6s ? 
If I use preferredMinimumSamplerate:44100 on iPhone6s I will get a different result than on iPhone5s? should I for iPhone6s use preferredMinimumSamplerate:48000 ? It’s right?

**Comment by superpoweredSDK** [comment]
You can not expect the same result between models. You need to adjust your processing to accept any sample rate.

**Comment by temkich** [comment]
I still do not understand what value I should substitute initially in preferredMinimumSamplerate?
For both devices, leave 44100 as the minimum value? or somehow it needs to be calculated before launching?

**Comment by superpoweredSDK** [comment]
I think 48000 is the safest bet, most mobile devices are the happiest with 48 kHz today.

**Comment by temkich** [comment]
But on the iPhone5s with Superpowered, the recording does not work if set the value of preferredMinimumSamplerate to 48000.

**Comment by superpoweredSDK** [comment]
Set it to 44100 then.
