### ISSUE TITLE
Artifacts in SuperpoweredLimiter on some Android devices

### ISSUE THREAD

**Issue by JazariMusic** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#453]
I'm able to consistently reproduce a bug with the SuperpoweredLimiter on two devices: a 2013 Nexus N7 and a Moto G 5S Plus. To be certain that the problem is in SuperpoweredLimiter, I modified the FrequencyDomain Android example project to have the following audioProcessing callback:

```
static bool audioProcessing(void * __unused clientdata, short int *audioInputOutput, int numberOfSamples, int __unused samplerate) {
    SuperpoweredShortIntToFloat(audioInputOutput, inputBufferFloat, (unsigned int)numberOfSamples); // Converting the 16-bit integer samples to 32-bit floating point.
    limiter->process(inputBufferFloat, inputBufferFloat, numberOfSamples);
    SuperpoweredFloatToShortInt(inputBufferFloat, audioInputOutput, (unsigned int)numberOfSamples);
    return true;
}
```

That code exhibits the problem; commenting out the limiter call fixes it. 

I've attached an WAV file of a short recording I recorded with Voloco that demonstrates the problem. 

[Voloco_Live_Output.wav.zip](https://github.com/superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform/files/1787800/Voloco_Live_Output.wav.zip)

**Comment by superpoweredSDK** [comment]
Are you using the latest version of Superpowered? What's the value of "numberOfSamples" on those devices?

**Comment by JazariMusic** [comment]
We are using the latest version, and the number of samples for both devices is 240.

**Comment by superpoweredSDK** [comment]
I'm not sure what the problem can be. Can you please try non-in-place processing, so the limiter's output is not the same as the input?

**Comment by JazariMusic** [comment]
I tried it, and the distortion remains. I agree this is a very strange problem. Should I ship you guys one of the devices along with the check I'm sending today?

**Comment by superpoweredSDK** [comment]
Please try setting the buffer size of the audio stack to 512 (i know it's not optimal on that device) and let me know.

**Comment by JazariMusic** [comment]
Buffer size of 512 fixes it.

**Comment by superpoweredSDK** [comment]
We found the bug in our code. The next update will have the fix.
