### ISSUE TITLE
Can I apply effects on an mp3 file?

### ISSUE THREAD

**Issue by pranay-mathur** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#454]
I am new to Superpowered. But would love to explore it for one of the projects I am working on. Have a quick question: Can I apply superpowered effects on a mp3 file which is already in my storage using Android?

**Comment by pranay-mathur** [comment]
and also can be final result file be MP3 after applying the effects?

**Comment by superpoweredSDK** [comment]
Yes, you can decode an mp3 file using Superpowered and apply effects on the decoded pcm audio using Superpowered.
No, we don't offer mp3 encoding.
