### ISSUE TITLE
SuperpoweredDecoder can't open AAC file on iOS

### ISSUE THREAD

**Issue by julien-dumas** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#455]
Hi,

I'm using SuperpoweredDecoder on iOS to decode an AAC audio file. When I open it, the kind returned is SuperpoweredDecoder_MP3 instead of AAC and the duration, samplerate, etc. are set to 0. I can not therefore decode the file as I get an EOF error immediately.

Could I send you the audio file for further investigation?

Thanks in advance,
Julien

**Comment by superpoweredSDK** [comment]
Yes, please send the file.

**Comment by julien-dumas** [comment]
Thanks.

[piano_test.aac.zip](https://github.com/superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform/files/1791988/piano_test.aac.zip)

**Comment by superpoweredSDK** [comment]
The next update of Superpowered will have the fix for this.
