### ISSUE TITLE
Superpowered Recorder and backtrack player Lag issue 

### ISSUE THREAD

**Issue by deepakrokz** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#458]
Hi @superpoweredSDK ,

I tried to record my voice with backtrack player of Superpowered and hearing back my voice instantly using earplug, there is a big lag of around (200-300 ms), the sample rate I am using for recording is 15000. The same lag of voice recording, I am feeling while reviewing my recording with backtrack player. At the review page, I am using two instances of superpowered player, I checked their duration seems to match exactly same. But lag is there, please help me out of this.

I will be very thankful to you. Here is my recording sample code:
`void
SuperpoweredExample::startRecord(const char *tempPath, const char *destinationPath, bool record) {
    if (record) {
        recorder = new SuperpoweredRecorder(tempPath, sampleRate);
        askRecording = true;
        isRecording = true;
        recordProcessed = false;
        recorder->start(destinationPath);
//        player->play(false);
    } else {
//        player->pause();
        recorder->stop();
        askRecording = false;
    };
}`

//method to receive recording parts
`bool SuperpoweredExample::processRecording(short int *input, unsigned int numberOfSamples) {
    if (askRecording) {
        unsigned int data = 0;
        try {
            if (isRecording) {
                filter->setResonantParameters(400.0f, 0.1f);
                filter->enable(true);
                filter->process(stereoBufferRecording, stereoBufferRecording, numberOfSamples);

                high_filter->setResonantParameters(3000.0f, 0.1f);
                high_filter->enable(true);
                high_filter->process(stereoBufferRecording, stereoBufferRecording, numberOfSamples);
                SuperpoweredShortIntToFloat(input, stereoBufferRecording, numberOfSamples);
                data = recorder->process(stereoBufferRecording, NULL, numberOfSamples);
                if (headphone_in) {
                    SuperpoweredVolume(stereoBufferRecording, stereoBufferRecording, volA, volA,
                                       numberOfSamples);
                    SuperpoweredFloatToShortInt(stereoBufferRecording, input, numberOfSamples);
                } else {
                    SuperpoweredVolume(stereoBufferRecording, stereoBufferRecording, 0.0f, 0.0f,
                                       numberOfSamples);
                    SuperpoweredFloatToShortInt(stereoBufferRecording, input, numberOfSamples);
                }
                return true;
            }
        } catch (...) {

        }
    }
    return false;
}`

Thanks!

**Comment by superpoweredSDK** [comment]
On which device are testing?

**Comment by deepakrokz** [comment]
Samsung Galaxy J7, J2 Pro, J2, MI A1, MOTO G serries devices

**Comment by superpoweredSDK** [comment]
On which device did you measure that big 2-300 ms long lag? Are you aware of the Android latency problem? http://superpowered.com/latency

**Comment by wyrl** [comment]
Use SuperpoweredAndroidAudioIO.. works for me..

**Comment by deepakrokz** [comment]
In all above-mentioned devices, I am facing the lag issue, yes I am aware of Android Latency, Please let me know how can I technically resolve this to 10 ms in my Android App.

**Comment by superpoweredSDK** [comment]
You can't. You are already using Superpowered, so you reduced the user-space latency to the minimum. The rest is Android system-space latency. Yes, Android is that bad.

**Comment by deepakrokz** [comment]
What about lag in the earphone while hearing instant playback of the recording voice by this :
`SuperpoweredShortIntToFloat(input, stereoBufferRecording, numberOfSamples);
                data = recorder->process(stereoBufferRecording, NULL, numberOfSamples);
SuperpoweredVolume(stereoBufferRecording, stereoBufferRecording, volA, volA,
                                       numberOfSamples);
                    SuperpoweredFloatToShortInt(stereoBufferRecording, input, numberOfSamples);`

Please suggest

**Comment by craftbox2245** [comment]
how to download pitch shift download using superpowered
