### ISSUE TITLE
SuperpoweredTimeStretcher samplesUsed is always 0

### ISSUE THREAD

**Issue by AstralStorm** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#460]
It seems that the time stretcher has a bug - if I print out samplesUsed from output (done exactly as per offline sample code), I always get 0.f unless there's no output, in which case the value is not touched.
SuperpoweredAudiobufferlistElement inputBuffer.samplesUsed is always 0.f;

Is this even implemented?

Tested on Android armv7 with Superpowered 1.2.2.

**Comment by superpoweredSDK** [comment]
Yes, it is implemented. But only if you set up the samplesUsed property when you input a buffer.
