### ISSUE TITLE
How to merge Latency's CMakeLists.txt with CrossExamples's CMakeLists.txt?

### ISSUE THREAD

**Issue by deepakrokz** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#462]
Hi @superpoweredSDK ,

I tried to implement both the examples in single Application when I am trying to combine their CMakeLists files into a single one. Getting this error at compile time:

> Error:(54) undefined reference to 'SuperpoweredAndroidAudioIO::stop()'
> Error:(55) undefined reference to 'SuperpoweredAndroidAudioIO::~SuperpoweredAndroidAudioIO()'
> Error:(59) undefined reference to 'SuperpoweredAndroidAudioIO::stop()'
> Error:(60) undefined reference to 'SuperpoweredAndroidAudioIO::~SuperpoweredAndroidAudioIO()'
> Error:(64) undefined reference to 'SuperpoweredAndroidAudioIO::stop()'
> Error:(65) undefined reference to 'SuperpoweredAndroidAudioIO::~SuperpoweredAndroidAudioIO()'
> Error:(69) undefined reference to 'SuperpoweredAndroidAudioIO::stop()'
> Error:(70) undefined reference to 'SuperpoweredAndroidAudioIO::~SuperpoweredAndroidAudioIO()'
> Error:(74) undefined reference to 'SuperpoweredAdvancedAudioPlayer::pause(float, unsigned int)'
> Error:(75) undefined reference to 'SuperpoweredAdvancedAudioPlayer::~SuperpoweredAdvancedAudioPlayer()'
> Error:(79) undefined reference to 'SuperpoweredAdvancedAudioPlayer::pause(float, unsigned int)'
> Error:(80) undefined reference to 'Sup
> Error:(84) undefined reference to 'SuperpoweredAdvancedAudioPlayer::pause(float, unsigned int)'
> Error:(85) undefined reference to 'SuperpoweredAdvancedAudioPlayer::~SuperpoweredAdvancedAudioPlayer()'
> Error:(90) undefined reference to 'SuperpoweredRecorder::~SuperpoweredRecorder()'
> Error:(132) undefined reference to 'SuperpoweredAdvancedAudioPlayer::pause(float, unsigned int)'
> Error:(133) undefined reference to 'SuperpoweredAdvancedAudioPlayer::~SuperpoweredAdvancedAudioPlayer()'
> Error:(148) undefined reference to 'SuperpoweredRecorder::~SuperpoweredRecorder()'
> Error:(177) undefined reference to 'SuperpoweredAdvancedAudioPlayer::process(float*, bool, unsigned int, float, double, double, double, double)'
> Error:(178) undefined reference to 'SuperpoweredFloatToShortInt(float*, short*, unsigned int, unsigned int)'
> Error:(217) undefined reference to 'SuperpoweredEcho::SuperpoweredEcho(unsigned int)'

etc.

I don't know, how to use them with different CMakeLists.txt.
Please help, Need to resolve this, I have already passed two days on this. 

Thanks in advance!

**Comment by deepakrokz** [comment]
Here is combined code of CMakeLists.text:
`cmake_minimum_required(VERSION 3.4.1)

set(
	PATH_TO_SUPERPOWERED
	CACHE STRING ""
)

message(${ANDROID_ABI})

file(GLOB_RECURSE CPP_FILES "*.cpp")

add_library(
	SuperpoweredExample
	SHARED
	${CPP_FILES}
	${PATH_TO_SUPERPOWERED}/AndroidIO/SuperpoweredAndroidAudioIO.cpp
)

include_directories(src/main/jni)
include_directories(${PATH_TO_SUPERPOWERED})

target_link_libraries(
    SuperpoweredExample
    log
    android
    OpenSLES
    ${PATH_TO_SUPERPOWERED}/libSuperpoweredAndroid${ANDROID_ABI}.a
)

add_library(
	WithoutAAudio
	SHARED
	${CPP_FILES}
)

add_library(
	WithAAudio
	SHARED
	${CPP_FILES}
)

target_compile_definitions(WithoutAAudio PUBLIC HAS_AAUDIO=0)

target_link_libraries(
    WithoutAAudio
    log
    android
    OpenSLES
)

target_compile_definitions(WithAAudio PUBLIC HAS_AAUDIO=1)

target_link_libraries(
    WithAAudio
    log
    android
    OpenSLES
    aaudio
)`

**Comment by superpoweredSDK** [comment]
There is nothing on the following path:

${PATH_TO_SUPERPOWERED}/libSuperpoweredAndroid${ANDROID_ABI}.a 

Either PATH_TO_SUPERPOWERED points to an invalid place or you are building against an ANDROID_ABI Superpowered doesn't support.

**Comment by deepakrokz** [comment]
${PATH_TO_SUPERPOWERED}/libSuperpoweredAndroid${ANDROID_ABI}.a, this thing is mentioned in CrossExamples CMakeLists.txt you can check. That is being managed using localproperties file.

**Comment by deepakrokz** [comment]
Here is the complete CMakeLists.txt of CrossExample given in sample:

cmake_minimum_required(VERSION 3.4.1)

set(
	PATH_TO_SUPERPOWERED
	CACHE STRING ""
)

message(${ANDROID_ABI})

file(GLOB CPP_FILES "*.cpp")

add_library(
	SuperpoweredExample
	SHARED
	${CPP_FILES}
	${PATH_TO_SUPERPOWERED}/AndroidIO/SuperpoweredAndroidAudioIO.cpp
)

include_directories(src/main/jni)
include_directories(${PATH_TO_SUPERPOWERED})

target_link_libraries(
    SuperpoweredExample
    log
    android
    OpenSLES
    ${PATH_TO_SUPERPOWERED}/libSuperpoweredAndroid${ANDROID_ABI}.a
)

**Comment by superpoweredSDK** [comment]
The "undefined reference" errors reveal that the .a static library file is not found. Therefore ${PATH_TO_SUPERPOWERED}/libSuperpoweredAndroid${ANDROID_ABI}.a is not correct in your project somehow.

**Comment by deepakrokz** [comment]
It's working fine when I am using only CrossExample references, but when I am trying to add codes of Latency check and adding CMakeLists.txt of latency in CrossExample that's when getting "undefined reference" errors.

That's my question, how can I use both? How to merge Latency's CMakeLists.txt with CrossExamples's CMakeLists.txt? please check

**Comment by superpoweredSDK** [comment]
"Merging" two different libraries is a bad idea. Why don't you "join" the two source codes and build just one native binary?
