### ISSUE TITLE
Web assembly as a build target

### ISSUE THREAD

**Issue by tommitytom** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#463]
With the recent introduction of the [AudioWorklet](https://developers.google.com/web/updates/2017/12/audio-worklet), running custom DSP in the browser with libraries compiled to web assembly has become a very interesting option.  Have you considered offering a version of the SDK compiled to web assembly so it can be used in the browser?

**Comment by superpoweredSDK** [comment]
We follow the developments in web audio, yes. But Superpowered is a closed-source library with patented innovation inside -- how could we deliver anything without exposing our code?

**Comment by tommitytom** [comment]
I presumed that web assembly is just that - assembly language.  Wouldn't someone have just as much luck reversing the binaries of your builds on other platforms?

**Comment by superpoweredSDK** [comment]
WebAssembly is not Assembly, and provides "View Source": http://webassembly.org/docs/faq/#will-webassembly-support-view-source-on-the-web

**Comment by tommitytom** [comment]
Yes but you can't see the original source, you see "linear assembly bytecode", which is surely just as hard to reverse engineer as an ordinary binary?  As described at http://webassembly.org/docs/text-format/ given the code:
```
int factorial(int n) {
  if (n == 0)
    return 1;
  else
    return n * factorial(n-1);
}
```

The output will be
```
get_local 0
i64.const 0
i64.eq
if i64
    i64.const 1
else
    get_local 0
    get_local 0
    i64.const 1
    i64.sub
    call 0
    i64.mul
end
```

**Comment by superpoweredSDK** [comment]
Seems reasonable. But WebAssembly is in the MVP stage yet, it doesn't cover many basics, such as threads or SIMD yet. We will follow the development of WebAssembly and see if it becomes a reasonable target.

**Comment by gaborszanto** [comment]
Superpowered WebAssembly is here!
https://github.com/superpoweredSDK/web-audio-javascript-webassembly-SDK-interactive-audio
