### ISSUE TITLE
Too much NOISE in real time Time Stretching

### ISSUE THREAD

**Issue by pro-softs** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#465]
Hi, I am using the SuperpoweredTimeStreching in the processing method of the SuperpoweredAndroidAudioIO for changing pitch and it is working correctly but the output audio contains too much noise to hear anything. Please help me out to solve the issue. Here is the relevant code - 

```
static bool audioProcessing(void * __unused clientdata, short int *audioInputOutput, int numberOfSamples, int __unused samplerate) {

    SuperpoweredAudiobufferlistElement inputBuffer;
    inputBuffer.startSample = 0;
    inputBuffer.samplesUsed = 0;
    inputBuffer.endSample = numberOfSamples;
    inputBuffer.buffers[0] = SuperpoweredAudiobufferPool::getBuffer((unsigned int) (numberOfSamples * 8 + 64));
    inputBuffer.buffers[1] = inputBuffer.buffers[2] = inputBuffer.buffers[3] = NULL;

    SuperpoweredShortIntToFloat(audioInputOutput, (float *)inputBuffer.buffers[0],
                                (unsigned int) numberOfSamples);

    timeStretch->setRateAndPitchShift(1.0f, -7);
    timeStretch->process(&inputBuffer, outputBuffers);

    // Do we have some output?
    if (outputBuffers->makeSlice(0, outputBuffers->sampleLength)) {
        __android_log_print(ANDROID_LOG_ERROR, "SuperpoweredExample", "decoder");

        while (true) { // Iterate on every output slice.
            // Get pointer to the output samples.
            int numSamples = 0;
            float *timeStretchedAudio = (float *)outputBuffers->nextSliceItem(&numSamples);
            if (!timeStretchedAudio || *timeStretchedAudio == 0) {
                break;
            }

            SuperpoweredFloatToShortInt(timeStretchedAudio, audioInputOutput,
                                        (unsigned int) numSamples);
        }

        outputBuffers->clear();
    }
    return true;
}
```

**Comment by superpoweredSDK** [comment]
- setRateAndPitchShift at every processing turn resets a lot of internals every time
- the audio processing callback needs "numberOfSamples" number of frames, but you get every content of "outputBuffers", plus overwriting the contents of "audioInputOutput", not appending to it

**Comment by pro-softs** [comment]
I couldn't understand. How to append the contents to "audioInputOuput"?

**Comment by superpoweredSDK** [comment]
audioInputOutput is just an array of floats. A regular array. Write after some index.

**Comment by pro-softs** [comment]
then what probably can be the cause of the noise and no change in voice? Any suggestions?

**Comment by pro-softs** [comment]
I have called it in the initialize method

**Comment by superpoweredSDK** [comment]
There can be many ways this is wrong, but i see you are doing offline processing. Then i recommend to simply use the offline example project's offlineTimeStretching method: https://github.com/superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform/blob/master/Examples_iOS/SuperpoweredOfflineProcessingExample/SuperpoweredOfflineProcessingExample/ViewController.mm
Just submit your own samples instead of the decoder.

**Comment by pro-softs** [comment]
I have checked out hat example but here I am trying to apply time stretching on the input of the SuperpoweredAndroidAudioIO and hear the changes in real time.

**Comment by superpoweredSDK** [comment]
you mean, pitch-shifting on the input? time-stretching real-time mic input in real-time is only possible with a time machine :-)

**Comment by pro-softs** [comment]
I meant using the timestreching class:)
But I am going with the offline processing only. Thanks for the help.

Regards.
