### ISSUE TITLE
Mono Recording & Stereo Playback

### ISSUE THREAD

**Issue by drusak** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#466]
I see that you support mono/stereo IO by changing NUM_CHANNELS in SuperpoweredAndroidAudioIO.cpp (I'm talking about Android)
How should I config IO if I want to record in Mono and play audio in Stereo simultaneously ?
Should I create two separate SuperpoweredAndroidAudioIO instances (one for playbacks with stereo and another for recording in mono)? 

Thanks in advance

**Comment by superpoweredSDK** [comment]
Always use just one audio I/O instance. That will be stereo in your case. "Convert" to mono using SuperpoweredStereoToMono.

**Comment by drusak** [comment]
Thank you, I'll try.
Meanwhile will it increase latency if I use 2-channel IO vs 1-channel IO?

**Comment by superpoweredSDK** [comment]
Please try using two separate buffers.
