### ISSUE TITLE
clicking at start of timestretching

### ISSUE THREAD

**Issue by weepy** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#467]
Hi I'm trying to use the Timestretcher. The output has various clicks at the beginning, but is fine for the rest of the file. See the output with a sine wave.
 
<img width="783" alt="screen shot 2018-04-09 at 15 10 15" src="https://user-images.githubusercontent.com/820/38502856-794254d0-3c08-11e8-89bb-e16fb7f72c79.png">

The discontinuities occur at ~473 samples intervals which corresponds to the sampleLength of the timestretch.

Here is a snip of the code: 

```
  while (numToWrite > 0) {
        // Try to fulfill the request from the output buffers first.
        int numberOfSamplesFromOutputBuffers = (numToWrite < outputBuffers->sampleLength) ? numToWrite : outputBuffers->sampleLength;
        
        if (outputBuffers->makeSlice(0, numberOfSamplesFromOutputBuffers)) {
            samplePositionOfTheFirstSampleInOutputBuffer = outputBuffers->nextSamplePosition();
            int num = 0;
            
            while (true) {
                int numSamples = 0;
                float *timeStretchedAudio = (float *)outputBuffers->nextSliceItem(&numSamples);
                if (!timeStretchedAudio) break;
                
                
                float* read = timeStretchedAudio;
                
                for(int i=0; i<numSamples*2;i++) {
                    *internalBufferWrite = *read;
                    internalBufferWrite++;
                    read++;
                }
                
                
                num += numSamples;
//                samplesWritten += numSamples;
            };
            
            outputBuffers->truncate(num, true);
            numToWrite -= num;
            if (numToWrite < 1) break;
        }
        
    
        // There were not enough samples in the output buffers at this point. Let's feed the time stretcher.
        SuperpoweredAudiobufferlistElement inputBuffer;
        
        int toAddToInput = 256;
//        int toAddToInput = timeStretcher->numberOfInputSamplesNeeded;
        
        inputBuffer.startSample = 0;
        inputBuffer.samplesUsed = 0;
        inputBuffer.endSample = toAddToInput;
        inputBuffer.buffers[0] = SuperpoweredAudiobufferPool::getBuffer(toAddToInput * 8 + 64);
        inputBuffer.buffers[1] = inputBuffer.buffers[2] = inputBuffer.buffers[3] = NULL;
        
        float* data = audioBuffer.data;
        float* datar = audioBuffer.datar;
        
        float* buffer = (float*) inputBuffer.buffers[0];
        int sloopLength = loopLength*fileSampleRate;
        int sloopPoint = (endLoopTime())*fileSampleRate;
        

        int i=0;
        for(; i<toAddToInput; i++) {
            
            if(ipos >= audioBuffer.length) {
                *(buffer + i*2) = 0;
                *(buffer + i*2+1) = 0;
            } else {
                *(buffer + i*2) = *(data + ipos );
                *(buffer + i*2 + 1) = *(datar + ipos);
            }
            
            ipos += 1;
            
            if(ipos >= sloopPoint) {
                if(!doLoop) {
                    playing = false;
                    break;
                } else {
                    ipos -= sloopLength;
                }
            }

        }
        
        if(ipos >= audioBuffer.length) {
            if(!doLoop) {
                playing = false;
            }
        }
        
        
        for(; i<toAddToInput; i++) {
            *(buffer + i*2) = 0;
            *(buffer + i*2+1) = 0;
        }
        
        timeStretcher->process(&inputBuffer, outputBuffers);
    }
```

I'm probably doing something stupid! I'm also calling timeStretcher->reset() and outputBuffers->clear() in the `start` method.

**Comment by weepy** [comment]
btw the loop length is much longer than the timescale seen in the above audio file

**Comment by superpoweredSDK** [comment]
We already fixed this bug thanks to another user report. The next update will have the fix.

**Comment by weepy** [comment]
OK - thanks for the reply. 
Any idea on timescale of next update ? Are there any workarounds ?

**Comment by superpoweredSDK** [comment]
Initialise the first 2048 samples with silence. We don't know the date for the next update yet, sorry.

**Comment by weepy** [comment]
So fill with 2048 and throw away 2048*scale samples ? 

I understand you don't want to commit to a specific date, but it would be great to get a sense of whether we're talking days, week or months ? 

Jonah

**Comment by weepy** [comment]
I've tried filling with silence 

```
void WavePlayer::fillWithZeros() {
    // There were not enough samples in the output buffers at this point. Let's feed the time stretcher.
    SuperpoweredAudiobufferlistElement inputBuffer;
    
    int toAddToInput = 2048;

    
    inputBuffer.startSample = 0;
    inputBuffer.samplesUsed = 0;
    inputBuffer.endSample = toAddToInput;
    inputBuffer.buffers[0] = SuperpoweredAudiobufferPool::getBuffer(toAddToInput * 8 + 64);
    inputBuffer.buffers[1] = inputBuffer.buffers[2] = inputBuffer.buffers[3] = NULL;

    
    float* buffer = (float*) inputBuffer.buffers[0];

    
    for(int i=0; i<toAddToInput; i++) {
    
        *(buffer + i*2) = 0;
        *(buffer + i*2+1) = 0;
    
    
    }

    timeStretcher->process(&inputBuffer, outputBuffers);
}
```
It seems to only push the erroneous data 2048 samples into the future.
<img width="786" alt="screen shot 2018-04-09 at 20 41 30" src="https://user-images.githubusercontent.com/820/38519042-6cee72ee-3c36-11e8-8f30-32a94a049233.png">

Is this what you meant ?

**Comment by weepy** [comment]
Ok - thanks for the update! 
Do you know the version where this bug first appeared as I think I will have to revert to that as I need to ship this month.

**Comment by superpoweredSDK** [comment]
I don't, sorry.

**Comment by weepy** [comment]
FYI : I rolled back to version 0.9.6 and there's no click now.

**Comment by superpoweredSDK** [comment]
Well, there is a click with 0.9.6 if you use the time-stretcher in a real-time context, but fortunately you don't. All clicks are fixed now, we're planning the release by the end of this month.

**Comment by weepy** [comment]
Hiya. Are you still planning to release the fix for this for the end of this month . ?

**Comment by superpoweredSDK** [comment]
No, sorry. We had some other stuff to do. We expect it by mid May.

**Comment by weepy** [comment]
Ah ok. 
I'm getting a problem with 0.9.6 where the first part of the audio is chopped off or not output (i.e. the initial attack of a kick drum is removed). Is this an expected/known bug with 0.9.6?

**Comment by weepy** [comment]
If it's any help to anyone. I managed to get around this by stuffing with 2048 samples of silence and discarding the first 2048 samples (this is with v0.9.6)

**Comment by weepy** [comment]
Is this fixed ?

**Comment by weepy** [comment]
@gaborszanto Hi - can you confirm whether you released the bugfix for this ?

**Comment by gaborszanto** [comment]
yes
