### ISSUE TITLE
Player position does not reflect vinyl mode jog wheel when rewinding past the beginning of the track

### ISSUE THREAD

**Issue by carmethene** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#468]
Issue:
The jog API's vinyl mode seems to allow the user to seek into the negative time range, even though the player itself does not allow this.

Repro:
1) Create player with no negative silence
2) Load track into player and seek to position 0
3) Call player::jogTouchBegin(JogMode_Scratch) and send some some negative cumulative ticks to jogTick().  Do not call jogTouchEnd().
4) Note that player's position/displayPosition values are still at 0.0, i.e. the  player position is not changed
5) Send some positive ticks to jogTick()
6) Player's position remains at 0.0 until the negative ticks have been cancelled out, at which point the position will start to increase.

Expected result:
I would expect either the player position to become negative (which does work if there is negative silence), or for negative ticks past the beginning of the track to be ignored.

If you call jogTouchEnd() after step 4, everything works as expected.  I.e. the next time you call jogStart() and send positive ticks to jogTick(), the position starts increasing immediately.

**Comment by superpoweredSDK** [comment]
Sorry for the late response. This is not a bug, but a feature. DJs are sensitive to "phase". If the jog ticks are not taken into account before "negative seconds", then jog wheels get out of phase.
