### ISSUE TITLE
SuperpoweredRecorder does not create resulting wav file on device

### ISSUE THREAD

**Issue by mihap** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#469]
Hello. 
I am playing with SuperpoweredRecorder on iOS.
Everything is working well on simulator, but something goes wrong on device.
When I call stop() it removes temporary files and not creates  finished recording file.
Nothing special in device console/logs. Same code works perfect on simulator.

using Superpowered 1.1.0 
iPhone 6s 11.3.1
writing into
/private/var/mobile/Containers/Data/Application/24753E3E-6C5C-46AD-9239-B48D9E29EF0B/tmp/
directory

Thanks.

**Comment by superpoweredSDK** [comment]
Sounds like a file system permissions problem. How do you set the paths?

**Comment by mihap** [comment]
`
NSString *filename = [NSTemporaryDirectory() stringByAppendingPathComponent:recTargetName];
const char *trueFilename = [filename fileSystemRepresentation];

recorder->start(trueFilename);
`

**Comment by EAmey** [comment]
I am also facing similar kind of issue. I am writing my audio tracks in the document directory 

When I tried to play file using superpoweredadvanceAudioPlayer like

Player->Open([targetFilePath fileSystemRepresentation ])
it is not playing.

**Comment by superpoweredSDK** [comment]
Did you set in Xcode that your application uses the documents directory?

**Comment by EAmey** [comment]
I have solved the problem by setting relativePath of document directory. Anyways thanks for the solution

**Comment by borisnadion** [comment]
@EAmey can you please be more specific, some code snippet would be appreciated ;-)
