### ISSUE TITLE
iOS audioIO.started == true when audioUnitRunning == false

### ISSUE THREAD

**Issue by flagoworld** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#470]
If I check audioIO.started to determine if i should call -start, there are times when interruptions cause the audio unit to stop without setting  started=false. This causes methods such as open() to hang.

While I realize this is probably not the correct way to use the class, I think it's not ideal for the class to be able to get into this state. If the audio unit is not running, I would expect either started to be set to false or an additional property called isRunning to return false.

Or, make the started property private since it doesn't seem to have any valid external use at the moment.

**Comment by superpoweredSDK** [comment]
Are you using the onforeground/onbackground methods?

**Comment by superpoweredSDK** [comment]
Are you using the onforeground/onbackground methods?

**Comment by flagoworld** [comment]
I'm not, but I see that the AudioIO class is using the notifications for those.

**Comment by superpoweredSDK** [comment]
The started property indicates that you want audioIO running, and if it's true, you don't need to call start, not even when an interrupt happens.

**Comment by flagoworld** [comment]
Right. That's what I would expect. But that is not the case. There is a bug where started == true when running == false, so calling open() or play() will cause the player to hang. (Because audioProcessing is not being called when the unit is not running)

Here, look at -everySecond in AutioProcessing.mm:

```
- (void)everySecond { // If we waited for more than 1 second with silence, stop RemoteIO to save battery.
    if (silenceFrames > samplerate) {
        [self beginInterruption];
        silenceFrames = 0;
    }
}
```

It appears the problem actually has to do with time spent loading the file. If the file is loading (progressive download) or you interact in a way that causes silenceFrames to increase beyond 1 second, this bug can happen. One example of interacting in a way that causes silenceFrames to increase is to call open() as soon as loadSuccess happens 3-4 times. A user might do this if they do several actions very quickly. The code will prevent open() from being called until loadSuccess event triggers, but after a few of those the silenceFrames > sampleRate and beginInterruption triggers. At this point, endInterruption is never called and the audioUnit is never restarted even though audioIO.started == true.

This only happens while backgrounded and appears to be a bug in the implementation of saveBatteryInBackground.

**Comment by superpoweredSDK** [comment]
I wouldn't consider this as a bug. Your use-case is different. 

When you are in the background and the app needs to open something, set audioIO.saveBatteryInBackground = false and call [audioIO start]. Then after some seconds you feel safe, enable saveBatteryInBackground again.

**Comment by flagoworld** [comment]
It's a bug. Even if it's annoying to fix, it's a bug.

There should never be a time when started == true but running == false when running is private. The code is doing something and not giving the user any feedback on what it's doing and no way to check for that state.

Easiest solution would be to call -stop after idling in the background instead of stopping the loop but leaving started == true.

**Comment by superpoweredSDK** [comment]
Calling stop would not resume I/O when the app returns to the foreground. Think outside your use-case as well!

**Comment by flagoworld** [comment]
Not resuming when it comes back to foreground makes a lot more sense than pausing without being able to tell if it's paused...

I'll leave it at that. It's still very much a bug to me but clearly we will have to agree to disagree. No need to keep going back and forth.

**Comment by superpoweredSDK** [comment]
Just change it to your liking. It's open-source.
