### ISSUE TITLE
SuperpoweredDecoder chokes on an AAC encoded via Android’s native MediaCodec/MediaMuxer

### ISSUE THREAD

**Issue by TiSsaa** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#471]
After encoding recorded WAV using Android’s native MediaCodec/MediaMuxer, the code crashes with error “**Unknown file format**” when trying to open that file with SuperPowered:

_const char *error = _decoder->open(path().c_str(), false, 0, 0);_

Any idea why is that happening? Very annoying!

**Comment by superpoweredSDK** [comment]
What format are you encoding to?

**Comment by TiSsaa** [comment]
M4A

**Comment by superpoweredSDK** [comment]
That is a container format. What's the stream format inside? How do you set up the format with MediaCodec?

**Comment by TiSsaa** [comment]
It is an AAC format, I do it like this:

                MediaMuxer mux = new MediaMuxer(outputFile.getAbsolutePath(), MediaMuxer.OutputFormat.MUXER_OUTPUT_MPEG_4);

                MediaFormat outputFormat = MediaFormat.createAudioFormat(COMPRESSED_AUDIO_FILE_MIME_TYPE,sampleRate, 2);
                outputFormat.setInteger(**MediaFormat.KEY_AAC_PROFILE, MediaCodecInfo.CodecProfileLevel.AACObjectLC**);
                outputFormat.setInteger(MediaFormat.KEY_BIT_RATE, COMPRESSED_AUDIO_FILE_BIT_RATE);
                outputFormat.setInteger(MediaFormat.KEY_MAX_INPUT_SIZE, 16384);

                MediaCodec codec = MediaCodec.createEncoderByType(COMPRESSED_AUDIO_FILE_MIME_TYPE);
                codec.configure(outputFormat, null, null, MediaCodec.CONFIGURE_FLAG_ENCODE);
                codec.start();

**Comment by superpoweredSDK** [comment]
Please send the file so we can investigate.

**Comment by Dshmuel** [comment]
Attached file as example. It's encoded with Android's MediaCodec + MediaMuxer. It's AAC-LC in M4A container.
It plays fine on PC and on Android. FFmpeg is happy with it.
But AdvancedAudioPlayer and SuperpoweredDecoder crash on trying to open it.
Claims: Error loading player: Unknown file format.

[smfmryavaz.zip](https://github.com/superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform/files/1990774/smfmryavaz.zip)

**Comment by TiSsaa** [comment]
Thanks **Dshmuel**.

**Comment by Dshmuel** [comment]
@superpoweredSDK Any clue?

**Comment by superpoweredSDK** [comment]
We had no time to investigate the file yet.

**Comment by superpoweredSDK** [comment]
This file has invalid data in the STTS atom, indicating strange samples per frame data. In other words, the encoder seems to be buggy.

We will improve Superpowered for the next update to handle this kind of badly encoded format.

**Comment by TiSsaa** [comment]
Thanks for your message.
Looking forward to next update.
