### ISSUE TITLE
SuperpoweredReverb crushes on Android 4.1 if numberOfSamples > 1024

### ISSUE THREAD

**Issue by ZumiKua** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#472]
It seems an old issue(#125 ) but I still encounter this crush on the newest sdk.
The device reported this issue is SUMSUNG I9300, Android 4.1.2.
This crush can be easily reproduced by executing the following code:
````
    SuperpoweredDecoder decoder;
    decoder.open("some mp3 file");

    auto buf = std::unique_ptr<short[]>(new short[decoder.samplesPerFrame * 2 + 32768]);
    auto float_buf = std::unique_ptr<float[]>(new float[decoder.samplesPerFrame * 2 + 32768]);

    SuperpoweredReverb rev(decoder.samplerate);
    rev.setMix(0.5f);
    rev.enable(true);

    while(true){
        unsigned int samples_read = decoder.samplesPerFrame;
        int result = decoder.decode(buf.get(), &samples_read);
        if(result == 0){
            break;
        }
        SuperpoweredShortIntToFloat(buf.get(), float_buf.get(), samples_read);
        rev.process(float_buf.get(), float_buf.get(), samples_read);
        //rev.process(float_buf.get(), float_buf.get(), samples_read / 2);
    }
````
above code will crush when function returns and SuperpoweredReverb got deleted.
But if I change `samples_read` to `samples_read / 2` then everything is fine.

BTW: I'm also tried this code on an Android 8.0 device ( OnePlus 5T ), which wont crush.

**Comment by superpoweredSDK** [comment]
The reverb would use too much memory if it would support more number of samples. Just process in 1024 or lower chunks.
