### ISSUE TITLE
missing doc info about SuperpoweredAudiobufferPool release count?

### ISSUE THREAD

**Issue by iamyellow** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#473]
hi!

not sure if i'm missing something, but here i'm with what i've found. i'm writing an app for android using this wonderful framework. it captures audio, encodes it and passthrough the device output. for now, no big deal; really. w/ android profiler i'm profiling memory usage and, though it worked nicely, i saw how the native memory was incrementing. that 'til i added `SuperpoweredAudiobufferPool::releaseBuffer` once appended the `SuperpoweredAudiobufferlistElement` to the audio pointer list. so, the question is: is the audio pointer list somehow retaining (retainCounter++) the buffer from the pool? if so, would be great to see that info in the docs :) i remember my days in objc w/out arc and learned some serious lessons about ownership and retain counting hehehe
the only example i saw in your examples, it's feeding the time streching engine and cannot see the logic behind, obviously. if somehow this is documented, sorry!

here're real code w/out boring stuff (please, let me know if something is missing and valuable for the record):

**producing (capturing)**
```
// iObuffer, numberOfSamples came from audioProcessingCallback android SuperpoweredAndroidAudioIO

SLuint32 byteCounter = numberOfSamples * mBytesPerChannel * mChannelCounter;

SuperpoweredAudiobufferlistElement inputBuffer;
inputBuffer.startSample = 0;
inputBuffer.endSample = numberOfSamples;
inputBuffer.samplePosition = mRecordedSampleCounter;
inputBuffer.samplesUsed = 0;
inputBuffer.buffers[0] = SuperpoweredAudiobufferPool::getBuffer(byteCounter);
inputBuffer.buffers[1] = inputBuffer.buffers[2] = inputBuffer.buffers[3] = NULL;

mAudioPointerList->append(&inputBuffer);
// THIS!
SuperpoweredAudiobufferPool::releaseBuffer(inputBuffer.buffers[0]);

memcpy(inputBuffer.buffers[0], iObuffer, byteCounter);

mRecordedSampleCounter += numberOfSamples;
```
**consuming (feeding the encoder)**

```
int data_samplesRead = 0;
void *data_buffer = NULL;
size_t in_size;

if (mAudioPointerList->makeSlice((int) mEncodedSampleCounter, mBufferSize)) {
  data_buffer = mAudioPointerList->nextSliceItem(&data_samplesRead);

  in_size = data_samplesRead * mBytesPerChannel * mChannelCounter;

  memcpy(in_audioBuffer, data_buffer, in_size);

  // ...

  SuperpoweredAudiobufferPool::releaseBuffer(data_buffer);

  // ...
}
```

**Comment by superpoweredSDK** [comment]
We'll extend the documentation to be more clear on that.
