### ISSUE TITLE
sync playback on different devices?

### ISSUE THREAD

**Issue by zarquon42** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#474]
You say:

_Syncing
The Superpowered audio player has a built-in ‘DJ’. Thanks to the tempo and beat sync features, multiple players can play together in perfect harmony._

This means multiple players on ONE device?
I'm looking for a solution to sync the playback on different devices. Can the superpoweredSDK be helpful on this?

**Comment by superpoweredSDK** [comment]
We offer no features for syncing on multiple devices. You need to use Ableton Link for that, and use it's values with our players. This is how i did in my DJ Player Pro application.
