### ISSUE TITLE
Address Sanitizer reported problem on Amazon KFDOWI

### ISSUE THREAD

**Issue by romanbsd** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#475]
This is a 32bit ARM afaik. It doesn't happen on arm64.

![screenshot 2018-05-28 17 17 44](https://user-images.githubusercontent.com/49660/40618794-489356f4-629b-11e8-9445-f801dd35fa5f.png)

**Comment by superpoweredSDK** [comment]
And what kind of problem did address sanitizer report? All i see is a stack trace.

**Comment by romanbsd** [comment]
I don't have it here, but if I remember correctly - protected memory access. Maybe ASAN bug as well...

**Comment by superpoweredSDK** [comment]
Please copy the full log next time, can't investigate otherwise.
