### ISSUE TITLE
send notes to controller midi, android

### ISSUE THREAD

**Issue by mochyx** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#479]
I'm trying understand the simpleusb project in android
I use an usb otg
The problem is that when I use SuperpoweredUSBMIDI::send function, it doesn't do anythiing..

I think that similar to this could send midi note on (in this case in a launchpad pro to illuminate a led, in programmer layout):
unsigned char* send[32] = {0}; 
send[0] = reinterpret_cast<unsigned char *> 0x90;
send[1] = reinterpret_cast<unsigned char *> 0x48;
send[2] = reinterpret_cast<unsigned char *>0x00;
`SuperpoweredUSBMIDI::send(1, send, 3);`
It's a problem here, or a programmer syntax issue?

The input notes, work well with the midi device: getLatestMidiMessage.
I try other midi programs in android with java and some go but others only receive notes but not send to device well.
If you need more info ask me.

**Comment by superpoweredSDK** [comment]
1. Are you sure your launchpad needs that message at the first MIDI channel? (Coming from 0x90.)

2. The "format" of send is wrong. Currently it is 32 pointers. It should be:

unsigned char send[3] = { 0x90, 0x48, 0 };

**Comment by mochyx** [comment]
Yes, the launchpad pro can specific device id and midi channels very simple in a setup layout, the problem shouldn't be that

I tried with the format you told me (thanks a lot) but without luck

**Comment by superpoweredSDK** [comment]
The third byte is the velocity. Are you sure zero will work there? How about sending a 127 instead?

**Comment by mochyx** [comment]
Yes, after my last message I realized that failure, I check with a daw (ableton live on pc/midi commander on android) send velocity 127 and have colour on led. I try with 0x7F in code but nothing. With 0 send black (on launchpad doc): not led.
And don't worry to repply fast, takes as long as you want to answer,  I didn't find other codes with the send function, maybe there is a possibility a simple fail for my part.

**Comment by superpoweredSDK** [comment]
I guess that the device is properly "opened" before you try doing this? So in the example projects you have all handshake done?
The first parameter of SuperpoweredUSBMIDI::send is the device id. I see it hardcoded to 1.

**Comment by superpoweredSDK** [comment]
Can i close this, does it work?

**Comment by mochyx** [comment]
I'm sorry for taking so long to answer, I have no time for look more... a lot of projects that I need to do haha.
Yes, the device its on and open when I test it, but I also try with usb, power on and put according the parameters on launchpad.
The example project, work perfect with onMidiReceive.

Yes, hardcoded 1 but I checked the default id and all, for only testing purposes and later make a functional app without anything hardcoded. This shouldn't be a issue. See pag 3 bootloader [device doc](https://global.novationmusic.com/sites/default/files/novation/downloads/10598/launchpad-pro-programmers-reference-guide_0.pdf)



You can close this don't worry, thanks a lot and best wishes 😃 .
