### ISSUE TITLE
Progressive downloads on poor network connections

### ISSUE THREAD

**Issue by flagoworld** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#480]
There are some issues with progressive downloads on poor network conditions. They can "hang" before LoadSuccess is even called, and it takes some large number of seconds before LoadSuccess is called. From what I can tell, it is not safe to call open() again before LoadSuccess is called or it can cause a crash. This means that there's no way to cancel a progressive download that's in the process of timing out and thus the user is forced to sit and wait for quite a while.

Is there a recommended way of handling this? Would it make sense to add a method for canceling progressive downloads, or maybe just make it safe to call open() before LoadSuccess is called? Or maybe make the timeout configurable? I'd prefer the ability to cancel it or safely call open() quickly over a configurable timeout, though, as that way it will be more flexible do different peoples' UIs.

Thanks

**Comment by superpoweredSDK** [comment]
We hear you, but please be patient. We will investigate this in a few weeks.

**Comment by flagoworld** [comment]
Excellent, thank you!

**Comment by superpoweredSDK** [comment]
The next version will have the ability to call open() at any time at any thread, but never on the audio processing thread. Concurrent open() calls will be protected with a mutex.

**Comment by flagoworld** [comment]
Excellent, thank you!

What happens is I call open() multiple times on a slow connection and LoadSuccess takes a while? Will it block until LoadSuccess due to the mutex, and then open the next file/url? Or will it cancel the download and open the next right away?

**Comment by superpoweredSDK** [comment]
No, LoadSuccess happens on a player's internal thread.
An open will cancel the download the open the next right away?

**Comment by flagoworld** [comment]
Perfect! Can’t wait to get my hands on next version. 😁

**Comment by flagoworld** [comment]
https://github.com/superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform/issues/609#issuecomment-581550009

So, in the new version did this behavior change again? Now calls to open() are ignored until the open is finished? There's no way to cancel a hanging call to open() by calling open() again? Or am I misunderstanding this? An example use case would be a user opening a URL and then deciding to open another URL before _Opened event happens due to slow connection. (This happens all the time in the wild)
