### ISSUE TITLE
Mic Recording Distorted on Xiaomi Handsets

### ISSUE THREAD

**Issue by shivamsingh** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#483]
Hi Superpowered,

We have found that users with Android handsets from certain manufacturers such as Xiaomi and HTC have been experiencing distorted recordings. The class implemented is SuperpoweredAudioRecorder, v0.9.2.
Here is a sample.

[Distortion.zip](https://github.com/superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform/files/2135876/Distortion.zip)

The user only experiences this when video recording is enabled as well along with the audio. Would this be solved by updating the SDK? Or is there some other problem at play here?

Thanks!

**Comment by superpoweredSDK** [comment]
The attached video sample has an MPEG-4 AAC audio track, but the SuperpoweredAudioRecorder outputs wav. So it's not the output of SuperpoweredAudioRecorder inside the video.
Is the output of SuperpoweredAudioRecorder (the wav file) having this distortion?

**Comment by shivamsingh** [comment]
Thank you Superpowered.
But is there an explanation for why the problem seems much worse when video recording is also enabled simultaneously?
Audio-only recordings seem to come out fine.

**Comment by superpoweredSDK** [comment]
It can be a million things. Maybe they left a mutex in the system audio stack for synchronization with video.

**Comment by shivamsingh** [comment]
Okay. Thank you!
