### ISSUE TITLE
Linux Examples build error

### ISSUE THREAD

**Issue by JamesMugford** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#487]
I'm getting the following error when building on Linux (Stock Ubuntu 18.04 LTS)

I've tested in Microsoft's WSL (Windows Subsystem For Linux) and a VM (VMWare)

The issue replicates across both platforms.

What version of Linux are you building against? Happy to change to that.

Thanks,
James

```
yzjm@ubuntu:~/Desktop/SuperpoweredSDK/Examples_Linux$ sh buildX86.sh
/tmp/ccwfPYCO.o: In function main:
offline1.cpp:(.text+0x27): undefined reference to operator new(unsigned long)
offline1.cpp:(.text+0x3c): undefined reference to SuperpoweredDecoder::SuperpoweredDecoder(void (*)(void*, SuperpoweredDecoder*), void*)
offline1.cpp:(.text+0x6d): undefined reference to SuperpoweredDecoder::open(char const*, bool, int, int, int, char**, int*)
offline1.cpp:(.text+0xa5): undefined reference to SuperpoweredDecoder::~SuperpoweredDecoder()
offline1.cpp:(.text+0xb2): undefined reference to operator delete(void*, unsigned long)
offline1.cpp:(.text+0xd6): undefined reference to createWAV(char const*, unsigned int, unsigned short)
offline1.cpp:(.text+0xfe): undefined reference to SuperpoweredDecoder::~SuperpoweredDecoder()
offline1.cpp:(.text+0x10b): undefined reference to operator delete(void*, unsigned long)
offline1.cpp:(.text+0x11f): undefined reference to operator new(unsigned long)
offline1.cpp:(.text+0x138): undefined reference to SuperpoweredFilter::SuperpoweredFilter(SuperpoweredFilterType, unsigned int)
offline1.cpp:(.text+0x158): undefined reference to SuperpoweredFilter::setResonantParameters(float, float)
offline1.cpp:(.text+0x1d9): undefined reference to SuperpoweredDecoder::decode(short*, unsigned int*)
offline1.cpp:(.text+0x209): undefined reference to SuperpoweredShortIntToFloat(short*, float*, unsigned int, unsigned int)
offline1.cpp:(.text+0x240): undefined reference to SuperpoweredFloatToShortInt(float*, short*, unsigned int, unsigned int)
offline1.cpp:(.text+0x2e0): undefined reference to closeWAV(_IO_FILE*)
offline1.cpp:(.text+0x2f1): undefined reference to SuperpoweredDecoder::~SuperpoweredDecoder()
offline1.cpp:(.text+0x2fe): undefined reference to operator delete(void*, unsigned long)
offline1.cpp:(.text+0x366): undefined reference to operator delete(void*, unsigned long)
offline1.cpp:(.text+0x381): undefined reference to operator delete(void*, unsigned long)
/tmp/ccwfPYCO.o:(.data.DW.ref.__gxx_personality_v0[DW.ref.__gxx_personality_v0]+0x0): undefined reference to __gxx_personality_v0
collect2: error: ld returned 1 exit status
```

**Comment by superpoweredSDK** [comment]
We are building Superpowered on Debian, but can happily use the builds on Ubuntu as well.
The undefined reference to operator new and delete hints that maybe your build system doesn't understand C++?

**Comment by JamesMugford** [comment]
Hey, thanks for the quick response.

I'm thinking you're right, I think it may be a dependency issue.

What dependencies are you running on your Debian box. I've just installed build-essential ( apt-get build-essential ) . This comes with gcc 7.3.0.

Also, what version of Debian are you running?

I've had to modify the buildX86.sh as well, as your gcc command line arguments weren't working, giving the following error: 

```
yzjm@yzwranglerii:/mnt/c/yzjm/yzmisc/SuperpoweredSDK/Examples_Linux$ sh buildX86.sh
: No such file or directory/libSuperpoweredLinuxX86.a
: No such file or directory/libSuperpoweredLinuxX86.a
: No such file or directory/libSuperpoweredLinuxX86.a
: No such file or directory/libSuperpoweredLinuxX86.a
```

**Comment by superpoweredSDK** [comment]
The SDK does have a libSuperpoweredLinuxX86.a file that you should link against. Please do not modify the buildX86.sh script, only the paths if needed.

**Comment by JamesMugford** [comment]
That's the strange thing.

I see the files are there but I still get that error message. I've just
tested this on Debian and I get the same errors.

I think I must be missing a dependency, or the build environments are
different in some way?

It just doesn't seem to link. I am running on a 64 bit machine. Could yours
have been 32 bit?

I've tried a number of things but it just won't compile.

**Comment by superpoweredSDK** [comment]
If it says "No such file or directory/libSuperpoweredLinuxX86.a" then the path is not correct still. The path context may be different than on the command line?

**Comment by superpoweredSDK** [comment]
If there is no response i will close this soon.

**Comment by JamesMugford** [comment]
Hey, thanks for the reply.

I'm using Bash with standard path variable set. I can use a different shell if needed?

I'm not sure quite what you mean by path context being different on the command line.

Do you mean the path variables set in the .bash

My $PATH variable looks like as follows: 

`yzjm@yzwranglerii:~$ echo $PATH                                                                                                                                         /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/Program Files/Oculus/Support/oculus-runtime:/mnt/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/iCLS:/mnt/c/Program Files/Intel/Intel(R) Management Engine Components/iCLS:/mnt/c/Windows/System32:/mnt/c/Windows:/mnt/c/Windows/System32/wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0:/mnt/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/DAL:/mnt/c/Program Files/Intel/Intel(R) Management Engine Components/DAL:/mnt/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/IPT:/mnt/c/Program Files/Intel/Intel(R) Management Engine Components/IPT:/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/mnt/c/Windows/System32:/mnt/c/Windows:/mnt/c/Windows/System32/wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0:/mnt/c/Windows/System32/OpenSSH:/mnt/c/Program Files/dotnet:/mnt/c/ProgramData/chocolatey/bin:/mnt/c/Program Files/Java/jdk1.8.0_172/bin:/mnt/c/Android/android-sdk/tools:/mnt/c/Android/android-sdk/platform-tools:/mnt/c/NVPACK/gradle-2.9/bin:/mnt/c/NVPACK/apache-ant-1.8.2/bin:/mnt/c/NVPACK/jdk1.8.0_77/bin:/mnt/c/NVPACK/android-ndk-r12b:/mnt/c/NVPACK/android-sdk-windows/extras/android/support:/mnt/c/NVPACK/android-sdk-windows/build-tools:/mnt/c/NVPACK/android-sdk-windows/platform-tools:/mnt/c/NVPACK/android-sdk-windows/tools:/mnt/c/Users/james/AppData/Local/Microsoft/WindowsApps:/mnt/c/Program Files/Microsoft VS Code/bin:/snap/bin`

(Sorry for the excess. It's a WSL instance. Please let me know if you'd like me to fire up the VM and debug in that. The output should be a lot cleaner. I don't beleive the fact I'm using a WSL instance is causing the issues)

I feel like everything I've done is correct so far. I'm thinking the issue lies in the SuperpoweredSDK Linux Examples? I think I'm running fairly reasonable setups (Debian, Ubuntu VM and WSL, multiple versions) with build-essential on each. I haven't touch each machines $PATH or .bashrc etc. I've tried as root and non root (not that that should make really any difference). I've checked the execution/access flags. They're all good.  Or perhaps a missing dependency?

I think you're right, I think it may be a pathing issue at this point (something missing out of $PATH) along with a missing dependency?

Looking forward to getting this resolved! :)

**Comment by superpoweredSDK** [comment]
if you build for 64-bit, then change the script to use libSuperpoweredLinuxX86_64.a instead of libSuperpoweredLinuxX86.a

**Comment by JamesMugford** [comment]
Hey,

Yeah, I tried this also but with no luck.

I got the same error message but with the new file name.

**Comment by superpoweredSDK** [comment]
can you please copy-paste the contents of the build script here?

**Comment by superpoweredSDK** [comment]
Do you still have this issue? Can you please copy-paste the contents of the build script here?

**Comment by b15h0y** [comment]
I am having the same issue, any idea how to build this correctly on Ubuntu especially x64 arch. I had linking issues and tried to solve them by installing the x86 bit version of the libraries. However I am stuck still here:
```
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/7/libstdc++.so when searching for -lstdc++
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/7/libstdc++.a when searching for -lstdc++
/usr/bin/ld: cannot find -lstdc++
collect2: error: ld returned 1 exit status
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/7/libstdc++.so when searching for -lstdc++
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/7/libstdc++.a when searching for -lstdc++
/usr/bin/ld: cannot find -lstdc++
collect2: error: ld returned 1 exit status
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/7/libstdc++.so when searching for -lstdc++
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/7/libstdc++.a when searching for -lstdc++
/usr/bin/ld: cannot find -lstdc++
collect2: error: ld returned 1 exit status
In file included from /usr/include/c++/7/stdlib.h:36:0,
                 from ./src/hls.cpp:2:
/usr/include/c++/7/cstdlib:41:10: fatal error: bits/c++config.h: No such file or directory
 #include <bits/c++config.h>
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
```
