### ISSUE TITLE
SuperpoweredAdvancedAudioPlayer cannot open some files via File Path

### ISSUE THREAD

**Issue by kathanshah** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#488]
Calling SuperpoweredAdvancedAudioPlayer::open() for an audio file (.wav) with duration 2.53 Minutes and file size 45.8 MB results in SuperpoweredAdvancedAudioPlayerEvent_LoadError.

It works fine if the file is put in assets and loaded with AssetFileDescriptor

But if loaded via file path on of it fails. (files links attached)
playerB->open("/data/user/0/com.superpowered.crossexample/files/CROSS/tune.wav");
but loaded with file path exist in-app and returns true for file object with file exist.

It throws SuperpoweredAdvancedAudioPlayerEvent_LoadError event in callback

have two files loaded via string path, attached both the files. one of it loads perfectly and another doesn't.

this file opens via file path and AssetFileDescriptor both
https://drive.google.com/open?id=1rpPIB3Q2EmSzcTnD_9pPecrF7zGt3Xkr

this file opens via only AssetFileDescriptor and not file path open->("/data/user/0/com.superpowered.crossexample/files/CROSS/tune.wav");
https://drive.google.com/open?id=18HKSmYHx3CDNfKmd4hWFuKj_AF1AIKyW

Please help.

**Comment by superpoweredSDK** [comment]
The first file is AAC, the second one is WAV with some strange 24-bit encoding. Looks like a non-standard header problem. We can check the second file in 2 weeks.

**Comment by kathanshah** [comment]
Sure, I will eagerly wait for your help

bellow is the list of files which I found not opening with direct file path from the android device but all work with AssetFileDescriptor when I keep in it raw folder.

It will help you to find out reason more quickly, Thank you 👍 

1. https://firebasestorage.googleapis.com/v0/b/tully-ios.appspot.com/o/producer%2F13%2F32%2FI'm%20Sorry%20Beat.mp3?alt=media&token=6c169786-ce7a-4c71-a935-4462dad2c1c2

2. https://firebasestorage.googleapis.com/v0/b/tully-ios.appspot.com/o/producer%2F6%2F28%2FDNA%20(Dirty).mp3?alt=media&token=59fbd25a-9318-4478-a738-9f0906dee4d5

3. https://firebasestorage.googleapis.com/v0/b/tully-ios.appspot.com/o/assets%2Ffairy%20Dust%20Master.wav?alt=media&token=5c1b8fa1-b32b-4364-9416-f61e35305e1b

**Comment by superpoweredSDK** [comment]
I hope you don't use the offset and length parameters for player::open() in those cases when opening directly (not from APK)?

**Comment by kathanshah** [comment]
Correct sir, not using offset and length parameter when passing file
absolute path.

Also as stated in above code i have added only absolute path in open
function ->open("absolute-path");

**Comment by kathanshah** [comment]
Resolved.

I had changed CrossFade value in c++ file and forgot that it has a function which changes volume variables.
My Bad, sorry for the long thread.

Love Superpowered.
I might seek more help in future.

Thank you 👍
