### ISSUE TITLE
Android undefined reference to SuperpoweredDecoder::open

### ISSUE THREAD

**Issue by grabskimike** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#489]
Hello. 
Recently I started to have issues with the newer version of the library. 
`    const char *openError = decoder->open(inputPath, false, 0, 0);`
**throws** undefined reference to 'SuperpoweredDecoder::open(char const*, bool, int, int, int, char**)'
and 
`new SuperpoweredTimeStretching(decoder->samplerate);` **throws** undefined reference to 'SuperpoweredTimeStretching::SuperpoweredTimeStretching(unsigned int, float)'
 while linking. 
Everything else however is fine and functions properly. If I comment out these lines and do something else with superpowered lib everything is fine so it seems the rest of the lib is being linked properly. It seems these are missing from the .a files? 
Please help.

**Comment by superpoweredSDK** [comment]
Maybe it compiles against the new version while links against the old one?

**Comment by superpoweredSDK** [comment]
If there is no response i will close this soon.
