### ISSUE TITLE
Use Spatializer in Android without Unity 

### ISSUE THREAD

**Issue by felicss** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#490]
Is it possible/are there example on how to use the Spatializer files natively in Android?

**Comment by superpoweredSDK** [comment]
Every Superpowered feature offers a clean C++ API, so the Spatializer can definitely be used on every platform, including Android.
Sorry, but we have no examples for that. But it works like a simple effect plugin: you create it, call it's process() function and you're done.
