### ISSUE TITLE
Can this library do pitch detection?

### ISSUE THREAD

**Issue by boris-dev** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#491]
Is there plan for it? 
Like FFT YIN algorithm or smth.
thank you

**Comment by superpoweredSDK** [comment]
Superpowered does offer FFT and time-domain to frequency domain transformation (including windowing and FFT). Out-of-the-box pitch detection is not offered.
