### ISSUE TITLE
How to Play audio from phone storage with this sdk?

### ISSUE THREAD

**Issue by vidjanidhi** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#493]
I want to play audio from internal sd card ...I put the  player->open("path_to_audio"); 
It does not give me any error but can't play audio.
Please suggest me how to play file from storage.

thank you.

**Comment by bibimonox** [comment]
How did you solve this issue? Can you give me a support
