### ISSUE TITLE
Errors are not documented(?) and not very meaningful, especially with progressive downloads

### ISSUE THREAD

**Issue by flagoworld** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#496]
Am I missing something or are all the possible errors each function/action can have not documented? I had to inspect the binary in vim just to find all the possible error strings that could be spit out, and then guess based on context where they might possibly be shown from.

And, especially when it comes to progressive downloads, they don't seem to be very meaningful.

Example:

1.) Specify an invalid URL to download the file from.
- Expected error: Maybe "No route to host" or "Hostname could not be reached" or "A server with the specified hostname could not be found."
- Actual error: Data connection lost.

2.) Block the connection using network link conditioner so it times out
- Expected error: "Connection timed out." or something similar
- Actual error: Data connection lost.

3.) Interrupt the connection after opening it (by turning on airplane mode, for example)
- Expected error: "Connection interrupted" or maybe even "Data connection lost" is appropriate here
- Actual error: Data connection lost.

Seeing the trend? I have no idea what I am supposed to do with these errors from a UI perspective because they are not meaningful.

It would be extra useful if errors came back as enum values, too. Then I could just switch() the error code and everything would be great.

If you turn on airplane mode after LoadSuccess but while it's still downloading, sometimes the ProgressiveDownloadError is triggered. Other times it will just pause once it hits the end of the buffer and never trigger any kind of error.

Thanks

**Comment by superpoweredSDK** [comment]
Network connections can return with many kinds of (HTTP) error codes. That's why the player has the "loadErrorCode" parameter. It returns the HTTP error code.

**Comment by flagoworld** [comment]
I see. I was on the previous 1.2.2 release and did not see that error code param. That does help a lot, thanks.

What about conditions where there was not an HTTP error, such as the connection dropping, DNS being unable to resolve, etc?
