### ISSUE TITLE
Crash in SuperpoweredAdvancedAudioPlayer.cpp

### ISSUE THREAD

**Issue by romanbsd** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#497]
![screenshot 2018-07-12 11 35 29](https://user-images.githubusercontent.com/49660/42621958-d3b9a82e-85c7-11e8-8539-9e5cbeeb203b.png)

**Comment by superpoweredSDK** [comment]
That line checks for the existence of the generic "internals" structure. Because it crashed, it seems like instance was deallocated. It happens frequently that developers forget to stop audio I/O first and destroy the players while audio I/O is still running. Maybe that's the case for you too?

**Comment by romanbsd** [comment]
I found the execution path when this can happen. Thanks!
