### ISSUE TITLE
initializeData with different file path even after pause both players produces old sound along with new file

### ISSUE THREAD

**Issue by Shashank112** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#498]
I am using super-powered cross example via wrapper in siwft.

i am able to play two files, pause them and unpause them

but once i change the urls and call initializeData(newfilepath,newfilepath2) after calling pause on both the players it still produces unclear sound with mix of old files.

If i create a new object of superpoweredwrapper second time at initialization it crashes.

**Comment by superpoweredSDK** [comment]
There is no "initializeData" or Swift wrapper in the cross example project. It seems like you are using some custom code. Please contact the developer of that, or fix the code yourself.

**Comment by superpoweredSDK** [comment]
Maybe you re-create everything, so you have two instances of everything? Sorry, but can't provide support to your own custom code.
