### ISSUE TITLE
Why is player->internals->downloader not exposed to the public? (bufferEndPercent, fullyDownloadedFilePath

### ISSUE THREAD

**Issue by flagoworld** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#499]
Hi,

This is mostly a curiosity, but I think it is a fairly reasonable question:

In the past I asked why player->fullyDownloadedFilePath and player->bufferEndPercent are not updated when superpowered is paused. I can't remember your response, but basically it was not something that was going to be fixed.

Well, I was in the debugger messing with other things, and I noticed that player->internals->downloader, which is a reference to the decoder, actually knows the actual fullyDownloadedFilePath and bufferEndPercent even when the player is paused. The decoder is updating correctly.

This begs the question: Why are the player->fullyDownloadedFilePath and bufferEndPercent variables not proxies to the internals->downloader? This would solve the updating issue when paused. Is there some other bug that was trying to be avoided or something?

The downloader/decoder wouldn't even have to be fully exposed if they were proxies.

Also, why is the downloader/decoder internal and not exposed?

Thanks

**Comment by superpoweredSDK** [comment]
Those variables are updated now.

We are not discussing Superpowered internals, but they more complex than you describe.

**Comment by flagoworld** [comment]
I wasn't trying to suggest that they are simple or anything, and hope that it didn't come across as though I was suggesting you make internal secret functionality public. Thanks for making those variables update!

**Comment by flagoworld** [comment]
I just tested in the latest release and those variables are still not being updated when paused. Is that supposed to be the case?
