### ISSUE TITLE
more SuperpoweredFrequencyDomain documentation

### ISSUE THREAD

**Issue by drtyhlpr** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#500]
Hi, thanks for the great project and very fair licensing!

(Others and) I need some more documentation on the

**SuperpoweredFrequencyDomain** incrementSamples and maxOverlap parameters:

> For advanced use, if you know how window overlapping works. 0 (the default value) means 4:1 overlap (good compromise in audio quality).

I have some basic understanding of FFT overlaping but other overlapping ratios or values are not documented so far (?). can you please add some info on that (or just some stuff in the headers).

ps. is the overlapping factor (working) independent from the chosen FFT size 256 - 8192*?

thanks you

**Comment by superpoweredSDK** [comment]
Windowing is a separate process to FFT.
It depends on your current FFT size how big overlapping is. For example, FFT size 256 with a 128 step would be 2:1 overlapping.
