### ISSUE TITLE
Feature Request: Noise Gate

### ISSUE THREAD

**Issue by TNorth22** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#501]
I have yet to find a library out there including `superpowered` that offers a good old-fashioned noise gate.  

Considering a noise gate is just a compressor that attenuates a signal _under_ a given threshold instead of _over_ like a traditional one I can imagine this to be a fairly simple exercise to implement.

Any chance that might be on your radar?

**Comment by superpoweredSDK** [comment]
Thank you for the feature request. We don't have this feature planned yet.

**Comment by TNorth22** [comment]
Thanks for your reply.  Any chance you'd would you be willing to provide your original source?

**Comment by superpoweredSDK** [comment]
There are lot of patented innovations inside. We don't provide source, sorry.

**Comment by TNorth22** [comment]
Never hurts to ask ;)
