### ISSUE TITLE
sync failed

### ISSUE THREAD

**Issue by alexd555** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#502]
Build command failed.

Error while executing process E:\Android\sdk\cmake\3.6.4111459\bin\cmake.exe with arguments {-HD:\OneDrive\OneDrive\projectA\Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform-master\Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform-master\Examples_Android\SuperpoweredRecorder\app -BD:\OneDrive\OneDrive\projectA\Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform-master\Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform-master\Examples_Android\SuperpoweredRecorder\app\.externalNativeBuild\cmake\release\armeabi-v7a -DANDROID_ABI=armeabi-v7a -DANDROID_PLATFORM=android-16 -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=D:\OneDrive\OneDrive\projectA\Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform-master\Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform-master\Examples_Android\SuperpoweredRecorder\app\build\intermediates\cmake\release\obj\armeabi-v7a -DCMAKE_BUILD_TYPE=Release -DANDROID_NDK=E:\Android\sdk\ndk-bundle -DCMAKE_C_FLAGS=-O3 -fsigned-char -DCMAKE_CXX_FLAGS=-fsigned-char -ID:\OneDrive\OneDrive\projectA\Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform-master\Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform-master\Examples_Android\SuperpoweredRecorder\app\..\..\..\Superpowered -DCMAKE_TOOLCHAIN_FILE=E:\Android\sdk\ndk-bundle\build\cmake\android.toolchain.cmake -DCMAKE_MAKE_PROGRAM=E:\Android\sdk\cmake\3.6.4111459\bin\ninja.exe -GAndroid Gradle - Ninja -DANDROID_PLATFORM=android-16 -DANDROID_TOOLCHAIN=clang -DANDROID_ARM_NEON=TRUE -DANDROID_STL=gnustl_static -DPATH_TO_SUPERPOWERED:STRING=D:\OneDrive\OneDrive\projectA\Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform-master\Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform-master\Examples_Android\SuperpoweredRecorder\app\..\..\..\Superpowered}

CMake Error: cmListFileCache: error can not open file D:/OneDrive/OneDrive /projectA/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform-master/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform-master/Examples_Android/SuperpoweredRecorder/app/CMakeLists.txt

-- Configuring incomplete, errors occurred!

CMake Error: Cannot open file for write: D:/OneDrive/OneDrive /projectA/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform-master/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform-master/Examples_Android/SuperpoweredRecorder/app/.externalNativeBuild/cmake/release/armeabi-v7a/CMakeCache.txt.tmp

CMake Error: : System Error: No such file or directory

CMake Error: Unable to open cache file for save. D:/OneDrive/OneDrive/projectA/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform-master/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform-master/Examples_Android/SuperpoweredRecorder/app/.externalNativeBuild/cmake/release/armeabi-v7a/CMakeCache.txt

Build command failed.

Error while executing process E:\Android\sdk\cmake\3.6.4111459\bin\cmake.exe with arguments {-HD:\OneDrive\OneDrive\projectA\Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform-master\Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform-master\Examples_Android\SuperpoweredRecorder\app -BD:\OneDrive\OneDrive\projectA\Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform-master\Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform-master\Examples_Android\SuperpoweredRecorder\app\.externalNativeBuild\cmake\debug\armeabi-v7a -DANDROID_ABI=armeabi-v7a -DANDROID_PLATFORM=android-16 -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=D:\OneDrive\OneDrive\projectA\Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform-master\Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform-master\Examples_Android\SuperpoweredRecorder\app\build\intermediates\cmake\debug\obj\armeabi-v7a -DCMAKE_BUILD_TYPE=Debug -DANDROID_NDK=E:\Android\sdk\ndk-bundle -DCMAKE_C_FLAGS=-O3 -fsigned-char -DCMAKE_CXX_FLAGS=-fsigned-char -ID:\OneDrive\OneDrive\projectA\Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform-master\Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform-master\Examples_Android\SuperpoweredRecorder\app\..\..\..\Superpowered -DCMAKE_TOOLCHAIN_FILE=E:\Android\sdk\ndk-bundle\build\cmake\android.toolchain.cmake -DCMAKE_MAKE_PROGRAM=E:\Android\sdk\cmake\3.6.4111459\bin\ninja.exe -GAndroid Gradle - Ninja -DANDROID_PLATFORM=android-16 -DANDROID_TOOLCHAIN=clang -DANDROID_ARM_NEON=TRUE -DANDROID_STL=gnustl_static -DPATH_TO_SUPERPOWERED:STRING=D:\OneDrive\OneDrive\projectA\Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform-master\Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform-master\Examples_Android\SuperpoweredRecorder\app\..\..\..\Superpowered}

CMake Error: cmListFileCache: error can not open file D:/OneDrive/OneDrive/projectA/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform-master/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform-master/Examples_Android/SuperpoweredRecorder/app/CMakeLists.txt

-- Configuring incomplete, errors occurred!

CMake Error: Cannot open file for write: D:/OneDrive/OneDrive/projectA/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform-master/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform-master/Examples_Android/SuperpoweredRecorder/app/.externalNativeBuild/cmake/debug/armeabi-v7a/CMakeCache.txt.tmp

CMake Error: : System Error: No such file or directory

CMake Error: Unable to open cache file for save. D:/OneDrive/OneDrive/projectA/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform-master/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform-master/Examples_Android/SuperpoweredRecorder/app/.externalNativeBuild/cmake/debug/armeabi-v7a/CMakeCache.txt

**Comment by alexd555** [comment]
Why is it closed ?
@superpoweredSDK

**Comment by superpoweredSDK** [comment]
You throw a log here without any explanation. Also, i recommend to read the contents of the log.

**Comment by alexd555** [comment]
What explantion do you want ?
I just tried to complie the project and got the error.
@superpoweredSDK

**Comment by superpoweredSDK** [comment]
It compiles fine for thousands of developers.
