### ISSUE TITLE
Real time buffer processing iOS help

### ISSUE THREAD

**Issue by TNorth22** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#503]
Hi there -

I'm attempting to get a processing path up and running in an iOS project using an `MTAudioProcessingTap` to process audio buffers via the standard Core Audio callback mechanism and running into issues with noise between each processed sample in the resulting rendered samples I'm hopeful you can help with.

My questions are:

1.  What is causing my noise per sample after processing?
2.  Can I use mono buffers where interleaved buffers are called out i.e. a `SuperpoweredCompressor`?
3.  Can you see anything obvious with my code sample below that's incorrect?

Here's some useful info:

1. I'm using a single non-interleaved mono `AudioBuffer` and leveraging a `SuperpoweredCompressor` instance to provide in-place processing of the buffer data received from a call to `MTAudioProcessingTapGetSourceAudio`.  Since I'm passing a previously initialized buffer to this method as per Apple doc's I am the owner of this buffer and not the system so am free to mutate as needed.

2.  The mono non-interleaved buffer is then passed into the `processBuffer` along with the total frame count [size] of the buffer.

3.  My returned buffer size is generally 4096 which is divisible by 8 so that should be fine.

4.  I've also tried creating an interleaved buffer by using the mono buffer for the left+right channels via the `SuperpoweredInterleave` method then passing the resulting interleaved buffer to `SuperpoweredCompressor->process(..)` then back to `SuperpoweredDeInterleave` and using a single channel of the result to send back to the system which is expecting a mono channel result but I still hear the same processing noise.

5.  The audio sounds fine if I set the compressor to enabled = false 

Here's a snippet of code for more clarity:

```
    /// `numberFrames` is a _request_. We may not have enough source samples to complete in its entirety.
    var framesRemaining = numberFrames

    /// `resultFlags` may indicate the start or end of a stream.
    /// "Returned from GetSourceAudio and should be propagated on return from the process callback"
    var resultFlags = MTAudioProcessingTapFlags()

    /// Keeps track of how many frames have been processed in each pass
    var framesProcessed: CMItemCount = 0

    while framesRemaining > 0 {

        var sourceFramesCount: CMItemCount = 0
        let maxFramesToRead = min(framesRemaining, numberFrames)

        // Acquire the source samples into the tap data's buffer lists
        _ = MTAudioProcessingTapGetSourceAudio(tap,
                                               maxFramesToRead,
                                               tapData.bufferListMutablePtr!.unsafeMutablePointer,
                                               &resultFlags,
                                               nil,
                                               &sourceFramesCount)
        switch resultFlags {
        case 0:  // The common case
            break
        case kMTAudioProcessingTapFlag_StartOfStream:  // common when resuming after video scrubbing
            // Reset any audio unit state, e.g. reverb
            tapData.compressor.reset()
        case kMTAudioProcessingTapFlag_EndOfStream:
            framesRemaining = 0
        default:
            // Unknown case; log it and discover what it is...
            DDLogError("Unknown case attempting to acquire source samples. Result flags is: \(resultFlags)")
        }

        let rawBuffer = tapData.bufferListMutablePtr![0].mData
        guard let inFloats = rawBuffer?.assumingMemoryBound(to: Float.self) else { return }

        tapData.compressor.processBuffer(inFloats, withSize: Float(sourceFramesCount))
        framesProcessed += CMItemCount(sourceFramesCount)
        framesRemaining -= framesProcessed
   }


```

**Comment by superpoweredSDK** [comment]
We've never used MTAudioProcessingTap, because it can not be used for real-time audio processing (the buffer sizes are too high).

Almost every Superpowered Fx requires 32-bit floating point interleaved stereo. Use the various functions in SuperpoweredSimple.h to convert to that format.

Cut the processing into 2048 sample chunks. We don't test Superpowered for super high buffer sizes.
