### ISSUE TITLE
Crash when play song

### ISSUE THREAD

**Issue by trungbv95** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#504]
Hello, I used Superpowered on my Unity project. 
It's got crash when i call togglePlayback();

Log:
08-09 09:15:16.459: E/CRASH(15037): signal 7 (SIGBUS), code 128 (?), fault addr 00000000
08-09 09:15:16.459: E/CRASH(15037): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
08-09 09:15:16.459: E/CRASH(15037): Build fingerprint: 'samsung/t03gxx/t03g:4.4.2/KOT49H/N7100XXUFNI4:user/release-keys'
08-09 09:15:16.459: E/CRASH(15037): Revision: '11'
08-09 09:15:16.459: E/CRASH(15037): pid: 15037, tid: 15074, name: UnityMain  >>> com.pianotiles.battle.mode.free <<<
08-09 09:15:16.459: E/CRASH(15037):     r0 6d80bae8  r1 00002b88  r2 00000000  r3 6211be28
08-09 09:15:16.459: E/CRASH(15037):     r4 00000000  r5 00000000  r6 0000000a  r7 63ad6e78
08-09 09:15:16.459: E/CRASH(15037):     r8 69303ac8  r9 63ad766c  sl 63ad7580  fp 63ad6e68
08-09 09:15:16.459: E/CRASH(15037):     ip aaaaaaaa  sp 63ad6e68  lr aaaad632  pc 820b63d8  cpsr 00000007
08-09 09:15:16.459: E/CRASH(15037): backtrace:
08-09 09:15:16.829: D/SSRMv2:SIOP(2486): SIOP:: AP = 370, Delta = 0

**Comment by superpoweredSDK** [comment]
Hello, i don't see anything related to Superpowered in this log.

**Comment by trungbv95** [comment]
Sorry, it's my fault. Please close this!
