### ISSUE TITLE
The SDK directory '/android/sdk' does not exist.

### ISSUE THREAD

**Issue by chanof** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#509]
My i ask an help to open the simpleusb example on android studio with mac highSierra,

Trying to open:

> /Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform-master-2/Examples_Android/SuperpoweredUSBExample/simpleusb

Android SDK location is correct, the same of local.properties:

```
sdk.dir=/Users/name/Library/Android/sdk
ndk.dir=/Users/name/Library/Android/sdk/ndk-bundle
```

but i still get this error:

> The SDK directory '/android/sdk' does not exist.
> 
> Please fix the 'sdk.dir' property in the local.properties file.
> Open File

Thanks

**Comment by superpoweredSDK** [comment]
go to File->Project Structure->SDK Location

**Comment by chanof** [comment]
I already check it:
Android SDK location /Users/gianmaria/Library/Android/sdk
JND location /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home 
Android NDK location /Users/gianmaria/Library/Android/sdk/ndk-bundle

**Comment by chanof** [comment]
Do you mean like below on local.properties
```
sdk.dir=/name/Library/Android/sdk
ndk.dir=/name/Library/Android/sdk/ndk-bundle
```
Still get the error

**Comment by superpoweredSDK** [comment]
I'm out of ideas, sorry.

**Comment by chanof** [comment]
Ok i got it working! i need to open this path

> /Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform-master-2/Examples_Android/SuperpoweredUSBExample

**Comment by cherifff** [comment]
can you please elaborate ? 
I am kind of newbie, where can i fix this isse please ? 
i have the error : the path home divine android sdks does not belong to a directory
