### ISSUE TITLE
open url: No internet connection

### ISSUE THREAD

**Issue by eduardhasanaj2** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#510]
Hi, 
I am trying to open a url but it says "Open Error: No internet connection". I open the url in all browsers and with android MediaPlayer and works great. It is not exactly an http server but it is emulated on top of server socket. Does your implementation differs from MediaPlayer and web browser for handling remote url?

**Comment by superpoweredSDK** [comment]
It sounds like the http flavor of your emulation can't talk with our http implementation.

**Comment by eduardhasanaj2** [comment]
But is there anything I can do?
My response headers are:
Content-length
Accept-ranges
Status.
I used MediaPlayer in my thesis but I failed because it is very unstable at start delay. If you point to standard you implemented I can fix it on my own.
Thanks

**Comment by eduardhasanaj2** [comment]
I was curious what is happening with my emulated server and decided to try apache.
The same error is thrown. Superpowered should play from apache web server, right?

**Comment by superpoweredSDK** [comment]
how does your url look like?

**Comment by eduardhasanaj2** [comment]
the url is http://192.169.0.163/Learning/song.mp3

**Comment by superpoweredSDK** [comment]
internet permission enabled in manifest?

**Comment by eduardhasanaj2** [comment]
yes, I can play from MediaPlayer

**Comment by superpoweredSDK** [comment]
and if you try an external server it works?

**Comment by eduardhasanaj2** [comment]
What do you mean with external server? I am currently using apache web server.

**Comment by superpoweredSDK** [comment]
I thought the server runs on the same Android device.

I have no idea what can be the problem. Maybe switch your server to HTTP 1.0.

**Comment by eduardhasanaj2** [comment]
I know that. if in header request i get
GET / HTTP/1.0
Host: 192.169.0.163:4050
Cache-Control: no-cache
Accept-Encoding: identity
Connection: Close
Connection is closed or I am wrong

**Comment by superpoweredSDK** [comment]
yes, http is stateless, this is normal, this is how it works

**Comment by eduardhasanaj2** [comment]
What headers should be in response? Currently are:
Content-Length
Content-Ranges
Content-Range
Status
Status can be ok or 206 partial content.

The above sever is opened by all web browsers and works ok. Is there any header that is required by superpowered?

**Comment by superpoweredSDK** [comment]
content-length and the http code, that's it

content-range is not parsed (it is http 1.1, not 1.0)

**Comment by eduardhasanaj2** [comment]
Here is the full response header.
HTTP/1.0 200 OK 
Content-Type: audio/mp3
Content-Length: 5130377
then is printed again \r\n and row binary data is send.
When i have free time I will try to find a solution, but it would be helpful to know in what conditions error no internet connection is shown in your library.
thank you for your help

**Comment by eduardhasanaj2** [comment]
I mean at the end of each row is inserted "\r\n"
HTTP/1.0 200 OK
Content-Type: audio/mp3
Content-Length: 5130377
but in the last one is inserted two time like 
Content-Length: 5130377 \r\n
\r\n

 binary data is send.
"\r\n" are not displayed but they are in the code that formats the header.

**Comment by superpoweredSDK** [comment]
it looks okay

**Comment by eduardhasanaj2** [comment]
yeah, anyway It has open error "No Internet Connection".
Thank you for the support.
If I find anything I will let you know.

**Comment by superpoweredSDK** [comment]
Can i close this?

**Comment by eduardhasanaj2** [comment]
I have not fixed yet the problem. Since the problem can be reproduced when using apache webserver I think it should stay open. If i find any solution I will close it.

**Comment by eduardhasanaj2** [comment]
I am unable to find any solution. There is not much that can be done on my side. You can close this but I recommend that you should test it by yourself using apache. 
Best regards
