### ISSUE TITLE
iOS: SuperpoweredAdvancedAudioPlayer.play breaks the entire sound of the system.

### ISSUE THREAD

**Issue by Violetdusk** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#511]
Hello.

First of all, thank you so much for this amazing platform.
I'm implementing stereo mixing playback & save to wav file with multiple effects (reverb, NBandEQ)
Most codes are based on the Example project you provided.

I did these things.

1. Initialize `SuperpoweredIOSAudioIO` with a delegate.
2. Initialize `SuperpoweredAdvancedAudioPlayer` with `playerEventCallback`
3. When `playerEventCallback` is called with `SuperpoweredAdvancedAudioPlayerEvent_LoadSuccess` event, I call `start` method of `SuperpoweredIOSAudioIO` and notify to Application that everythings ready. (my coworker who is working on the application doesn't know, care about the internal flow of this)
4. From Application, it calls `play` method of my module, which simply calls `player->play(false)` and set a `shouldPlay` flag to `YES`

The problem I'm facing is

- When _my_ `play` method is called, intermittently (2-3 times in 10-15 runs) crashes the entire sound system and device needs to reboot after that.
- When it went wrong (crashed), right after `play` is called, the device plays short booming noise (Like when you plug off your earset from phone) and entire _systems_ sounds are gone, not only the application.
        
I've been looking for GitHub issues to solve this problem for 3 days but unfortunately, I didn't find any good answer.

Any help would be appreciated!

Thanks

**Comment by superpoweredSDK** [comment]
Can i close this?
