### ISSUE TITLE
Unity audio latency

### ISSUE THREAD

**Issue by ATHellboy** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#512]
Hey there,

I want to know if this sdk is good for my problem or not.

I'm making a rhythm game which ball bounces on platforms and it hits the platforms at the exact time which music reach its noticeable beats (my music is 165 bpm and my ball hits the platform each 2 beat from beginning of the music) also I want to change tempo along the game.

But I have huge audio latency on Android when I play the music.

**Comment by superpoweredSDK** [comment]
Sorry, but Unity audio latency on Android can not be solved. Only if you run your own audio engine (using Superpowered) in parallel.
