### ISSUE TITLE
Caculate dbfs from a magnitude of fft

### ISSUE THREAD

**Issue by doublekw** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#513]
Dear superpoweredSDK team
I’m thank to you since you support good dsp 
I had tried to caculate dbfs or db from value of magnitude in fft result. But I’m not sure how do i calculate dbfs on Android.

Currently i used dbfs=20*log10(magnitude*2/2024)... 

Could you let me know the formula to calculate it? 

Please check it : )
Thank you 
Regards

**Comment by superpoweredSDK** [comment]
Your formula looks almost okay, but i guess your FFT size is 2048, not 2024. Please check your FFT size.

**Comment by doublekw** [comment]
Thank you for your response. 

Exactly. FFT size is 2048. 
So, Could you double check the formula?

dbfs = 2 * log10(2*magnitude / 2048) = 2 * log (magnitude / 1024) 

Thank you.
