### ISSUE TITLE
change of magnitude for Right is not working with Galaxy S7

### ISSUE THREAD

**Issue by doublekw** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#514]
Dear SuperpoweredSDK

I have a question about gorgeous superpowered SDK !!
With Pixel, it works well to change value of magnitude for both left and right. 
However, with Galaxy S7, It not works. I mean that sound doesn't change if i change value of right's magnitude. but both left and right sound are changed when I change value of left's magnitude

Please recommend for the above  

Thank you
Wonkyun

**Comment by superpoweredSDK** [comment]
There are multiple features in Superpowered which can change the volume. Which feature do you use for that?

**Comment by doublekw** [comment]
When i change the left, both left and right sound are changed..

**Comment by superpoweredSDK** [comment]
It seems like your device is in mono. Did you change the example project's code?

**Comment by doublekw** [comment]
No. Actually It works well with galaxy s4 and same code.

**Comment by gaborszanto** [comment]
How do you check left and right? Using the built-in speaker or headphones?

**Comment by doublekw** [comment]
A headphones. I think It’s impossible to chekc left and right with built-in speaker.

**Comment by gaborszanto** [comment]
Try the player example project. It doesn't use the audio input. Check if it is stereo or not.

**Comment by gaborszanto** [comment]
Did you perform the check?

**Comment by gaborszanto** [comment]
Did you perform the check?
