### ISSUE TITLE
AndroidIO multiple callback 

### ISSUE THREAD

**Issue by jisung0920** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#515]
To Superpowered.

Thanks to your SDK.
I am trying to use two androidIO callbacks. I have to implement, using two mics on my work.

So, I used two SuperpoweredAndroidAudioIO objects  like this

`    
    SuperpoweredCPU::setSustainedPerformanceMode(true);

    pathTracker_m = new PathTracker(FRAME_SIZE, FREQUENCY);
    cd_m.pathTracker = pathTracker_m;
    cd_m.mic = FRIST_MIC;
    audioIO_m = new SuperpoweredAndroidAudioIO(AUDIO_SAMPLE_RATE, FRAME_SIZE, true, false,
                                               performRender, &cd_m, SL_ANDROID_RECORDING_PRESET_GENERIC, -1, FRAME_SIZE * 6);
    pathTracker_c = new PathTracker(FRAME_SIZE, FREQUENCY);
    cd_c.pathTracker = pathTracker_c;
    cd_c.mic = SECOND_MIC;
    audioIO_c = new SuperpoweredAndroidAudioIO(AUDIO_SAMPLE_RATE, FRAME_SIZE, true, false,
                                               performRender, &cd_c, SL_ANDROID_RECORDING_PRESET_CAMCORDER, -1, FRAME_SIZE * 6);`

But the callback functions do not work at the same time. 
Only the first callback function works.

Is it impossible to use two mics simultaneously in this SDK?
Could you suggest some solutions for me?

**Comment by superpoweredSDK** [comment]
1. I'm not sure if Android can open two different audio inputs simultaneously.

2. I see only one callback passed ("performRender"), not two.

**Comment by superpoweredSDK** [comment]
Can i close this?

**Comment by jisung0920** [comment]
I will close this when I solve this or give up.

**Comment by gaborszanto** [comment]
Since this is not an issue with Superpowered i close this.
