### ISSUE TITLE
double check for dbfs formula 

### ISSUE THREAD

**Issue by doublekw** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#516]
Thank you for your response about previous question.

Exactly. FFT size is 2048.
 So, Could you double check the formula?

dbfsforLeft = 2 * log10(2*magnitudeLeft / 2048) = 2 * log10(magnitudeLeft / 1024)
dbfsforRight = 2 * log10(2*magnitudeRight / 2048) = 2 * log10(magnitudeRight / 1024)

Thank you.
Regards

**Comment by superpoweredSDK** [comment]
This is not an issue with Superpowered.
To solve and check basic mathematic problems please use wolframalpha.com
