### ISSUE TITLE
is it possible to route internal midi?

### ISSUE THREAD

**Issue by sensn** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#519]
Hi,

I'm new to Superpowered and I just built my first test-app. Previously I tried android.media.midi and switched to Superpowered because of jitter.
It works really great with USB-Midi interface so far. 

My question: Is it possible to use Superpowered Midi to connect to another app on the phone like fluidsynth? Using it as internal Midi, or to connect via normal USB cable to a DAW using USB midi-mode on the phone?
I hope this is the right place to ask that question. 
thanks.

**Comment by gaborszanto** [comment]
Superpowered is a software development kit. It should be built into that other app in order to use its benefits.
