### ISSUE TITLE
distortion in playback

### ISSUE THREAD

**Issue by mehdisam** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#520]
Please check this file with ios sample code. I tested it with ios sample code(performance). The file is a sweep sin file from 20 ~ 20000. With core audio, it plays as expected and sound goes from low pitch to high pitch linearly while in superpowered it adds some sounds like old radio distortion noise.

Thank you
[sweep.mp3.zip](https://github.com/superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform/files/2370624/sweep.mp3.zip)

**Comment by gaborszanto** [comment]
I put the file into the SuperpoweredPerformance example project for the Superpowered part. It plays properly without any artifact.

**Comment by mehdisam** [comment]
try it on a device with volume = 100%. I tried it on 2 different devices. 6s and 6.

**Comment by gaborszanto** [comment]
Not happening on my iPad Air (with volume 100%). Can you record it and show me?

**Comment by mehdisam** [comment]
sure, here it is.
[sweep-superpowered.mp3.zip](https://github.com/superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform/files/2373774/sweep-superpowered.mp3.zip)

**Comment by gaborszanto** [comment]
This is the product of the resampler. It has a linear resampler inside for regular playback, and some very high frequencies "wrap around" the Nyquist frequency. This is not normally a problem for typical musical signals, but this synthetic signal revealed it.

**Comment by mehdisam** [comment]
In normal playback, it shows itself in high pitches. In this case, you can hear it clearly. But why it doesn't happen in iPad( I check it too)?

**Comment by gaborszanto** [comment]
The resampler is off, because the sample rates match.

**Comment by mehdisam** [comment]
Is there anything that I can fix it?

**Comment by gaborszanto** [comment]
I'm not sure if there is anything to fix. This artifact happens for this very synthetic signal only, and only when it's resampled (so it comes in a 44.1 kHz file while played back on a 48 kHz system).

**Comment by mehdisam** [comment]
It happens in all playbacks but I guess there is no way to show it. If you compare playback in high pitch song you can see that it reduces the sharpness of the song.

**Comment by gaborszanto** [comment]
I'm not sure what you mean under "high pitch song".
Please make a recording with such song with a samplerate matching the output samplerate, and another recording with a samplerate not matching the output samplerate, so we will have a direct comparison.

**Comment by gaborszanto** [comment]
Are you working on this, did you see my last comment?
