### ISSUE TITLE
Pitch shift many files limitation

### ISSUE THREAD

**Issue by AliMunchkin** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#521]
Hi,

First of all, thank you for this awesome SDK :)

I have run into a problem with pitchshifting many (16+) files. On a slower phone (Samsung J3) I sometimes experience bad audio during pitchshift. I searched the existing issues and found a related comment:

> “Pitch shifting for 16 tracks may be too much for many Android devices with small buffer sizes and not-so-strong processors. Increase the buffer size.”

Increasing the buffer size didn’t completely fix the issue. So I’m curious, is there anything else that may help here? I realise this is **a lot** of processing for such a low powered CPU but thought it worth asking here before refactoring etc.

Thanks

**Comment by AliMunchkin** [comment]
I should add, using Android Profiler CPU usage is only around 50-60% while playback is failing (bad audio)

**Comment by gaborszanto** [comment]
If you reach 50% on the CPU core performing the audio processing callback, audio dropouts will happen.

Pitch-shifting 16 files simultaneously in real-time is a great achievement on any mobile device, and even on a desktop. There is nothing more you can do.
