### ISSUE TITLE
Non-HTTP streaming

### ISSUE THREAD

**Issue by woko666** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#524]
Hello,
is it possible to play compressed audio files from a buffer? My use case is streaming mp3 files from non-HTTP sources, so I have a buffer with a chunk of mp3 file once every couple of milliseconds, and I'd like to feed it to superpowered. Is it even possible?
Thanks!

**Comment by gaborszanto** [comment]
There is no such feature in Superpowered, sorry.
