### ISSUE TITLE
loadError - no internet connection on subsequent plays

### ISSUE THREAD

**Issue by drorsun** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#525]
Hi,
In our app we use open with URL. This works well on the first time.
we destroy the player and create a new one for each new play.
In some cases, the second and every subsequent open fails with event SuperpoweredAdvancedAudioPlayerEvent_LoadError and text "No internet connection" (but we made sure there is an active internet connection)

we use setTempFolder to the application cache directory.
we tried clearing the temp folder in between plays but that did not help.

we use the latest release - SuperpoweredSDK 1.2.4B.
This is how we create the player:
```cpp
SuperpoweredAdvancedAudioPlayer *player = new SuperpoweredAdvancedAudioPlayer(wrapper,
                                                                                  playerCallback,
                                                                                  (unsigned int) sampleRate,
                                                                                  0);
```

Thanks in Advance
Dror

**Comment by gaborszanto** [comment]
This looks fine. "No internet connection" means that Superpowered couldn't connect to the server at all (not an error message from the server).
What's the benefit of destroying the player for each new play? It sounds expensive.

**Comment by drorsun** [comment]
What could be the reasons that Superpowered is not be able to connect? We know the device has active connections. The only change from previous play AFAIK is that we created a new player.

**Comment by gaborszanto** [comment]
The network socket can not connect to the server for some reason.
Try to not recreating the player every time. Just simply call open() on it for another url.

**Comment by drorsun** [comment]
The problem happens long time after destroying the player. There's no reason to keep the player around for a long time if the user moved on to other activities.
