### ISSUE TITLE
input channel size different in callback

### ISSUE THREAD

**Issue by binodrok** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#527]
numInputChannels in SuperpoweredUSBAudioProcessingCallback shows 2 channel while the  audioIO contains only mono data.

**Comment by gaborszanto** [comment]
What is "audioIO"?

**Comment by binodrok** [comment]
Its float pointer, please check SuperpoweredUSBAudio.h,  and see SuperpoweredUSBAudioProcessingCallback prototype's third parameter.

**Comment by gaborszanto** [comment]
The documentation says: "audioIO 32-bit interleaved audio input and/or output"

How do you know it's mono? It's just a buffer. Interleaved stereo.
