### ISSUE TITLE
SuperpoweredUSBAudio leading unnknown crash

### ISSUE THREAD

**Issue by binodrok** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#528]
I am trying to use SuperpoweredUSB api but getting crashed. 
Here is flow after all setup done like in complexUSB example.

1.    SuperpoweredUSBAudio::startIO()
Then i want to change the device interface.
So, I performed.
2. SuperpoweredUSBAudio::stopIO()
3.  SuperpoweredUSBAudio::startIO() immediately called without waiting with new param.

Once or twice it won't crash but it would stopped getting callback called. Again repeating steps 2 and 3 several times would crash application. 
Temporary workaround was to wait few milliseconds between stopIO() and startIO(). But repeating step 2 and 3 several times, would crash, mostly due to memory corruption.

How long it must wait for startIO() after stopIO() is called? Is there any fix, or any wrong I am doing?

**Comment by gaborszanto** [comment]
Wait 1 seconds in between. We will check this later.

**Comment by walterbelleville** [comment]
I have the same problem.  The app crashes when trying to add the SuperpoweredUSBAudio.  I have followed your example on your github page for add USB for android.

**Comment by gaborszanto** [comment]
The issue is related to stopping and starting I/O rapidly, not "when trying to add the SuperpoweredUSBAudio". Do you really have the same problem?

**Comment by gaborszanto** [comment]
Next update will have the fix, coming in a few weeks.
