### ISSUE TITLE
Audio recording is not working in iOS

### ISSUE THREAD

**Issue by alimehdipk** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#529]
here is my code for recording the audio
`rec = new SuperpoweredRecorder([path fileSystemRepresentation], 44100);
rec->start([path fileSystemRepresentation]);`

**Comment by gaborszanto** [comment]
That's not enough code. You don't pass any audio to your recorder. Check the SuperpoweredRecorder.h header for the process() function.
