### ISSUE TITLE
Progressive streamer + unknown Content-Length

### ISSUE THREAD

**Issue by flagoworld** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#531]
If the server provides no Content-Length, such as if a file is being live-transcoded as it's being sent to the progressive downloader, Superpowered will wait until the file is completely finished downloading before starting playback. Is there any way to allow it to start playing as soon as it has enough data to play, but to set the duration as some "indeterminate" value while it's still downloading?

**Comment by gaborszanto** [comment]
Yes, we implemented this feature for regular files ("progressive download"). Maybe you are using a file format where Superpowered can not get any idea about the duration until it reads the entire thing? Sometimes this info is at the end.

**Comment by flagoworld** [comment]
I'm downloading MP3s. if I supply a content-length, it works fine, but if not it wont actually start playing until the download is complete. The same URL with no content-length plays in the browser and most other streamers. They just don't show the length of the audio until the download finishes.

It "feels" like there shouldn't be anything stopping Superpowered from also doing this, but I know nothing of the internal workings so can't really comment.

It would be an awesome feature to have, though, and would make the progressive downloader much more robust.

**Comment by gaborszanto** [comment]
We have no plans to support this use-case, sorry. Yes, Superpowered can't read or predict the length of your mp3 file if there is no content-length.

**Comment by flagoworld** [comment]
So, just to double-confirm, definitely no way to just start playing audio and leave the "duration" as "indefinite" until all the data comes in?

What if I provided the data straight into the audioprocessing from my own decoder instance or custom decoder or something? Do you think something like that would be feasible?

**Comment by gaborszanto** [comment]
We support "indefinite" duration with HTTP Live Streaming only, which is a very different thing.
We provide no "custom decoder API", sorry.
