### ISSUE TITLE
Disable microphone usage

### ISSUE THREAD

**Issue by schartyom** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#534]
Every time I clean and then run a project containing your library on iOS Simulator an alert appears: “AppName would like to access the microphone.” This alert breaks our CI flow, because you can’t automate the tap on it. Setting `USES_AUDIO_INPUT 0` doesn’t help to hide it. Is there any way to prevent microphone permissions request?

The issue can be reproduced on your SuperpoweredCrossExample on macOS Mojave.

**Comment by gaborszanto** [comment]
The cross example project doesn't use any audio input and doesn't require any input permissions. Maybe you are using a modified project?

**Comment by schartyom** [comment]
No, I'm not using a modified project. The only thing I changed is set `USES_AUDIO_INPUT` to 0. The issue reproduces every time you clean and then run the project, you can check that.

**Comment by gaborszanto** [comment]
I can't check that as i have no idea about your CI environment. Please try an unchanged project directly from our SDK. "USES_AUDIO_INPUT" has no effect on audio input, but audio session category does.

**Comment by schartyom** [comment]
I've just tried on unchanged project one more time, situation hasn't changed. You don't need any CI environment, just clean and run the project on macOS Mojave and you will see the microphone permissions alert

**Comment by gaborszanto** [comment]
Sounds like an emerging iOS Simulator bug: https://stackoverflow.com/questions/53285441/ios-simulator-would-like-to-access-microphone

**Comment by schartyom** [comment]
Well, it would make sense. Thanks for help
