### ISSUE TITLE
While generating APK gives me error 

### ISSUE THREAD

**Issue by syam82** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#535]
Error:(175) undefined reference to 'SuperpoweredAdvancedAudioPlayer::setPosition(double, bool, bool)'
Error:(104) undefined reference to 'SuperpoweredAdvancedAudioPlayer::SuperpoweredAdvancedAudioPlayer(void*, void (*)(void*, SuperpoweredAdvancedAudioPlayerEvent, void*), unsigned int, unsigned int, unsigned int)'
Error:(110) undefined reference to 'SuperpoweredAdvancedAudioPlayer::SuperpoweredAdvancedAudioPlayer(void*, void (*)(void*, SuperpoweredAdvancedAudioPlayerEvent, void*), unsigned int, unsigned int, unsigned int)'
Error:(101) undefined reference to 'SuperpoweredAdvancedAudioPlayer::SuperpoweredAdvancedAudioPlayer(void*, void (*)(void*, SuperpoweredAdvancedAudioPlayerEvent, void*), unsigned int, unsigned int, unsigned int)'
Error:(117) undefined reference to 'SuperpoweredRecorder::SuperpoweredRecorder(char const*, unsigned int, unsigned int)'
Error:(107) undefined reference to 'SuperpoweredAdvancedAudioPlayer::SuperpoweredAdvancedAudioPlayer(void*, void (*)(void*, SuperpoweredAdvancedAudioPlayerEvent, void*), unsigned int, unsigned int, unsigned int)'
Error:(38) undefined reference to 'SuperpoweredAdvancedAudioPlayer::setPosition(double, bool, bool)'
Error:(78) undefined reference to 'SuperpoweredAdvancedAudioPlayer::setPosition(double, bool, bool)'
Error:(52) undefined reference to 'SuperpoweredAdvancedAudioPlayer::setPosition(double, bool, bool)'
Error:(196) undefined reference to 'SuperpoweredAdvancedAudioPlayer::process(float*, bool, unsigned int, float, double, double)'
Error:(220) undefined reference to 'SuperpoweredAdvancedAudioPlayer::process(float*, bool, unsigned int, float, double, double)'
Error:(221) undefined reference to 'SuperpoweredAdvancedAudioPlayer::process(float*, bool, unsigned int, float, double, double)'
Error:(222) undefined reference to 'SuperpoweredAdvancedAudioPlayer::process(float*, bool, unsigned int, float, double, double)'
Error:error: linker command failed with exit code 1 (use -v to see invocation)
Error:(33) undefined reference to 'SuperpoweredRecorder::SuperpoweredRecorder(char const*, unsigned int, unsigned int)'

**Comment by gaborszanto** [comment]
This is not a Superpowered issue, but a generic programming issue, therefore i close it.
It means that you are not linking with Superpowered.
