### ISSUE TITLE
Timestretch: Number of samples out not accurate/rounded

### ISSUE THREAD

**Issue by jimsimonz** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#537]
For example at a timestretch rate of 1.2 with no pitch shift at 44.1kHz.

Feeding in 9830 samples/frames outputs 8113 frames but should output 8192. (Frame = 1 Stereo sample)

i.e. 8192 * 1.2 = 9830.4 so feeding in 9830 in should get you back to an output of 8192.

Does the timestretch algorithm round to some sort of fixed buffer size boundary? It's hard to use it to stream if the number of output samples can't be predicted accurately based upon the rate. 

- Windows x64 build

**Comment by jimsimonz** [comment]
Added sample code: In this example outputBuffers->sampleLength will end up being 8113 when input size is 9830.

	if (!TimeStretcher)
	{
		TimeStretcher = new SuperpoweredTimeStretching(SampleRate);
	}
	if (TimeStretcher->rate != TimeStretchRatio)
	{
		TimeStretcher->setRateAndPitchShift(TimeStretchRatio, 0); 
	}
	int32 NumRawPCMFrames = NumFrames;

	// This buffer list will receive the time-stretched samples.
	SuperpoweredAudiopointerList *outputBuffers = new SuperpoweredAudiopointerList(NumChannels * sizeof(float), 16);
	// Create an input buffer for the time stretcher.
	SuperpoweredAudiobufferlistElement inputBuffer;
	inputBuffer.samplePosition = 0;
	inputBuffer.startSample = 0;
	inputBuffer.samplesUsed = 0;
	inputBuffer.endSample = NumRawPCMFrames; // <-- Important!
	inputBuffer.buffers[0] = SuperpoweredAudiobufferPool::getBuffer(NumRawPCMFrames * NumChannels * sizeof(float) + 64);
	inputBuffer.buffers[1] = inputBuffer.buffers[2] = inputBuffer.buffers[3] = NULL;

	// assumes stereo frames so half num for mono?
	SuperpoweredShortIntToFloat(InputBuffer, (float*)inputBuffer.buffers[0], (NumRawPCMFrames *  NumChannels) / 2);
	TimeStretcher->process(&inputBuffer, outputBuffers);


	int NumFramesWritten = 0;
	// Do we have some output?
	if (outputBuffers->makeSlice(0, outputBuffers->sampleLength))
	{
		while (true)
		{ // Iterate on every output slice.
		  // Get pointer to the output samples.
			int numFrames = 0;
			float *timeStretchedAudio = (float *)outputBuffers->nextSliceItem(&numFrames);
			if (!timeStretchedAudio) break;
			memcpy(&AudioOut[NumFramesWritten * NumChannels], timeStretchedAudio, numFrames * sizeof(float)* NumChannels);
			NumFramesWritten += numFrames;
		};
		// Clear the output buffer list.
		outputBuffers->clear();
	};
	delete outputBuffers;

**Comment by gaborszanto** [comment]
The time-stretcher handles transients in a different way in order to preserve them. Therefore the output number of samples is not predictable. On the longer average (1-2 seconds) the time ration will be what you set. But in the small timescale the output can greatly vary.

**Comment by jimsimonz** [comment]
Thanks for getting back, it still seems a little out from the expected though with larger sounds too. 

So with an 8 Second sound stretched by 1.2, the output is down by 1000 samples (40ms). This causes issues when looping multiple sounds together (e.g. two drum loops, one 8 seconds, one 16 seconds long)

I can zero pad the end to sync them but then there'll be glitches on looping. It seems like there's something more happening than just transients as the offset accumulates with time.

**Comment by gaborszanto** [comment]
I wrote the time-stretcher. There is nothing else happening in relation of output sample number.
Several DJ apps are using this without any problems (looping synced chunks of audio frequently happens there).

**Comment by jimsimonz** [comment]
Ok, thanks I'll attach an example at some point so you can repro anyway. 

I can only assume the DJ apps are setting their loop lengths based on the timestretch output length rather than using a multiple of their original duration(s) and maybe crossfading.

**Comment by gaborszanto** [comment]
Yes, of course apps need to work with the output length and not some imaginary multiple of the original duration.

**Comment by gaborszanto** [comment]
Correct, you never get exactly the amount of samples you requested for in the short term. On the long term you do. This is how every high-quality time stretcher in the world works.
Some of them hide this fact by returning with fixed number of samples using an internal buffer. You can do that using the time stretcher's output buffer list. For example, if you are fixed to an N number of samples, pull N number of samples only when the output buffer list has N number of samples. Just input some samples to the time-stretcher until it's output buffer has N number of samples. Then you can mix and save the results.

**Comment by jimsimonz** [comment]
Ok got it, many thanks for the advice.
