### ISSUE TITLE
help plz 

### ISSUE THREAD

**Issue by cobrax1** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#539]
well  i'm not  a good  programmer or something  i'm just a user and  i wanna  know how to add  superpowered  plugin  to  my phone  ??  plz  someone give  me some help

**Comment by gaborszanto** [comment]
Superpowered is a software development kit, not a "plugin". As a user you can't "use" Superpowered, it's a toolkit and library for developers.
