### ISSUE TITLE
Approach to build a tuner for Guitar notes

### ISSUE THREAD

**Issue by rtiwarihr** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#541]
I have a requirement wherein I need to record the note being played on Guitar and then match it with the predefined audio in order to check whether its tuned properly or not

I browsed through the classes in SuperpoweredSDK and came across SuperpoweredAdvancedAudioPlayer and SuperpoweredTimeStretching, but I am not sure how I can utilize them 

Also, I need to do this at realtime #256

Any supporting example would be helpful

**Comment by gaborszanto** [comment]
If you need to "detect" notes from the incoming audio, then player or time stretching is not useful. I recommend a bunch of filters (using SuperpoweredBandpassFilterbank) tuned to specific notes.

**Comment by rtiwarihr** [comment]
Is there any sample which can help me try this out?

**Comment by gaborszanto** [comment]
This may help: https://github.com/superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform/blob/master/Examples_iOS/SuperpoweredFrequencies/SuperpoweredFrequencies/Superpowered.mm
