### ISSUE TITLE
Are there Superpowered Android Audio Record and Play example?

### ISSUE THREAD

**Issue by Faigorgor** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#542]
Hi SuperPowered Team,

Thanks for your contribution, I am looking for low latency Audio library for Android development.
I had download SuperPowered SDK and could not find the example of Android real time record and playback example.

Can you send me some document or tell me where can I get them. 

Thank you so much

Will

**Comment by gaborszanto** [comment]
Recorder: https://github.com/superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform/tree/master/Examples_Android/SuperpoweredRecorder

Player: https://github.com/superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform/tree/master/Examples_Android/SuperpoweredPlayer
