### ISSUE TITLE
Strange "preattack" artefact with single short drums + timestretching

### ISSUE THREAD

**Issue by weepy** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#544]
I'm timestretching/repitching some audio files and am getting strange issues with instruments with attack. You can here the issue in the links below, but essentially the first attack sounds fine, but subsequent sound like they are "fading in" ?

Timestretched/repitched:
https://instaud.io/3101

Original:
https://instaud.io/3103

Here's the audio code I used : 
```
    int numberOfSamples = output->length;
    float* internalBufferWritePointer = internalBuffer;

    while (numberOfSamples > 0) {
        // Try to fulfill the request from the output buffers first.
        int numberOfSamplesFromOutputBuffers = (numberOfSamples < outputBuffers->sampleLength) ? numberOfSamples : outputBuffers->sampleLength;
        
        if (outputBuffers->makeSlice(0, numberOfSamplesFromOutputBuffers)) {
            samplePositionOfTheFirstSampleInOutputBuffer = outputBuffers->nextSamplePosition();
            numberOfSamplesFromOutputBuffers = 0;
            
            while (true) {
                int numSamples = 0;
                float *timeStretchedAudio = (float *)outputBuffers->nextSliceItem(&numSamples);
                if (!timeStretchedAudio) {
                    break;
                }
                
                memcpy(internalBufferWritePointer, timeStretchedAudio, numSamples * 8);
                internalBufferWritePointer += 2*numSamples;

                numberOfSamplesFromOutputBuffers += numSamples;
            };
            
            outputBuffers->truncate(numberOfSamplesFromOutputBuffers, true);
            numberOfSamples -= numberOfSamplesFromOutputBuffers;
            if (numberOfSamples < 1) break;
        }
        // There were not enough samples in the output buffers at this point. Let's feed the time stretcher.
        SuperpoweredAudiobufferlistElement inputBuffer;
        
        int toAddToInput = 256;
//        int toAddToInput = timeStretcher->numberOfInputSamplesNeeded; // Unfortunately this is zero if rate = 1 && cent = 0
        
        inputBuffer.startSample = 0;
        inputBuffer.samplesUsed = 0;
        inputBuffer.endSample = toAddToInput;
        inputBuffer.buffers[0] = SuperpoweredAudiobufferPool::getBuffer(toAddToInput * 8 + 64);
        inputBuffer.buffers[1] = inputBuffer.buffers[2] = inputBuffer.buffers[3] = NULL;
        
        float* data = audio_file->buffer->data;
        float* datar = audio_file->buffer->datar;
        int audioLength = audio_file->buffer->length;
        float* buffer = (float*) inputBuffer.buffers[0];
        
        int i=0;    
        for( ; i<toAddToInput; i++) {
            *(buffer + i*2) = *(data + ipos );
            *(buffer + i*2 + 1) = *(datar + ipos);
            ipos += 1;               
        }

        for(; i<toAddToInput; i++) {
            *(buffer + i*2) = 0;
            *(buffer + i*2+1) = 0;
        }
        timeStretcher->process(&inputBuffer, outputBuffers);        
    }

```

**Comment by weepy** [comment]
Code is copied from another example. Am I doing anything obviously wrong ?

**Comment by weepy** [comment]
In fact I get a very similar result in the OfflineProcessing example if I set it to call the timeStretch with a pitch shift down: 

```
   SuperpoweredTimeStretching *timeStretch = new SuperpoweredTimeStretching(decoder->samplerate);
    timeStretch->setRateAndPitchShift(1.00f, -500);
```

**Comment by weepy** [comment]
The bug also occurs with rate increases ala `timeStretch->setRateAndPitchShift(1.50f, 0);`. 

@gaborszanto any ideas ? This looks non-trivial to fix, but I can confirm that Ableton doesn't have an issue with it, so looks like a problem with Superpowered.

**Comment by gaborszanto** [comment]
I will check this in a few days. I hope i will have some time next week.

**Comment by weepy** [comment]
Ok - thanks for the feedback - look forward to your thoughts.

**Comment by gaborszanto** [comment]
Okay, so the time stretcher/pitch shifter is pitch shifting the transients as well, causing them to be less "transient". I could make them unchanged, however it sounds not so good when transients are playing at the original pitch and everything else is pitched. I'm not sure how to compromise.

**Comment by weepy** [comment]
How come it sounds ok if the transient is at the start ?

You could look at how Ableton does it for reference ?

**Comment by weepy** [comment]
Actually I was sort of fixing this my resetting the timestretcher when it got to a transient. Perhaps you could do this ?

**Comment by gaborszanto** [comment]
At the start there is no pitch shifting at all. Ableton licenses a third-party solution which is not so great for high performance. Yes, i'm thinking about transient handling as i wrote before.

**Comment by gaborszanto** [comment]
Please check the attached test audio file. Is this better?
[Recording 2019.01.15 17:58:11.wav.zip](https://github.com/superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform/files/2760606/Recording.2019.01.15.17.58.11.wav.zip)

**Comment by gaborszanto** [comment]
Can you please listen to this?

**Comment by weepy** [comment]
Hi sorry ...

I would actually say that it's worse.

If you listen to => https://instaud.io/3101 you can hear the first attack
is "ok", but not the three others - in the audio you just sent they are all
"bad".

I can pitch it in ableton if you like for a "target render" ?

J

**Comment by gaborszanto** [comment]
Yes, please.

**Comment by gaborszanto** [comment]
Yes, please send an Ableton-processed target render.

**Comment by weepy** [comment]
Hi - my co-worker is away today (who has ableton) . I'll send it as soon as
I can.

**Comment by gaborszanto** [comment]
?

**Comment by weepy** [comment]
here you go => https://instaud.io/3cRh

**Comment by gaborszanto** [comment]
I'm sorry, but this is stretched, not pitched.

**Comment by gaborszanto** [comment]
Superpowered can both stretch and pitch-shift. You opened this issue about pitch-shifting.

**Comment by weepy** [comment]
Sorry I’ll pitch one tomorrow

**Comment by weepy** [comment]
Here's 3 semitones down => https://instaud.io/3d6g

and 12 semitones down => https://instaud.io/3d6h

Listening to the version I had an issue with - you can hear that the first snare is ok.

**Comment by gaborszanto** [comment]
Is this better?
[Recording 2019.01.28 17:49:36.wav.zip](https://github.com/superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform/files/2804002/Recording.2019.01.28.17.49.36.wav.zip)

**Comment by weepy** [comment]
Yes is improved.

Though you can hear the windowing that you're doing (because each of the
pitched snares are slightly different - the input snares are identical).
The ableton version sounds tighter here - I wonder if they transient
detection ( a luxury since they can process the entire wave offline ).

**Comment by gaborszanto** [comment]
Here is a sample generated by the upcoming version of Superpowered (3 semitones down). Please review.
[05.wav.zip](https://github.com/superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform/files/2828457/05.wav.zip)

**Comment by weepy** [comment]
good job much better

**Comment by gaborszanto** [comment]
The "bleed" before the transients is much reduced now. Better results were achieved during development, however they were good for drum tracks only and disaster for anything else.
