### ISSUE TITLE
SuperpoweredAndroidAudioIO microphone input latency

### ISSUE THREAD

**Issue by hakoptak** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#545]
Hi, I am building a small mobile game framework based on SDL2, where I replaced its audio module with Superpowered. On iOS all is fine, but on Android I am noticing an unusual high latency when processing the microphone input on my MotoG3 device (Android 6.0.1). This, however, can be undone when I plug in my earbuds. After plugging them in the input latency suddenly drops to its expected low value. The input latency stays low after I plug out my earbuds.

This is how I instantiate the IO object for low latency input:

```
static SuperpoweredAndroidAudioIO* audio_io;
...
// Use SL_ANDROID_RECORDING_PRESET_VOICE_RECOGNITION for low latency input
audio_io = new SuperpoweredAndroidAudioIO(sample_rate, buffer_size, true, true, io_callback, NULL, SL_ANDROID_RECORDING_PRESET_VOICE_RECOGNITION, SL_ANDROID_STREAM_MEDIA, buffer_size);
```

Some other findings:

- When I run my test app directly from Android Studio with my device usb-connected I get low latency input
- When I run my test app directly from Android Studio with my device usb-connected and the SL_ANDROID_RECORDING_PRESET_GENERIC flag I get a high input latency, which reproduces the problem
- It thus seems that Android does not respect the SL_ANDROID_RECORDING_PRESET_VOICE_RECOGNITION flag when starting the IO instance

Any ideas what is going on?

**Comment by weepy** [comment]
was the latency low when using SDL2 ?

**Comment by hakoptak** [comment]
I have never benchmarked the SDL input latency. My first guess was that its audio module interfered with Superpowered but the problem remained after I completely disabled SDL's audio module. But to make sure that it really does not interfere with Superpowered I should run it without SDL... And maybe it is also worth looking into SDL's input latency without Superpowered. It remains, however, strange that the latency drops when I plug in the audio jack...

Thanks for thinking with me!

**Comment by gaborszanto** [comment]
The increased latency indicates that some kind of noise canceling DSP gets activated, increasing input latency. When you plug in a headphone it's deactivated.
By using SL_ANDROID_RECORDING_PRESET_VOICE_RECOGNITION it tries to notify Android that such DSP should be turned off. However device manufacturers may not implement that.

**Comment by hakoptak** [comment]
Thanks for bringing this up. That is indeed what I was afraid of... So there is no simple workaround to force the device into the `SL_ANDROID_RECORDING_PRESET_VOICE_RECOGNITION` mode?

I see that SDL interfaces with the `AudioRecord` class, which can be configured with the `MediaRecorder.AudioSource.VOICE_RECOGNITION` flag. But if device manufacturers don't implement this feature this won't work either.

There might be one option left: fake the headphone jack interrupt. I just found these sources:

Chapter XII - The Android Input Architecture
http://newandroidbook.com/Book/Input.html

https://android.googlesource.com/kernel/exynos/+/8f5424dd720c3c10241b20e1e5f37c5a22513521/drivers/misc/sec_jack.c with the functions `sec_jack_probe` and `sec_jack_remove`

Not sure if this could work, but it's worth trying.

**Comment by gaborszanto** [comment]
There is no way to force the device into the SL_ANDROID_RECORDING_PRESET_VOICE_RECOGNITION mode if the device doesn't implement it at all.
