### ISSUE TITLE
Multiple AudioPlayer on android

### ISSUE THREAD

**Issue by mfpolat** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#546]
I am trying to make an application based on Superpowered android sdk,
I created array of audioplayer but its not working correctly 

here is my code any help to make it work 

`#include <jni.h>
#include <string>
#include <android/log.h>
#include <AndroidIO/SuperpoweredAndroidAudioIO.h>
#include <SuperpoweredAdvancedAudioPlayer.h>
#include <SuperpoweredSimple.h>
#include <SuperpoweredCPU.h>
#include <malloc.h>
#include <SLES/OpenSLES_AndroidConfiguration.h>
#include <SLES/OpenSLES.h>

#define log_print __android_log_print

static SuperpoweredAndroidAudioIO *audioIO;
static SuperpoweredAdvancedAudioPlayer *player[20];
static float *floatBuffer;
static jstring allFilePaths[20];

// This is called periodically by the audio engine.
static bool audioProcessing(
        void *__unused clientdata, // custom pointer
        short int *audio,           // buffer of interleaved samples
        int numberOfFrames,         // number of frames to process
        int __unused samplerate     // sampling rate
) {
    for (int i = 0; i < 20; ++i) {
        if (player[i]->process(floatBuffer, false, (unsigned int) numberOfFrames))
            SuperpoweredFloatToShortInt(floatBuffer, audio, (unsigned int) numberOfFrames);

    }
    return true;
}

// Called by the player.
static void playerEventCallback(
        void *__unused clientData,
        SuperpoweredAdvancedAudioPlayerEvent event,
        void *value
) {
    switch (event) {
        case SuperpoweredAdvancedAudioPlayerEvent_LoadSuccess:
            break;
        case SuperpoweredAdvancedAudioPlayerEvent_LoadError:
            log_print(ANDROID_LOG_ERROR, "PlayerExample", "Open error: %s", (char *) value);
            break;
        case SuperpoweredAdvancedAudioPlayerEvent_EOF:
            // loop track
            break;
        default:;
    };
}

extern "C"
JNIEXPORT void JNICALL
Java_com_mobimore_ubeats_ui_activity_PlayMusicActivity_onForeground(JNIEnv *env, jobject instance) {

    audioIO->onForeground();

}extern "C"
JNIEXPORT void JNICALL
Java_com_mobimore_ubeats_ui_activity_PlayMusicActivity_onBackground(JNIEnv *env, jobject instance) {

    audioIO->onBackground();

}extern "C"
JNIEXPORT void JNICALL
Java_com_mobimore_ubeats_ui_activity_PlayMusicActivity_Cleanup(JNIEnv *env, jobject instance) {

    delete audioIO;
    for (int i = 0; i < 20; ++i) {
        delete player[i];
    }
    free(floatBuffer);

}extern "C"
JNIEXPORT void JNICALL
Java_com_mobimore_ubeats_ui_activity_PlayMusicActivity_PlayAudio(JNIEnv *env, jobject instance,
                                                                 jstring filePath_) {
    const char *filePath = env->GetStringUTFChars(filePath_, 0);

    int index = 0;
    for (int i = 0; i < 20; ++i) {
        if (filePath_ == allFilePaths[i]) {
            index = i;
        }
    }
//    if (!player[index]->playing) {
    player[index]->togglePlayback();
    SuperpoweredCPU::setSustainedPerformanceMode(player[index]->playing);
//    }

    env->ReleaseStringUTFChars(filePath_, filePath);
}extern "C"
JNIEXPORT void JNICALL
Java_com_mobimore_ubeats_ui_activity_PlayMusicActivity_StopAudio(JNIEnv *env, jobject instance,
                                                                 jstring filePath_) {
    const char *filePath = env->GetStringUTFChars(filePath_, 0);
    int index = 0;
    for (int i = 0; i < 20; ++i) {
        if (filePath_ == allFilePaths[i]) {
            index = i;
        }
    }
//    if (player[index]->playing)
    player[index]->togglePlayback();
    env->ReleaseStringUTFChars(filePath_, filePath);
}extern "C"
JNIEXPORT void JNICALL
Java_com_mobimore_ubeats_ui_activity_PlayMusicActivity_ReplayAudio(JNIEnv *env, jobject instance,
                                                                   jstring filePath_) {
    const char *filePath = env->GetStringUTFChars(filePath_, 0);

    int index = 0;
    for (int i = 0; i < 20; ++i) {
        if (filePath_ == allFilePaths[i]) {
            index = i;
        }
    }
    player[index]->seek(0);
    env->ReleaseStringUTFChars(filePath_, filePath);
}extern "C"
JNIEXPORT void JNICALL
Java_com_mobimore_ubeats_ui_activity_PlayMusicActivity_StartAudio(JNIEnv *env, jobject instance,
                                                                  jint samplerate, jint buffersize,
                                                                  jobjectArray allPaths) {

    floatBuffer = (float *) malloc(sizeof(float) * 2 * buffersize);
    audioIO = new SuperpoweredAndroidAudioIO(
            samplerate,                     // sampling rate
            buffersize,                     // buffer size
            false,                          // enableInput
            true,                           // enableOutput
            audioProcessing,                // process callback function
            NULL,                           // clientData
            -1,                             // inputStreamType (-1 = default)
            SL_ANDROID_STREAM_MEDIA,        // outputStreamType (-1 = default)
            buffersize * 2                  // latencySamples
    );

    for (int i = 0; i < 20; ++i) {
        player[i] = new SuperpoweredAdvancedAudioPlayer(
                NULL,                           // clientData
                playerEventCallback,            // callback function
                (unsigned int) samplerate,       // sampling rate
                0                               // cachedPointCount
        );
        jstring string = (jstring) (env->GetObjectArrayElement(allPaths, i));
        allFilePaths[i] = string;
    }

    for (int i = 0; i < 20; ++i) {
        const char *filePath = env->GetStringUTFChars(allFilePaths[i], 0);
        player[i]->open(filePath);
    }

}`

**Comment by gaborszanto** [comment]
"I created array of audioplayer but its not working correctly" <- What is your issue?

**Comment by mfpolat** [comment]
audio player not playing correct audio and if i try to play more than one player its overlapping sounds

**Comment by gaborszanto** [comment]
Your audio processing callback handles the "bufferAdd" parameter and the buffer wrong. Check the cross example project in our SDK on how to do this correctly.
