### ISSUE TITLE
Can't open files with Unicode filenames on Windows systems

### ISSUE THREAD

**Issue by carmethene** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#547]
Windows NTFS encodes file and folder names in Unicode.  We've been manually converting filenames down to ASCII thus-far, but we now have some users in non-English territories who have non-ASCII characters in their folders, e.g. accented letters in their user names.

The following functions only allow for ASCII filenames and so these users cannot access any files in their standard Windows folders, despite them having valid paths:

SuperpoweredDecoder::open()
SuperpoweredAdvancedAudioPlayer::open()

Would it be possible to add overloads of these functions that receive the path as a const wchar_t* instead of a const char* and call the appropriate Windows wide-string functions (e.g. wfopen vs fopen)?

**Comment by gaborszanto** [comment]
Hello,

sorry for this bug. The next update will have the fix, where you will be able to use a UTF-8 encoded path with open(). (Not a wchar_t, still a const char *.)

**Comment by carmethene** [comment]
UTF-8 will solve the problem perfectly.  Thanks Gabor!

**Comment by gaborszanto** [comment]
The next update will come in a few weeks, maybe earlier. I just checked the fix and it works, so i close this.

**Comment by carmethene** [comment]
Thanks @gaborszanto!  Just to check, it'll be in the next update, not the v1.3.0 that just came out?
