### ISSUE TITLE
Custom file handling callbacks

### ISSUE THREAD

**Issue by rh101** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#548]
Is there any possibility of implementing a callback to handle file open, read, seek, and tell, similar to what is provided in libvorbis (ov_callbacks) and libmpg123 (mpg123_replace_reader_handle)?

The reason is that by allowing this approach, the audio data stream can come from any source.  An example would be a virtual file system, and more specifically where the audio files are contained within a ZIP file, which is mounted in the virtual file system framework.  The file operations need to go through this framework in order to correctly access the data in these audio files.  

At the moment the file handling is done internally in SuperpoweredSDK, so there is no way to support this.

**Comment by gaborszanto** [comment]
Thank you for the feature request.
