### ISSUE TITLE
Compiling USBExample

### ISSUE THREAD

**Issue by bem1009** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#549]
Hi,

I am currently trying to build and run a Superpowered SDK example project (SuperpoweredUSBExample by importing through build.gradle), however I am running into the following error when building:

```
Build command failed.
Error while executing process C:\Users\bmiller\AppData\Local\Android\Sdk\cmake\3.6.4111459\bin\cmake.exe with arguments {--build C:\Users\bmiller\Downloads\SuperpoweredSDK\SuperpoweredSDK\Examples_Android\SuperpoweredUSBExample\complexusb\.externalNativeBuild\cmake\debug\arm64-v8a --target SuperpoweredExample}
[1/4] Building CXX object CMakeFiles/SuperpoweredExample.dir/latencyMeasurer.cpp.o
[2/4] Building CXX object CMakeFiles/SuperpoweredExample.dir/C_/Users/bmiller/Downloads/SuperpoweredSDK/SuperpoweredSDK/Superpowered/AndroidIO/SuperpoweredAndroidAudioIO.cpp.o
ninja: build stopped: .
ninja: error: mkdir(CMakeFiles/SuperpoweredExample.dir/C_/Users/bmiller/Downloads/SuperpoweredSDK/SuperpoweredSDK/Superpowered/AndroidIO): No such file or directory
```

Here is my current CMakeLists.txt for the complexusb app (simpleusb is identical)

```
cmake_minimum_required(VERSION 3.4.1)

# convert SDK path to forward slashes on Windows
file(TO_CMAKE_PATH ${PATH_TO_SUPERPOWERED} PATH_TO_SUPERPOWERED)

include_directories(src/main/jni)
include_directories(${PATH_TO_SUPERPOWERED})

file(GLOB CPP_FILES "*.cpp")

# compile USB example to a native library
add_library(
	SuperpoweredExample
	SHARED
	${CPP_FILES}
	${PATH_TO_SUPERPOWERED}/AndroidIO/SuperpoweredAndroidAudioIO.cpp
)

# link the native library against the following libraries
target_link_libraries(
    SuperpoweredExample
    log
    android
    OpenSLES
    ${PATH_TO_SUPERPOWERED}/libSuperpoweredAndroid${ANDROID_ABI}.a
)
```

Anyone know how to resolve this error? Is my AndroidIO directory in the wrong spot? 
CMake looks like it's looking at the correct path.

Any suggestions would be greatly appreciated.
Thanks

**Comment by gaborszanto** [comment]
PATH_TO_SUPERPOWERED seems to get a wrong value, the path of "C_" doesn't look correct
or parts of the SDK are missing, did you accidentally remove files/folders from it?

**Comment by bem1009** [comment]
I don't believe so because I've tried downloading the SDK twice and get the same error. 

Is it ok to open the example project using file->open->project's topmost build.gradle? Or should I be using the 4 step process in the README

Assuming it is ok, where would I be able to manually alter the path that involves "C_"?

**Comment by bem1009** [comment]
Fixed, I deleted the following line of code

`${PATH_TO_SUPERPOWERED}/AndroidIO/SuperpoweredAndroidAudioIO.cpp`

And just copied the ANDROIDIO folder into each app's jni folder.

**Comment by trinhcu18** [comment]
Did you find out the solution, @bem1009 ? I have the same problem
