### ISSUE TITLE
SuperpoweredAndroidAudioIO buffer problem at startup

### ISSUE THREAD

**Issue by hakoptak** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#550]
This issue is root cause of issue #545.

**The problem in short**

When I start my test app I find an unusual high latency when processing the microphone input. Furthermore, my test app zeros out the input/output buffer (silence) in the callback but I still hear some left overs from the microphone input through my device speaker. Hence, there seems to be a problem with the buffer handling of SuperpoweredAndroidAudioIO at startup.

**The solution**

After a lot of trial and error I found that when I replaced the SuperpoweredAndroidAudioIO with [opensl_stream](https://github.com/nettoyeurny/opensl_stream) the input latency and microphone left overs disappeared.

@gaborszanto: could you pinpoint why this solution works? I tried but failed...

Thanks in advance!

**Comment by hakoptak** [comment]
For what I understand is that SuperpoweredAndroidAudioIO uses a fifo buffer while opensl_stream keeps the input and output into separate buffers. It thus seems that the read and write index of the fifo buffer get out of sync somehow...

**Comment by gaborszanto** [comment]
We will check this in a few weeks (i hope).

**Comment by oazya500** [comment]
some time my app has problem and work after force stop

**Comment by romanbsd** [comment]
Subscribing to updates to this issue.

**Comment by gaborszanto** [comment]
Can you please test the attached test version of SuperpoweredAndroidAudioIO please?
[SuperpoweredAndroidAudioIO.cpp.zip](https://github.com/superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform/files/2755497/SuperpoweredAndroidAudioIO.cpp.zip)

**Comment by oazya500** [comment]
up to now it is ok with me . if the problem back I will tell you

**Comment by oazya500** [comment]
up to now it is ok with me . if the problem back I will tell you

**Comment by oazya500** [comment]
up to now it is ok with me . if the problem back I will tell you

**Comment by hakoptak** [comment]
Hi Gabor, sorry for my late response! I am now going to test your version...

**Comment by hakoptak** [comment]
Unfortunately your version didn't solve the problem. To test your code I've used the following:

```
#define STEREO_SAMPLE_SIZE 2 * sizeof(float)

static float* _stereo_buffer = (float*)malloc(_buffer_size * STEREO_SAMPLE_SIZE);

bool play_record_callback(void* __unused client_data, short int* input_output, int samples, int __unused sample_rate)
{
	// work with float buffer
	SuperpoweredShortIntToFloat(input_output, _stereo_buffer, (unsigned int)samples);
	
	// convert to silence
	memset(_stereo_buffer, 0, STEREO_SAMPLE_SIZE * samples);
	
	// convert back into android format
	SuperpoweredFloatToShortInt(_stereo_buffer, input_output, (unsigned int)samples);

	return true;
}
```

Here the `_buffer_size` parameter is set through the JNI function at startup (960 samples for my MotoG3 device). Switching back to the `opensl_stream` implementation instantly fixed the problem.

The fact that plugging my headphones in and out makes the problem go away (just as before) suggests that it is a timing issue related to buffering. In this case Logcat reports:

```
W/AudioTrack: dead IAudioTrack, PCM, creating a new one from obtainBuffer()
W/AudioRecord: dead IAudioRecord, creating a new one from obtainBuffer()
```

The OpenSL ES buffers are now recreated/reset and the timing issue becomes irrelevant because we are already running now. What I see is that the `opensl_stream` implementation has some timing related logic at startup but I need to dive in to see if this is part of the solution. I'll come back to this later.

Thanks for following up.

**Comment by gaborszanto** [comment]
Do you still hear the leftovers from mic input to device speaker?

**Comment by hakoptak** [comment]
Yes and I am experiencing a low latency. But only at startup, not when I've plugged my headphones in and out...

**Comment by gaborszanto** [comment]
What happens if you start with headphones already plugged in?
How do you measure latency if you zero the input?

**Comment by hakoptak** [comment]
I've just tested with my headphones plugged in at startup: same problem. However, when plugging out the problem remains (Logcat report that only the IAudioRecord buffer is recreated, not the IAudioTrack).

I "measure" the latency with a simple sound detection algorithm and some visual feedback. When everything works fine it responds immediately, else with a lag. To be clear: I am only talking about the input latency here. Also: the detection algorithm does not interfere since I have a handler with and without it.

**Comment by gaborszanto** [comment]
Please explain your latency detection in detail, i still don't understand how measuring latency is possible with zeroing the input.

**Comment by hakoptak** [comment]
Of course:

1. Convert and copy the `input_output` into the `_stereo_buffer`:
`SuperpoweredShortIntToFloat(input_output, _stereo_buffer, (unsigned int)samples);`

2. Hand over the `_stereo_buffer` to the detection algorithm. When this function finds a cue (a beep in my case), it signals the game loop to draw a square. This signalling is done via an SDL_event and is thread safe.

3. After detection zero the `_stereo_buffer`:
`memset(_stereo_buffer, 0, STEREO_SAMPLE_SIZE * samples);`

4. Covert and copy back into input_output buffer:
`SuperpoweredFloatToShortInt(_stereo_buffer, input_output, (unsigned int)samples);`

I hope this makes sense. So it's not really measuring latency, just using some visual cues. And I now realize that it could well be that this is not really a latency issue but more a mangling up of the input due to the leftovers... It only appears to be that way. Maybe we should indeed forget about the latency.

**Comment by gaborszanto** [comment]
It looks like we have a non-issue here then, but some wrong measurement. I'm not sure what your goal is with this. But your "issues" are perhaps coming from the fact that Superpowered sets up a "low latency" audio path with different scheduling in the Android system space vs. the other solution. So i close this now and if you've questions please don't hesitate to contact us.

**Comment by hakoptak** [comment]
Hi Gabor, the issue with the leftovers is quite real but I think we somehow do not understand each other (partly my fault since I brought up latency). My goal here is to help improve your product (I have a working setup with `opensl_stream` after all) and I am well aware that this might be an edge case. Just to make sure we're on the same page: by zeroing the input I don't mean initializing SuperpoweredAudioIO without input. If you cannot investigate further then at least I have provided a workaround for those who may also experience this edge case. Thanks for your time.

**Comment by gaborszanto** [comment]
This new test version sets all buffers to zero on start. Therefore it's impossible to have any leftovers inside SuperpoweredAndroidAudioIO.
I still don't understand what issue or edge case do you have. Please explain what you do and perhaps show some code snippets as well.

**Comment by hakoptak** [comment]
The issue is that when I clear the input and divert it to the output I still hear the input (e.g. the noise when I blow into the mic):

```

SuperpoweredAndroidAudioIO* audio_io = new SuperpoweredAndroidAudioIO(sample_rate, buffer_size, true, true, io_callback, NULL, SL_ANDROID_RECORDING_PRESET_VOICE_RECOGNITION, SL_ANDROID_STREAM_MEDIA, buffer_size);

bool io_callback(void* __unused client_data, short int* input_output, int samples, int __unused sample_rate)
{
	// work with float buffer
	SuperpoweredShortIntToFloat(input_output, _stereo_buffer, (unsigned int)samples);
	
	// convert to silence
	memset(_stereo_buffer, 0, STEREO_SAMPLE_SIZE * samples);
	
	// convert back into android format
	SuperpoweredFloatToShortInt(_stereo_buffer, input_output, (unsigned int)samples);

	return true;
}
```

This should be impossible but it happens. But even more important: it does not happen with `opensl_stream`. Same memset(0). And the problem disappears after plugging in and out headphones.

All code snippets I use are listed above, really. Since it is so strange, I suspect it to be a device dependent edge case. I could try to test on another MotoG device, but that'll take some time since I am quite busy with other things. Let me come back to this after I have tested on my friends MotoG device, ok?

**Comment by gaborszanto** [comment]
Why do you convert from short int, memset, then back to float? You can memset input_output directly.
What's the use of _stereo_buffer then? How does it coming from?

**Comment by hakoptak** [comment]
You are right that it's a bit cumbersome. I put them in because I use these steps in the more advanced stuff (instead of using memset(0) ;)). I am sorry if this confuses you. The `_stereo_buffer` is defined above (my 4th post above).

For your information: using

`memset(input_output, 0, 2 * sizeof(short int) * samples);`

on `input_output` directly does not solve the issue. Let me come back to this in a later moment when I have tested on the other MotoG device, okay?

**Comment by gaborszanto** [comment]
Another possibility is that your device implements SL_ANDROID_RECORDING_PRESET_VOICE_RECOGNITION with some bugs. It happens.
opensl_stream doesn't set that.
Maybe you can try SL_ANDROID_RECORDING_PRESET_GENERIC for input stream type and -1 for output stream type.

**Comment by hakoptak** [comment]
Thanks for that suggestion. I've just tested it with these parameters but no luck... I've even disabled the SLAndroidConfigurationItf code block for input and output in SuperpoweredAndroidAudioIO to mirror opensl_stream, but still no improvement. I then added the SLAndroidConfigurationItf code with params SL_ANDROID_RECORDING_PRESET_VOICE_RECOGNITION and SL_ANDROID_STREAM_MEDIA to opensl_stream, and it still functions properly.

My knowledge of OpenSL ES is zero so I find it hard to pinpoint the problem. But let me sleep on it :)

**Comment by gaborszanto** [comment]
The test IO class outputs two values to LogCat with the text "mytest". Can you please let me know the values there?

**Comment by hakoptak** [comment]
It outputs:

mytest 960 960
mytest 960 960

**Comment by gaborszanto** [comment]
Do you continuously hear back from the microphone, or just for a moment at start?

**Comment by hakoptak** [comment]
I just did a test over a longer time period: turning up the volume I hear a continuously feedback loop effect from the very beginning... Plugging in and out the headphones and it creates silence, as expected. So it has to do with way the underlying OpenSL buffers are read at startup (LogCat reports that they are recreated when the audio is routed through the headphones and back to speaker). Very strange indeed.

**Comment by oazya500** [comment]
problem is back again 

http://mesbahey.com/a.mp4

**Comment by oazya500** [comment]
dear gaborszanto did you see the video and know what is the problem

**Comment by gaborszanto** [comment]
@oazya500 For your application you need audio input open?

**Comment by hakoptak** [comment]
Dear @oazya500, I saw/heard the glitch in your audio but this issue is about the (microphone) input. To address your issue, it would be beter to create a new issue thread and expose some details about your implementation. It could be related to my issue but I would have to check if this is the case.

**Comment by gaborszanto** [comment]
@oazya500 If your application doesn't need audio input, create the audio I/O instance with input set to false.

**Comment by oazya500** [comment]
it is false I think problem related to buffer . you can check my implementation in the links 

https://mesbahey.com/Player1/App.java
https://mesbahey.com/Player1/Player.java
https://mesbahey.com/Player1/SuperPlayer.cpp

**Comment by hakoptak** [comment]
@oazya500: I cannot reproduce my issue with the input flag set to false and output set to true (memset(0) outputs true silence). Only with input and output enabled I hear left overs from the mic.

**Comment by gaborszanto** [comment]
Please try the attached file and let me know if it helps.
[SuperpoweredAndroidAudioIO.cpp.zip](https://github.com/superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform/files/2803657/SuperpoweredAndroidAudioIO.cpp.zip)

**Comment by hakoptak** [comment]
This did not do the trick, but I found the solution: setting the latency samples parameter to **twice** the buffer size fixed the issue. It failed when is was set to 0 or buffer size on my MotoG3 device.

So the correct instantiation is

`SuperpoweredAndroidAudioIO* audio_io = new SuperpoweredAndroidAudioIO(sample_rate, buffer_size, true, true, io_callback, NULL, SL_ANDROID_RECORDING_PRESET_VOICE_RECOGNITION, SL_ANDROID_STREAM_MEDIA, 2 * buffer_size);`

This was set correctly in your examples, but the default value in its header definition equals 0.

Suggestion: add comment that it should be at least twice the buffer size when experiencing this issue?

**Comment by gaborszanto** [comment]
I'm happy that you found a workaround, but i keep searching for the real cure. Please try the attached file with latency samples parameter set to buffer size (so it's _not_ doubled).
[SuperpoweredAndroidAudioIO.cpp.zip](https://github.com/superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform/files/2808812/SuperpoweredAndroidAudioIO.cpp.zip)

**Comment by hakoptak** [comment]
No luck unfortunately... It only works with twice the buffer size for the latency samples.

Let me put some extra logging in to see if the OpenSL callbacks arrive in expected order.  You'll hear from me in a couple of days. Thus far I did not find any inconsistencies in your original code.

**Comment by hakoptak** [comment]
You fixed it! I will keep testing, but at this moment I cannot reproduce the issue.

Finally I can continue creating my Superpowered game :)
Thanks for taking this issue seriously.
