### ISSUE TITLE
Sample rate issue with device speaker and earphone

### ISSUE THREAD

**Issue by surjeetsg** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#551]
I am developing an app using SuperpoweredAdvancedAudioPlayer. As per my requirement, I need to play multiple players at same time, each with a different file for a song like Vocal, Instruments, etc.   
I load all the tracks and set the same sample rate 44100 (if output is earphone) or 48000 (if output is device speaker) for SuperpoweredAdvancedAudioPlayer and output.
Below is the code, how I configure SuperpoweredAdvancedAudioPlayer:
```
samplerate = 48000;
    if ([self isHeadphonesConnected]) {
        samplerate = 44100;
    }
    //     SuperpoweredAdvancedAudioPlayer::setTempFolder([NSTemporaryDirectory() fileSystemRepresentation]);
    playerV = new SuperpoweredAdvancedAudioPlayer((__bridge void *)self, playerEventCallbackVoice, samplerate, 0);
audioIOV = [[SuperpoweredIOSAudioIO alloc] initWithDelegate:(id<SuperpoweredIOSAudioIODelegate>)self preferredBufferSize:12 preferredSamplerate:44100 audioSessionCategory:AVAudioSessionCategoryPlayback channels:2 audioProcessingCallback:audioProcessingV clientdata:(__bridge void *)self];
[audioIOV start];
```
With above code, all players works fine and played songs in sync, because of that, it doesn't feels like I am playing multiple songs.
Now while players are playing song, If I switch output from device speaker to earphone or earphone to device speaker, players losses their sync with each other, and all played at a different rate.
To resolve that, I used below code and update player samplerate if any change received with below code:

```
static bool audioProcessingV(void *clientdata, float **buffers, unsigned int inputChannels, unsigned int outputChannels, unsigned int numberOfSamples, unsigned int samplerate, uint64_t hostTime) {
    __unsafe_unretained ModifyViewController *self = (__bridge ModifyViewController *)clientdata;
    if (self->samplerate != samplerate) {
        self->samplerate = samplerate;
        self->playerV->setSamplerate(self->samplerate);
    };
    NSLog(@"Vocal: %f samplerate: %i ", self->playerV->positionMs, samplerate);
    bool hasAudio = self->playerV->process(self->interleavedBuffer, false, numberOfSamples, self->_playerVVolume);
    if (hasAudio) SuperpoweredDeInterleave(self->interleavedBuffer, buffers[0], buffers[1], numberOfSamples);
    return hasAudio;
}
```

But still It doesn't works and keeps playing out of sync each other and some players played with faster rate (like 1.25 or 1.5) instead of 1 while other are playing at same rate. 

When I checked played duration with **self->playerV->positionMs**, before switching all players return same time for  **positionMs** but after switching all return a different time. Also this time difference keeps increasing if I keeps play players.

Do you have any advice on this, How can I play multiple players in sync of each other ?

**Comment by gaborszanto** [comment]
I don't see multiple players in your code. You need exactly ONE audio I/O instance (SuperpoweredIOSAudioIO) and multiple SuperpoweredAdvancedAudioPlayer instances.

**Comment by surjeetsg** [comment]
I have created 4-5 players instances with same config. With that I faced issue as mentioned above

**Comment by gaborszanto** [comment]
So you are absolutely sure that you have: 1 instance of IO and 4 instances of players?

**Comment by surjeetsg** [comment]
No, I have equal instance of IO as of players. 
For reference, I have written two player and their IO below:  

**Player initialisation:**
playerOne = new SuperpoweredAdvancedAudioPlayer((__bridge void *)self, playerEventCallbackVoice, samplerate, 0);
    playerTwo = new SuperpoweredAdvancedAudioPlayer((__bridge void *)self, playerEventCallbackBass, samplerate, 0);

**IO's initialisation:**

 audioIOOne = [[SuperpoweredIOSAudioIO alloc] initWithDelegate:(id<SuperpoweredIOSAudioIODelegate>)self preferredBufferSize:12 preferredSamplerate:44100 audioSessionCategory:AVAudioSessionCategoryPlayback channels:2 audioProcessingCallback:audioProcessingV clientdata:(__bridge void *)self];
    [audioIOOne start];
    audioIOTwo = [[SuperpoweredIOSAudioIO alloc] initWithDelegate:(id<SuperpoweredIOSAudioIODelegate>)self preferredBufferSize:12 preferredSamplerate:44100 audioSessionCategory:AVAudioSessionCategoryPlayback channels:2 audioProcessingCallback:audioProcessingB clientdata:(__bridge void *)self];
    [audioIOTwo start];

I have create multiple instance of IO, since I need to track progress of each player, and need to adjust my UI as per progress.

Let me know, if this creates any isssue.

**Comment by gaborszanto** [comment]
Yes, that is the issue. You need ONE audio I/O and multiple players. Any app should have exactly ONE and no more audio I/O.

**Comment by surjeetsg** [comment]
I have made few changes in one of the sample code from your repository to generate issue which I am facing . 
Here is the updated iOS code:
https://www.dropbox.com/s/1dc9wszxwpllgji/SuperpoweredCrossExample.zip?dl=0

My requirement is to play multiple (2 player in sample code) player simultaneously. 
And to test sync of both players, I opened same audio file on both players. If you play this sample, you could clearly listen both song playing out of sync to each other.
Please help to fix this issue.

**Comment by gaborszanto** [comment]
I already told you what is the issue. Furthermore the SDK has an example project as well, running two players in sync (cross example).

**Comment by surjeetsg** [comment]
I have checked that sample, but seems that doesn't work in sync.  
I changed example project audio files with mine, and played same track on both player, and clearly listen one player following other with some delay, and completely out of sync.
I have uploaded **updated cross example** on dropbox and provide you link for same sample project.

**Comment by gaborszanto** [comment]
Cross example not only starts playback at the same time, but synchronizes bpm and beatgrid as well. 

Of course the new files don't sync, because their bpm and beatgrid is different to the included example files.
