### ISSUE TITLE
Audio sync issue when played multiple players simultaneously 

### ISSUE THREAD

**Issue by surjeetsg** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#552]
For the issue #551 , 

I have made few changes in one of the sample code from your repository to generate issue which I am facing . This sample code have 1 audio I/O and 2 players.
Here is the updated iOS code:
https://www.dropbox.com/s/1dc9wszxwpllgji/SuperpoweredCrossExample.zip?dl=0

My requirement is to play multiple (2 player in sample code) player simultaneously.
And to test sync of both players, I opened same audio file on both players. If you play this sample, you could clearly listen both song playing out of sync to each other.
Please help to fix this issue.

**Comment by gaborszanto** [comment]
I close this now, because it's discussed at #551 . We don't provide custom code support for free btw.
