### ISSUE TITLE
iOS record permission delegate never called

### ISSUE THREAD

**Issue by roussetjc** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#553]
Hi everyone,
Unless I'm missing something, it seems that the delegate method which handles the record permission is never called even if the user denied:
`- (void)recordPermissionRefused { }`

I was also wondering: what is the reason why `- (void)mapChannels` method is called multiple times?
Thanks!

**Comment by gaborszanto** [comment]
It is definitely called, i just tested. Right after the user responds "no" when iOS asks for the permission, or any time when it is already refused and an audio session is opened with a record audio session category.
mapChannels is called every time when iOS changes the audio route.

**Comment by roussetjc** [comment]
I tested again. Curiously, it is not called if the category `AVAudioSessionCategoryPlayAndRecord` is declare in the `initwithdelegate` method:
`    audioIO = [[SuperpoweredIOSAudioIO alloc] initWithDelegate:(id<SuperpoweredIOSAudioIODelegate>)self preferredBufferSize:bufferSize preferredSamplerate:sampleRate audioSessionCategory:AVAudioSessionCategoryPlayAndRecord channels:channels audioProcessingCallback:audioProcessing clientdata:(__bridge void *)self];`

However, if I add `[audioIO reconfigureWithAudioSessionCategory:AVAudioSessionCategoryPlayAndRecord];`, everything is fine.

**Comment by gaborszanto** [comment]
I see. That is not handled properly, will change.

**Comment by gaborszanto** [comment]
The next update will have this fixed. Meanwhile please use this:

[SuperpoweredIOSAudioIO.mm.zip](https://github.com/superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform/files/2812779/SuperpoweredIOSAudioIO.mm.zip)
