### ISSUE TITLE
"Open error: Data connection lost" in Android

### ISSUE THREAD

**Issue by sahil-sdei** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#554]
I am getting "Open error: Data connection lost" in player callback while trying to play a progressive download url if another url is already playing.

I am calling player->togglePlayback() if player is playing before calling the player->open(str);

Audio url - "https://d3ed4soouou2ye.cloudfront.net/remix/d6f7977bca70/f1d5fd1ae3275887.m4a"

**Comment by gaborszanto** [comment]
I can't reproduce the issue. I tried opening your url in the cross example project on both players simultaneously and it just works.
