### ISSUE TITLE
some time glitch audio 

### ISSUE THREAD

**Issue by oazya500** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#555]
app work fine but some time there is glitch in audio and not fix again unless force stop app . some time must restart phone 

https://mesbahey.com/a.mp4
https://mesbahey.com/Player1/App.java
https://mesbahey.com/Player1/Player.java
https://mesbahey.com/Player1/SuperPlayer.cpp

**Comment by gaborszanto** [comment]
You need one audio I/O instance open with multiple players, don't re-create audio I/O and players every time.

**Comment by oazya500** [comment]
it is one at app starte 

this methode called at starte app 

> Player::Player(unsigned int samplerate, unsigned int buffersize, float *frequencies) : crossValue(
        0.0f), volB(0.0f), volA(1.0f * headroom) {
    stereoBuffer = (float *) memalign(16, (buffersize + 16) * sizeof(float) * 2);
    playerA = new SuperpoweredAdvancedAudioPlayer(&playerA, playerEventCallbackA, samplerate, 0);
    bandEQ = new SuperpoweredNBandEQ(samplerate, frequencies);
    bandEQ->enable(true);
    SuperpoweredCPU::setSustainedPerformanceMode(true);
    audioSystem = new SuperpoweredAndroidAudioIO(samplerate, buffersize, false, true,
                                                 audioProcessing, this, -1, SL_ANDROID_STREAM_MEDIA,
                                                 buffersize * 2);
    audioSystem->stop();
}



and this call att open file

> void Player::PlayFile(const char *path) {
    audioSystem->start();
    playerA->open(path);
    playerA->setTempo(1, true);
}


and this player.h class

> 
#ifndef Header_SuperpoweredExample
#define Header_SuperpoweredExample
#include <math.h>
#include <AndroidIO/SuperpoweredAndroidAudioIO.h>
#include <SuperPlayer/SuperpoweredAdvancedAudioPlayer.h>
#include <SuperPlayer/SuperpoweredNBandEQ.h>
#include <SuperPlayer/SuperpoweredReverb.h>
#define HEADROOM_DECIBEL 3.0f
static const float headroom = powf(10.0f, -HEADROOM_DECIBEL * 0.025f);
class Player {
public:
    Player(unsigned int samplerate, unsigned int buffersize, jfloat *fileAoffset);
    ~Player();
    bool process(short int *output, unsigned int numberOfSamples);
    void onPlayPause(bool play);
    double getCurentBpm();
    double getDefulteBpm(int Bpm);
    void onSpeed(int value);
    void onEQBand(unsigned int index, int gain);
    void PlayFile(const char *path);
private:
    SuperpoweredAndroidAudioIO *audioSystem;
    SuperpoweredAdvancedAudioPlayer *playerA;
    SuperpoweredNBandEQ *bandEQ;
    float *stereoBuffer;
    float crossValue, volA, volB;
};
#endif

**Comment by oazya500** [comment]
if app start and play file normal it work normal until close app . but if start app and there is glitch it not fix until force stop app . some time must restart phone to work normal

**Comment by oazya500** [comment]
my problem is with SuperpoweredNBandEQ . I did not set 0-terminated list of frequency bands
after I add 0 to end off my list the app work fine 

thanks
