### ISSUE TITLE
How can i mix Audio played in headhones to the input audio.

### ISSUE THREAD

**Issue by AshutoshXus** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#556]
I want to add audio played in the headphones using Superpowered player to input by Superpowered recorder.

THanks
Ashutosh

**Comment by gaborszanto** [comment]
The player puts the output into a buffer (when it does process). You need to pass that buffer to the recorder's process() method.
