### ISSUE TITLE
iOS - Recorded audio sounds different from actual voice

### ISSUE THREAD

**Issue by mrikh** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#557]
I am using the library to record and playback another audio simultaneously. Everything is working fine apart from one thing and that is that the recorded audio sounds different from my actual voice. Even if I don't play the music in the background the issue remains the same. I am attaching a sample project for your reference in which the issue occurs. I have mostly picked up stuff from the SDK examples where i could.

[TestSuperpower.zip](https://github.com/superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform/files/2816125/TestSuperpower.zip)

Edit: Also is there any way so that the recorder only records the vocal inputs and not the background music?

**Comment by gaborszanto** [comment]
You need to set the recorder's samplerate to the actual samplerate of the audio processing callback.

We don't offer noise suppression features, sorry.
