### ISSUE TITLE
iOS 12 + Airplay Hang

### ISSUE THREAD

**Issue by flagoworld** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#558]
I believe this is new to iOS 12, but if one switches to AirPlay while audio is playing, the audioProcessingCallback stops being called and the player hangs. open()ing after that causes the open() command to hang as expected and the whole program freezes up.

I tracked the problem down to SuperpoweredIOSAudio.mm, line 381:

```
div_t d = div(inNumberFrames, 8);
if ((d.rem != 0) || ((int)inNumberFrames < self->minimumNumberOfFrames) || ((int)inNumberFrames > self->maximumNumberOfFrames) || ((int)ioData->mNumberBuffers != self->numChannels)) {
    return kAudioUnitErr_InvalidParameter;
};
```

What's happening, only when switching between airplay and iphone, is that at least one time this callback is called the inNumberFrames variable is 1114, which is not divisible exactly by 8. So the kAudioUnitErr_InvalidParameter is returned, and the OS keeps retrying the callback with the same inNumberFrames. This causes the audio processing callback to never be called.

By removing the check for divisibility by 8, everything seems to work...

Are there any known side effects in doing this? Is this an OS bug or a change in iOS 12? It may have been present before then but I only just noticed it. Seems unlikely that it's been like this for years. Is there a better recommended workaround or fix? I don't understand the point of ensuring divisibility, so if you could educate me on why this check exists maybe I can suggest an actual fix and not just a work around.

Thanks

**Comment by gaborszanto** [comment]
I can't reproduce this on my Apple TV currently. However there will be a slightly changed source for this in the upcoming version of Superpowered. Please try the attached file and let me know.
[iosio.zip](https://github.com/superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform/files/2828764/iosio.zip)

**Comment by flagoworld** [comment]
OK I will give it a try. One thing I forgot to mention... try turning airplay on while mid playback. I think that repro's it much more consistently.

**Comment by gaborszanto** [comment]
Yes, i turned it on mid playback.

**Comment by gaborszanto** [comment]
Success? No?

**Comment by flagoworld** [comment]
It looks like you accidentally sent me the OSXAudioIO, I need the iOSAudioIO. Thanks

**Comment by gaborszanto** [comment]
Sorry, please try this.

[ios.zip](https://github.com/superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform/files/2842017/ios.zip)

**Comment by flagoworld** [comment]
Still happens. It's stuck returning kAudioUnitErr_InvalidParameter and not calling self->processingCallback inside the coreAudioProcessingCallback. In number of frames is 1114, which is not divisible by 8.

If it helps, this is on an iPhone Xs.

**Comment by flagoworld** [comment]
I think this is due to the AudioStreamBasicDescription.mFormat changing when switching between internal speakers and airplay. I tested and can confirm that the format's sample rate is changing but the streamFormatChangedCallback is not always getting called.

More info on this: https://github.com/libpd/libpd/issues/177

**Comment by flagoworld** [comment]
https://developer.apple.com/library/archive/qa/qa1777/_index.html

**Comment by gaborszanto** [comment]
Okay, please test this for me then (i still can't reproduce the issue on my devices):
[SuperpoweredIOSAudioIO.mm.zip](https://github.com/superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform/files/2845994/SuperpoweredIOSAudioIO.mm.zip)

**Comment by flagoworld** [comment]
I actually tried that change you made with listening for SampleRate to no avail yesterday. In further testing what I am seeing is that the sample rate is not changing when you switch between airplay and local speakers, but it does change if you kill the app, switch output device, and then reopen the app. It seems as though the audio unit is doing a "Sample Rate Conversion" (per apples docs above) instead of changing the stream format when the output device changes on the fly. As it is documented that this can happen, I think the assumption in coreAudioProcessing that inNumberSamples will always be divisible by 8 is incorrect. What do you think? I have a suspicion, and I will test next week, that restarting the audio unit when the output device changes will also fix the problem. But that is not ideal. Ideally superpowered gracefully deals with these "Sample Rate Conversions" that the audio unit is doing. Removing the check for div(inNumberFrames, 8) does not seem to break anything. Is there a reason that existed? Could it break something? That said, my understanding of all this is still very limited so I may be missing something obvious.

**Comment by gaborszanto** [comment]
Perfect matching with the hardware sample rate is important for audio quality and performance. Div by 8 is also great for performance, and some audio engines may require that too.
Please try the attached file, it tries to recreate the audio unit when it detects this problem and let me know.
[SuperpoweredIOSAudioIO.mm.zip](https://github.com/superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform/files/2851297/SuperpoweredIOSAudioIO.mm.zip)

**Comment by flagoworld** [comment]
That seems to work! The only thing is that the coreAudioProcessingCallback gets called multiple times while the audio unit is being restarted... I have no idea if there's consequence to that, but in general my experience with things like that is to add a variable, lock, etc that gets checked and prevents the action from happening again while it's already happening. So like... self.isRestartingAudioUnit = true, iif(self.isRestartingAudioUnit) return;, etc etc.

One more thing, on line 98 the [self release] should be surrounded in "#if !__has_feature(objc_arc) ... endif"

**Comment by gaborszanto** [comment]
Yes, div.rem != 0 is called multiple times, because the actual "restart" of the audio unit is happening on the main thread. However the self->audioUnitRunning condition prevents the reset happening multiple times, so it's harmless.
The next update will have this new version and that release thing at line 98 as well.
