### ISSUE TITLE
Oreo SIGBUS fault in player and cross examples 

### ISSUE THREAD

**Issue by contriteobserver** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#563]
SIGBUS in `SuperpoweredAdvancedAudioPlayer.open(const char *path, int offset, int length)`,
works fine with Nougat

com.superpowered.playerexample A/libc: Fatal signal 7 (SIGBUS), code 2, fault addr 0x77e631b000 in tid 8215 (AudioFile Read)

com.superpowered.crossexample A/libc: Fatal signal 7 (SIGBUS), code 2, fault addr 0x77e4289164 in tid 13679 (AudioFile Read)

**Comment by gaborszanto** [comment]
Please disable Instant Run in Android Studio. Instant Run is not compatible with native projects.

**Comment by contriteobserver** [comment]
That did correct the issue, sorry, overlooked that Instant Run was turned on.

**Comment by tabahkanlahhati** [comment]
On pull request
