### ISSUE TITLE
with recent versions of Android Studio, the env var ${ANDROID_ABI} uses x86 instead of X86,

### ISSUE THREAD

**Issue by contriteobserver** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#564]
so the builds fail

**Comment by gaborszanto** [comment]
Which Android Studio version? The latest official release version (3.3.1) works just fine.

**Comment by contriteobserver** [comment]
from the Help >> About screen

Android Studio Version 3.3.1
Build #AI-182.5107.16.33.5264788, build on January 28 2019
JRE 1.8.0_152-release-1248-b01 amd64
JVN OpenJDK 64bit server VM by JetBrains s.r.o

**Comment by gaborszanto** [comment]
Windows?

**Comment by contriteobserver** [comment]
Linux

Build command failed.
Error while executing process /home/elkq/Android/Sdk/cmake/3.6.4111459/bin/cmake with arguments {--build /home/elkq/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform/Examples_Android/SuperpoweredPlayer/app/.externalNativeBuild/cmake/debug/x86_64 --target PlayerExample}

ninja: error: '../../../../../../../Superpowered/libSuperpoweredAndroidx86_64.a', needed by '../../../../build/intermediates/cmake/debug/obj/x86_64/libPlayerExample.so', missing and no known rule to make it

**Comment by gaborszanto** [comment]
Will be lowercase in the next update.
