### ISSUE TITLE
request for SuperpoweredAdvancedAudioPlayer.open(int fd)

### ISSUE THREAD

**Issue by contriteobserver** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#566]
Would be nice to have a file descriptor based open for SuperpoweredAdvancedAudioPlayer(), so we can use Java constructs such as:
```
        AssetFileDescriptor afd = getResources().openRawResourceFd(resourceId);
        int fd = afd.getParcelFileDescriptor().getFd();
        OpenFile(fd);         // open audio file from APK
```

**Comment by gaborszanto** [comment]
Thank you for the feature request.

**Comment by contriteobserver** [comment]
Is there a more appropriate way to place feature requests?
Sorry, somewhat new to this project

**Comment by gaborszanto** [comment]
i'd prefer hello@superpowered.com
