### ISSUE TITLE
Disabled microphone when screen's off on android P

### ISSUE THREAD

**Issue by loics2** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#568]
On Android P, the microphone is now disabled when the app's idle, as said [here](https://android-developers.googleblog.com/2018/03/previewing-android-p.html):

> While your app's UID is idle, the mic reports empty audio and sensors stop reporting events

My app uses a USB microphone with the following Superpowered code:

```cpp
SuperpoweredCPU::setSustainedPerformanceMode(true);
SuperpoweredUSBAudio::startIO(
    this->deviceId,
    this->inputIndex,
    this->outputIndex,
    SuperpoweredUSBLatency_High,
    nullptr,
    callback);
```

The callback is correctly called, and everything is working until the screen turns off. A few seconds after, the callback is not called anymore, but the c++ class managing Superpowered is not destroyed and still work correctly (a timer call a method of that class each second, and it still work). It seems the `SuperpoweredUSBAudio` process is not receiving anything/is killed.

I tried disabling the adaptive battery feature and turn off the battery optimization for my app, but it does not change anything. Nothing special is mentioned in `logcat`, even with `verbose` log lovel.

Could this be due to this idle UID limitation and, if that's the case, is there a way to force the microphone usage?

**Edit**: the same code was obviously working on Oreo

**Comment by gaborszanto** [comment]
I don't know any way to prevent Android's "Doze" system to put an app into the "idle" state.

**Comment by gaborszanto** [comment]
Unfortunately none of my Google contacts could respond to this via email, so i made an Android issue here: https://issuetracker.google.com/issues/127290666
