### ISSUE TITLE
Change the pitch shifting (not rate or time stretch scale) from the microphone in real-time and record it.

### ISSUE THREAD

**Issue by j-how** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#569]
I have a requirement to change the pitch shifting (not rate or time Stretch scale) from the microphone in real-time and record it.
Would you provide a complete example of using SuperpoweredTimeStretching and SuperpoweredRecorder on the same time (or just SuperpoweredTimeStretching)?

I've looked at all these issues  and stackoverflow and offline2.cpp(I have used it in my project). But there was still no answer. 
[#467](https://github.com/superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform/issues/467)[#256](https://github.com/superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform/issues/256)[#465](https://github.com/superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform/issues/465) etc.

**Comment by gaborszanto** [comment]
Sorry, but we're not providing free development for you.

**Comment by mdsitton** [comment]
That's a rather rude response, i'm not even the OP. I was considering evaluating the use of this library for it's time stretching implementation. And there is no examples or even documenation of how to use it in a real-time scenario.

I think this would be a very useful example to have....
