### ISSUE TITLE
HLS Live Streaming Doesn't Work on iOS

### ISSUE THREAD

**Issue by zsaraf** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#572]
Hello,

I'm testing the HLS iOS Example App on a custom live HLS url: http://192.168.1.36:1935/disco/Q7zkpypMymQUyJs4_vJ47_pgWn230f-Oh9xTncVkZR4xjMsD6Ti-vEUMoLMs8qlX/playlist.m3u8 (on my local network).

Live streaming this URL using any other audio processing library (IJKPlayer, VLCKit, AVPlayer, safari) works perfectly, but barely works using this library. I get <1 second of audio output every 10-15 seconds. I'm wondering why this is happening, any ideas?

Here is the entire diff of the changes that I've made to the Example app:

```
--- a/Examples_iOS/SuperpoweredHLSExample/SuperpoweredHLSExample/ViewController.mm
+++ b/Examples_iOS/SuperpoweredHLSExample/SuperpoweredHLSExample/ViewController.mm
@@ -4,7 +4,8 @@
 #include "SuperpoweredSimple.h"

 // some HLS stream url-title pairs
-static const char *urls[8] = {
+static const char *urls[10] = {
+    "http://192.168.1.36:1935/disco/Q7zkpypMymQUyJs4_vJ47_pgWn230f-Oh9xTncVkZR4xjMsD6Ti-vEUMoLMs8qlX/playlist.m3u8", "Localhost",
     "https://devimages.apple.com.edgekey.net/streaming/examples/bipbop_16x9/bipbop_16x9_variant.m3u8", "Apple Advanced Example Stream",
     "http://qthttp.apple.com.edgesuite.net/1010qwoeiuryfg/sl.m3u8", "Back to the Mac",
     "http://playertest.longtailvideo.com/adaptive/bbbfull/bbbfull.m3u8", "JW Player Test",
(END)
```

Just added in that one URL at the top of the list. Would love some insight as to what's going on here!

Best
Zach

**Comment by gaborszanto** [comment]
This is a url in your local network. We're not able to test.

**Comment by zsaraf** [comment]
Okay, I've found another live URL that works on Safari/other libraries but doesn't work in Superpowered: https://kanlivep2event-i.akamaihd.net/hls/live/749624/749624/kanbet_mp3/chunklist.m3u8

While I can't give you one of our actual streams, I can give you the m3u8 file that wasn't working:

`#EXTM3U
#EXT-X-VERSION:3
#EXT-X-STREAM-INF:BANDWIDTH=71030,CODECS="mp4a.40.2"
chunklist_w721656322.m3u8`

chunklist_w721656322.m3u8:
`#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:1
#EXT-X-MEDIA-SEQUENCE:121
#EXTINF:0.488,
media_w721656322_121.ts
#EXTINF:0.488,
media_w721656322_122.ts
#EXTINF:0.487,
media_w721656322_123.ts
#EXTINF:0.488,
media_w721656322_124.ts
#EXTINF:0.487,
media_w721656322_125.ts
#EXTINF:0.558,
media_w721656322_126.ts
#EXTINF:0.487,
media_w721656322_127.ts
#EXTINF:0.488,
media_w721656322_128.ts
#EXTINF:0.488,
media_w721656322_129.ts
#EXTINF:0.487,
media_w721656322_130.ts
#EXTINF:0.557,
media_w721656322_131.ts
#EXTINF:0.488,
media_w721656322_132.ts
#EXTINF:0.488,
media_w721656322_133.ts
#EXTINF:0.487,
media_w721656322_134.ts
#EXTINF:0.488,
media_w721656322_135.ts
#EXTINF:0.488,
media_w721656322_136.ts
#EXTINF:0.557,
media_w721656322_137.ts
#EXTINF:0.487,
media_w721656322_138.ts
#EXTINF:0.488,
media_w721656322_139.ts
#EXTINF:0.488,
media_w721656322_140.ts
#EXTINF:0.487,
media_w721656322_141.ts
#EXTINF:0.488,
media_w721656322_142.ts
#EXTINF:0.557,
media_w721656322_143.ts
#EXTINF:0.488,
media_w721656322_144.ts`

Is our target duration too low? We need ultra-low latency for HLS so our target duration is set to 1 second. I will try to work on getting our own public live stream going so that you can test on our actual file type.

Thanks

**Comment by zsaraf** [comment]
I now have a public stream that you can test this on: http://ec2-54-90-255-215.compute-1.amazonaws.com:1935/disco/blablabla/playlist.m3u8

I will try to leave this on all day, feel free to send me a ping whenever you get a chance to take a look. Now it works. BUT it takes ~10 seconds for initial playback to start and it pauses and buffers every 5-10 seconds for at least a few seconds. Once again, this doesn't happen on any other players that I've found. Any ideas why this might be happening? Is it because of the short segment size/

**Comment by gaborszanto** [comment]
This stream: 
https://kanlivep2event-i.akamaihd.net/hls/live/749624/749624/kanbet_mp3/chunklist.m3u8

Doesn't confirm to strict HLS encoding, because it has MPEG-2 audio in its MPEG-TS stream. MPEG-1 Layer III (that is: mp3) is supported. 

For audio transmissions it doesn't make sense including the audio in MPEG-TS btw, because audio can be transferred without any transmuxing.

The second stream: 
http://ec2-54-90-255-215.compute-1.amazonaws.com:1935/disco/blablabla/playlist.m3u8

Also has unnecessary MPEG-TS on top of audio. I'm investigating why audio playback stops periodically.

**Comment by zsaraf** [comment]
Thanks a lot for your fast response times @gaborszanto, really appreciate it. 

Going to look into changing our streaming server to not include the audio in MPEG-TS. Let me know what you find on the audio playback stopping periodically.

**Comment by gaborszanto** [comment]
The second stream has some strange network communication. 

The downloader thread of our HLS reader is blocking for a long time when downloading the next audio chunk (.ts file). It seems like the download begins, but then the actual payload arrives in "bursts" instead of a "normal" download.

The HLS protocol was made for regular web servers, so every file can be a simple download. Maybe you're serving the .ts files with some custom component, that is producing the bytes "live"?

**Comment by zsaraf** [comment]
Hmm, we're using a pretty basic Wowza setup. The only difference in our configuration is that we have a very small segment size (of ~1 second) because we need very low latency. Do you think that the small segment size is having an effect on reading in the files?

I don't know of any other unusual configuration settings that we have on our Wowza streaming server. If you have any experience with Wowza, I can change any configuration you want me to in order to help with testing.

It is also odd that this m3u8 URL works with Safari/AVPlayer/IJKPlayer without any problems.

Let me know how to proceed. Thanks!

**Comment by zsaraf** [comment]
Just to reiterate, the two problems that we have with the HLS link to our Wowza streaming server (http://ec2-54-90-255-215.compute-1.amazonaws.com:1935/disco/blablabla/playlist.m3u8) are:

1. Startup time for the stream (~10 seconds w Superpowered vs ~1 second with other players)
2. Buffering every 5-10 seconds throughout the stream

There is a chance that these are both symptoms of the same issue though!

**Comment by gaborszanto** [comment]
The segment size on this stream is 8+ seconds, which is definitely not too small or problematic at all.

**Comment by gaborszanto** [comment]
I don't have any experience with Wowza. However the downloads stall. I see that every fourth or fifth download doesn't complete in a short time, but it begins then stalls for 5-6 seconds and finishes after that.

**Comment by zsaraf** [comment]
I've sent an email via zendesk, closing this issue for now!
