### ISSUE TITLE
Can't create an instance of `SuperpoweredNBandEQ`

### ISSUE THREAD

**Issue by drspaceboo** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#573]
I'm writing an Android application and working with a fair number of the FX offered by Superpowered. However today I hit a weird issue.

Android studio lets me `#include` the `SuperpoweredNBandEQ.h`

`Execution failed for task ':app:externalNativeBuildDebug'.
> Build command failed.
  Error while executing process /Users/cassiewilson/Library/Android/sdk/cmake/3.10.2.4988404/bin/cmake with arguments {--build /Users/cassiewilson/Downloads/SuperpoweredSDK/Examples_Android/SuperpoweredEffect/app/.externalNativeBuild/cmake/debug/arm64-v8a --target EffectExample}
  [1/1] Linking CXX shared library ../../../../build/intermediates/cmake/debug/obj/arm64-v8a/libEffectExample.so
  FAILED: ../../../../build/intermediates/cmake/debug/obj/arm64-v8a/libEffectExample.so 
  : && /Users/cassiewilson/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++ --target=aarch64-none-linux-android21 --gcc-toolchain=/Users/cassiewilson/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64 --sysroot=/Users/cassiewilson/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/sysroot -fPIC -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -fno-addrsig -Wa,--noexecstack -Wformat -Werror=format-security -stdlib=libc++ -fsigned-char -I/Users/cassiewilson/Downloads/SuperpoweredSDK/Examples_Android/SuperpoweredEffect/app/../../../Superpowered -O0 -fno-limit-debug-info  -Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libatomic.a -static-libstdc++ -Wl,--build-id -Wl,--warn-shared-textrel -Wl,--fatal-warnings -Wl,--no-undefined -Qunused-arguments -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -shared -Wl,-soname,libEffectExample.so -o ../../../../build/intermediates/cmake/debug/obj/arm64-v8a/libEffectExample.so CMakeFiles/EffectExample.dir/src/main/cpp/EffectExample.cpp.o CMakeFiles/EffectExample.dir/Users/cassiewilson/Downloads/SuperpoweredSDK/Superpowered/AndroidIO/SuperpoweredAndroidAudioIO.cpp.o  -llog -landroid -lOpenSLES ../../../../../../../Superpowered/libSuperpoweredAndroidarm64-v8a.a -latomic -lm && :
  CMakeFiles/EffectExample.dir/src/main/cpp/EffectExample.cpp.o: In function `Java_com_superpowered_effect_MainActivity_StartAudio':
  /Users/cassiewilson/Downloads/SuperpoweredSDK/Examples_Android/SuperpoweredEffect/app/.externalNativeBuild/cmake/debug/arm64-v8a/../../../../src/main/cpp/EffectExample.cpp:42: undefined reference to `SuperpoweredNBandEQ::SuperpoweredNBandEQ(unsigned int, float*)'
  clang++: error: linker command failed with exit code 1 (use -v to see invocation)
  ninja: build stopped: subcommand failed.
`

I was able to recreate this same issue in the SuperpoweredEffect example. Just try to create an instance of the NBandEQ.

**Comment by gaborszanto** [comment]
You need to compile SuperpoweredNBandEQ.cpp as well. It's an open-source class, you need to have it in your project just like any other source code file.

**Comment by drspaceboo** [comment]
I have included it with the rest of the SDK. Is there specific configuration for this file?

I have had no issues with Reverb, Echo, 3BandEQ, Compressor, ect...

Were you able to recreate the issue in the example project?

**Comment by gaborszanto** [comment]
How did you "include it"? As "the rest of the SDK" is a static library, but this is an open C++ source code file. Maybe just copy it to your jni/cpp source code folder is the easiest.

**Comment by drspaceboo** [comment]
Oh I didn't realise there was a distinction there. I had `#include <SuperpoweredNBandEQ.h>` at the top of my file. Android Studio was happy enough with that except for when it came to building.

I was able to add `${PATH_TO_SUPERPOWERED}/SuperpoweredNBandEQ.cpp` to my `CMakeLists.txt` file. Looks like it is working now.
