### ISSUE TITLE
Freeing USB resources

### ISSUE THREAD

**Issue by Babelfish001** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#574]
Perhaps this is covered in the response to issue #386.

What is the correct way to free or release USB resources when an app is killed on Android?

In one test case, when a USB headset is attached to the phone, audio is automatically routed through that audio device.  When I then launch an app built with SuperpoweredUSBSystem and satisfy permissions, the app works well with the Superpowered latency improvements in the USB stack.  If I stop the app using the Overview button, the USB headset no longer functions.  I must physically detach and re-attach the device to regain its functionality, whether for any other audio source, or if I choose to re-launch my app.

Some cleanup is not occurring obviously.  As OnDestroy is apparently really never invoked when apps are killed in this fashion on Android, and as OnStop produces the wrong behavior (the app is killed when moved to background ...), how should we properly clean up when a user kills an app with Overview?  Note that using SuperpoweredUSBAudio:stopIO (and startIO or easyIO) when the app is still running produces the "correct" behavior.

Thx in advance ...

**Comment by gaborszanto** [comment]
Yes, stopIO is the correct way and it's a problem if you can't trigger it because OnDestroy is never invoked. What else is invoked if you kill an app with "Overview"?

**Comment by gaborszanto** [comment]
(Please note this is not an issue with Superpowered, but an issue with Android.)

**Comment by gaborszanto** [comment]
I will close this due inactivity.
