### ISSUE TITLE
prevent audio system crash when audio record permission is not granted (android)

### ISSUE THREAD

**Issue by matejbart** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#576]
As soon as the audio system is enabled for input processing, it requires the android RECORD_AUDIO permission - otherwise it will crash at initialization. I'm aware of that, but the issue is that this permission has to be requested and granted at runtime, which in general wouldn't be such a problem unless the user decides to revoke that permission (while the audio system is running in background), which causes an inevitable crash.

Is there any clean way on how I can prevent the audio system from a crash in such a case?

**Comment by gaborszanto** [comment]
Change the open-source SuperpoweredAndroidAudioIO class to handle this case: https://github.com/superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform/blob/master/Superpowered/AndroidIO/SuperpoweredAndroidAudioIO.cpp

**Comment by gaborszanto** [comment]
But actually, it's best to check the permission in Java every time...
