### ISSUE TITLE
Superpowered record multiple-time crash frequently

### ISSUE THREAD

**Issue by dineshbiwall** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#577]
How multiple take for recording in activity in android. It is crash frequently when I start recording and also mix filter and effects. How we multi-take with superpowered recorder.

Crash error :   
Fatal signal 11 (SIGSEGV), code 1, fault addr 0x52c00000 in tid 12157 (RenderThread), pid 12004

A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 14153, pid 14153

Help me.

**Comment by gaborszanto** [comment]
Perhaps you can pinpoint which line of code is crashing in your application?

**Comment by dineshbiwall** [comment]
Its random when increase reverb, EQband value  and pitch its its crash app. Some time I start recorder its crash. Its not stop on pinpoint i have to check it. But not getting on fix place and/or reason to crash.

**Comment by gaborszanto** [comment]
Sounds like you have a bug in your code.

**Comment by dineshbiwall** [comment]
Android build not generate getting this error 'libSuperpoweredExample.so', missing and no known rule to make it

Help me

**Comment by gaborszanto** [comment]
You've generic Android development issues. We can help with Superpowered issues here.
