### ISSUE TITLE
Problems when iOS Screen Recording enabled with microphone on

### ISSUE THREAD

**Issue by schartyom** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#580]
Enabling iOS Screen Recording with microphone on when playback is started results in UI issues and crash sometimes.

This can be reproduced on your example project. Steps to reproduce:
1. Add a Screen Recording button to your iOS control center (in Settings > Control Center > Customize Controls).
2. Run SuperpoweredCrossExample https://github.com/superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform/tree/master/Examples_iOS/SuperpoweredCrossExample.
3. Tap “Play”.
4. Open Control Center, press deeply on Screen Recording button and tap Microphone.
5. Tap Start Recording, then wait for the three-second countdown.
On the last step audio stops playing, you can see serious UI glitches if you try to move the slider on the screen. Sometimes app crashes on this step.

After experimenting I’ve found that initializing SuperpoweredIOSAudioIO with AVAudioSessionCategoryPlayAndRecord category mitigates this issue. But this change results in new issues like freezing UI for several seconds (I can provide steps to reproduce as well).

Is there a correct way to fix it?

**Comment by gaborszanto** [comment]
The cross example doesn't enable the audio input (microphone), because it doesn't need it. It doesn't even request audio input permission.
Do you experience the same problem with the SuperpoweredFrequencies example? That one do use microphone input.

**Comment by gaborszanto** [comment]
Closing due inactivity.

**Comment by schartyom** [comment]
This issue reproduces when microphone recorded by any other app (in this case it’s iOS Screen Recording), not the CrossExample itself. So you don't need to request audio input permission.

I've checked SuperpoweredFrequencies, it works perfectly because it doesn’t play any audio. But this issue reproduces only when playback is started.

**Comment by gaborszanto** [comment]
I just tested your scenarios on the iPad Pro. Works without any glitch. This must be an iOS issue.
