### ISSUE TITLE
Any plans on supporting Opus/Ogg decoders sometime soon?

### ISSUE THREAD

**Issue by zsaraf** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#581]
This would be an awesome feature for us as we've found Opus to be a much better compressed format than MP3.

**Comment by gaborszanto** [comment]
We've no immediate plans. What's wrong with the open-source ones btw?

**Comment by gaborszanto** [comment]
Closing due inactivity.

**Comment by newbyca** [comment]
Fwiw, I'd like to see ogg support too. Ogg had been the recommend format on Android, at least historically. In my case I have an older android app with tons of ogg files. Converting to mp3, for example, is fine in and of itself ...but upgrading legacy users is problematic.
