### ISSUE TITLE
Advanced audio player pitch shift does not work with small .wav files -Android

### ISSUE THREAD

**Issue by erincdemir** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#582]
I tried to open single cycle waveforms from Adventure Kid's archive. They play well but they don't respond to setPitchShiftCents() method. Then I tried with longer samples and pitch shift worked.

Actually I am pretty new to the Superpowered SDK and audio development. I would appreciate if theres another way I can make oscillators.

Thanks for your time again.

**Comment by gaborszanto** [comment]
How short are those wav files?

**Comment by erincdemir** [comment]
"This is the original pack and consists of samples that are 600 samples long." 
this what he says on his site.

Here you can check the waveforms.
https://www.adventurekid.se/akrt/waveforms/adventure-kid-waveforms/

**Comment by gaborszanto** [comment]
Frequency domain transformations require much longer audio. 600 samples are not even one FFT window size...
For your use-case i recommend to use the SuperpoweredResampler instead, because making these waveforms longer or shorter a little bit will not change their fundamental "sound".

**Comment by erincdemir** [comment]
Huge thanks for information and help. I guess I can close this one. 

Have a nice day/night.
