### ISSUE TITLE
"Can't open this file" on Android  

### ISSUE THREAD

**Issue by SergeyChernonog** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#583]
Hello
Here's my example project https://github.com/SergeyChernonog/SimpleCrossExample
I want to reuse player and load new .wav. But every time I try to do this I'm handling LoadError with "Can't open this file" event and player stops.
Any suggestions ?

**Comment by gaborszanto** [comment]
Wrong file format or open parameters (such as path).

**Comment by SergeyChernonog** [comment]
First load call is always succesful and it uses same apk path (which I store in variable) and file with the same format as in the following load calls

**Comment by gaborszanto** [comment]
Your path becomes invalid quickly, because you forget to copy the actual path string.
