### ISSUE TITLE
Audio Looping

### ISSUE THREAD

**Issue by mgood7123** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#585]
could you provide an example that utilizes audio looping? (eg for synths or segments of audio)

as i am developing a high performance audio application capable of playing user defined loop segments per audio track, in which an acceptable minimum is 50 to 100ms looping playback without stutter

in which fast looping is vital, something in which `android.media.MediaPlayer` is not capable of

for example
```
        media = Media(this)
            .init()
            .loadMediaPath("/sdcard/RAW_FILE/mp3/00001240.mp3")
            .loop(true)
            // test loopers
            .addLooper("5 milliseconds", 10000, 10005)
            .addLooper("1 second", 10000, 11000)
            .addLooper("5 seconds", 10000, 15000)
            .setLooper("5 seconds")
            .play()
```

as i tried using `player->loop(1000, 2000, true, 255, true);` but i am unable to notice anything different in the playback, moreover it does not appear to be looping as it plays past `2000` ms nor does it seek to `1000` ms if it is below `1000` ms (for example, if it starts at `0` ms)

is there a correct way to achieve this given a sample?

**Comment by gaborszanto** [comment]
Did you try player->loop(1000, 2000, true, 255, false)?

**Comment by gaborszanto** [comment]
also, the second parameter is the loop length

**Comment by mgood7123** [comment]
> Did you try player->loop(1000, 2000, true, 255, false)?

yes, and `player->loop(1000, 1000, false, 255, false);`

**Comment by gaborszanto** [comment]
... and nothing happens? Just because many apps are using the looping feature...
