### ISSUE TITLE
Latency/clicking sound when looping a WAV

### ISSUE THREAD

**Issue by cschwing** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#588]
I am using a SuperpoweredAdvancedAudioPlayer to play a wav file in a loop. This wav file is recorded using the SuperpoweredRecorder. The problem is, every time the track loops, there is a little hiccup with a popping sound and a very small delay. It is noticeable and makes looping totally useless

Here is the callback function I am using to loop
```

// Called by the playerA.
static void playerEventCallbackA (
        void * __unused clientData,
        SuperpoweredAdvancedAudioPlayerEvent event,
        void *value
) {
    switch (event) {
        case SuperpoweredAdvancedAudioPlayerEvent_LoadSuccess:
            break;
        case SuperpoweredAdvancedAudioPlayerEvent_LoadError:
            log_print(ANDROID_LOG_ERROR, "Player", "Open error: %s", (char *)value);
            break;
        case SuperpoweredAdvancedAudioPlayerEvent_EOF:
            playerA->seek(0);    // loop track
            break;
        default:;
    };
}
```
Considering the entire point of this SDK is to have minimal latency with recording and playback, I figure I must be doing something wrong.

Any tips?

**Comment by gaborszanto** [comment]
Use the player->loop() or player->loopBetween() methods instead.
