### ISSUE TITLE
Old versions of Superpowered

### ISSUE THREAD

**Issue by svenoaks** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#589]
> NOTE: Using Superpowered Audio (prior to 1.4.0) after October 1 2019 may cause your apps/products to cease functioning. Developers must upgrade to the latest Superpowered version with API keys. API keys are available at our Superpowered Dev site.

If we upgrade our apps to Superpowered 1.4.0, there will still be a very significant number of users using old versions past October 1, 2019. Please give us assurance that the library will not stop functioning for them.

**Comment by gaborszanto** [comment]
We moved to discussion to private email.
