### ISSUE TITLE
Question : Implement chorus effect

### ISSUE THREAD

**Issue by pro-softs** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#590]
I am trying to implement a chorus effect using the Superpowered library. Is there any way to do it with the available classes in the library?
I tried using third party code but it produces noise in the output wav.

**Comment by gaborszanto** [comment]
We don't offer a chorus effect in the Superpowered library and we don't offer a tapped delay line primitive component either, sorry.
