### ISSUE TITLE
SuperpoweredRecorder records like mono

### ISSUE THREAD

**Issue by Ufosek** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#591]
Hello,

I used unchanged code from examples: **Android -> SuperpoweredRecorder**. I put speaker with looped music 10 cm from my device (Samsung S8) and recorded it with provided example and with built in camera. Then I removed video from camera's recording and compared the results (attached files). As you can hear sound from recorder looks like mono (or just flat) comparing to second file. The number of channels are properly set in example:
```
    // Initialize the recorder with a temporary file path.
    recorder = new SuperpoweredRecorder (
            temp,               // The full filesystem path of a temporarily file.
            (unsigned int)samplerate,   // Sampling rate.
            1,                  // The minimum length of a recording (in seconds).
            2,                  // The number of channels.
            false,              // applyFade (fade in/out at the beginning / end of the recording)
            recorderStopped,    // Called when the recorder finishes writing after stop().
            NULL                // A custom pointer your callback receives (clientData).
    ); 
```

What may be the issue here? How can we achieve better quality?

[recorded.zip](https://github.com/superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform/files/3417778/recorded.zip)

Thanks in advance!

**Comment by gaborszanto** [comment]
Superpowered records into wav. Can you share the original recordings please?
Are you using the latest version of Superpowered (1.4.0) and the latest example project in it?

**Comment by Ufosek** [comment]
@gaborszanto I just tested on latest version and results are the same. I also tested it with pure voice and the difference is smaller but also hearable.
I attach original wav files with those recorded with camera app.

[superpowered_recordings.zip](https://github.com/superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform/files/3432684/superpowered_recordings.zip)

**Comment by gaborszanto** [comment]
Did you perform any additional processing on the buffer you pass to the SuperpoweredRecorder?
If not, did you play with the various inputStreamType options when creating SuperpoweredAndroidAudioIO, such as SL_ANDROID_RECORDING_PRESET_GENERIC? SLES/OpenSLES_AndroidConfiguration.h has the options.

**Comment by Ufosek** [comment]
In `RecorderExample` there is no additional processing on the buffer:
```
static bool audioProcessing (
        void * __unused clientdata, // custom pointer
        short int *audio,           // buffer of interleaved samples
        int numberOfFrames,         // number of frames to process
        int __unused samplerate     // sampling rate
) {
    SuperpoweredShortIntToFloat(audio, floatBuffer, (unsigned int)numberOfFrames);
    recorder->process(floatBuffer, (unsigned int)numberOfFrames);
    return false;
}
```
I also tried all configurations for `inputStreamType` but results are similar.

**Comment by gaborszanto** [comment]
Then my guess is that there is a system-space audio processing bug in the S8, providing mono streams for native layer microphone input. Unfortunately there are many bad Android system-space audio implementations, and the S8 is especially a bad one, because we received many other system-space audio bug reports. Many times the manufacturers test the high latency Java input only.

**Comment by gaborszanto** [comment]
Can i close this? Is there any change on this?
