### ISSUE TITLE
Old version support

### ISSUE THREAD

**Issue by schartyom** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#592]
According to email from Superpowered: "using earlier versions (prior to 1.4.0) of Superpowered after October 1 2019 will interrupt app function.".

Could you please clarify the meaning of "will interrupt app function."? Is there some internal mechanism which will stop the SDK from functioning correctly or you mean just stopping the support of the old version?

We have a bunch of users who stays with an old version of an app for a long time, which means they will be using version prior to 1.4.0 and we can't force them to update. Does it mean they won't be able to use it in October?

**Comment by gaborszanto** [comment]
Please email support@superpowered.zendesk.com ASAP and provide details on your app(s) so we can help you.
