### ISSUE TITLE
Error decoding audio files w/ iOS offlineAnalyze example.

### ISSUE THREAD

**Issue by ocarey** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#593]
**Xcode: 11.0
iOS: 13.1
Superpowered: 2.0**

Hi Superpowered team,

I am using the Superpowered Offline Analyzer in a swift iOS project. I need to detect bpm, key and beatgridStart from recorded audio files in-app. Analyzing audio URLs picked with MPMediaPickerController work fine, however when analyzing URLs from the app's bundle or with video URLs chosen with UIImagePicker I get an **`Open error 1006: File open error.`** from the decoder. This is the case with mp3, m4a and wav audio files. 

_I also get this same **`Open error 1006: File open error.`** error when trying to analyze an audio file from the app bundle with the iOS SuperpoweredOfflineProcessingExample, but again it works fine with a URL from MPMediaPickerController._

In SuperpoweredDecoder.h there is a recommended action for error 1006: **`Recommended action: check if the path and read permissions are correct.`** Unfortunately, I'm not sure what action to actually take with this recommendation, or if there is actually a different underlying problem.

Project: https://github.com/ocarey/SwiftBPMAnalyzer

I've attached my sample project. My errors can be replicated by uncommenting either of these options in ViewController viewDidLoad:
```
override func viewDidLoad() {
        super.viewDidLoad()
        superpowered = SuperpoweredBridge()
        
        // THIS OPTION WORKS
        presentMediaPickerController()
        
        // THESE OPTIONS DONT WORK
//        presentImagePickerController()
//        analyzeLocalAudioFile()
    }
```

I do not like to submit support tickets, but at this point I've been trying to fix this issue for 2 days but haven't gotten anywhere. Hoping you might be able to help! Thank you.

Best Regards,
Owen Carey

**Comment by gaborszanto** [comment]
Thank you for this detailed and precise support ticket, i wish all tickets would look like this.

In the cross example project this is how we open a bundled file:

[[[NSBundle mainBundle] pathForResource:@"lycka" ofType:@"mp3"] fileSystemRepresentation]

I think the "fileSystemRepresentation" part is the key. Apple URLs can be very strange sometimes and not mapping to direct file system paths in many cases.

**Comment by ocarey** [comment]
Thanks for the response.

I reviewed the cross example project again. It looks like the code **[[[NSBundle mainBundle] pathForResource:@"lycka" ofType:@"mp3"] fileSystemRepresentation]** actually returns a path C string for the file location which is given to the player open() function:

```
/// @brief Opens an audio file with playback paused.
/// Playback rate, pitchShift, timeStretching and syncMode are NOT changed if you open a new file.
/// @warning This method has no effect if the previous open didn't finish or if called in the audio processing thread.
/// @param path Full file system path or progressive download path (http or https).
/// @param customHTTPRequest If custom HTTP communication is required (such as sending http headers for authorization), pass a fully prepared http request object. The player will copy this object.
/// @param skipSilenceAtBeginning If true, the player will set the position to skip the initial digital silence of the audio file (up to 10 seconds).
    void open(const char *path, Superpowered::httpRequest *customHTTPRequest = 0, bool skipSilenceAtBeginning = false);
```

However, the offlineAnalyze() function in SuperpoweredOfflineProcessingExample requires a URL. 

```
- (void)offlineAnalyze:(NSURL *)url
```

I don't think the fileSystemRepresentation should make a difference as long as it's a valid URL right?

Here's the exact code I've tested in SuperpoweredOfflineProcessingExample: 

```
NSURL *url = [[NSBundle mainBundle] URLForResource:@"lycka" withExtension:@"mp3"];
[self performSelectorInBackground:@selector(offlineAnalyze:) withObject:url]; 
```

Which again gives the error `Open error 1006: File open error.`. 

Would you mind trying to run the SuperpoweredOfflineProcessingExample's offlineAnalyze() function with a bundled audio file/URL and letting me know what code works? At this point I'm not sure I can figure it out :(

Definitely appreciate the help!

Best Regards,
Owen Carey

**Comment by gaborszanto** [comment]
You can change offlineAnalyze to accept a "const char *" for the url (the decoder needs a "const char *" anyway).

fileSystemRepresentation does make a significant difference for file NSURLs.
[NSURL UTF8String] is different to [NSURL fileSystemRepresentation]

**Comment by ocarey** [comment]
Amazing thank you! I did not know that fileSystemRepresentation made such a big difference (and I pretty much such with Objective C). Changing the function to accept **constant char** worked great in my swift project too!

```
let path = Bundle.main.path(forResource: "Guitar_100bpm_A", ofType: "m4a")!
let cStringPath = FileManager.default.fileSystemRepresentation(withPath: path)
let results = superpowered.offlineAnalyze(cStringPath)
```

Gives the results:
```
Bpm is 100.000000, average loudness is -28.026257 db, peak volume is -8.477505 db, key index is -1, beat grid start Ms is 0.000000.
```

One unrelated problem I'm still having is that every time the **key index** is predicted to be **-1**, even when I know the audio file is recorded in a certain key. The above analyzed audio file is Acoustic Guitar at 100bpm in key Amaj, but the key index is predicted as -1. I've analyzed about 10 audio files recorded in a given key and they are all predicted as having a key index of -1. Any suggestions here? 

```
Key index: The dominant key (chord) of the music. 0..11 are major keys from A to G#, 12..23 are minor keys from A to G#.
```

Thanks for all your help!

Best Regards,
Owen

**Comment by gaborszanto** [comment]
How long are those files please? This feature was primarily designed to analyze complete music tracks.

**Comment by ocarey** [comment]
While testing I was analyzing music tracks ranging from 20 seconds to 40 seconds. In practical use, I hope to analyze 20-second musical videos for their bpm, key and beat onset. 

Throughout all my 20-second audio tests BPM detection has been extremely accurate, but BeatGridStarMs has always been 0. I would think that the BeatgridStartMs prediction would be accurate if the bpm prediction is? But I guess not necessarily.

**I just tested with a full mp3 track and BeatgridStartMs was predicted to be 1522.284302 so it is working, but only for some tracks.** Looks like I may have to figure out an algorithm to find the first beat onset in shorter audio tracks.

**Comment by gaborszanto** [comment]
Also, this feature was mostly designed for modern dance music mostly, where the bpm detection demand is the highest.

**Comment by ocarey** [comment]
Thank you for all the help!
