### ISSUE TITLE
Support library 1.3.x

### ISSUE THREAD

**Issue by filippodelfra** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#594]
Hello,
We have an app released as closed beta (that is about to hit production) using superpowered 1.3.3 version. 
According to email from Superpowered: "using earlier versions (prior to 1.4.0) of Superpowered after October 1 2019 will interrupt app function.".

Can you please clarify this "will interrupt app function."? 
We also sent an email requesting a quote but we didn't got any reply. 

Thanks

**Comment by gaborszanto** [comment]
Please email licensing@superpowered.com
