### ISSUE TITLE
fftLogSize crashing app in SuperpoweredFrequencyDomain 1.4.0

### ISSUE THREAD

**Issue by zaid2kazi** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#595]
Hey all when i have `frequencyDomain = new SuperpoweredFrequencyDomain(13);` my application has had the same code base for multiple versions and now it crashes. when i pass fftLogSize as 11 the app doesn't crash.

**Comment by gaborszanto** [comment]
Hello,

i tested the SuperpoweredFrequencyDomain example project with new SuperpoweredFrequencyDomain(13) and it works okay with Superpowered 2.0.0 (we don't provide support for 1.4.0).
Where does your app crash, at which call?

**Comment by gaborszanto** [comment]
I will close this due inactivity soon.
