### ISSUE TITLE
player->seek method is not working in android. When seekbar is moved, the song starts from the beginning. How to fix this?

### ISSUE THREAD

**Issue by manishh776** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#597]

**Comment by gaborszanto** [comment]
Superpowered offers no user interface features. User interface must be implemented with your own code. Please check your code why not the appropriate value is sent to player->seek when you handle your seekbar's movement.
