### ISSUE TITLE
Crash with multiple devices / streams on MacOS

### ISSUE THREAD

**Issue by roussetjc** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#598]
Implementing multiple devices / streams on macOS seems to work correctly.
I'm doing something like this:
```
audioDevice *deviceList = [SuperpoweredOSXAudioIO getAudioDevices];
while (deviceList != NULL) {
        ...
        SuperpoweredOSXAudioIO *audioIO = [[SuperpoweredOSXAudioIO alloc] initWithDelegate:(id<SuperpoweredOSXAudioIODelegate>)self
                                                                        preferredBufferSizeMs:BUFFER_SIZE
                                                                             numberOfChannels:deviceList->numInputChannels
                                                                                  enableInput:true
                                                                                 enableOutput:true
                                                                                audioDeviceID:deviceList->deviceID];

        // Then, manage the devices array, the callbacks, etc.

        deviceList = deviceList->next;
}
```

However, it crashes when unplugging a device.
Apparently, `devicesChangedCallback` keeps being called as the listener is not deallocating when `audioIO` is set to `nil`.
Shouldn't there be `AudioObjectRemovePropertyListener` in the dealloc function?
Something like this:
```
- (void)dealloc {
...
    
    AudioObjectPropertyAddress hdaddress = { kAudioHardwarePropertyDevices, kAudioObjectPropertyScopeGlobal, kAudioObjectPropertyElementMaster };
    AudioObjectRemovePropertyListener(kAudioObjectSystemObject, &hdaddress, devicesChangedCallback, (__bridge void *)self);
#if !__has_feature(objc_arc)
    [super dealloc];
#endif
}
```

It sopped crashing, however I still get errors:

> 2019-10-22 19:15:49.642318+0200 MicrophoneAnalysis[34403:2615424]  HALC_ProxyIOContext::IOWorkLoop: failed to send the final message to the server, Error: 0x10000003
> 2019-10-22 19:15:49.645527+0200 MicrophoneAnalysis[34403:2615357]  HAL_HardwarePlugIn_DeviceDestroyIOProcID: no device
> 2019-10-22 19:15:49.645702+0200 MicrophoneAnalysis[34403:2615357]  HALPlugIn::DeviceCreateIOProcID: got an error from the plug-in routine, Error: 560947818 (!obj)
> 2019-10-22 19:15:49.647261+0200 MicrophoneAnalysis[34403:2615357]  HAL_HardwarePlugIn_ObjectHasProperty: no object
> 2019-10-22 19:15:49.647365+0200 MicrophoneAnalysis[34403:2615357]  HAL_HardwarePlugIn_ObjectHasProperty: no object
> 2019-10-22 19:15:49.647444+0200 MicrophoneAnalysis[34403:2615357]  HAL_HardwarePlugIn_ObjectHasProperty: no object
> 2019-10-22 19:15:49.647513+0200 MicrophoneAnalysis[34403:2615357]  HAL_HardwarePlugIn_ObjectHasProperty: no object
> 2019-10-22 19:15:49.647571+0200 MicrophoneAnalysis[34403:2615357]  HAL_HardwarePlugIn_ObjectHasProperty: no object
> 2019-10-22 19:15:49.647595+0200 MicrophoneAnalysis[34403:2615357]  HAL_HardwarePlugIn_ObjectHasProperty: no object
> 2019-10-22 19:15:49.647611+0200 MicrophoneAnalysis[34403:2615357]  HAL_HardwarePlugIn_ObjectHasProperty: no object
> 2019-10-22 19:15:49.670388+0200 MicrophoneAnalysis[34403:2615538]  HALC_ProxyIOContext::IOWorkLoop: the server failed to start, Error: 0x6E6F7065
> 2019-10-22 19:15:49.912013+0200 MicrophoneAnalysis[34403:2615357]  HAL_HardwarePlugIn_DeviceStart: no device
> 2019-10-22 19:15:49.912095+0200 MicrophoneAnalysis[34403:2615357]  HALPlugIn::StopIOProc: got an error from the plug-in routine, Error: 560947818 (!obj)
> 2019-10-22 19:15:49.938018+0200 MicrophoneAnalysis[34403:2615357]  HAL_HardwarePlugIn_DeviceDestroyIOProcID: no device
> 2019-10-22 19:15:49.938093+0200 MicrophoneAnalysis[34403:2615357]  HALPlugIn::DeviceCreateIOProcID: got an error from the plug-in routine, Error: 560947818 (!obj)
> 2019-10-22 19:15:49.939578+0200 MicrophoneAnalysis[34403:2615357]  HAL_HardwarePlugIn_ObjectHasProperty: no object
> 2019-10-22 19:15:49.939647+0200 MicrophoneAnalysis[34403:2615357]  HAL_HardwarePlugIn_ObjectHasProperty: no object
> 2019-10-22 19:15:49.939696+0200 MicrophoneAnalysis[34403:2615357]  HAL_HardwarePlugIn_ObjectHasProperty: no object
> 2019-10-22 19:15:49.939713+0200 MicrophoneAnalysis[34403:2615357]  HAL_HardwarePlugIn_ObjectHasProperty: no object
> 2019-10-22 19:15:49.939726+0200 MicrophoneAnalysis[34403:2615357]  HAL_HardwarePlugIn_ObjectHasProperty: no object
> 2019-10-22 19:15:49.939739+0200 MicrophoneAnalysis[34403:2615357]  HAL_HardwarePlugIn_ObjectHasProperty: no object
> 2019-10-22 19:15:50.009776+0200 MicrophoneAnalysis[34403:2615357]  HAL_HardwarePlugIn_ObjectHasProperty: no object

**Comment by gaborszanto** [comment]
This class was designed to be initialized at startup and deallocated when the application quits. It was also designed to have just one instance of it per app.
We will include the removelistener calls in the next update.
The error messages above are not related to this class.
