### ISSUE TITLE
There is one issue in running HLS for iOS project.

### ISSUE THREAD

**Issue by fullstact69** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#599]
I have tried to build HLS sample project.
https://github.com/superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform/tree/master/Examples_iOS/SuperpoweredHLSExample

In this project, open URL is http://qthttp.apple.com.edgesuite.net/1010qwoeiuryfg/sl.m3u8 for ex.
So I have changed this URL to other sample audio URL such as https://s3.amazonaws.com/kargopolov/kukushka.mp3
But unfortunately, Player doesn't play this URL.
How can I resolve this issue?

**Comment by gaborszanto** [comment]
The openHLS method opens a HLS stream. Only HLS streams should be opened with the openHLS method.
An mp3 is NOT a HLS stream. It should be opened with the open method.
