### ISSUE TITLE
MainPage.xaml.cpp file is broken

### ISSUE THREAD

**Issue by Exidius** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#601]
It appears to be the MainPage.xaml.cpp file in the Examples_Windows\SuperpoweredEffect folder is cut in half.

**Comment by gaborszanto** [comment]
Seems like GitHub had a bug while syncing the project. Please find the missing few lines in an older version: https://github.com/superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform/blob/bd2aec08b9e68862927442502387c2894d4d13f2/Examples_Windows/SuperpoweredEffect/MainPage.xaml.cpp
