### ISSUE TITLE
Android SDK is missing

### ISSUE THREAD

**Issue by dhemku** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#602]
Whenever you are create a new application, and run it, will through error like **sdk** is missing.
so that you have to create a new file in, 
android -> local.properties (create a new file) and then paste your sdk path

in mac you have to put like this 👍 
**sdk.dir = /Users/USERNAME/Library/Android/sdk**
in Windows 👍
**sdk.dir = C:\\Users\\USERNAME\\AppData\\Local\\Android\\sdk**
in linux 👍
**sdk.dir = /home/USERNAME/Android/Sdk**

![Screenshot 2019-11-12 at 11 21 32 AM](https://user-images.githubusercontent.com/46310678/68645613-99859080-053e-11ea-90e1-378de89172aa.png)

**Comment by gaborszanto** [comment]
You can also set the SDK path in Android Studio, globally for all projects.
Also please note that not everybody is having those paths set up.

**Comment by dhemku** [comment]
> You can also set the SDK path in Android Studio, globally for all projects.
> Also please note that not everybody is having those paths set up.

Thanks for Information.👍
