### ISSUE TITLE
SuperpoweredAnalyzer bpm is zero

### ISSUE THREAD

**Issue by weepy** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#603]
Hiya I'm trying to do some bpm detection and I'm getting zero for the grid and the bpm return as zero. The key index returns as 3 though.

Does zero here mean that it failed to find a bpm ?

**Comment by gaborszanto** [comment]
Yes, it means that. But it's unlikely. What parameters do you set when calling makeResults?

**Comment by weepy** [comment]
I wrote out the audio to a file and its fine (interleaved 32bit float).

I'm just doing 
```
SuperpoweredOfflineAnalyzer a(44100);
a.process(zipped, length);
 anal.getresults(
        &averageWaveform,
        &peakWaveform,
        &lowWaveform,
        &midWaveform,
        &highWaveform,
        &notes,
        &waveformSize,
        &overviewWaveform,
        &overviewSize,
        &averageDecibel,
        &loudpartsAverageDecibel,
        &peakDecibel,
        &bpm,
        &beatGridStartMs,
        &keyIndex
    );

```

**Comment by weepy** [comment]
Also odd is : peakDecibel is -10.4393921 since there's definitely a sample that's peaking.

**Comment by weepy** [comment]
I suspect it's because I'm using an old version ?

**Comment by gaborszanto** [comment]
Yes, it is an old version that we don't support anymore. The API is different now.
Is this song long enough (at least 30 seconds)? Does it have enough transitions, especially beats?

**Comment by weepy** [comment]
I think the problem was that I wasn't passing in the song duration (not
sure what the point of being optional is?).  Seems to work ok. Does the
beat grid try and suggest the first bar or the first beat?

**Comment by gaborszanto** [comment]
The duration is not optional in the current version of the API. Yes, the beat grid suggests the first bar.
