### ISSUE TITLE
SuperpoweredAndroidAudioIO 200ms input latency

### ISSUE THREAD

**Issue by romanbsd** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#604]
I'm creating an instance of SuperpoweredAndroidAudioIO:
```cpp
io = new SuperpoweredAndroidAudioIO(sampleRate, bufferSize, true, true, audioProcessingCallback, this, inputStreamType, SL_ANDROID_STREAM_MEDIA);
```
Where inputStreamType is either SL_ANDROID_RECORDING_PRESET_VOICE_RECOGNITION or SL_ANDROID_RECORDING_PRESET_UNPROCESSED, and sampleRate and bufferSize are those returned by AudioManager in Java.

In the callback I'm writing both the produced audio and received samples. When I open the audio in Sonic Visualiser, there's a 200ms delay between samples sent to speaker and received from microphone.

SuperpoweredLatency reports 44ms latency.

I tried using oboe with the same settings and the samples recorded in this scenario show ~40ms latency (just as SuperpoweredLatency predicted).

What might be the reason for such huge delay?

P.S. Only OpenSLES was evaluated, AAudio wasn't used.

**Comment by gaborszanto** [comment]
Please replace SuperpoweredAndroidAudioIO.cpp with the attached experimental build and let me know the results.
[SuperpoweredAndroidAudioIO.cpp.zip](https://github.com/superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform/files/3879539/SuperpoweredAndroidAudioIO.cpp.zip)

**Comment by gaborszanto** [comment]
Is anybody there?

**Comment by romanbsd** [comment]
I'll try it tomorrow

**Comment by gaborszanto** [comment]
Tomorrow?

**Comment by romanbsd** [comment]
Sorry, I got busy with other things. Yes, tomorrow I'll get to it.

**Comment by romanbsd** [comment]
Tested. Same thing. Also, the new version uses AAudio, so might be not exactly apples to apples. I suspect that you have some internal buffers that add to latency.

**Comment by gaborszanto** [comment]
No, there are no internal buffering at all. You can check the source, it's open.

What are the input and output stream type settings? AAudio is used only if:

- Android 8.1+
- low latency stream types:
-- output type: stream media or -1
-- input type: anything except camcorder or voice communication

**Comment by romanbsd** [comment]
But I assume that there has to be some buffer since the callbacks arrive in different times? I'll try it later on a blank slate project.

**Comment by gaborszanto** [comment]
All buffers are coming from the operating system. There is no additional buffering.

**Comment by gaborszanto** [comment]
Are you still working on this?

**Comment by romanbsd** [comment]
No, sorry. Too busy with other stuff :(

**Comment by gaborszanto** [comment]
No worries, i will close this now and when you have time you can comment.
