### ISSUE TITLE
Is it possible to use superpowered with the iOS13 style MPMediaPickerController?

### ISSUE THREAD

**Issue by mlostekk** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#605]
Apple did some changes with their way to retrieve the "local" files that are in the apple music library. I am only referring to the once that are available on the local device, not streaming.

Is it possible to access those files' buffers and let superpowered run with them?

**Comment by gaborszanto** [comment]
Absolutely, here is an example: https://github.com/superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform/tree/master/Examples_iOS/SuperpoweredOfflineProcessingExample

**Comment by mlostekk** [comment]
Okay thanks for the example. I assume this is not working for streamed objects from the cloud?

**Comment by gaborszanto** [comment]
Apple doesn't provide any streaming access for third parties.

**Comment by mlostekk** [comment]
Mh, when i try it (its a bit older version of superpowered) then I will get an 

`SuperpoweredAdvancedAudioPlayerEvent_LoadError`

The asset url looks like this

`ipod-library://item/item.m4a?id=8956556064155754225` which should be fine. I have tested the example above, and the same asset url seems to work fine. 

Was there a required update to your library? (I cant just update, still in evaluation phase. its a pretty old app)

**Comment by mlostekk** [comment]
@gaborszanto i am having an older app that uses 1.3.1 of superpowered. Do you know if this version shall still support the iOS13 music access of downloaded files (as working in the latest examples above)
