### ISSUE TITLE
Unwanted echo effect when shifting pitch of voice

### ISSUE THREAD

**Issue by dschnabel** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#607]
Hi there, I modified the Linux example [offline2.cpp](https://github.com/superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform/blob/master/Examples_Linux/src/offline2.cpp) to shift the pitch instead of stretching the time:
```
    // Create the time stretcher.
    Superpowered::TimeStretching *timeStretch = new Superpowered::TimeStretching(decoder->getSamplerate());
//    timeStretch->rate = 1.04f; // 4% faster
    timeStretch->pitchShiftCents = 600;
```

There is a strange echo effect in the resulting audio which I don't expect.

Created using offline2.cpp with above code change (pitch shift of 600):
https://vocaroo.com/1ANYSlHjWi2

For comparison this is how I want it to sound like:
https://vocaroo.com/oSHlsqTWTDv
(created using [ChipmunkVoiceChanger](https://lingojam.com/ChipmunkVoiceChanger))

The original sounds like this:
https://vocaroo.com/eXRI32uWd0I

Any ideas what's going on? Any help appreciated.

**Comment by gaborszanto** [comment]
That is the only change you made to the example? That one line?

**Comment by dschnabel** [comment]
And also changed the [filename](https://github.com/superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform/blob/master/Examples_Linux/src/offline2.cpp#L24) to match my M4A example. No other changes were made.

**Comment by gaborszanto** [comment]
I believe there is nothing wrong with the result, it actually sounds better than the ChipmunkVoiceChanger because there is no "grainy-ness", you can't hear the individual segmented sound.
However i understand that you need to do some more to achieve that specific chipmunk sound. I recommend to steeply filter out the unwanted low-end, using the Superpowered Filter.

**Comment by dschnabel** [comment]
> it actually sounds better than the ChipmunkVoiceChanger because there is no "grainy-ness"

I see, yeah even though there's "grainy-ness" in the ChipmunkVoiceChanger version, it's easier to understand the words which is more important to my project than a clean pitch shift.

>  I recommend to steeply filter out the unwanted low-end, using the Superpowered Filter.

Thanks. I'll play around with the Superpowered Filter. However, I don't have a trained ear like you do, so not really sure which frequencies I should be looking at to get rid of the echo.

**Comment by dschnabel** [comment]
Ok, so I did some more research and I think this is what's going on: Superpowered splits the file up into small chunks, doubles the speed of each chunk and then repeats each chunk to fill in the gaps. So the slight echo is what you hear as each chunk is repeated.

This is something that can't be fixed by applying additional filters.

There are more sophisticated algorithms that don't show this echo/reverb effect. For me a better result is achieved using [rubberband](https://github.com/breakfastquay/rubberband). There's no echo/reverb and even the "grainy-ness" you mentioned from the ChipmunkVoiceChanger version is not there.

Example using rubberband:
https://vocaroo.com/bQpqS8MRVXU

I'm leaving this issue open in case you want to look into how the Superpowered algorithm can be improved to avoid the echo/reverb effect. Feel free to close if you feel so.

**Comment by gaborszanto** [comment]
No, Superpowered doesn't work like you describe, but it uses the same frequency domain principles as Rubberband. However it has better time-stretching audio quality vs Rubberband, so i'm not sure where your "more sophisticated" statement comes from.
Please send me the original file so i can play with it a little bit.

**Comment by gaborszanto** [comment]
I just tested this on mac and it doesn't have that echo sound. Perhaps it's a Linux build bug, i will investigate.

**Comment by gaborszanto** [comment]
Please convert your input file to 48000 Hz and test. It will sound very different.

**Comment by dschnabel** [comment]
Converting to 48000 Hz did the trick! There's still a tiny echo but the words are much easier to understand now. Also I had to filter out the 125-200 Hz range to get rid of some weird harmonics but I think it's now close to where I want it to be. Thank you for your help!
