### ISSUE TITLE
Crash in mp3huffman.cpp, possibly when out of memory

### ISSUE THREAD

**Issue by flagoworld** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#608]
I believe this is related to an OOM condition not being properly handled. Maybe not though, but if it is, would it be possible to handle the allocation error and then cancel the decoding with an error that I can handle in my UI? Here is the stack trace:

```
EXC_BAD_ACCESS KERN_PROTECTION_FAILURE 0x0000000105614000

Crashed: AudioPlayer Shadow
0  MyApp                     0x100ebdc54 MP3DecodeHuffman(MP3DecInfo*, unsigned char*, int*, int, int, int) + 4367506516 (mp3huffman.cpp:4367506516)
1  MyApp                     0x100ed7dfc mp3Decoder::decodeFrame(int*, unsigned char**, int, short*) + 4367613436 (mp3File.h:4367613436)
2  MyApp                     0x100ed8374 mp3File::decodeFrame(short*, unsigned int, bool*, bool*) + 4367614836 (mp3File.h:4367614836)
3  MyApp                     0x100ed7678 mp3File::decode(short*, unsigned int*) + 4367611512 (mp3File.h:4367611512)
4  MyApp                     0x100ed2ec0 SuperpoweredDecoder::decode(short*, unsigned int*) + 4367593152 (SuperpoweredDecoder.cpp:4367593152)
5  MyApp                     0x100eae494 shadowThreadFunc(void*) + 4367443092 (SuperpoweredAdvancedAudioPlayer.cpp:4367443092)
6  libsystem_pthread.dylib        0x1963cdd8c _pthread_start + 156
7  libsystem_pthread.dylib        0x1963d176c thread_start + 8
```

**Comment by flagoworld** [comment]
Here's another instance of what appears to be the same crash, this one has line numbers. They might not be correct but hopefully helps narrow it down.

```
Crashed: AudioPlayer Shadow
0  MyApp                     0x1047edc54 MP3DecodeHuffman(MP3DecInfo*, unsigned char*, int*, int, int, int) + 127 (mp3huffman.cpp:127)
1  MyApp                     0x104807dfc mp3Decoder::decodeFrame(int*, unsigned char**, int, short*) + 141 (mp3File.h:141)
2  MyApp                     0x104808374 mp3File::decodeFrame(short*, unsigned int, bool*, bool*) + 669 (mp3File.h:669)
3  MyApp                     0x104807678 mp3File::decode(short*, unsigned int*) + 543 (mp3File.h:543)
4  MyApp                     0x104802ec0 SuperpoweredDecoder::decode(short*, unsigned int*) + 789 (SuperpoweredDecoder.cpp:789)
5  MyApp                     0x1047de494 shadowThreadFunc(void*) + 1531 (SuperpoweredAdvancedAudioPlayer.cpp:1531)
6  libsystem_pthread.dylib        0x1963cdd8c _pthread_start + 156
7  libsystem_pthread.dylib        0x1963d176c thread_start + 8
```

**Comment by gaborszanto** [comment]
It definitely looks like an invalid memory access, not an out of memory. Please send the audio file triggering this.

**Comment by flagoworld** [comment]
I was able to locate and test the problematic files. When playing from a local file, they play fine, but when progressively streaming from the same URL, they have issues. For me it doesn't crash, but it also doesn't play and keeps erroring with "Download error". I can download the file from the same URL and then play it from that file without issue.

Let me know when you download the zip and I want to delete it off of this comment, as it should not remain publicly downloadable.

[problematic.zip](https://github.com/superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform/files/4099068/problematic.zip)

**Comment by flagoworld** [comment]
Ah... these files are 22050 samplerate. That is why they are playing locally using the iOS built in decoder, but not when using the progressive streamer decoder. However, the streamer shouldn't crash when these are encountered, so that should be fixed.

**Comment by gaborszanto** [comment]
I downloaded the files and tested with the latest Superpowered. Yes, they don't play when streamed progressively, however they don't crash either. I can't reproduce the crash.

**Comment by flagoworld** [comment]
I can’t reproduce it either, but it did happen to users. According to the logs they were also just about completely out of RAM when it happened, which is why I thought maybe it was a low memory issue. Hmmm...

**Comment by gaborszanto** [comment]
Then it seems like invalid paging by the host operating system. Some pages in use are unloaded, which should not happen. If this is the case there is nothing i can do (to fix the OS).
