### ISSUE TITLE
after, open(), getLatestEvent can get cleared before calling getLatestEvent

### ISSUE THREAD

**Issue by flagoworld** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#609]
I have an event loop that calls getLatestEvent() every 100ms. The loop also checks for eofRecently(). When it hits EOF, it calls a function that does some stuff and then calls open(). If open() is called on a local file, the next time the event loop calls getLatestEvent() it's always _None. I have to manually trigger the event loop to fire immediately after open() in order for it to work.

It's possible I might be calling other things on the player in between the time open() is called and the next time the event loop executes, but I still see no reason why getLatestEvent() should be cleared out. It should only ever be cleared out if there's a new event to replace it or it is read, I think?

**Comment by gaborszanto** [comment]
An event is delivered only once, then typically a "none" follows. So you can react to an event once.

**Comment by flagoworld** [comment]
Right, but in this case if getLatestEvent isnt called immediately after open(), it will always returns None. So it becomes impossible to get the Opened event unless the event loop is triggered manually.

**Comment by gaborszanto** [comment]
No. An event is never "discarded". If you don't read the event with getLatestEvent(), then the "opened" event will just wait indefinitely.

**Comment by flagoworld** [comment]
Except my bug report is that it IS getting discarded... I can put together an example project and try to repro it there. It repros consistently in my code and I have made sure to only call it in that one place.

**Comment by gaborszanto** [comment]
Yes, please do that example so i can investigate.

**Comment by flagoworld** [comment]
OK so here's a modified version of the Cross example that repro's it. Once thing I noticed is that the issue is actually somewhat difficult to reproduce on this example, whereas in the real code it is fairly easy to repro. Run in simulator and alternate between pressing play1 and play2. After a few times you will notice a time where clicking one of the buttons doesn't work. If you look at the console when that happens, you'll see the -open log, but then the only events that follow are "0" (none).

[EventConsumed.zip](https://github.com/superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform/files/4149320/EventConsumed.zip)

**Comment by gaborszanto** [comment]
Please note this from the documentation of the open method: "This method has no effect if the previous open didn't finish or if called in the audio processing thread."

If the previous open didn't return with any event yet, the next open will have no effect.

**Comment by flagoworld** [comment]
Excuse the changeup here, I think I misspoke in the last post. I hadn't looked at this for a few days and a few details slipped my mind. The project I sent you actually does reproduce it 100% consistently.

Alternate between pressing play1 and play2 every second or two. The audio will open and play correctly, but if you look at the "EVENT:" log, it always returns "0". The event codes seem to get consumed for some reason before the event loop gets the chance to consume them.

![image](https://user-images.githubusercontent.com/263509/73680239-c85c6000-4670-11ea-91b1-2abfce282aef.png)


However, if you add the line "[self eventLoop:self.eventLoopTimer] at the end of the onPlay1 and onPlay2 functions, so it's called right after open() and play(), then the events come through as expected.

![image](https://user-images.githubusercontent.com/263509/73680449-1e310800-4671-11ea-8e81-d90b28b9671e.png)

**Comment by gaborszanto** [comment]
I see. Because of the slow update frequency (0.5 seconds), the player doesn't see any internal state changed while running getLatestEvent, because the state remained at "Opened".
Your workaround is correct for now. The next Superpowered update will handle this case correctly by resetting the internal state on each open, so you will not miss any event.

**Comment by flagoworld** [comment]
Excellent, thanks!
