### ISSUE TITLE
[HTTP] 40x responses don't have any data

### ISSUE THREAD

**Issue by jkleve** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#610]
Using the SuperpoweredHTTP library, if I get a 400 response from the web server, the data section of the response object is always `null`.

**Comment by gaborszanto** [comment]
Correct, it will not deal with the rest of the message in that case. Do you want to request an "enhancement"?

**Comment by jkleve** [comment]
There have been many times where I've switch to an http client (httpie, postman, etc) to re-create the request so that I can see the error being returned by the web server.

So yes, I think it'd be a great addition to have that data returned upon errors.

**Comment by gaborszanto** [comment]
The next update (coming soon) will have a returnWithDataOnError property on the httpRequest class (default: false). If you set it to true, it will return with the full body of the response.
