### ISSUE TITLE
Using different audio source and sink in the SuperpoweredEffect sample Android app

### ISSUE THREAD

**Issue by mahaju** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#611]
I am testing out the SuperpoweredEffects app for android
Is this app based on AAudio or OpenSL ES? I can see refercences to both in the source code files. Does it chosse what to use itself?
I want the app to always use the builtin microphone for audio input regardless of whether an external mic is connected or not, but it seems to choose the audio input source automatically.

Is it possible to make the app choose a particular audio input source and output sink?

**Comment by gaborszanto** [comment]
For audio I/O the example provides an open-source class, SuperpoweredAndroidAudioIO. It auto-detects if AAudio is available, and if low-latency is required, will try to use that first (then fall back to OpenSL ES). 

On Android routing is not "guaranteed" but you can affect that with standard Android APIs in Java.

You can check the source directly in the SDK: https://github.com/superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform/blob/master/Superpowered/OpenSource/SuperpoweredAndroidAudioIO.cpp
