### ISSUE TITLE
macOS SDK Example

### ISSUE THREAD

**Issue by patrickbdev** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#612]
Hello, there are a great set of examples but there's one missing for macOS. Is there any chance that could be created, in particular the offline analysing?
Thank you.

**Comment by gaborszanto** [comment]
Hello, we're not able to provide and maintain an example for each platform, however offline analyzing is available on iOS and most of the code is copy-paste. It's a trivial exercise to "port" (copy-paste) the relevant parts of the iOS example into a macOS project, and also a good practice!
