### ISSUE TITLE
Apple Watch Compatibility?

### ISSUE THREAD

**Issue by frogg** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#613]
Would love to give this a try on Apple Watch. Any chance that it‘s somehow compatible?

**Comment by gaborszanto** [comment]
We don't see Apple Watch a good platform for custom audio processing, because of the limited audio I/O capabilities. Can you set up an audio I/O on the Apple Watch these times and process audio in real-time?
