### ISSUE TITLE
SuperpoweredDecoder causes fatal SIGSEGV fault on Android with DRM file

### ISSUE THREAD

**Issue by flamewave000** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#614]
I have recently run into an issue where a user tries to open a M4A file that has Apple's DRM protection built into it. Unfortunately Android does not give me information on if a file is DRM protected. Currently when this file is passed to Superpowered for analysis, SuperpoweredDecoder.decode() will cause a Segmentation Fault (SIGSEGV) which cannot be caught and causes the app to be immediately terminated. I assume that the decoder is likely getting some kind of bad block size, and then jumping outside the confines of the app's designated memory region.

It would be nice if the decoder could detect the "corrupted" state of the file (due to the encryption) and either return an error state, or throw a native exception that I can catch in my Kotlin JNI wrapper.

**Comment by gaborszanto** [comment]
We handled tons of similar cases already, but a new one can always surprise us. It seems like this is the case now. Please send the file.

**Comment by gaborszanto** [comment]
I was not able to crash the latest (2.0.3) version of Superpowered with the file you sent, nor was able to detect any corrupted memory access.

**Comment by gaborszanto** [comment]
Can you reproduce the crash with Superpowered 2.0.3?

**Comment by gaborszanto** [comment]
Can you reproduce the crash with Superpowered 2.0.3?
