### ISSUE TITLE
Android pops and clicks during playback

### ISSUE THREAD

**Issue by flagoworld** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#615]
We are updating our android app to the latest version of Superpowered, from the 1.x range to 2.0.3. In doing this, we noticed some popping and clicking during playback. We tried compiling the example projects and noted the same popping and clicking on both emulator and device.

NDK version 21.0.6113669, but tried older versions as well

Attached a recording of the popping that happens during playback.

[sp_upgrade_artifacts.zip](https://github.com/superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform/files/4356125/sp_upgrade_artifacts.zip)

**Comment by gaborszanto** [comment]
Do the pops go away when you insert the following line into SuperpoweredAndroidAudioIO.cpp, before line 445? internals->aaudio = false;

**Comment by flagoworld** [comment]
Yup! That appears to fix it.

**Comment by gaborszanto** [comment]
On which device is this?

**Comment by flagoworld** [comment]
So far Pixel 3 XL (10), Moto G5 (8.1.0) and Emulator (7.1.1). I have not done a complete set of tests

**Comment by gaborszanto** [comment]
I can replicate this in the Emulator. Unfortunately it happens with Google's own Oboe library as well. I contacted Oboe to start working on a real fix.

**Comment by gaborszanto** [comment]
Disabled AAudio in the new update for now.
