### ISSUE TITLE
Alternative to setPitchShift...() methods

### ISSUE THREAD

**Issue by Sandeep-Satheesh** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#616]
Hi,

I've used the earlier version of the Superpowered Audio SDK, where I could change the pitch of the audio by using the player->setPitchShift() and player->setPitchShiftCents() methods. However, I can't seem to find them in the current version of the SDK, and the docs too don't mention anything like a simple function to do so.

Am I missing anything here (like, are they in a different header file or something)? If not, what should be my alternative for implementing pitch shift?

PS: The above is true not only for the setPitchShift...() methods, but also for the setTempo() methods too.

**Comment by gaborszanto** [comment]
Those are simple properties now. playbackRate and pitchShiftCents.

**Comment by Sandeep-Satheesh** [comment]
Thanks for your response, Mr. Szanto. 

However, when I tried to directly change the pitchShiftCents in the `audioProcessing()` function, I don't get any pitch shift effect:
           ` player->timeStretching = true;`
            `player->pitchShiftCents = transpose;`

Could you please let me know what am I missing here?
