### ISSUE TITLE
[SuperpoweredHTTP] CantConnect with POST & DELETE

### ISSUE THREAD

**Issue by jkleve** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#618]
v2.0.3

With the latest update we get error 3 CantConnect when making POST and DELETE calls to the API. On Windows we can't login because the POST to try and authenticate receives a CantConnect. On macOS, we are able to login but when trying to DELETE resources, we get a 3 CantConnect even though the resource is being deleted on the server.

**Comment by gaborszanto** [comment]
Is this related to the new returnWithDataOnError property? Does it work if it's false?

**Comment by jkleve** [comment]
I'm not seeing that property in v2.0.3. On the HTTP Request object?

**Comment by gaborszanto** [comment]
The latest update is v2.0.4, please try that.
Also I wonder why you get different behaviour on Windows vs macOS, since exactly the same code runs on both.

**Comment by jkleve** [comment]
Yea, I'm still seeing the issue.

**Comment by gaborszanto** [comment]
Just tested with a simple PHP script echoing back the contents of POST and DELETE and it works great.

Superpowered has exactly the same code running on both macOS and Windows, therefore I don't understand how this is possible at all. Maybe you've some networking or proxy issues?

**Comment by gaborszanto** [comment]
Jesse?

**Comment by jkleve** [comment]
Sorry. Yea unsure, maybe something specific about our security on our API?

We're not dedicating resources to investigating it right now.

**Comment by gaborszanto** [comment]
Okay, then I guess this issue will sit until you can investigate, since I'm not able to reproduce it.

**Comment by jkleve** [comment]
We can go ahead and close this and revisit it if we find this detrimental.
