### ISSUE TITLE
iOS WiFi-Cellular Switch For Progressive Download

### ISSUE THREAD

**Issue by flagoworld** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#619]
If the network connection dies in the middle of a progressive download, the PlayerEvent_ProgressiveDownloadFinished event will get triggered instead of an error event.

Repro: Start a progressive download on ios. Turn off wifi and cellular data. Wait a while. When the download times out, it will send that event instead of an error event.

**Comment by gaborszanto** [comment]
Can reproduce. Next update (coming very soon) will have the fix. Please test when it's out.

**Comment by gaborszanto** [comment]
It's out!

**Comment by flagoworld** [comment]
OK I gave it a try. It looks like it's mostly fixed now, but there is still an issue. Might be a different issue though...

On iOS, make sure wifi and cellular data are both ON. Open a progressive download. Turn off wifi mid download. The download gets stuck in a state where it doesn't recover until wifi is turned back on, even though there's still connection via cellular.

I would expect it to either seamlessly transfer over to cellular, OR for it to time out and throw an error so I can write code that makes it retry. Currently it will get stuck "forever" in this state.

**Comment by gaborszanto** [comment]
We're not able to incorporate iOS' reachability API to detect this scenario currently. But you can pass a custom Superpowered::httpRequest to the player's open method, and you can set its timeoutSeconds property.

**Comment by flagoworld** [comment]
I have timeoutSeconds set to 30. If I open the request on cellular and then turn off cellular, the timeout works. If I open the request on wifi and turn off wifi, it never times out. This is not an uncommon occurrence... For example, if the user walks out of wifi range, walks by open networks and the wifi turns on and off, etc.

**Comment by gaborszanto** [comment]
How do you turn off wifi? Because using the control center it doesn't turn off wifi, just disconnects from the network. It might not be a "true" wifi off, therefore the socket is still open. I guess that you need to use the reachability framework of iOS to handle this situation, which we aren't able to build into a pure C++ library.

**Comment by flagoworld** [comment]
I have tried both in Settings and from Control Center with the same results. Should the httpRequest not time out of no packets are received in timeoutSeconds? How do you recommend I handle this? Manually implement a timeout and call open() again if buffer % hasnt changed in a certain amount of time?

**Comment by gaborszanto** [comment]
Absolutely, the socket must time out. But it seems like the operating system thinks about this differently. I'm not sure how to handle this properly yet.

**Comment by flagoworld** [comment]
Could this be related?

https://stackoverflow.com/questions/32362482/in-ios-why-doesnt-socket-recv-fail-when-the-underlying-network-changes

**Comment by gaborszanto** [comment]
Let's see if that help. Can you please try the attached experimental build?
[libSuperpoweredAudioIOS.a.zip](https://github.com/superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform/files/4575779/libSuperpoweredAudioIOS.a.zip)

**Comment by flagoworld** [comment]
Thanks, that doesn't seem to fix it, unfortunately. :( If I come across anything else that might help I will pass it along. For now I will manually implement timeout if the player gets stuck buffering for more than the specified timeoutInterval.

**Comment by gaborszanto** [comment]
Here is another try, please test:
[libSuperpoweredAudioIOS.a.zip](https://github.com/superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform/files/4579567/libSuperpoweredAudioIOS.a.zip)

**Comment by gaborszanto** [comment]
Can you please test it? The one above?

**Comment by flagoworld** [comment]
Just finished testing. Same results, doesn't time out.

**Comment by gaborszanto** [comment]
What you just tested was not sockets, but NSStream... If official Apple API can't do that, then I don't know what can.

**Comment by flagoworld** [comment]
I think that's all backed by C sockets but yeah... either there's a special configuration for this or there isn't and it's some kind of software bug.

**Comment by flagoworld** [comment]
Ah, I found another reference to this issue.. it appears to be a known issue.

https://github.com/grpc/grpc-swift/issues/337

**Comment by gaborszanto** [comment]
Yes, it's all backed by BSD sockets, but according to the Apple engineers NSStream (CFStream) also does some additional "smarts".
