### ISSUE TITLE
Compile using Xcode 11.3

### ISSUE THREAD

**Issue by flagoworld** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#621]
There's a bug on Xcode 11.4 that causes armv7 devices to crash when running apps compiled in Xcode 11.4. It is fixed in 11.5 beta, but the beta Xcode cannot be used to compile apps for the app store.  The latest SP release is built using Xcode 11.4, so I have to use the previous version of SP in order to compile the app in Xcode 11.3.

Would it be possible to rebuild SP using Xcode 11.3 until 11.5 comes out so that I can use the latest  with our users?

Thanks

**Comment by gaborszanto** [comment]
Is your application crashing? Our test apps are not crashing on the iPad 2 (which is armv7).

**Comment by flagoworld** [comment]
You have to compile in release mode (distribute adhoc) and possibly include certain libraries? Not exactly sure but code generation corrupts certain things in release mode. It was reproducible for a lot of people running various libraries including us. I am not sure if it was reproducible without any of those libraries... But its not the fault of the libraries, its an Xcode bug. One such lib for us was Starscream websocket lib (swift)

**Comment by gaborszanto** [comment]
Let's hope that 11.5 gets out of beta soon. We can't distribute libraries built with beta Xcode versions, because submitting apps to the App Store with such builds is not possible.

**Comment by flagoworld** [comment]
Agreed. For now, we are compiling using 11.3 instead of 11.4 and that works fine. However, that restricts me to SP 2.0.4 since that is the last version compiled on 11.3.
