### ISSUE TITLE
Android audioTrack play question

### ISSUE THREAD

**Issue by charlie-captain** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#622]
Hi, I have a question about using audioTrack to play audio buffer.
```
audioIO = new SuperpoweredAndroidAudioIO(samplerate, buffersize, true, false, audioProcessing, NULL, microPhoneType, SL_ANDROID_STREAM_MEDIA, buffersize * 2); // Start audio input/output.
```
Here is AudioTrack code
```
val audioAttributes = AudioAttributes.Builder()
            .setUsage(AudioAttributes.USAGE_MEDIA)
            .setLegacyStreamType(AudioManager.STREAM_MUSIC)
            .setContentType(AudioAttributes.CONTENT_TYPE_SPEECH)
            .setFlags(AudioAttributes.FLAG_AUDIBILITY_ENFORCED)
            .build()
        val audioFormat = AudioFormat.Builder()
            .setEncoding(AudioFormat.ENCODING_PCM_16BIT)
            .setSampleRate(SAMPLE_RATE)
            .setChannelMask(AudioFormat.CHANNEL_OUT_STEREO)
            .build()
        bufferSize = AudioTrack.getMinBufferSize(SAMPLE_RATE, AudioFormat.CHANNEL_OUT_STEREO, AudioFormat.ENCODING_PCM_16BIT)
        audioTrack = AudioTrack(audioAttributes, audioFormat, bufferSize, AudioTrack.MODE_STREAM, AudioManager.AUDIO_SESSION_ID_GENERATE)
        audioTrack?.play()
```

When I play buffer from io, it sounds strange.
Do you know the right way to record and playback together?

**Comment by gaborszanto** [comment]
You have to use native audio OR Java audio, but never both.
Use native audio using SuperpoweredAndroidAudioIO. It can set up both input and output simultaneously.

**Comment by charlie-captain** [comment]
> You have to use native audio OR Java audio, but never both.
> Use native audio using SuperpoweredAndroidAudioIO. It can set up both input and output simultaneously.

OK, thank you, could you tell me the example?

**Comment by gaborszanto** [comment]
Put the player stuff here: https://github.com/superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform/blob/master/Examples_Android/SuperpoweredPlayer/app/src/main/cpp/PlayerExample.cpp

Into this project: https://github.com/superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform/tree/master/Examples_Android/SuperpoweredRecorder

**Comment by charlie-captain** [comment]
thx
