### ISSUE TITLE
Audio stuttering on lower end Android devices

### ISSUE THREAD

**Issue by flagoworld** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#623]
We are experiencing some bad audio stuttering issues on lower end Android devices.

- This can be reproduced using the android example apps.
- This happens any time the CPU is loaded at all.
- It happens more frequently when the app is in the background.
- Other players do not have this problem.
- There is a slight improvement when moving the buffersize up to 1024, though 240 is what the system is suggesting

The devices we can reproduce this on are as follows, but I would expect there to be many more out there that it happens on:
- Moto 4 g
- Alcatel Raven LTE

**Comment by gaborszanto** [comment]
Is this with the latest Superpowered having AAUDIO turned off in SuperpoweredAndroidAudioIO.cpp? What is the Android version on those? Do you expect high-performance audio working on such old devices? (I understand that Java-based players might work okay. But those are not designed for high performance.)

**Comment by flagoworld** [comment]
Latest version, yes. AAudio off. I think android version is 7.0

I misspoke slightly. It's Moto G (4th gen) not Moto 4 G.

I think it would be OK if high performance audio was less high performance on really old devices, but having them not work at all is problematic.

If there was a way to adjust performance level based on device specs (maybe an API available to us developers with a few levels of performance or something) that would probably be sufficient. A flag "low performance mode", maybe.

These phones are 4 years old, yes, but they are not THAT slow. It seems like if superpowered only requires a a little bit of CPU to function, that it should not bog down on these phones. It's still a quad core 1.5ghz phone according to the googles.

The iphone 5 is much slower and older and doesn't have any stuttering issues at all, even when loaded pretty heavily.. Not sure what the bottleneck is on android specifically, but there must be a way to make it behave the same as the old iphones if native code is being used?? (Or maybe its because of lack of hardware accel and there isnt an easy way?)

**Comment by gaborszanto** [comment]
This is purely a software problem and has nothing to do with device specs. There are two ways to set up audio I/O for an Android app: Java or native. The native path is considered to be "high performance - low latency", while the Java path is the "regular one" with "low performance - high latency". Superpowered is a native library. Device manufacturers often forget to test the native path.
There is nothing to "tune" here, you can see in the code that Superpowered takes the recommended best values provided by the official Android APIs.

**Comment by flagoworld** [comment]
I see. In the interest of providing the best experience to users, is there a way to allow audio to be higher latency in extreme cases such as these devices whose software is not properly supporting low latency audio? At least that way it would work even if not as low latency. I guess I could technically fall back to a java based player, but that is quite a lot of extra work.

**Comment by gaborszanto** [comment]
It's not about latency. Many of these problems can not be solved by increasing latency. For example, it can also be a bug in the resampler in the audio HAL of the device, as it just happened on the Galaxy S20. Can you try fixing the sample rate to 44100 (when passing sample rate to the native layer) to see if it helps?

**Comment by flagoworld** [comment]
We will try 44100 and get back to you soon.

**Comment by flagoworld** [comment]
We might have been able to mitigate this by reducing certain CPU-heavy operations our app does. Not 100% sure yet but waiting to hear back from a few users.

**Comment by gaborszanto** [comment]
still waiting?
