### ISSUE TITLE
Superpowered::netRecv(int, unsigned char*, int, int) in libSuperpoweredAudioIOS.a(net.o)

### ISSUE THREAD

**Issue by Saravana-iOS** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#624]
Hi 

I have used Superpowered for my iOS Application past one year it works amazing, you guys are doing great job. 

My Error in the current version 2.0.5 is:

Undefined symbols for architecture x86_64:
  "___darwin_check_fd_set_overflow", referenced from:
      Superpowered::netRecv(int, unsigned char*, int, int) in libSuperpoweredAudioIOS.a(net.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

After integrated the latest files to my projects and run i received this type of errors. In Sample App(SuperpoweredCrossExample) also i couldn't able Run.

Please check and give some suggestion to clear this issues.

Thanks in Advance 😊

**Comment by gaborszanto** [comment]
Thank you! I think you need to update Xcode.

**Comment by Saravana-iOS** [comment]
Oh, Thanks for your response. My XCode Version is  11.3.1, i will update and check.

**Comment by Saravana-iOS** [comment]
Thanks @gaborszanto , my issue is fixed.
