### ISSUE TITLE
Position incorrect when starting before defined loop

### ISSUE THREAD

**Issue by flamewave000** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#625]
There is an issue with the following 2 scenarios:

- User sets loop for 00:05 to 00:06.
- User moves playhead to 00:01.
- User hits play.

Currently the audio output comes through as expected, the first 4 seconds before the loop are played, and then the loop begins to play and loop properly. The issue is with the position report, currently it does not report back the proper position that is currently being output. Instead it does the following:

- From 00:01 to 00:04, position reports: 00:05 constant (doesn't move)
- From 00:04 to 00:05, position moves through the loop 00:05 to 00:06 (as if playing the loop)
- At 00:05, position restarts at beginning of loop and finally syncs up with the actual audio output.

The other scenario is when the user moves the position to a point before the loop that is less than the duration of the loop itself:

- User sets loop for 00:04 to 00:08
- User moves playhead to 00:02
- User hits play.

The position report will be as follows:

- From 00:02 to 00:04, position reports: 00:06 to 00:08
- At 00:04, position restarts at beginning of loop and finally syncs up with the actual audio output.

It appears the position reported magnets to the beginning of the loop if the current playback is further than the duration of the loop, but once the playback is within the distance of one loop duration, it reports the position as being in the loop but actually outputting the proper before-loop audio. Then when the actual playback reaches the start of the loop, the audio output and the play position finally line back up again.

I was seeing a similar issue on the old version of Superpowered, but have since upgraded to 2.0.5 and I am still seeing an issue, albeit slightly different than before.

**Comment by gaborszanto** [comment]
Please note there are two different position getters for this reason: getDisplayPositionMs and getPositionMs. Maybe try the other one?

**Comment by flamewave000** [comment]
@gaborszanto I've tried both getPositionMs and getDisplayPositionMs. They both have the same issue.

**Comment by gaborszanto** [comment]
I just checked these properties. These were created for very sophisticated "DJ-style" looping and have very complex mechanisms behind, therefore changing it would break many applications.
In those applications they implemented the following approach: when the user sets a loop outside of the current position, loopBetween() is called only after actually entering into the loop.
