### ISSUE TITLE
Superpowered::Reverb predelayMs

### ISSUE THREAD

**Issue by svenoaks** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#630]
The docs state this property is "Pre-delay in milliseconds. 0 to 500."

However, it is impossible to set higher than 1.0. If set higher, reading the property from the Reverb object will just yield 1.0.

I thought maybe it is actually in seconds, but I can't hear anything different between 0.0 and 0.5, but maybe it is difficult to hear.

Could you clarify this property?

**Comment by gaborszanto** [comment]
Thank you discovering this bug. Will be fixed in the next update.
