### ISSUE TITLE
Superpowered::FX defaults and ranges in docs

### ISSUE THREAD

**Issue by svenoaks** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#631]
Some doc pages like Superpowered::Compressor list the default values for the properties, while others like Superpowered::Reverb don't. Could you list the defaults in the docs for all the effects so we don't have to discover them manually?

Likewise, a lot of the values are missing accepted ranges for the values of the properties.

**Comment by gaborszanto** [comment]
The next update will have this, however relying on defaults is not a good practice, as they might change. Always set your own values after creating an effect.
