### ISSUE TITLE
Superpowered::Analyzer probability of being correct

### ISSUE THREAD

**Issue by svenoaks** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#634]
Could you add a result to this class which is the probability that the "fuzzy" results (such as key and BPM) are correct or confidence level? I know some similar audio analysis tools do this.

**Comment by gaborszanto** [comment]
Our algorithms doesn't have an internal confidence level that I can just expose. I'm not sure if we'll change our implementations to get come confidence level, since you're the very first requesting this so far.
