### ISSUE TITLE
 superpowered Recorded Audio File Size is too large

### ISSUE THREAD

**Issue by rajaroni** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#635]
i,hope you are doing good. Actually I am using superpowered for audio effects/filters but the recorded file size is too large. Is there any way to reduce file size or any way to record file of lower size. as 1 min file size is almost 22mb now.

**Comment by gaborszanto** [comment]
The Superpowered Recorder outputs uncompressed PCM audio into a WAV file. That is the normal size of that format. The SDK doesn't offer encoding to MP3 or AAC, please use the APIs available in your platform to do that.
