### ISSUE TITLE
How to get frequency or Pitch while Recording Using SuperPowered Recorder

### ISSUE THREAD

**Issue by rajaroni** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#636]
How to get frequency or Pitch while Recording Using Super Powered Recorder as i am trying to draw pitch time graph

**Comment by gaborszanto** [comment]
Use the BandpassFilterbank class. Tune each filter in the filter bank to a note.
