### ISSUE TITLE
Superpowered Recorded Wav file is corrupted

### ISSUE THREAD

**Issue by syedateeb1** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#638]
I'm trying to record audio with reverb effect first time it is working fine but when i try to record the audio for second time the wav file generated is corrupted and the size of this file is 44 byte.

**Comment by gaborszanto** [comment]
This bug will be fixed in the upcoming release of Superpowered, expect it within a week or so.
