### ISSUE TITLE
AudioiO is taking time to stop

### ISSUE THREAD

**Issue by syedateeb1** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#641]
I'm calling this function to stop the audioIo processing.
 audioIO -> stop();
But it takes 1 min to stop

**Comment by gaborszanto** [comment]
It's definitely too much. How quickly does it stop in the example projects that ship with the SDK?

**Comment by syedateeb1** [comment]
takes minimum i guess 30 seconds to stop.. when is call this stop function i still can hear my voice feedback for sometime then it stop sending sending feedback

**Comment by gaborszanto** [comment]
Which example project did take 30 seconds to stop? 
Is it an unmodified example project directly from the SDK?
On what device?

**Comment by syedateeb1** [comment]
Example Recorder project. I just add two functions in this example that is pause and resume.. In pause function i call audioio->stop but it stops after sometime.. I'm testing it on android version 9.0 .. Infinix Hot 8

**Comment by gaborszanto** [comment]
How long does it take to stop for the _unmodified_ Recorder example project?

**Comment by syedateeb1** [comment]
Minimum 30 seconds . Sometime it is more than that.

**Comment by gaborszanto** [comment]
This is the very first time we receive a problem like this. However there are many badly implemented Android devices out there, so maybe this is caused by the audio stack of your Infinix device. Can you test on another device to see if it makes a difference?
