### ISSUE TITLE
How to pause and resume superpowered Recorder?

### ISSUE THREAD

**Issue by syedateeb1** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#642]
How to implement pause and resume functionality in superpowered Recorder?

**Comment by gaborszanto** [comment]
Just don't call the recorder's process() function when you don't want to record.

**Comment by syedateeb1** [comment]
I call it in the audio processing call back. how can i stop this call back
and start again?

**Comment by gaborszanto** [comment]
Just don't call it there. Or, since you set up audio I/O with the SuperpoweredAndroidAudioIO class, use its start and stop methods.

**Comment by syedateeb1** [comment]
yes i did use it. it is working fine but audioio stop takes time to stop.
