### ISSUE TITLE
When corrupted wav file issue will be fixed?

### ISSUE THREAD

**Issue by syedateeb1** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#643]

**Comment by syedateeb1** [comment]
When i reopen the app it is created fine but when i try to record the second time without closing the app then wav file is corrupted and of 44 bytes.. How other apps using this library never face this issue?

P.s This library is the best one in the whole world related to low latency audio. Thankyou

**Comment by gaborszanto** [comment]
it will be fixed in the next update, coming early September

**Comment by syedateeb1** [comment]
I think delete recorder does not work. Thats why we have to kill the app to delete the recorder before recording again

**Comment by gaborszanto** [comment]
No, that was not the problem, but a missing file descriptor for the log file.

**Comment by syedateeb1** [comment]
Thanks alot for your help and reply. (Y)

**Comment by syedateeb1** [comment]
Hi. When this will be fixed?

**Comment by gaborszanto** [comment]
It will be fixed in the next update. Previously I thought it will come early September, but I'm not able to predict it precisely. Will come this September.
