### ISSUE TITLE
How to return pitch or frequency while recording to java function

### ISSUE THREAD

**Issue by syedateeb1** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#645]
I want user's voice real time pitch or frequency to implement singing training app where user's voice pitch will match the song note and will get marks according to it. After alot of researched could'nt achieve that. Please help

**Comment by gaborszanto** [comment]
Use a Superpowered::BandpassFilterbank, tune each filter to specific notes with narrow widths. Check the filter with the highest magnitude.

**Comment by syedateeb1** [comment]
Can you please share some example? :(
