### ISSUE TITLE
Any Example for how to use bandpassfilter to tune filter to a note?

### ISSUE THREAD

**Issue by syedateeb1** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#646]
Any Example for how to use bandpassfilter to tune filter to a note?

**Comment by gaborszanto** [comment]
We are not able to provide an example for every feature of Superpowered, because there are simply too many. There is no example for this filter, however its API is extremely simple, so please read the documentation.
