### ISSUE TITLE
Decoded Audio produces to faster than the actual audio.

### ISSUE THREAD

**Issue by nilamvaddoriya-simformsolutions** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#648]
Hi,
I am using a superpowered decoder and facing an issue, after decoding audio produces to faster than actual audio especially when I get the decoder sample rate 22050, Is there any way I can resample the audio for such a case. Any help would be much appreciated.
Thank you.

**Comment by gaborszanto** [comment]
Hi,

the decoder will always return with the original sample rate of the audio file. You can use our Resampler class to resample.

**Comment by nilamvaddoriya-simformsolutions** [comment]
Hii @gaborszanto Yes, I have used a resampler to convert 22050 to 44100 but it's not working properly, Can you please help me with resampling audio or is there any example for resampling and also what would be the sampling rate to convert sample rate from 22050 to 44100.

**Comment by gaborszanto** [comment]
Please check out the various support options here: https://superpowered.com/support I close this ticket now, since it's not an issue with Superpowered, but your custom code.
