### ISSUE TITLE
Duration of audio changed after resample the audio.

### ISSUE THREAD

**Issue by nilamvaddoriya-simformsolutions** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#649]
Hi, I am resampling audio using Superpowered SDK and after resampling, audio duration gets changed and also getting noise in audio, It would be much-appreciated anyone can help with this.

Thank you.

**Comment by gaborszanto** [comment]
Changes in duration is completely normal for compressed formats. Most compressed formats doesn't contain precise duration information, only an estimate, so the decoder will only know the exact duration after decoding every frame. This is the behaviour of most decoders, including Core Audio by Apple.

You shouldn't receive "noise" in the audio after resampling, maybe there is an implementation problem in your code, such as not taking the returned number of frames after resampler->process()?

**Comment by nilamvaddoriya-simformsolutions** [comment]
Hii @gaborszanto
I want to mix two audio files one is having a sample rate 22kHZ and another one has 44.1kHZ, How can I do it using Superpowered SDK?

What I have tried is I have first try to resample the audio file from 22kHZ to 44.1kHZ  and then decode both audio files and then mix both decoded audio files using Superpowered SDK. But due to the resample audio duration being changed so the actual output is being wrong.

**Comment by gaborszanto** [comment]
Decode one audio file, resample to 44100, buffer the result. Decode the other audio file, mix with the buffer. Please note that you will get different number of frames available, so you need some fifo implementation.
