### ISSUE TITLE
SuperpoweredRecorder takes too long after stop() is called

### ISSUE THREAD

**Issue by romanbsd** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#650]
We're using the version 1.4 of Superpowered SDK.

We have observed that it may take hundreds of milliseconds after the stop() is called and the file is ready at its destination (yesterday it was taking more than 1 s on Samsung S7 device for a ~6MB file).
Since the disk IO bandwidth is higher than the audio IO bandwidth, it's unlikely that it's "catching up". I suspect that what is being done is the large temporary file being copied to the final destination. If this is indeed the case, is it possible to modify the WAV header in the temporary file in-place and then use rename(2) call, and only if it fails with EXDEV, then actually perform a copy as a fallback?
Can there be something else that can be done meanwhile?

Thank you in advance!

**Comment by gaborszanto** [comment]
Yes, the temporary file is moved to the final destination. However it's performed using the standard "rename" API, not a copy. We don't provide support for 1.4 anymore, so I can't check what's happening in that call. From 2.x, the stop call just flips a flag, so it can't block.

**Comment by romanbsd** [comment]
I ran a polling test doing a stat() call, and the file was growing after the stop() was called. It took 60-90ms until the file appeared in the final destination, and then hundreds of ms until it was completely there. So it looks that it's being copied rather than renamed. Please check. We're planning to upgrade to 2.x at some point, but not there yet.

**Comment by gaborszanto** [comment]
In 2.x we have the standard Posix "rename" call. I will not check the source of 1.4, but I doubt it has copy. However the operating system may perform a copy under the hood.

**Comment by romanbsd** [comment]
I'll check how it behaves after upgrading to 2.x. Closing for now.
