### ISSUE TITLE
Android SuperpoweredUSBExample Garbled Audio Passthrough

### ISSUE THREAD

**Issue by adamhs1997** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#651]
I would like to use Superpowered to handle USB audio input and output for my Android application. I built and ran the SuperpoweredUSBExample on my phone (a Samsung Galaxy S7 running Android 8) and got garbled audio when trying to use the passthrough option. The audio has a lot of background noise, with my voice seeming to have a higher pitch. It also sounds like there is some data being clipped, giving it a "robotic" sound.

This file contains some audio I recorded from the device. In it, I tap on the microphone twice, then say the word "test" twice.
[sample_audio.zip](https://github.com/superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform/files/5255158/sample_audio.zip)

I had considered it being a device issue since I have seen that listed as a possible explanation for other issues posted here. My colleague tested on his device (I do not remember the device model, but he has mentioned that he is using Android 10) and got the same result.

At one point, I modified the SuperpoweredUSBExample to write the input to an uncompressed PCM file. The recording sounds fine when I play this back on Audacity. It properly recorded with the parameters I specified (44.1k mono). Regardless of the options I choose in the SuperpoweredUSBExample, I get similar results for the passthrough.

My concern is that there may be an issue with passing a mono input to a stereo output. Superpowered only ever detects mono input and stereo output options, and I see no way to treat my stereo output as a mono output to have a simple 1 to 1 passthrough. Can Superpowered handle a passthrough of a mono audio recording to a stereo output? If not, is there a way that I can resize the buffer in the callback for the StartIO function so that I can duplicate the incoming data for each channel?

I appreciate any advice you can give.

**Comment by gaborszanto** [comment]
Your USB sound device has mono inputs and stereo outputs only?

**Comment by adamhs1997** [comment]
Yes. I actually have three USB devices and they all have the same configuration reported by the SuperpoweredUSBExample. The devices I am using are all USB to TRS adapters, each with one mic input and one headphone output.

**Comment by gaborszanto** [comment]
I see. The example is not prepared to handle that, in pass-through mode it doesn't change the contents of the buffers, they just pass through. So the output expects an interleaved stereo signal, but actually it receives mono and some memory garbage.

**Comment by adamhs1997** [comment]
I was afraid of that. Does that mean there is no way to make a passthrough that would take in this mono input and convert it to an interleaved stereo output? The only way I could see to do this was using either the StartIO or EasyIO functions, which both use a callback like the example application.

I guess my other option might be to use separate StartIO calls, one for the input device, one for the output device, then use separate callback functions. The input callback could write to a shared buffer, then the output callback could read from that buffer and do the interleaving. I think that'd get messy though.

**Comment by gaborszanto** [comment]
There is an easy way. Audio flows through the "audioProcessing" function here: https://github.com/superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform/blob/master/Examples_Android/SuperpoweredUSBExample/complexusb/src/main/jni/complexusb.cpp

At line 335 you see pass-through (default case). Put some code there to handle the case where numInputChannels is 1, but numOutputChannels is more.

**Comment by adamhs1997** [comment]
Okay, wow, it is that simple. My worry was that since it's mono to stereo, the size of the output buffer had to double to properly interleave the output. I figured my buffer size was constrained by numberOfSamples in the callback function but I guess that's somehow not the case? Thank you for your help!
