### ISSUE TITLE
Crash in SuperpoweredCPU.cpp

### ISSUE THREAD

**Issue by romanbsd** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#652]
Superpowered v1.4.0
```
Thread
#00 pc 0x6f2be1fca0 libAudioAPI.so (nopThreadFunc(void*) [SuperpoweredCPU.cpp:88])
#01 pc 0x6f2be1fc48 libAudioAPI.so (nopThreadFunc(void*) [SuperpoweredCPU.cpp:81])
#02 pc 0x701fc84b24 libc.so 
#03 pc 0x701fc26330 libc.so 
```

**Comment by gaborszanto** [comment]
- We provide no support for 1.4.0, as announced more than a year ago.
- Is this a crash log? I don't see any crash information (what happened, such as a SIG_something).

**Comment by romanbsd** [comment]
Sorry, I somehow missed that. I vaguely remember that we had to upgrade to 1.4.0 because of licensing changes, but was under impression that we can stay on 1.4.
I'll close it and reopen if it still happens on 2.0 after we upgrade.
