### ISSUE TITLE
Will there be support for Apple's Universal Binary format for ARM hardware?

### ISSUE THREAD

**Issue by jkleve** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#653]

**Comment by gaborszanto** [comment]
We were waiting for the official Xcode 12 release to include an ARM64 macOS build in the SDK. You will have it in the next Superpowered update.

**Comment by jkleve** [comment]
Cool. Is there an estimation on when this will be?

**Comment by gaborszanto** [comment]
It seems like Xcode 12 is not enough to build it, but macOS Big Sur is also required. There is no official stable release of Big Sur yet.
