### ISSUE TITLE
ShortIntToFloat Issue

### ISSUE THREAD

**Issue by JasonAnytune** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#654]
Running into a reoccurring crash with Superpowered::ShortIntToFloat(intBuffer, floatBuffer, framesDecoded) from the SuperpoweredSimple.h file. We are using this function call to analyze the BPM of a song in our code. We are not able reproduce this crash but are seeing it in our crash reports. The BPM is calculating properly for the files we are testing with.

Was there any recent changes to this section of the code? Are we missing something?

We followed the example and are using this call as follows:

> - (void)offlineAnalyzeWithSuperpowered:(NSURL *)url {
>     Superpowered::Decoder *decoder = openSourceFile([url.path UTF8String]);
>     if (!decoder) return;
> 
>     // Create the analyzer.
>     Superpowered::Analyzer *analyzer = new Superpowered::Analyzer(decoder->getSamplerate(), decoder-getDurationSeconds());
> 
>     // Create a buffer for the 16-bit integer audio output of the decoder.
>     short int *intBuffer = (short int *)malloc(decoder->getFramesPerChunk() * 2 * sizeof(short int) + 16384);
>     // Create a buffer for the 32-bit floating point audio required by the effect.
>     float *floatBuffer = (float *)malloc(decoder->getFramesPerChunk() * 2 * sizeof(float) + 16384);
>     
>     //int progress  = 0;
> 
>     // Processing.
>     while (true) {
>         int framesDecoded = decoder->decodeAudio(intBuffer, decoder->getFramesPerChunk());
>         if (framesDecoded == Superpowered::Decoder::BufferingTryAgainLater) { // May happen for progressive downloads.
>             usleep(100000); // Wait 100 ms for the network to load more data.
>             continue;
>         } else if (framesDecoded < 1) break;
> 
>         // Submit the decoded audio to the analyzer.
>         Superpowered::ShortIntToFloat(intBuffer, floatBuffer, framesDecoded); // * This is the line * //
>         analyzer->process(floatBuffer, framesDecoded);
> 
>         //progress = (double)decoder->getPositionFrames() / (double)decoder->getDurationFrames();
>         //eventually update ui with importTracker.importProgress = progress after refractoring
>     };
>     
>     analyzer->makeResults(60, 200, 0, 0, false, false, false, false, false); // min of 60 and max of 200 for best results
>     NSLog(@"Bpm is %f, average loudness is %f db, peak volume is %f db.", analyzer->bpm, analyzer-loudpartsAverageDb, analyzer->peakDb);
> 
>     bpm_ = analyzer->bpm;
>     
>     // Cleanup.
>     delete decoder;
>     delete analyzer;
>     free(intBuffer);
>     free(floatBuffer);
>     
> }

Any insights would be greatly appreciated. Thank-you

**Comment by gaborszanto** [comment]
There were no changes to that function for years now. What's the actual crash log?

**Comment by JasonAnytune** [comment]
Thanks, that was my assumption. I am investigating and will update you with results.

**Comment by JasonAnytune** [comment]
I sent an email with an attached application that demonstrates the ShortIntToFloat crash

**Comment by gaborszanto** [comment]
Issue has been resolved on Zendesk.
