### ISSUE TITLE
MPMediaPicker mostly useless with apple music?

### ISSUE THREAD

**Issue by mlostekk** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#655]
Am i right the most of the songs that you get via the MPMediaPickerController are not working, because they are either cloud songs or DRM assets? And both of which are not supported by superpowered?

**Comment by gaborszanto** [comment]
Not just with Superpowered. Any app or framework. Third parties can't "pull" any music from Apple Music, just the tracks owned by the user (such as purchased).

**Comment by mlostekk** [comment]
Okay, so only way is to use AVFoundation.. Thats too bad.

**Comment by gaborszanto** [comment]
Not really. You'll not receive access to the audio data with any API. 

You can only use the built-in player to play those tracks (using AVSomething, yes.)
