### ISSUE TITLE
How to get Pitch of Voice While Recording 

### ISSUE THREAD

**Issue by rajaroni** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#656]
is there any way to get pitch i am using BandPassFilter But unable to get accurate frequency and there is no snippet available how to get accurate pitch of user input.

**Comment by gaborszanto** [comment]
Maybe you can use the FrequencyDomain class to get a near frequency reading. You can tune accuracy for your needs by setting the log size of the internal FFT.
