### ISSUE TITLE
How to disable output using some other approach rather than in initialisation of SuperpoweredAndroidAudioIO

### ISSUE THREAD

**Issue by syedateeb1** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#657]
I can enable output when i initialize SuperpoweredAndroidAudioIO by setting the enableoutput to true.
```
audioIO = new SuperpoweredAndroidAudioIO (
            samplerate,                     // sampling rate
            buffersize,                     // buffer size
            true,                           // enableInput
            true,                           // enableOutput
            audioProcessing,                // process callback function
            NULL,                           // clientData
            -1,                             // inputStreamType (-1 = default)
            -1                              // outputStreamType (-1 = default)
    );
```
What if at some point during recording i want to disable the output. How can i do that?

**Comment by gaborszanto** [comment]
In that specific case just memset the contents of the audio output buffer to zero.

**Comment by rajaroni** [comment]
static bool audioProcessing (
        void * __unused clientdata, // custom pointer
        short int *audio,           // output buffer
        int numberOfFrames,         // number of frames to process
        int samplerate              // current sample rate in Hz
) {
    compressor->samplerate = (unsigned int)samplerate;
    reverb->samplerate = (unsigned int)samplerate;
    limiter->samplerate = (unsigned int)samplerate;
    echo->samplerate = (unsigned int)samplerate;
    float floatBuffer[numberOfFrames * 2];
    memset(audio,0, sizeof(audio));
    Superpowered::ShortIntToFloat(audio, floatBuffer, (unsigned int)numberOfFrames);

    compressor->process(floatBuffer, floatBuffer, (unsigned int)numberOfFrames);
    reverb->process(floatBuffer, floatBuffer, (unsigned int)numberOfFrames);
    limiter->process(floatBuffer, floatBuffer, (unsigned int)numberOfFrames);
    echo->process(floatBuffer, floatBuffer, (unsigned int)numberOfFrames);
  //  Superpowered::VolumeAdd(floatBuffer,floatBuffer,1.0f,1.0f,(unsigned int) numberOfFrames);

     Superpowered::FloatToShortInt(floatBuffer, audio, (unsigned int)numberOfFrames);

    return true;
}

I did memset audio to 0 but still hearing my feedback
