### ISSUE TITLE
Pop/Click in beginning of recording using SuperpoweredRecorder (Android)

### ISSUE THREAD

**Issue by tinder-brunokongawi** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#658]
I have built the Android example `SuperpoweredRecorder` which records a Wav file. However, I am hearing clicks/pops right at the beginning of the sound (always). I know the applied fade should mitigate that a bit, but it doesn't seem to get rid of it entirely. What is the best practice/approach to remove the clicks/pops? Should it be done on the fly/real-time or post recording? Thank you.

**Comment by gaborszanto** [comment]
There should be no clicks/pops at the beginning. Did you experience this with an unmodified, original version of the recorder example project? If yes, can you show a recording?

**Comment by tinder-brunokongawi** [comment]
Yes. I first built my own project using the example (`SuperpoweredRecorder`) as basis, but came back to the example here to verify it was also happening. Find an example below (recorded using `SuperpoweredRecorder` example on a Pixel 3a). Note also that the click is also happening at the end.

https://drive.google.com/file/d/1xmqwgRhh8IFZOTzvz7k_3KbpW6nymCtl/view?usp=sharing

**Comment by gaborszanto** [comment]
That's very weird, never saw anything like that. Is this with the latest version of Superpowered, 2.0.9?

**Comment by tinder-brunokongawi** [comment]
Yes. I did a pull before building.

**Comment by tinder-brunokongawi** [comment]
Any update/insight on this? Are you able to reproduce this at all?

**Comment by gaborszanto** [comment]
Not able to reproduce this with our devices, however we don't have a Pixel 3a. Can you reproduce this on other devices if you have some?

**Comment by gaborszanto** [comment]
Not able to reproduce this with our devices, however we don't have a Pixel 3a. Can you reproduce this on other devices if you have some?

**Comment by tinder-brunokongawi** [comment]
Sorry for the delay. Yes, I am able to reproduce this on the Pixel 2 as well. Example below. 
https://drive.google.com/file/d/19gXP-lV7Oo_h8GU8tw7V1L6jYaraNT4O/view?usp=sharing

**Comment by gaborszanto** [comment]
Can you please update to 2.1.0 (the latest version) and check if still does this? We made some changes that may resolve it.

**Comment by gaborszanto** [comment]
Can you please update to 2.1.1 (the latest version) and check if still does this? We made some changes that may resolve it.

**Comment by EtherBit** [comment]
Yes, using the latest sample `SuperpoweredRecorder`, I still get the clicks. It seems to be happening to Pixel devices only. (hear recording example below).
https://drive.google.com/file/d/1dEFCQh0hETmIlRa70KKANkxnTSXKssoI/view?usp=sharing

**Comment by gaborszanto** [comment]
Please check the updated SDK (version 2.2.0).

**Comment by gaborszanto** [comment]
Please check the updated SDK (version 2.2.0). Still having this issue?

**Comment by tinder-brunokongawi** [comment]
Still happening. Tested on Pixel 3a

**Comment by gaborszanto** [comment]
Some Android devices have strange audio I/O bugs, this one looks one of them. I'm afraid we can't come up with a good solution for this, Android just sucks for audio overall.
