### ISSUE TITLE
Audio effect on monitor mic input

### ISSUE THREAD

**Issue by nilamvaddoriya-simformsolutions** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#660]
Hello Team,
I am using a superpowered recorder for recording audio, I have to monitor mic input while using headphones which is done by enabling input in the constructor of SuperpoweredAndroidAudioIO, Now I want to apply audio effects also on the monitor mic input, Can you guys please guide me how can I apply audio effects on the monitored mic input.

`audioSystem = new SuperpoweredAndroidAudioIO(
    samplerate, buffersize, true, true, audioProcessing, this, -1, SL_ANDROID_STREAM_MEDIA, buffersize * 2);`

Thank you.

**Comment by gaborszanto** [comment]
Please check out the SuperpoweredEffect example project.
