### ISSUE TITLE
Edit Track is not working

### ISSUE THREAD

**Issue by bhoomi-simformsolutions** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#661]
Hii,
I am using a superpowered recorder for recording, I am getting an issue while editing track. I am following the below steps:
Recording a track, Adding another track, After adding another track I am re-recording on first track again, So expected result should mix of the old one and new one but I am getting an only new recording in the result. I am resetting the recorder after adding every track, Can you guys please help me with this. Any help would be much appreciated. Is there any function available to overwrite the audio instead of mixing the audio?

Thank you.

**Comment by gaborszanto** [comment]
Sorry, but I don't understand your message. Which Superpowered APIs are you using and how?

**Comment by bhoomi-simformsolutions** [comment]
I am using Superpowered Android SDK, So If I re-record on an already recorded file then it is behaving as and new audio-only. Let's say I have recorded 10-secs audio. and then after I am editing 1-5 sec audio then the final result should be of 10 secs. but I am getting only 5 secs audio in a result, So every time the recorder considering it as a new recording, So Is there any way to re-record the audio.

**Comment by gaborszanto** [comment]
There is no such feature in the SDK as "re-recording an already recorded file". Please let me know exactly which Superpowered API calls are you using and how.

**Comment by bhoomi-simformsolutions** [comment]
I am using the Superpowered C++ Audio Library.

**Comment by gaborszanto** [comment]
Let me repeat: There is no such feature in the SDK as "re-recording an already recorded file". 

Which Superpowered API calls are you using from the Superpowered library? Which Superpowered API calls are doing the "re-recording"?

**Comment by bhoomi-simformsolutions** [comment]
Actually, We are managing multiple audio tracks which contain separate recording, Now we are going to implement edit track functionality, So we came across this query.

So as per our above conversation, I haven't got anything regarding "re-recording" from the SDK. I was just trying with the currently available operations like resetting the recorder, deinitializing the recorder but that is considering as a new recording only, So I have asked for a "re-recording" thing as I also haven't found that thing in the SDK.

**Comment by gaborszanto** [comment]
The Recorder class writes onto disk the audio data it receives through one of its record... methods.
You can pass any kind of audio data there. The Recorder will not perform any "mixing" on the audio data. You need to mix that data using other Superpowered features.

**Comment by bhoomi-simformsolutions** [comment]
Yes, We can mix but in that case, two audios will be mix and we have to overwrite not mix as we are editing the audio at a given interval of time.

**Comment by gaborszanto** [comment]
You don't need to overwrite anything. You can do anything with the data in your buffers, such as copy them.
