### ISSUE TITLE
Memory Crash with Superpowered Analyzer

### ISSUE THREAD

**Issue by JasonAnytune** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#662]
With version SP 2.0.9 multiple analysis of certain audio files cause a crash / memory leak

We have included a sample project here:
https://drive.google.com/file/d/1Cl4U_LM6L_o3LtCkAD214cSfmyF941vG/view?usp=sharing

Usually when running this test application the first couple files analyze then eventually an audio file crashes on analysis.
These audio files have a low sample rate / bit rates. This may or may not be related to this issue.

We found that doubling the buffer padding fixes the problem, however this is not a great solution and believe that there is something more serious taking place:

```
 // Create a buffer for the 16-bit integer audio output of the decoder.
    short int *intBuffer = (short int *)malloc(decoder->getFramesPerChunk() * 2 * sizeof(short int) + 16384);
    // Create a buffer for the 32-bit floating point audio required by the effect.
    float *floatBuffer = (float *)malloc(decoder->getFramesPerChunk() * 2 * sizeof(float) + 16384);
    
//--> becomes
    
    /*  Temporary Solution */
    /*// Create a buffer for the 16-bit integer audio output of the decoder.
    short int *intBuffer = (short int *)malloc(decoder->getFramesPerChunk() * 2 * sizeof(short int) + (16384*2));
    // Create a buffer for the 32-bit floating point audio required by the effect.
    float *floatBuffer = (float *)malloc(decoder->getFramesPerChunk() * 2 * sizeof(float) + (16384*2));*/
```

Error Logs:

```
SuperpoweredOfflineProcessingExampleMacOS(10146,0x1001d2dc0) malloc: Incorrect checksum for freed object 0x10282d810: probably modified after being freed.
Corrupt value: 0x396001c0ba100120
SuperpoweredOfflineProcessingExampleMacOS(10146,0x1001d2dc0) malloc: *** set a breakpoint in malloc_error_break to debug
SuperpoweredOfflineProcessingExampleMacOS(10146,0x1001d2dc0) malloc: Incorrect checksum for freed object 0x10282d810: probably modified after being freed.
```

MacOS Catalina 10.15.7

**Comment by gaborszanto** [comment]
The error log says that calling free() on something crashes. At which line does your code crash?

**Comment by JasonAnytune** [comment]
Hey Gabor,
Thanks for looking into this. It crashes on this line.

*int* framesDecoded = decoder->decodeAudio(intBuffer, decoder->
getFramesPerChunk());

The crash is very reproducible on a Mac please run the provided test
application.
Jason

**Comment by gaborszanto** [comment]
The problem was: Apple changed its decoder behavior. 

Explanation: the files you loaded are unsupported by Superpowered. As a last resort, it turns to Apple's decoders in this case (on Apple platforms). It seems like that Apple changed the decoders, so now they return with a different, much larger frames vs detected/requested.

The next Superpowered update will have a fix for this.

**Comment by JasonAnytune** [comment]
Thanks Gabor.

When can we expect the next release? Is doubling the buffer padding a good
temporary solution?

**Comment by gaborszanto** [comment]
Hopefully in December. Yes, the padding is a good solution meanwhile.
