### ISSUE TITLE
Samsung devices (Android 10) with SampleRate 48000 crash while Recording audio

### ISSUE THREAD

**Issue by drusak** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#664]
We see crashes on some Samsung devices with Android 10 when trying to create AudioIO for playback and record.

**SIGSEGV 0x0000000000000000**
```
SuperpoweredAndroidAudioIO.cpp - Line 528
SuperpoweredAndroidAudioIO::SuperpoweredAndroidAudioIO(int, int, bool, bool, bool (*)(void*, short*, int, int), void*, int, int) + 528
```

these lines are here in code SuperpoweredAndroidAudioIO
```
if (enableOutput) { // Initialize the audio output buffer queue.
            memset(internals->outputFifo.buffer, 0, internals->fifoBufferSizeBytes);
            (*internals->outputBufferQueue)->GetInterface(internals->outputBufferQueue, SL_IID_BUFFERQUEUE, &internals->outputBufferQueueInterface);
            (*internals->outputBufferQueueInterface)->RegisterCallback(internals->outputBufferQueueInterface, SuperpoweredAndroidAudioIO_OutputCallback, internals);
            (*internals->outputBufferQueueInterface)->Enqueue(internals->outputBufferQueueInterface, internals->outputFifo.buffer, (SLuint32)buffersize * NUM_CHANNELS * 2);
        };
```

No other devices crashes with such error. So it happens only on Samsung with such configuration.
Observations:
All these devices have sample rate = 48000 and buffer size = 192, returned from 
```
audioManager.getProperty(AudioManager.PROPERTY_OUTPUT_SAMPLE_RATE);
audioManager.getProperty(AudioManager.PROPERTY_OUTPUT_FRAMES_PER_BUFFER);
```

If init for playback only then it works fine.

I have a list of models: sm-a217f, sm-a207f, sm-a207m, sm-a205u and currently this list is growing

I asked one user to change the sample rate to 44100 and buffer size to 2 * 192, seems helped, but didn't get final confirmation from user.

version of Superpowered is 2.0.7

Did you face with such an issue? What can be done here?

**Comment by drusak** [comment]
Just checked previous releases and seems that problem did exist early (Superpowered 1.4)

**Comment by gaborszanto** [comment]
Samsung products tend to break native audio functionality from time to time. Which line crashes inside that block?

**Comment by drusak** [comment]
From Crashlytics:
`(*internals->outputBufferQueueInterface)->RegisterCallback(internals->outputBufferQueueInterface, SuperpoweredAndroidAudioIO_OutputCallback, internals);`

**Comment by gaborszanto** [comment]
Please modify the code and check before that line if internals->outputBufferQueueInterface is NULL. Is it NULL?

**Comment by drusak** [comment]
Unfortunately, this crash is on production only, We cannot reproduce it here. 
And it is about 30 crashes per day in Crashlytics.

**Comment by gaborszanto** [comment]
I close this issue now since it's a bug in Samsung's audio stack, which happens way too often unfortunately and we can't do anything about it.
