### ISSUE TITLE
Low volume on Android (Samsung Note 5, Nokia 6)

### ISSUE THREAD

**Issue by vietnghi** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#665]
I'm using Superpowered 2.0.9. When I run PlayerExample on Android (Galaxy Note5, Nokia 6), I saw that the volume is lower than ExoPlayer (4x). Do you have any suggestion for us to investigate and solve the problem

**Comment by gaborszanto** [comment]
How much lower is the volume?

**Comment by vietnghi** [comment]
If the volume control (on Android OS) is max, Superpowered is a little bit louder than ExoPlayer, when the volume control is 50%, the volume on Superpowered lower than Exoplayer about 4x.

**Comment by gaborszanto** [comment]
Then ExoPlayer adjusts the volume curve somehow, maybe it even has a limiter included. The PlayerExample doesn't adjust volume at all.
