### ISSUE TITLE
BigSur Silicon Universal Build Failure - Undefined symbols for architecture arm64

### ISSUE THREAD

**Issue by JasonAnytune** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#666]
Cannot compile MacOs Example Project and other Mac projects on BigSur for Apple Silicon with Xcode 12.3.

See the provided video:
https://drive.google.com/file/d/1XagOyY0sWyTo4RTFXgpPtjFu4TZG228e/view?usp=sharing

Errors are as follows:

```
Undefined symbols for architecture arm64:
  "formantCorrector::adjust(int, float)", referenced from:
      Superpowered::setRateAndPitchShiftCentsAndFormantCorrection(Superpowered::TimeStretching*, Superpowered::stretchInternals*) in libSuperpoweredAudioOSX.a(SuperpoweredTimeStretching.o)
  "formantCorrector::correct(float*, float*)", referenced from:
      Superpowered::TimeStretching::advancedProcess(Superpowered::AudiopointerlistElement*) in libSuperpoweredAudioOSX.a(SuperpoweredTimeStretching.o)
  "formantCorrector::formantCorrector(int)", referenced from:
      Superpowered::TimeStretching::TimeStretching(unsigned int, float) in libSuperpoweredAudioOSX.a(SuperpoweredTimeStretching.o)
  "formantCorrector::~formantCorrector()", referenced from:
      Superpowered::TimeStretching::~TimeStretching() in libSuperpoweredAudioOSX.a(SuperpoweredTimeStretching.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

```
Undefined symbol: formantCorrector::adjust(int, float)

Undefined symbol: formantCorrector::correct(float*, float*)

Undefined symbol: formantCorrector::formantCorrector(int)

Undefined symbol: formantCorrector::~formantCorrector()
```

Superpowered version 2.1.0

**Comment by gaborszanto** [comment]
Hi, we'll fix this soon.

**Comment by gaborszanto** [comment]
I just checked libSuperpoweredAudioIOS.a using "nm" and those symbols are included. Are you sure you're building against the latest version of Superpowered?

**Comment by JasonAnytune** [comment]
The issue is not with libSuperpoweredAudioIOS.a, it is with libSuperpoweredAudioOSX.a. libSuperpoweredAudioIOS.a is not relevant to this issue. I am using the most recent superpowered, version 2.1.0. The errors I am seeing are the same as the errors within your example project (SuperpoweredSpatializer->ambi->ambi.xcodeproj). The issue exists building on BigSur and Catalina with XCode 12.3. See the video I have provided if there is still confusion in regards to this issue. 

Additionally, I'm seeing the same thing, it also happens for the Examples_iOS/SuperpoweredCrossExample which uses the libSuperpoweredAudioIOS.a

**Comment by senoalvrtsyan** [comment]
@gaborszanto I'm getting `Undefined symbols for architecture x86_64:` while using `libSuperpoweredAudioOSX.a` to build my project in MacOS Catalina. Any ideas how can I fix this issue ?

**Comment by wacheski** [comment]
@gaborszanto. Have you reproduced Jason's compile issue?  Do you need anything else from us?

**Comment by gaborszanto** [comment]
Yes, Tony. Because of your strong push right before Christmas, we released a weakly tested version Superpowered with Apple Silicon and now we got this issue. We learned from that mistake, we'll not rush with any release anymore. Please be patient, we want to do this "properly" now.

**Comment by wacheski** [comment]
Thank you Gabor.   The introduction of Apple Silicon is unique and covering all configurations is a challenge.  We can test the libs before the official release. Take advantage of your extended team. We are happy to help. Your success is our success. :)

**Comment by gaborszanto** [comment]
Just pushed an update, please check.

**Comment by wacheski** [comment]
Thanks Gabor!   Will do.

**Comment by JasonAnytune** [comment]
Thanks Gabor! I was able to compile a BigSur universal build of our application with your update. We are working through issues with other libs, but will let you know if we find any other SuperPowered related issues.
