### ISSUE TITLE
playSynchronizedToPosition not working after update from 2.0.4 to 2.1.0

### ISSUE THREAD

**Issue by renezuidhof** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#667]
After updating Superpowered from 2.0.4 to 2.1.0 the playSynchronizedToPosition function does not work as I expected.

I'm syncing like this. Setting `currentSyncPositionInMilliseconds` to some value when I want to start the audioPlayer.
```
void AudioTrack::process(float *floatBuffer, unsigned int numberOfFrames, bool mix) {
    if (currentSyncPositionInMilliseconds >= 0) {
        if (audioPlayer.isPlaying()) {
           __android_log_print(ANDROID_LOG_DEBUG, "AudioTrack", "Synced. audioPlayer.positionMs: %f", audioPlayer.getPositionMs());

            currentSyncPositionInMilliseconds = -1;
        } else {
            audioPlayer.playSynchronizedToPosition(currentSyncPositionInMilliseconds);

            currentSyncPositionInMilliseconds += framesToMilliseconds(numberOfFrames);
        }
    }

   // Other stuff
}
```

On 2.0.4 the `android_log_print` would print the correct position. After updating to 2.1.0 the printed value is always 0.0f.

**Comment by gaborszanto** [comment]
Your code prints only once, because sets "currentSyncPositionInMilliseconds" to -1 after the first log output. However "playSynchronizedToPosition" may not start playback immediately. Did you try continously logging? Does it start playing?

**Comment by renezuidhof** [comment]
Just did some other tests. The audioplayer does start at the correct position. It's `isPlaying` or `getPositionMs` that is not updated the same between `2.0.4` and `2.1.0`.

I've got a piece of code that waits for `audioPlayer.isPlaying` to be true before it updates a progressbar. With `2.0.4` this worked fine, as `audioPlayer.getPositionMs` gave the correct position once `audioPlayer.isPlaying` is true. With `2.1.0` this is not the case, it always returns `0` directly after `isPlaying` is set to true. This causes my progressbar to always start at the start.

PS. Also `audioPlayer.getDisplayPositionMs()` gives me 0 when requested directly after `isPlaying` is set to true.

**Comment by renezuidhof** [comment]
Not sure if you're interested, but here is my sync-call:
void AudioTrack::sync() {
    audioPlayer.pause();

    currentSyncPositionInMilliseconds = <some position in milliseconds>;
}

**Comment by gaborszanto** [comment]
Yes, please expect this the behaviour now. isPlaying() will return false and the position will not be updated until this function succeeds starting playback at the specified position.

**Comment by gaborszanto** [comment]
You can use the getWaitingForSyncStartMs() function to query how long the player is waiting to start playback on the synchronization event. I will rename this method to getMsUntilSynchronizedPlaybackStarts() in the next update for clarity. This value is continuously updated.

**Comment by gaborszanto** [comment]
Actually, no, it will be named getMsRemainingToSyncEvent().

**Comment by renezuidhof** [comment]
It works, thanks!

**Comment by renezuidhof** [comment]
After checking a bit more it actually doesn't seem to work. It just always prints `0.000000` for `getWaitingForSyncStartMs()`. With the tests I did a few days ago the UI was probably slow, requesting only after the audioPlayer was already playing.

The audio starts playing at the correct position. I just don't have a way of knowing when the audioPlayer is synced to get a correct value from `audioPlayer.getPositionMs()`.

Not sure if it matters, but `syncMode` is `SyncMode_None`.

```
void AudioTrack::process(float *floatBuffer, unsigned int numberOfFrames, bool mix) {
    if (currentSyncPositionInMilliseconds >= 0) {
        __android_log_print(ANDROID_LOG_DEBUG, "AudioTrack", "Synced. currentSyncPositionInMilliseconds: %d. getWaitingForSyncStartMs: %f", currentSyncPositionInMilliseconds, audioPlayer.getWaitingForSyncStartMs());
        if (!getIsSearching()) {
            currentSyncPositionInMilliseconds = -1;
        } else {
            audioPlayer.playSynchronizedToPosition(currentSyncPositionInMilliseconds);

            currentSyncPositionInMilliseconds += framesToMilliseconds(numberOfFrames);
        }
    }

    // Other stuff
}

void AudioTrack::syncWithLoopTimer() {
    audioPlayer.pause();

    currentSyncPositionInMilliseconds = <target position in ms>;
}

bool AudioTrack::getIsSearching() {
    return audioPlayer.getWaitingForSyncStartMs() > 0;
}
```
