### ISSUE TITLE
SIGABRT on initialization with 2.1.0 on Android

### ISSUE THREAD

**Issue by jklein24** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#668]
After upgrading to superpowered 2.1.0 with no other changes to our app, I'm hitting a crash right after initialization. The crash seems to be happening on a network thread. Here's the stack trace:

```
abort 0x0000007262a152cc
lshift(void*, Superpowered::httpRequest*, Superpowered::httpResponse*) 0x0000006f5e0500b8
Superpowered::httpRequest::sendBlocking(bool (*)(void*, Superpowered::httpRequest*, Superpowered::httpResponse*), void*, char const*, bool, void (*)(void*, char const*)) 0x0000006f5e05da08
Superpowered::httpRequestThread(void*) 0x0000006f5e05e688
__pthread_start(void*) 0x0000007262a76d50
__start_thread 0x0000007262a1728c
```

Let me know if there's any more useful debug info I can try to capture here.

**Comment by jklein24** [comment]
Ah, now that I'm looking closer, is this just what happens since our license is expired if we try to update the SDK @gaborszanto? That makes sense.. Feel free to close this out if that's the case. We can discuss extending the license to test formant correction over a zendesk request.

**Comment by EtherBit** [comment]
I am having the same issue. @jklein24 were you able to confirm it was due to expired license?

**Comment by jklein24** [comment]
No confirmation yet, but that does seem likely :-/. Are you also using the "ExampleLicenseKey-WillExpire-OnNextUpdate" key? I realized it was likely the reason when I read the text of that sample license haha.

**Comment by EtherBit** [comment]
@jklein24 yes, I am. Indeed, that seems to be the culprit.

**Comment by gaborszanto** [comment]
Yes, this is a licensing issue.
