### ISSUE TITLE
SuperpoweredAndroidAudioIO with USB input

### ISSUE THREAD

**Issue by qunten** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#669]
I have an usb input device which card number is [-D 1 -d 0], plugged on the tv box, how could I use SuperpoweredAndroidAudioIO to make a sound loopback with the usb microphone?

**Comment by gaborszanto** [comment]
If your Android device works properly with that USB input device, then all you need is opening an audio I/O using SuperpoweredAndroidAudioIO and don't do anything in the audio processing callback. The input and output buffer is the same, so if you don't change it, input will be routed to the output.
