### ISSUE TITLE
Is it possible to handle audio output(|feedback) volumn?

### ISSUE THREAD

**Issue by rajaroni** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#670]
I want to increase the output volumn . I have used this line to increase the volumn. It does increase the output feedback but also effects the input buffer too and also increases the noise.
```
Superpowered::VolumeAdd(floatBuffer, floatBuffer, 0.5f, 0.5f, (unsigned int) numberOfFrames);
```

**Comment by gaborszanto** [comment]
It doesn't affect the "input buffer". It affects the contents of "floatBuffer", whatever content that buffer has. However, 0.5f will not increase anything, but multiply by half, meaning decreasing the values in "floatBuffer".
