### ISSUE TITLE
Cannot build for Simulator on M1 Macbook

### ISSUE THREAD

**Issue by akivab** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#671]
Seeing the following error on a new Macbook M1, wondering what the recommended solution is?

ld: in /PROJECT_DIR/Superpowered/libSuperpoweredAudioIOS.a(SuperpoweredHome.o), building for iOS Simulator, but linking in object file built for iOS, for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by rajendersha** [comment]
Same error on xcode 12

**Comment by simba909** [comment]
@akivab did you ever find a solution that worked for you?
