### ISSUE TITLE
How to initialize SuperpoweredIOSAudioIO object in cpp file?

### ISSUE THREAD

**Issue by IHNEL** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#673]
Hi
I'm trying to integrate Superpowered into my iOS app without writing code in the ViewController like your examples. There is a C++ class in my iOS project which is entry point for Superpowered stuffs. It seems I couldn't import `#include "Superpowered/SuperpoweredIOSAudioIO.h"` in this C++ class, the compiler throws "Unknown type name 'NSString'". 

Is there other way to initialize SuperPowered objects and use it in C++ code instead of Objective-C? 
My purpose is writing the core features in  C++ code, which can be used on any platforms including Android, iOS, Windows, ...

**Comment by gaborszanto** [comment]
Hi,

you can't use that class in a cpp file. Rename your cpp file to an .mm file, which means "Objective-C++". You can use both in that context.
