### ISSUE TITLE
playSynchronizedToPosition not working after update from 2.0.4 to 2.1.0

### ISSUE THREAD

**Issue by renezuidhof** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#674]
Reopening this one: https://github.com/superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform/issues/667

After checking a bit more it actually doesn't seem to work. It just always prints 0.000000 for getPositionMs() once getWaitingForSyncStartMs() == 0.

The audio starts playing at the correct position. I just don't have a way of knowing when the audioPlayer is synced to get a correct value from getPositionMs().

Not sure if it matters, but syncMode is SyncMode_None.

```
void AudioTrack::process(float *floatBuffer, unsigned int numberOfFrames, bool mix) {
    if (currentSyncPositionInMilliseconds >= 0) {
        __android_log_print(ANDROID_LOG_DEBUG, "AudioTrack", "Syncing... currentSyncPositionInMilliseconds: %d. getWaitingForSyncStartMs: %f", currentSyncPositionInMilliseconds, audioPlayer.getWaitingForSyncStartMs());
        if (!getIsSearching()) {
            currentSyncPositionInMilliseconds = -1;
        } else {
            audioPlayer.playSynchronizedToPosition(currentSyncPositionInMilliseconds);

            currentSyncPositionInMilliseconds += framesToMilliseconds(numberOfFrames);
        }
    }

    // Other stuff
}

void AudioTrack::syncWithLoopTimer() {
    audioPlayer.pause();

    currentSyncPositionInMilliseconds = <target position in ms>;
}

bool AudioTrack::getIsSearching() {
    return audioPlayer.getWaitingForSyncStartMs() > 0;
}
```

**Comment by gaborszanto** [comment]
Yes, syncmode_none matters. Any feature that has "sync" requires a sync mode.

**Comment by renezuidhof** [comment]
Since I'm not syncing to a tempo or bpm I am unsure what syncmode to use (Tempo or TempoAndBeat). I just want the player to start at a specific/precise point. This was working fine in `2.0.4` without setting `syncmode`.

If I would set the syncmode to `SyncMode_Tempo` I am assuming I need to set `originalBPM`? I prefer the old way so I don't have to worry about the bpm.

**Comment by gaborszanto** [comment]
You need TempoAndBeat.

**Comment by renezuidhof** [comment]
Thanks for letting me know about the syncmode. Anything else I can have a look at? Since it's not working for me atm.

**Comment by gaborszanto** [comment]
After playback starts getPositionMs returns with 0 still?

**Comment by renezuidhof** [comment]
I added a bit more logging. I'm not using `getWaitingForSyncStartMs` as it was not working for me (probably because not using a syncmode?)

```
void AudioTrack::process(float *floatBuffer, unsigned int numberOfFrames, bool mix) {
    if (currentSyncPositionInMilliseconds >= 0) {
        __android_log_print(ANDROID_LOG_DEBUG, "AudioTrack", "Synced. currentSyncPositionInMilliseconds: %d. getMsRemainingToSyncEvent: %f. audioPlayer.getPositionMs: %f, PlaybackRate: %f", currentSyncPositionInMilliseconds, audioPlayer.getWaitingForSyncStartMs(), audioPlayer.getPositionMs(), audioPlayer.playbackRate);
        if (!getIsSearching()) {
            currentSyncPositionInMilliseconds = -1;
        } else {
            audioPlayer.playSynchronizedToPosition(currentSyncPositionInMilliseconds);

            currentSyncPositionInMilliseconds += framesToMilliseconds(numberOfFrames);
        }
    }

    __android_log_print(ANDROID_LOG_DEBUG, "AudioTrack", "Synced. audioPlayer.getPositionMs: %f", audioPlayer.getPositionMs());
}

bool AudioTrack::getIsSearching() {
    return !audioPlayer.isPlaying() && currentSyncPositionInMilliseconds >= 0;
}
```

Results in:

```
AudioTrack: Synced. currentSyncPositionInMilliseconds: 455. getMsRemainingToSyncEvent: 0.000000. audioPlayer.getPositionMs: 0.000000, PlaybackRate: 0.488076
AudioTrack: Synced. audioPlayer.getPositionMs: 0.000000
AudioTrack: Synced. audioPlayer.getPositionMs: 19.387755
AudioTrack: Synced. audioPlayer.getPositionMs: 30.907029
AudioTrack: Synced. audioPlayer.getPositionMs: 457.278912
AudioTrack: Synced. audioPlayer.getPositionMs: 468.095238
```

As you can see `getPositionMs` only returns a correct value after 3 'process-calls'. In the example above the playbackrate was quite low (< 0.6), I noticed it takes a bit more time in those cases. When `playbackrate = 1` it only takes 1 'process-call' in most cases.

I expect `getPositionMs` to return with a correct value right after `getIsSearching` return `false`.

**Comment by gaborszanto** [comment]
Since the player is "opening", I don't expect getPositionMs returning anything useful until it's not opened?

**Comment by renezuidhof** [comment]
The code will keep 'syncing' with `currentSyncPositionInMilliseconds` until the player starts playing.
This behaviour also happens when syncing with an already playing audioplayer. It will be paused though (see the `syncWithLoopTimer` function)

As mentioned before this did work on 2.0.4. So I something must have changed here.

**Comment by gaborszanto** [comment]
Please check the updated SDK (version 2.2.0), I wonder if the behavior is different?

**Comment by renezuidhof** [comment]
Since I'm having an issue opening audioplayers (https://github.com/superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform/issues/677) I can't test this.

**Comment by gaborszanto** [comment]
I guess you can test this now?

**Comment by renezuidhof** [comment]
Yes, I'll give an update once my code is fixed for the other issue.

**Comment by renezuidhof** [comment]
So far it seems to work as expected. It might be because I was not running `process` before I got an `OPENED` back from `getLatestEvent`. I'll close it for now. Thanks for the help!
