### ISSUE TITLE
Android quite Recording on some devices

### ISSUE THREAD

**Issue by drusak** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#675]
Observed the following issue on my Samsung A10 (also got many comments in production on other devices)

While recording with Superpowered SDK (version 2.0.7) the voice is very quite (FFmpeg shows max loudness **-36db**). The app using system sampleRate and bufferSize (48000 and 192).
If I change sampleRate from 48000 to 44100 - it becomes few times louder (FFmpeg shows max loudness **-6db**)

Is there anything we can do here?

**Comment by gaborszanto** [comment]
Samsung devices are very often shipped with broken system audio layers, see: https://github.com/superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform/issues/620

There is nothing you or we can do unfortunately.

**Comment by drusak** [comment]
Thanks!

Should We record with 44100 sample rate for all Samsung devices (and e.g. doubled buffer size)? Seems 44100 is support by all Android devices

**Comment by drusak** [comment]
Just wondering, is there any workaround for such cases (Samsung devices have major segment in the world, so We need to make it as better as We can even with such limitations). Also We observed such problems on some other devices.

Probably We can change sample rate (e.g. to 44100) or\and buffer size (2x or 3x times from system's value), or probably try mono/stereo? Is there anything in Superpowered SDK that can help with it?

Thanks in advance.

**Comment by romanbsd** [comment]
You can try working with OpenSLES instead of AAudio on Samsung devices. We found AAudio to be buggy on some models.

**Comment by drusak** [comment]
Thanks, @romanbsd 
But as far as I know Superpowered SDK is not using AAudio.

**Comment by romanbsd** [comment]
https://github.com/superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform/blob/master/Superpowered/OpenSource/SuperpoweredAndroidAudioIO.cpp#L427

You can use superpowered with oboe instead of SuperpoweredAndroidAudioIO.cpp btw.

**Comment by gaborszanto** [comment]
I need to close this issue, since it's an issue with Android, not Superpowered.
