### ISSUE TITLE
AdvancedAudioPlayer.open issue on 2.1.1 (Android)

### ISSUE THREAD

**Issue by renezuidhof** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#677]
I'm getting an issue where opening an AdvancedAudioPlayer does not work anymore after changing from 2.1.0 to 2.1.1. In the example below (it's not all code but I hope it's clear) `Superpowered::PlayerEvent_Opened` is never reached.

I did not change any code between switching from 2.1.0 to 2.1.1.

Kotlin
```
val apkPath = context.packageResourcePath
val beatAudioFileDescriptor = context.resources.openRawResourceFd(R.raw.some_wav)

initializeCpp(
         apkPath,
         beatAudioFileDescriptor.startOffset.toInt(),
         beatAudioFileDescriptor.length.toInt()
)

beatAudioFileDescriptor.parcelFileDescriptor.close()
```

The values from `initializeCpp` are passed to the `PlayOnceAudioSample` class. I left out the middle code since I don't think its important.

c++
```
PlayOnceAudioSample(int sampleRate1,
                        const char *apkPath,
                        int audioFileOffset,
                        int audioFileLength) {
        PlayOnceAudioSample *thisPtr = this;

        audioPlayer = new Superpowered::AdvancedAudioPlayer ((unsigned int) sampleRate1, 0);

        audioPlayer->open(apkPath, audioFileOffset, audioFileLength);
}

// This is called periodically
bool checkOpen() {
        bool isOpened = false;

        switch (audioPlayer->getLatestEvent()) {
            case Superpowered::PlayerEvent_Opened: {
                isOpened = true;

                break;
            }
            default: {}
        }

        return isOpened;
    }
```

**Comment by gaborszanto** [comment]
I see you're handling the _Opened event only. Do you receive an error event? Do you call audioPlayer->process() every time, regardless of the playback status?

**Comment by renezuidhof** [comment]
Good point. Changed the code to

```
bool checkOpen() {
        auto event = audioPlayer->getLatestEvent();

        __android_log_print(ANDROID_LOG_DEBUG, "PlayOnceAudioSample", "event: %d", event);

        switch (event) {
            case Superpowered::PlayerEvent_Opened: {
                isOpened = true;

                break;
            }
            case Superpowered::PlayerEvent_OpenFailed: {
                isOpened = false;

                __android_log_print(ANDROID_LOG_DEBUG, "PlayOnceAudioSample", "audioPlayer->getOpenErrorCode(): %d", audioPlayer->getOpenErrorCode());


                break;
            }

            default: {}
        }

        return isOpened;
    }
```

The `PlayerEvent_OpenFailed` is not hit. I only get `PlayerEvent_Opening` once, afterwards just a bunch of `PlayerEvent_None`'s

I'm waiting for the `checkOpen` to return `true`. Therefor my app keeps hanging so I never get to the point to call `process`

**Comment by romanbsd** [comment]
I tried updating our superpowered from 2.0.4 to 2.1.1 and player stopped working, so I rolled back. Hadn't had time to look into it. It can be due to the same issue as described here.

**Comment by gaborszanto** [comment]
Please check the updated SDK (version 2.2.0).

**Comment by renezuidhof** [comment]
Just tried it out with version 2.2.0 but I'm still having the same issue. I'm getting the `PlayerEvent_Opening` event and afterwards only `PlayerEvent_None` events.

**Comment by renezuidhof** [comment]
I'm also getting this issue when opening an audiofile by path of the wav file.

```
audioPlayer.open(audioFilePath);
```

**Comment by gaborszanto** [comment]
audioPlayer.open doesn't look like a valid Superpowered API?

**Comment by renezuidhof** [comment]
That's what I have been using so far.

When opening a wav file from storage
```
Superpowered::AdvancedAudioPlayer audioPlayer(samplerate, 0);
audioPlayer.open(audioFilePath);
```

When opening a wav file from apk
```
Superpowered::AdvancedAudioPlayer audioPlayer(sampleRate, 0);
audioPlayer->open(apkPath, audioFileOffset, audioFileLength);
```

**Comment by gaborszanto** [comment]
Still having this issue with Superpowered 2.2.0?

**Comment by renezuidhof** [comment]
Yes

**Comment by gaborszanto** [comment]
Do the cross example project work (loads file, plays it)?

**Comment by renezuidhof** [comment]
Hmm, the cross example on 2.2.0 works. I will spend some time checking what is different for me.

**Comment by renezuidhof** [comment]
So far I haven't found anything that could explain the behaviour. Do you have any ideas on where to look for?

**Comment by gaborszanto** [comment]
Looks like a file permissions issue. Please check if you can get a file handle on that path using the standard "fopen" API.

**Comment by renezuidhof** [comment]
Getting a file handle with `fopen` works. Also the `Superpowered::Decoder` works fine. I am able to retrieve the duration (`decored.getDurationFrames`) and read some audio with `decoder.decodeAudio` (I only tested if the call works, I didn't check the result).

Just the AdvancedAudioPlayer does not open it. When using Superpowered 2.0.4 I don't have the issue, so I would not expect it to be a permission issue.

**Comment by gaborszanto** [comment]
Example works, fopen works, Decoder works. Do you call audioPlayer->process() in an active audio I/O, regardless of the playback status?

**Comment by renezuidhof** [comment]
Ah that's it! I didn't, I wait for the `getLatestEvent` to return a success before processing.

I just did some tests and after calling `process` a `PlayerEvent_Opened` popped up.

Thanks for the help, I'll rearrange my code a bit.
