### ISSUE TITLE
AdvancedAudioPlayer playback done callback?

### ISSUE THREAD

**Issue by luanvotrongdev** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#678]
Hi! I want to know moment when playback is finished.
Is there any callback? or any suggestion on how to implement it?
Thank you.

**Comment by gaborszanto** [comment]
Hi, there is no such callback. But maybe you're looking for an end-of-file event? If yes, then you can poll the player->eofRecently() in the audio processing callback after player->process(), so you'll know immediately.
