### ISSUE TITLE
glibc/libm issue

### ISSUE THREAD

**Issue by AntoneB** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#679]
This is the result that I get when I try to compile using ./buildX86.sh

/usr/bin/ld: ../Superpowered/libSuperpoweredLinuxX86.a(playerprocess.o): undefined reference to symbol 'log10f@@GLIBC_2.2.5'
/usr/bin/ld: /lib/x86_64-linux-gnu/libm.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status

I'd really like to try out this superpowered's SDK Have been trying to change my version of GLIBC or LIBM with little success.
I'm using Focal Fasa LTS

**Comment by gaborszanto** [comment]
The error message is clear, a standard lib function (log10f) is not found. If you have that installed and the flag is in the build script, maybe there is a problem with the order? See this: https://stackoverflow.com/questions/19901934/libpthread-so-0-error-adding-symbols-dso-missing-from-command-line
