### ISSUE TITLE
[iOS] AudioProcessing still pause after IronSource ads displayed

### ISSUE THREAD

**Issue by luanvt-amanotes** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#680]
As title mentioned:

1. Play audio playing
2. call AdvancedAudioPlayer togglePlayback
3. display IronSource Ads
4. call AdvancedAudioPlayer togglePlayback
5. AudioProcessing doesnt called.

Thanks in advance.

**Comment by gaborszanto** [comment]
Looks like your audio I/O class gets paused. Which platform is this? iOS, Android, ... ?

**Comment by luanvt-amanotes** [comment]
Sorry for the lack of information, 
the bug happens on iOS.
I managed to overcome the problem by calling AudioOutputUnitStop before display ads.
But Im still not quite sure why it works.

**Comment by gaborszanto** [comment]
It seems like that ads platform or your app is set up to require exclusive audio access. I wonder if you call SuperpoweredIOSAudioIO interruptionStarted/interruptionEnded? Those might be the built-in ways to handle this.

**Comment by luanvt-amanotes** [comment]
No we do not.
As far as I know interruptionStarted/interruptionEnded are two callbacks of SuperpoweredIOSAudioIODelegate.
Im not sure if we are suppose to call it?

**Comment by gaborszanto** [comment]
Sorry, I was wrong. Just call the start/stop API then?

**Comment by luanvt-amanotes** [comment]
I were thinking about start/stop API.
But I think I will stick with this solution for now.
Thank you 😄
