### ISSUE TITLE
[iOS] play multiple mp3 simultaneously 

### ISSUE THREAD

**Issue by luanvt-amanotes** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#681]
We have 10 different short sound effect clips and we want to play these sfx based on action in the game. 
Sometime there must be more than 2 sfx playing at the same time. 
How can we do this with superpowerer? could you provide us any samples?
Thank you :)

**Comment by gaborszanto** [comment]
Instantiate 10 AdvancedAudioPlayers please.
