### ISSUE TITLE
Superpowered::CPU::setSustainedPerformanceMode(true) does not affect performance cores

### ISSUE THREAD

**Issue by svenoaks** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#682]
On a big.LITTLE CPU only the efficiency cores are affected, the performance cores do not get maxed out in frequency. Does it still solve the problem it's meant to solve?

See screenshot on an S8+ after running some time, it seems to be like this on any CPU with big.LITTLE.

![Screenshot_20210429-103813_Simple System Monitor](https://user-images.githubusercontent.com/5206058/116574020-53abbc00-a8db-11eb-9589-bca0d9e4577a.jpg)

**Comment by gaborszanto** [comment]
This is correct. By spinning up the most powerful cores, the entire CPU will run at its maximum capacity.
