### ISSUE TITLE
[QUESTIONS] about multi-sound effects

### ISSUE THREAD

**Issue by luanvt-amanotes** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#684]
I apologize for previous question not being clear enough.
I'm having a couple of problems right now with multi-sfx with superpowered on iOS.

1. SFX can be played overlapping multiple times. So I can't use one AdvancedAudioPlayer to play one SFX multiple times. Leads to problem no2.
2. Instantiate many AdvancedAudioPlayer::openMemory with input from decodeToAudioInMemory.
So my questions are:
- decodeToAudioInMemory have void pointer input, I assume that its actually char pointer?
- Can I use Superpowered::httpRequest to fetch mp3 content and fetch it into decodeToAudioInMemory?
- I tried to use httpRequest but the data response is always NULL. What is the correct way to use httpRequest?

Warm regards
Lulu

**Comment by gaborszanto** [comment]
- A void pointer has no type. Can be treated as a char pointer, why not.
- Yes, you can use Superpowered::httpRequest to fetch mp3 and then use decodeToAudioInMemory.
- Check the status code/error code on what happened?

**Comment by luanvt-amanotes** [comment]
- Check the status code/error code on what happened?
The statusCode is "StatusCode_Success 200", but the response data is always null.
I'm not sure where is the problem, below is my piece of code.

``` C++
static bool fileRequestComplete(void *clientData, Superpowered::httpRequest *request, Superpowered::httpResponse *response)
{
//    printf("LULU %d", response->statusCode);
    if(response->statusCode == 200)
    {
        printf("LULU");
        char *data = new char[response->contentLengthBytes];
        memcpy(response->data, data, response->contentLengthBytes);
        Superpowered::AudioInMemory*pointer = (Superpowered::AudioInMemory *)Superpowered::Decoder::decodeToAudioInMemory(data, response->contentLengthBytes);
        return false;
    }
    return true;
}
fileRequest = new Superpowered::httpRequest("http://music.amanotes.net/media/c01a912b-46cc-4354-9e38-ffe63d9dd503/20449a23-8d1d-4422-b951-39b2567cf7ae.mp3");
fileRequest->sendAsync(fileRequestComplete)
```
Thanks in advance.

**Comment by luanvt-amanotes** [comment]
`I see that memcpy copying memory garbage (the contents of "data") into response->data. You need that the other way around, but actually you don't need to copy it at all, use decodeToAudioInMemory the response->data directly.`

You are right I used memcpy incorrectly.
Everything works now.
Thank you for your patience.
