### ISSUE TITLE
Android: API 30+ (Android 11 & up) no longer allows direct external file access

### ISSUE THREAD

**Issue by flamewave000** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#686]
I have a media player app that uses the Superpowered SDK on Android. Google has stated that they will be blocking apps that attempt to use the legacy file access. We are expected to use the Scoped Storage system instead. This means I can no longer access the raw file path of a song file. Instead I'm given a Content URI that is used to open an Input File Stream for the given file.

What is Superpowered's plan for updating their SDK to support Android's new file access. I have already tried passing the Content URI to the decoder, but it unsurprisingly gives me a `1006: File Open Error` as I would expect. Even if there was a way to build an interop component that act as a stream iterator for Superpowered, I'd be more than happy opening the File Stream myself and feeding it into the decoder, but I do not know of a way to do that with Superpowered 2.2.2

**Comment by flamewave000** [comment]
Relevant article: https://developer.android.com/about/versions/11/privacy/storage

**Comment by HBiSoft** [comment]
@flamewave000 
`Google has stated that they will be blocking apps that attempt to use the legacy file access.`

This is not true, Google did not say that. From the link you shared above:

>After you update your app to target Android 11, the system ignores the requestLegacyExternalStorage flag.

---
Android 10 added restrictions to file access, that is where `requestLegacyExternalStorage` was introduced - for developers who still want to access files.

Android 11 removed this restrictions and files are once again accessible.

When targeting Android 11, `requestLegacyExternalStorage` will be ignored (your app will NOT be blocked). You still have to keep `requestLegacyExternalStorage` when targeting Android 11 to ensure you have file access on Android 10.

**Comment by gaborszanto** [comment]
The document also says:

> Access files using direct file paths and native libraries
> 
> To help your app work more smoothly with third-party media libraries, Android 11 allows you to use APIs other than the MediaStore API to access media files from shared storage using direct file paths. These APIs include the following:
> 
> The File API.
> Native libraries, such as fopen().

Superpowered uses fopen().

**Comment by flamewave000** [comment]
So the primary problem is not that Superpowered can open a raw file path, but the fact that **obtaining** those Raw File Paths has become deprecated in API 29+. The current method of querying the [MediaStore's DATA](https://developer.android.com/reference/android/provider/MediaStore.MediaColumns#DATA) column has been **deprecated**, and they are restricting access to raw files to only those within your application's [Scoped Storage](https://developer.android.com/about/versions/11/privacy/storage#scoped-storage). We are a media player app, and currently query the MediaStore for all music on the device so the user can easily find and play their music, but in Android R, we will no longer be able to retrieve a raw path to those files.

Our only option for targeting Android R (API 30) would be to copy the file into our Scoped Storage, and then open it in Superpowered. This is logistically not viable, as many users use our app for listening to large high quality and/or long duration files, and the delay in copying a file and maintaining that cache would negatively impact our users. Especially when they are known to switch files frequently.

What I would like to request is for Superpowered to provide a `Decoder::openStream(std::istream data)` function that can be given a stream of binary data. This would provide a great amount of flexibility for implementations to manage all sorts of data sources other than just raw file and HTTP. This includes, for example, on Android where shared files from other apps are not tied to any physical file on the device, and can ONLY be obtained via the ContentResolver and the associated Content URI sent to our application.

PS. @HBiSoft Android 11 does not remove the restrictions, but does the opposite. It ignores the `requestLegacyExternalStorage` flag in your manifest because it completely disallows the use of legacy broad file access. Therefore it is now strictly enforcing the new Scoped Storage system, and apps transitioning to API 30 must conform. We received an email from Google Play that stated our app would no longer be allowed to access files as it currently does. In order for us to do so, we would need the `MANAGE_EXTERNAL_STORAGE` permission, which requires us to make a case to Google Play and obtain explicit approval to use. This is because that permission is specifically made for File Management apps, not for Media Player style apps such as ours.

**Comment by gaborszanto** [comment]
The Decoder has a feature now that is maybe useful for your use-case. Please check Decoder::openMemory and the AudioInMemory classes in the documentation.

**Comment by flamewave000** [comment]
Per the documentation for `AudioInMemory`:
> size - AdvancedAudioPlayer: the number of audio frames inside the payload. Decoder: the size of the payload in bytes.

Since I am using the `AdvancedAudioPlayer`, how do I get the number of audio frames in a memory block? The directions for using  `AudioInMemory` for the Decoder make sense since it is just the memory block size in bytes, but the `AdvancedAudioPlayer` seems to need the `AudioInMemory` in some kind of unspecified format and for me to know how many "audio frames" are in that memory block. Do I have to load it fully into the Decoder first, and then use its `decodeToAudioInMemory()` so I can load it into the `AdvancedAudioPlayer`?

**Comment by flamewave000** [comment]
So I am able to load a song myself from file using the following steps:

1. Use fopen/ftseek/ftell to load a block of contiguous memory the same size as the file.
2. Use fread to read the data into that memory block, and verify read success.
3. invoke `Decoder::decodeToAudioInMemory()`, passing it the file data pointer to generate an `AudioInMemory` data structure.
4. Pass the data structure to the `AdvancedAudioPlayer::openMemory()`.

My primary issues with this are speed and memory efficiency. As mentioned before, some of our users utilize our app for listening to either very long audio files, or high quality audio files. These files can be in excess of 100MiB in size. Due to the nature of the heap, it is a known issue that you may be unable to allocate a single 100+MiB contiguous block of memory on Android. I would much rather use progressive loading, or even just non-contiguous memory. Also, this means we have to fully load the entire file, and the playback has to wait until the entire file has been loaded and processed before it can begin playback. Which increases the delay between hitting play and sound coming out of the speakers. I'd like to be able to run a background thread that progressively loads the file into non-contiguous memory, and allow the player to start playing immediately.

Superpowered's AudioInMemory is a very straight forward data structure, and the Decoder already will accept file data in that format, but the issue is that there is only one method that will decode the data into the AudioInMemory data structure, which is `Decoder::decodeToAudioInMemory()`. This method ONLY accepts a pointer to the raw file data array. My issues would likely be resolved if this function was overloaded to accept a pointer to an AudioInMemory Main Table. This would allow me to load the file into non-contiguous memory, and provide the decoded data to the player also in non-contiguous memory.

In case you're curious, this is the code I'm currently using to load the file:
```cpp
try {
    auto file = std::unique_ptr<FILE, file_deleter>(fopen(c_path, "rb"));
    fseek(file.get(), 0, SEEK_END);
    self->data.resize(ftell(file.get()));
    rewind(file.get());
    size_t readSize = fread(self->data.data(), 1, self->data.size(), file.get());
    if (readSize != self->data.size()) {
	    cerr << "AdvancedAudioPlayer: Failed to read entire audio file into memory" << endl;
    }
    self->player->openMemory(self->decoder->decodeToAudioInMemory(self->data.data(), self->data.size()));
}
catch(exception &e) {
    cerr << "AdvancedAudioPlayer: Failed to read audio file into memory\n" << e.what() << endl;
}
```

**Comment by gaborszanto** [comment]
If you can open a file using fopen, then the Decoder or the AdvancedAudioPlayer can also open it, since they will use the same fopen call with "rb".

**Comment by flamewave000** [comment]
@gaborszanto sorry for the confusion, this was just a peice of test code to test the AudioInMemory for loading a file from memory instead of from a file path directly. What I am actually given is a Java InputStream object, not a file path. The current option would be to fully load the entirety of the data stream into memory, which defeats the purpose of a stream, and then pass that entire contiguous memory block to the decoder. I would prefer it if I could pass an AudioInMemory object to the decoder so it could progressively decode the file data for the AdvancedAudioPlayer.

**Comment by gaborszanto** [comment]
You can add to AudioInMemory progressively using its append() API.

**Comment by flamewave000** [comment]
Yes I can progressively load a file into an AudioInMemory data structure, but that's not the issue. The superpowered Decoder provides only One function (decodeToAudioInMemory) for retrieving a Decoded AudioInMemory object, and that function Requires that I give it a pointer to the entire file loaded into a single contiguous memory array. The decoder does Not allow me to use an AudioInMemory data structure so I cannot load a file progressively for the decoder to process.

**Comment by gaborszanto** [comment]
What if you write the data coming from the Java InputStream onto the disk (local app storage) that is readable by Superpowered? I understand it's not progressive access, but might solve your memory concerns.

**Comment by flamewave000** [comment]
This is what we currently will need to do to work around Superpowered's limitation. But this means a delay from the time the user taps the "play" button on a song, to the time it actually starts playing, while the entire file is first copied to our local folder, and then opened into Superpowered. For large podcasts, and high quality audio files, this is a significant delay. We would also need to perform cache management on those files. The Decoder can already take an AudioInMemory data structure, but the only function that will return a decoded AudioInMemory object that can be played in the AdvancedAudioPlayer only accepts the memory pointer as mentioned previously. So if the Decoder already supports AudioInMemory as an input, could Superpowered provide an overload to the `decodeToAudioInMemory` function that takes an AudioInMemory object containing the file data instead of a contiguous memory block?

**Comment by gaborszanto** [comment]
The AdvancedAudioPlayer can also work with an AudioInMemory with its openMemory() API. You can append() the incoming data into the AudioInMemory that is opened by the player?

**Comment by flamewave000** [comment]
So from what I have read in the Superpowered 2.2.2 documentation is that the `AdvancedAudioPlayer` will **only** accept a Decoded `AudioInMemory` data structure. This means our file data `InputStream` needs to be passed through the `Superpowered::Decoder` first. The decoder only provides One function (`decodeToAudioInMemory`) for retrieving a decoded audio as an `AudioInMemory` data structure, and it **only** accepts a single contiguous memory block of the completely loaded file, and will the decode the entire things. This is not progressive, and significantly increases the amount of time it takes to get a song to play in in the `AdvancedAudioPlayer`. What I would prefer is for the following function to be defined in the `Superpowered::Decoder` class:

```C++
/// @brief Opens a memory location of file data in Superpowered AudioInMemory format for progressive decoding.
/// @param pointer Pointer to file data in Superpowered AudioInMemory format.
/// @return AudioInMemory Pointer or NULL on error. The output can be loaded by the AdvancedAudioPlayer.
static void * decodeToAudioInMemory(void *pointer);
```

This would allow for Asynchronous, progressive loading from any source we choose as a developer, and would apply to all platforms uniformly.

The decoder already has the capability of loading such a progressive data structure, and is also capable of progressively decoding the data. We just want to be able to have progressive loading end-to-end where we provide the AudioInMemory to the decoder from any file data source we choose, instead of our only options being FileSystem or HLS.

**Comment by gaborszanto** [comment]
Why do you need the Decoder? The AdvancedAudioPlayer can read your progressively loaded AudioInMemory structure.

**Comment by flamewave000** [comment]
@gaborszanto it is my understanding that the `AdvancedAudioPlayer::openMemory()` method requires the `AudioInMemory` data structure to be already decoded. Per the Decoder's own documentation:

> `Decoder::decodeToAudioInMemory()`
> Decodes an entire audio file in memory to AudioInMemory format in a single call. The output can be loaded by the AdvancedAudioPlayer.

Can the `AdvancedAudioPlayer` read from an `AudioInMemory` data structure containing the raw file data? The documentation does not specify that it can, and this one document implicates that it cannot.

**Comment by gaborszanto** [comment]
Yes, the AdvancedAudioPlayer can read raw file data (compressed audio) via AudioInMemory.

**Comment by flamewave000** [comment]
Ok, I will build a test to try this out and get back to you. If this is the case then I will be able to resolve my issue and transition away from using raw file paths on Android.

**Comment by gaborszanto** [comment]
I wonder if that solution works?

**Comment by flamewave000** [comment]
Ok so I made a test for this and it unfortunately did not work. I got nothing but very loud robotic noise.

The following is the function I wrote for testing this. I open a local file and load the raw file data into an AudioInMemory table in chunks of 512KiB, then give that table pointer to the AdvancedAudioPlayer. It appears the AdvancedAudioPlayer does appear to need the data to already be decoded.

```C++
void testFileToAudioInMemory(Superpowered::AdvancedAudioPlayer * player, const char * c_path, int sampleRate) {
	try {
		auto file = std::unique_ptr<FILE, decltype(&file_deleter)>(
				fopen(c_path, "rb"), &file_deleter);
		const size_t BUFFER_SIZE = 512 * 1024; // 512 KiB buffer
		uint8_t *buffer;
		size_t readSize;
		size_t totalSize = 0;
		auto fileDataTable = Superpowered::AudioInMemory::create(0, sampleRate, 0, false);
		do {
			buffer = new uint8_t[BUFFER_SIZE];
			readSize = fread(buffer, 1, BUFFER_SIZE, file.get());
			totalSize += readSize;
			if (readSize < BUFFER_SIZE) {
				auto temp = new uint8_t[readSize];
				memcpy(temp, buffer, readSize);
				delete[] buffer;
				buffer = temp;
			}
			Superpowered::AudioInMemory::append(fileDataTable, buffer, readSize);

		} while (readSize == BUFFER_SIZE);
		Superpowered::AudioInMemory::setSize(fileDataTable, totalSize);
		Superpowered::AudioInMemory::complete(fileDataTable);
		player->openMemory(fileDataTable);
	}
	catch (std::exception &e) {
		std::cerr << "AdvancedAudioPlayer: Failed to read audio file into memory\n"
				  << e.what()
				  << std::endl;
	}
}
```

**Comment by gaborszanto** [comment]
Please try this: 

`player->open(path);`

Where path looks like: "memory://audiofile.XXX" <- the pointer to your AudioInMemory table that is progressively filled with the data of your compressed audio "stream"

printf can produce that string like this: `printf("memory://audiofile.%lli", pointer);`

**Comment by flamewave000** [comment]
@gaborszanto That appears to work!! It would be great if Superpowered could document this hidden functionality of the AdvancedAudioPlayer 👍🏽 

As an aside, I tried to do a progressive file load, but it appears the player does not like having the AudioInMemory only partially loaded before opening. I'm doing the following as a test:

```c++
void testFileToAudioInMemory(Superpowered::AdvancedAudioPlayer *player, const char *c_path, int sampleRate) {
    static const size_t BUFFER_SIZE = 512 * 1024; // 512 KiB buffer
    auto file = std::unique_ptr<FILE, decltype(&file_deleter)>(fopen(c_path, "rb"), &file_deleter);
    auto fileDataTable = Superpowered::AudioInMemory::create(0, sampleRate, 0, false);
    std::thread loaderThread([&fileDataTable, &file]() -> void {
        uint8_t *buffer;
        size_t readSize;
        size_t totalSize = 0;
        do {
            buffer = new uint8_t[BUFFER_SIZE];
            readSize = fread(buffer, 1, BUFFER_SIZE, file.get());
            totalSize += readSize;
            if (readSize < BUFFER_SIZE) {
                auto temp = new uint8_t[readSize];
                memcpy(temp, buffer, readSize);
                delete[] buffer;
                buffer = temp;
            }
            Superpowered::AudioInMemory::append(fileDataTable, buffer, readSize);
        } while (readSize == BUFFER_SIZE);
        Superpowered::AudioInMemory::setSize(fileDataTable, totalSize);
        Superpowered::AudioInMemory::complete(fileDataTable);
    });
    char uri[64];
    sprintf(uri, "memory://audiofile.%lli", reinterpret_cast<int64_t>(fileDataTable));
    player->open(uri);
}
```

I get several errors when I do this. Is there an issue with how I have maybe initialized the AIM main table? Should I manage the memory instead of allowing Superpowered to delete it when it is done?

**Comment by gaborszanto** [comment]
Are you trying to load an audio file or raw pcm 16 audio with the code above? If it's an audio file and not raw pcm 16 audio, then samplerate should be set to 0 when you create the AudioInMemory.

Why are you using two buffers inside the iteration? "temp" is not needed. Please also use malloc() to create it, because Superpowered will try to deallocate it using free().

**Comment by flamewave000** [comment]
I am loading an MP3 audio file. The documentation did not specify how to handle files as AIM, so I can change that to 0 if that is the expected input.

For the final chunk of file data, I am just doing an optimization to copy the data to a buffer of the exact size if the amount read is less than the buffer size.

I can also switch to malloc if your using the old C free function. Would be good to add a comment in the docs for AIM that memory not self managed is deallocated using `free()`.

**Comment by gaborszanto** [comment]
All of these added. Please test the latest release.

**Comment by flamewave000** [comment]
Thank you @gaborszanto for all the assistance. The new version (2.3) is working exactly as needed. I was continuing to have issues with progressively loading from a file in C++ for some unknown reason on Android, but I moved the progressive load up to Kotlin, funnelling the data down through the JNI and everything is working with the updated `AdvancedAudioPlayer::openMemory()`. I would call this case closed, thank you!

For posterity and in case anyone else comes across this, here is the current solution that I am using on Android for loading data from a file or stream:
```kotlin
class AdvancedAudioPlayer {
	// Open data stream
	fun open(stream: InputStream) {
		// Create the AiM table and invoke player->openMemory()
		internalOpenMemory()
		// Launch a worker coroutine to read the file
		GlobalScope.launch(Dispatchers.IO) {
			stream.use {
				var read: Long
				val bytes = ByteArray(kotlin.io.DEFAULT_BUFFER_SIZE)
				do {
					read = it.read(bytes).toLong()
					internalOpenMemoryAppend(bytes, read)
				} while (read > 0)
			}
		}
	}
	private external fun internalOpenMemory()
	private external fun internalOpenMemoryAppend(data: ByteArray, size: Long)
}
```
```c++
JNIEXPORT void JNICALL Java_com_superpowered_AdvancedAudioPlayer_internalOpenMemory(JNIEnv *env, jobject k_obj) {
	currentData.table = static_cast<Superpowered::AudioInMemory *>(Superpowered::AudioInMemory::create(0, 0, 0, false));
	currentData.size = 0;
	player->openMemory(currentData.table);
}
JNIEXPORT void JNICALL Java_com_superpowered_AdvancedAudioPlayer_internalOpenMemoryAppend(JNIEnv *env, jobject k_obj, jbyteArray data, jlong size) {
	if (size > 0) {
		jbyte *bytes = env->GetByteArrayElements(data, nullptr);
		if (!bytes) {
			std::cerr << "AdvancedAudioPlayer::internalAppendData > Failed to retrieve data chunk from JVM" << std::endl;
			return;
		}
		void *c_data = malloc(size);
		memcpy(c_data, bytes, size);
		Superpowered::AudioInMemory::append(currentData.table, c_data, size);
		currentData.size += size;
	}
	if (read <= 0) {
		Superpowered::AudioInMemory::setSize(currentData.table, currentData.size);
		Superpowered::AudioInMemory::complete(currentData.table);
	}
}
```
