### ISSUE TITLE
iOS 14.5 + Airplay Hang, it's back

### ISSUE THREAD

**Issue by flagoworld** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#687]
As of iOS 14.5+, it appears, the AudioIO airplay hang appears to be back. ( #558 )

Repo:

1. Open sample app
2. Open something and play it
3. Pause Playback
4. Open something else and play it
5. open() hangs

AudioIO is attempting to recover, however since open() was called on the main thread and hangs, the onMediaServerReset: selector call never occurs, and coreAudioProcessingCallback keeps returning with InvalidParameter.

I believe an acceptable fix would be to allow the callback to continue successfully after firing off the onMediaServerReset call, which allows open() to not hang, and then the media server reset code can run. This may cause a split second of "unoptimized, no divisible by 8" audio to run, but it quickly resets the server and starts playing the optimized audio.

    static OSStatus coreAudioProcessingCallback(void *inRefCon, AudioUnitRenderActionFlags *ioActionFlags, const AudioTimeStamp *inTimeStamp, UInt32 inBusNumber, UInt32 inNumberFrames, AudioBufferList *ioData) {
    __unsafe_unretained SuperpoweredIOSAudioIO *self = (__bridge SuperpoweredIOSAudioIO *)inRefCon;
    self->lastCallbackTime = mach_absolute_time();
    
    if (!ioData) ioData = self->inputBufferListForRecordingCategory;
    div_t d = div(inNumberFrames, 8);
    if (d.rem != 0) {
        // Core Audio performs sample rate conversion, but received no streamFormatChangedCallback. Recreate audio I/O for perfect match with hardware.
        if (self->audioUnitRunning) {
            self->audioUnitRunning = false;
            [self performSelectorOnMainThread:@selector(onMediaServerReset:) withObject:nil waitUntilDone:NO];
        }
        // return kAudioUnitErr_InvalidParameter; // <--------- COMMENT OUT THIS LINE AND EVERYTHING WORKS AS EXPECTED
    }

    if (((int)inNumberFrames < self->minimumNumberOfFrames) || ((int)inNumberFrames > self->maximumNumberOfFrames) || ((int)ioData->mNumberBuffers != self->numChannels)) {
        return kAudioUnitErr_InvalidParameter;
    };

**Comment by gaborszanto** [comment]
What kind of "open()" API hangs? SuperpoweredIOSAudioIO has no "open".

**Comment by flagoworld** [comment]
player->open()

**Comment by gaborszanto** [comment]
I confirm, it's a good fix (removing that line). Next version will have it.
