### ISSUE TITLE
Enhancement: Sound Font player ?

### ISSUE THREAD

**Issue by rene-dohan** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#688]
Or is it posible implement somewhat easily for Android ?

**Comment by gaborszanto** [comment]
We have no plans to implement playing of the .sf2 format, sorry.

**Comment by romanbsd** [comment]
This is a good implementation you can use: https://github.com/schellingb/TinySoundFont
