### ISSUE TITLE
ANRs upon audioIO destruction

### ISSUE THREAD

**Issue by kenneide** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#690]
Hi,

In our app, we have a screen which allows the users to fix sample rates and buffer sizes for their device in case the system defaults give issues -- see for example: https://github.com/superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform/issues/664

In this screen, audio will play and the audioIO is destroyed and re-created when new settings are selected.  Usually this works fine, however we now notice a number of ANRs which seem to be a result of the destruction of the OpenSLES instance.

`(*internals->outputBufferQueue)->Destroy(internals->outputBufferQueue);
` 

Upon execution of the above line, the app is hanging.  A very old and very similar issue seems to be described here:
https://github.com/superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform/issues/86

It seems to be have become and issue recently as older builds of Superpowered do not demonstrate the same behaviour.  Any insights here?

Cheers

**Comment by gaborszanto** [comment]
Is it about older builds of Superpowered or new Android devices with increasingly bad audio stacks instead? Please note that the SuperpoweredAndroidAudioIO class is open-source and is not "built" into Superpowered, but compiled with your app.

**Comment by kenneide** [comment]
Indeed, I think it’s limited to a number of (popular) android devices — Samsung A71, S20, for example — as I’m not able to reproduce it faithfully on every device.

However, it is consistently freezing upon destruction of the SuperpoweredAndroidAudioIO object. Why would this happen?

**Comment by gaborszanto** [comment]
If it freezes on outputBufferQueue->Destroy, then it's a bad OpenSL ES API implementation on those devices.

**Comment by gaborszanto** [comment]
Is this with the latest version of Superpowered, which has USE_AAUDIO set to 0 in SuperpoweredAndroidAudioIO.cpp?

**Comment by kenneide** [comment]
Yes! Haven’t used AAudio since it was disabled some months ago.

/Alan

**Comment by gaborszanto** [comment]
When you destroy audio I/O, is this happening from a thread that is "backed" by Java, so it's called from Java?

**Comment by gaborszanto** [comment]
When you destroy audio I/O, is this happening from a thread that is "backed" by Java, so it's called from Java?

**Comment by kenneide** [comment]
(Strange, I see that my original response didn't update with the question.)

The app calls a JNI function which then calls the destructor. So, presumably yes, it is backed by Java.  Let me confirm and get back to you.
