### ISSUE TITLE
Reset the Superpowered::FX values

### ISSUE THREAD

**Issue by pro-softs** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#691]
Not much of an issue but a doubt. 

Did you guys remove the **reset() function** in the latest version? Is there any way now to reset the values of a filter to initial state?

**Comment by gaborszanto** [comment]
It was removed a long time ago, yes. A reset can be achieved by processing 64 frames of zeros for most effects, except the ones with a "tail" (echo, reverb).

**Comment by pro-softs** [comment]
Ok, thanks
