### ISSUE TITLE
SuperpoweredPlayer example fully optimised for latency?

### ISSUE THREAD

**Issue by kakonyitibor** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#692]
Hello,

I’m quite a beginner on this field, so sorry if this question is a bit dumb.

I started experimenting with the /Examples_Android/SuperpoweredPlayer example, and it shows significant improvement in terms of latency compared to other methods I tried before, but the delay is still noticeable.
Is this example fully optimised for low latency, or does any other parameter combination exist to achieve an even better result?

Thanks in advance!

**Comment by gaborszanto** [comment]
Yes, it's optimized for low latency, can't go any lower than that on your device.
