### ISSUE TITLE
AAC-LC / M4A not able to decode/play

### ISSUE THREAD

**Issue by flagoworld** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#693]
The attached file is not able to be decoded. It appears at a glance to be a valid and supported format.

```
  Duration: 00:03:03.25, start: 0.000000, bitrate: 136 kb/s
    Stream #0:0(eng): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 6 kb/s (default)

```
It throws a "1005" which is "The decoder is not able to decode this file format."

[1005.zip](https://github.com/superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform/files/6786131/1005.zip)

**Comment by gaborszanto** [comment]
This file has an empty STTS atom and multiple small MDAT atoms. I'm guessing this file is coming from some streaming source. Superpowered is not prepared to understand this strange format.
