### ISSUE TITLE
Unable to locate source for Clipper Effect

### ISSUE THREAD

**Issue by ReeceKetley** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#694]
First off really useful bit of kit this has given my old Samsung a new lease of life as an external fx processor. 

I've been using the clipper effect on android but i can't locate the source as id like to change it from a hard clip to a soft clip? is this because it's closed source?

**Comment by gaborszanto** [comment]
Superpowered is closed source.
