### ISSUE TITLE
Build Errors

### ISSUE THREAD

**Issue by v6Point0** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#696]
Why am I receiving the lowing errors in my build?

The C++ compiler

    "C:/Users/user/AppData/Local/Android/Sdk/ndk/21.1.6352462/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: C:/Users/user/Documents/Audio Engineering/SuperpoweredSDK/Examples_Android/SuperpoweredPlayer/app/.cxx/cmake/debug/armeabi-v7a/CMakeFiles/CMakeTmp
    
    Run Build Command:"C:\Users\user\AppData\Local\Android\Sdk\cmake\3.10.2.4988404\bin\ninja.exe" "cmTC_989e6"
    [1/2] Building CXX object CMakeFiles/cmTC_989e6.dir/testCXXCompiler.cxx.o
    FAILED: CMakeFiles/cmTC_989e6.dir/testCXXCompiler.cxx.o 
    C:\Users\user\AppData\Local\Android\Sdk\ndk\21.1.6352462\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe --target=armv7-none-linux-androideabi19 --gcc-toolchain=C:/Users/user/AppData/Local/Android/Sdk/ndk/21.1.6352462/toolchains/llvm/prebuilt/windows-x86_64 --sysroot=C:/Users/user/AppData/Local/Android/Sdk/ndk/21.1.6352462/toolchains/llvm/prebuilt/windows-x86_64/sysroot    -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -march=armv7-a -mthumb -Wformat -Werror=format-security  -fsigned-char -IC:\Users\user\Documents\Audio Engineering\SuperpoweredSDK\Examples_Android\SuperpoweredPlayer\app\..\..\..\Superpowered  -fPIE -o CMakeFiles/cmTC_989e6.dir/testCXXCompiler.cxx.o -c testCXXCompiler.cxx
    clang++: error: no such file or directory: 'Engineering\SuperpoweredSDK\Examples_Android\SuperpoweredPlayer\app\..\..\..\Superpowered'
    ninja: build stopped: subcommand failed.
      

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt

Windows 10 Pro 20H2 19042.928
Dell Latitude E6440 
Intel Core i7-4610M @3.GHz, 16GB RAM
Andriod Studio 4.1.3
Visual Studio Community 16.9.3, SDK 10
NET Framework V4.8.04084

**Comment by gaborszanto** [comment]
The error log says "no such file or directory". Did you check that path, is it correct?

**Comment by v6Point0** [comment]
Is there a global path that I should set? I was simply trying to do a quick download and build to test the features. These paths look like some type of temp paths and files that Superpower uses to build, is this correct? Are these paths a part of the install or are they something that I should set in the Andriod Studio environment?

**Comment by gaborszanto** [comment]
Maybe you need to install Android NDK.

**Comment by gaborszanto** [comment]
Did installing the Android NDK resolve your issue?

**Comment by v6Point0** [comment]
No! installing the Android NDK did not resolve my issue. But I think that this may be the direction that I need to explore more, so I am experimenting.

**Comment by gaborszanto** [comment]
That 'Engineering\SuperpoweredSDK path still doesn't look good to me, missing drive or at least a relative path information.

**Comment by gaborszanto** [comment]
Could you resolve this?

**Comment by gaborszanto** [comment]
I need to close this if you don't respond.
