### ISSUE TITLE
Using `AudioInMemory` to Replay Appended Data Produces a Nasty Buzzing Sound Instead

### ISSUE THREAD

**Issue by EtherBit** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#698]
👋🏾 
I would like capture the incoming signal data, and replay them.
I start by initializing the player and `AudioInMemory` as such:
```
player = new Superpowered::AdvancedAudioPlayer((unsigned int) sample_rate, 0);
audioInMemory = static_cast<Superpowered::AudioInMemory *>(Superpowered::AudioInMemory::create(0, sample_rate, 0, false));
player->openMemory(audioInMemory);
```

During audio process, I capture and append the audio as below:
```
void *c_data = malloc(number_of_frames * sizeof(short int));
memcpy(c_data, audio, number_of_frames);
Superpowered::AudioInMemory::append(audioInMemory, c_data, number_of_frames);
```

Once done, I complete appending as below:
```
Superpowered::AudioInMemory::complete(audioInMemory);
```
And then I call `player->play();`

The playback block for player looks like:
```
float playerOutput[number_of_frames * 2];
Superpowered::FloatToShortInt(playerOutput, audio, (unsigned int) number_of_frames);
player->outputSamplerate = (unsigned int) sample_rate;
return player->processStereo(playerOutput, false, (unsigned int) number_of_frames);
```
But I get a nasty buzzing sound instead (of the length of the data appended).

Am I doing something wrong?

**Comment by gaborszanto** [comment]
If copying raw PCM data into the AudioInMemory, then do it in interleaved stereo instead of mono please.

**Comment by EtherBit** [comment]
Hey @gaborszanto 
could an example/sample be provided?

**Comment by EtherBit** [comment]
Since the audio data from the callback is already interleaved, I updated the block responsible for copying as such:
```
void *c_data = malloc(number_of_frames * 2 * sizeof(short int));
memcpy(c_data, audio, number_of_frames * 2);
Superpowered::AudioInMemory::append(audioInMemory, c_data, number_of_frames);
```

However, still getting the buzz

**Comment by EtherBit** [comment]
Never mind. I was copying with an incorrect size. Thank you
