### ISSUE TITLE
[iOS][QUESTION] Suddenly can not load MP3 remotely

### ISSUE THREAD

**Issue by luanvotrongdev** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#699]
Hello, sorry for troubling you again.

I failed play this [MP3](https://music.musikit.net/media/14872cb3-2123-463c-98e4-9c36a7e6043f/14872cb3-2123-463c-98e4-9c36a7e6043f.mp3 ) remotely and Superpowered only shows a few logs.
But when I upload the same MP3 file to another host, it works fine. 
My question is, how can I get more debug information from Superpowered to pinpoint the problem?

thank you.

**Comment by gaborszanto** [comment]
If it works from another host, then the cipher suites on that https connection are outside of Superpowered's supported cipher suites of:

TLS_RSA_WITH_AES_256_CBC_SHA256
TLS_RSA_WITH_AES_256_CBC_SHA
TLS_RSA_WITH_AES_128_CBC_SHA256
TLS_RSA_WITH_AES_128_CBC_SHA

**Comment by luanvotrongdev** [comment]
Noted, I will check the server setting.
For now, I'm using NSURLSession as a workaround.

Thank you.
