### ISSUE TITLE
Looping mp3

### ISSUE THREAD

**Issue by renezuidhof** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#701]
So far I've been using wav files to loop audio in my app, this is working perfectly.

For a new feature I want to give the user a bunch of loop samples to work with. In order to save some storage space I would prefer these files to be compressed, like mp3 (or any other compressed format). When looping mp3's with the same code as the wav's there's a small silence (just a few milliseconds) at the start. I've read this is because of the compressed files.

Is it therefor not possible to smoothly loop compressed files with Superpowered? When I loop the same mp3 file with for example SimpleExoPlayer (Android) the mp3 file loops perfectly.

I've tried setting `skipSilenceAtBeginning` to `true` when opening the file but this does not seem to help.

The code I use to open the audio files:
```
audioPlayer.open(audioFilePathString.c_str(), nullptr, true);
audioPlayer.loopOnEOF = true;
audioPlayer.loopBetween(0, durationInMilliseconds, false, 255, false);
```

**Comment by renezuidhof** [comment]
In case the answer involves using `getAudioStartFrame` to set the `loopBetween`: Does that not also detect intended silence at the start?

**Comment by gaborszanto** [comment]
`skipSilenceAtBeginning` detects the silence at the start. `getAudioStartFrame` reads the offset value that you can use with `loopBetween`.
