### ISSUE TITLE
RealFFT / ComplexFFT / PolarFFT minimum array length and logSize question

### ISSUE THREAD

**Issue by tehsven** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#704]
When using `RealFFT`/`PolarFFT`/`ComplexFFT`, what are the minimum input array length requirements relative to `logSize`?

For `RealFFT`/`PolarFFT`, does Superpowered expect the array lengths of the two input arrays to be `>= 2^(logSize-1)`, or something else?

For `ComplexFFT`, does Superpowered expect the array lengths to be `>= 2^logSize`, or something else?

The [Superpowered documentation](https://github.com/superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform/blob/master/Superpowered/SuperpoweredFFT.h) for these functions point to Apples [Data Packing for Real FFTs](https://developer.apple.com/documentation/accelerate/data_packing_for_fourier_transforms) documentation.

The [Superpowered FFT tests](https://github.com/superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform/blob/master/Examples_iOS/SuperpoweredPerformance/fftTest.h#L79) are unclear about the expectation since always supplying arrays that are `>= 2^logSize` for all three FFT methods.

**Comment by gaborszanto** [comment]
The array length is fixed to the size, this is how FFTs work. The tests also submit exactly the required amount of frames to each FFT.

**Comment by gaborszanto** [comment]
Real FFT expects no imaginary parts, therefore the input data size is half and consists of real data only.
As described in Apple's data packing documentation, real data must be "packed" in the real and imag inputs in this case.

**Comment by gaborszanto** [comment]
It writes into both.
