### ISSUE TITLE
How to recognized the number of loop using Superpowerd sdk loopBetween function

### ISSUE THREAD

**Issue by ashojon** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#708]
For studying purpose, I just try to make a small application for Android using Superpowered SDK 2.3.0.

I use the loopBetween function for two players to loop a specefic region of the Songs.

What I would like to achieve is to stop the first player exactly after one loop and start the second player immidiatly.

I tried to set numLoops Number to 1 but the player plays to the end of the Song. My Problem is to recognize when exactly one loop was played.

Thank you for helping me in advance.

**Comment by gaborszanto** [comment]
You need to track the progress of getPositionMs or similar APIs directly in the audio processing callback.
