### ISSUE TITLE
Apple M1 support required to develop SwiftUI apps

### ISSUE THREAD

**Issue by AliMunchkin** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#709]
A simulator build of a Superpowered project on an Apple M1 machine results in the following error:

`…/Superpowered/libSuperpoweredAudioIOS.a(SuperpoweredHome.o), building for iOS Simulator, but linking in object file built for iOS, for architecture arm64`

SwiftUI invokes a simulator build to provide the preview screens which are required to layout the GUI. This makes it impossible to develop a SwiftUI app on an M1 machine using Superpowered.

**Comment by gaborszanto** [comment]
Next update will have this.

**Comment by FfinguMpingo** [comment]
How long until the next update is released?

**Comment by gaborszanto** [comment]
I don't have an ETA, sorry.
