### ISSUE TITLE
Audio playback incorrect for a simple click track

### ISSUE THREAD

**Issue by ben-melzer** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#711]
I forked the SuperpoweredPlayer Android example and tested it with a simple click track. The audio doesn't play correctly as the clicking at times is not on beat and some clicks are completely missing.

The original audio track can be found here:
https://github.com/ben-melzer/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform/tree/click_audio_bug/Examples_Android/SuperpoweredPlayer/app/src/main/res/raw

And here is a recording of the resulting audio with the SuperpoweredPlayer Example:
https://user-images.githubusercontent.com/88662227/144072167-2bbd55ea-6089-4f87-a84d-cbab35ca530e.mp4

To reproduce the fork is here:
https://github.com/ben-melzer/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform/tree/click_audio_bug/Examples_Android/SuperpoweredPlayer/

**Comment by gaborszanto** [comment]
I see that Superpowered is incorrectly decoding this mp3 file. This is the first one in 5 years that looks like a valid MPEG Layer III file at the first sight, but Superpowered doesn't decode it properly. I recommend using a different mp3 encoder.
