### ISSUE TITLE
How to create a Superpowered::httpRequest

### ISSUE THREAD

**Issue by xieliwei1** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#712]
![image](https://user-images.githubusercontent.com/23618414/146747855-6078c8f8-40b4-407a-bcc3-9d37bf689bf5.png)
I tried to create the Superpowered::httpRequest followed the example in the SDK, but it didn't work. What is the correct way here?

**Comment by gaborszanto** [comment]
Check out the Superpowered::Initialize function and set enableNetworking to true.
