### ISSUE TITLE
How to recognized the number of loop using Superpowerd sdk loopBetween function twice

### ISSUE THREAD

**Issue by ashojon** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#714]
I refer to the closed issue #708.
Thank you for reply. I have still a problem. 
If I pick some values from outside of the function 'audioProcessing' the values do not change. I have still the same value.

I do this.

float songPosition;
audioProcessing(...){
...

songPosition = (int)player->getPositionMs();

....
}

void play() {
    
    while (true) {
                log_print(ANDROID_LOG_DEBUG, TAG_CPP, "songPosition1: %i", songPosition);
               // Here I get allways the same Value for songPosition1 . It does not change
            }
}

**Comment by gaborszanto** [comment]
I guess nothing is playing? The player's process function is never called?

**Comment by ashojon** [comment]
You were absolutely right. Thank you.  My While-Loop was within a none true If-Condition.

I have  2 more questions:
My android application is a Singlton so I do not have a destroy() method where I can call a cleanup function on c++ side to delete the player.
I have a list of songs and choose one after  the other to play. 

1: Do I have to close each file to free up memory or superpowerd does it for me?
2: Will be there a problem with memory increasing, because I do not call the delete methode for player?



That is my implementation:

I call the  initialize() method  of the AudioService only once in the constructor of AudioService. There I call the native
NativeInit method and create a player named playerMain . See below.

Each time when I choose a song from the list, I call the openFile function on c++ side via the openFile method of Audioservice 

Code:
Java side
class PlayerApplication extends Application
    
    private static AudioService mAudioService;

   
   @Override
    public void onCreate() {
         mAudioService = new AudiService(getApicationContext());
     }
}

public class AudioService(){
  private void initialize() {
     .....
     NativeInit(samplerate, buffersize, mContext.getCacheDir().getAbsolutePath());
     ..........
  }
  void openFile() {
      OpenFilesFromAPK(path)
   }
  
   native void OpenFilesFromAPK(String path);
  
}

C++ side:
static Superpowered::AdvancedAudioPlayer *playerMain;
Java_com_mapani_mediaservice_audio_NativeAudioService_NativeInit(..){
     .......
     playerMain = new Superpowered::AdvancedAudioPlayer((unsigned int) samplerate, 0);
    ......
}

Java_com_mapani_mediaservice_audio_NativeAudioService_OpenFilesFromAPK(String path){
 .......
 playerMain->open(str, fileMainoffset, fileMainlength);
......
}**
