### ISSUE TITLE
Android Singlton application: How to avoid memory leak and memory increasing in Superpowered

### ISSUE THREAD

**Issue by ashojon** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#716]
My android application is a Singlton so I do not have a destroy() method where I can call a cleanup function on c++ side to delete the player.
I have a list of songs and choose one after the other to play.

1: Do I have to close each file to freeing up memory or superpowerd does it for me?
2: Will be there a problem with memory increasing, because I do not call the delete methode for player?

That is my implementation:

I call the initialize() method of the AudioService only once in the constructor of AudioService. There I call the native
NativeInit method and create a player named playerMain . See below.

Each time when I choose a song from the list, I call the openFile function on c++ side via the openFile method of Audioservice

Code:
Java side
class PlayerApplication extends Application

private static AudioService mAudioService;
@OverRide
public void onCreate() {
mAudioService = new AudiService(getApicationContext());
}
}

public class AudioService(){
private void initialize() {
.....
NativeInit(samplerate, buffersize, mContext.getCacheDir().getAbsolutePath());
..........
}
void openFile() {
OpenFilesFromAPK(path)
}

native void OpenFilesFromAPK(String path);

}

C++ side:
static Superpowered::AdvancedAudioPlayer *playerMain;
Java_com_mapani_mediaservice_audio_NativeAudioService_NativeInit(..){
.......
playerMain = new Superpowered::AdvancedAudioPlayer((unsigned int) samplerate, 0);
......
}

Java_com_mapani_mediaservice_audio_NativeAudioService_OpenFilesFromAPK(String path){
.......
playerMain->open(str, fileMainoffset, fileMainlength);
......
}**

**Comment by ashojon** [comment]
Thank you for youtr reply:
Yes NativeInit runs only once for each application lifecycle.
Do I understand you right that there is no problem with memory leak or memory increasing?

**Comment by gaborszanto** [comment]
Yes, your understanding is correct.
