### ISSUE TITLE
ConnectionLost when streaming M4A file from the network

### ISSUE THREAD

**Issue by VovaYevt** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#717]
I have built [SuperpoweredPlayer](https://github.com/superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform/tree/master/Examples_Android/SuperpoweredPlayer) sample project and launched it on x86 Android API 30 emulator. It works fine for a local file but when I've replaced it with a http link to M4A (http://assets.yokee.cms.yokee.tv/M4A/USK4W0040246.m4a) after ~10 sec of playback I constantly receive an error **Superpowered::AdvancedAudioPlayer::PlayerEvent_ConnectionLost:**
This does also happen on some arm64 real android devices (reproduced on Samsung Note 10).

**Comment by gaborszanto** [comment]
Please try another server or server configuration. Maybe there is some exotic configuration, such as ranged http.

**Comment by VovaYevt** [comment]
Thanks I will try. Also are there plans to support https streams? Currently for all encrypted traffic I get **Open error 3: Network socket error**

**Comment by gaborszanto** [comment]
https is supported, but not every cipher suite is implemented

from superpoweredhttp.h:
    /// TLS_RSA_WITH_AES_256_CBC_SHA256
    /// TLS_RSA_WITH_AES_256_CBC_SHA
    /// TLS_RSA_WITH_AES_128_CBC_SHA256
    /// TLS_RSA_WITH_AES_128_CBC_SHA
