### ISSUE TITLE
Question regarding AdvancedAudioPlayer's sample rate

### ISSUE THREAD

**Issue by priyankjain12** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#718]
Hello team, I am using superpowered SDK in the karaoke application for the real-time music playback as well as recording feature. I am facing a problem related to the synchronization of music and the recorded voice. After testing I found out that the issue lies in the sample rate selection. 

The scenario is something like this. My android device has an output sample rate of 48000. The music has a sample rate of 44100. I am creating SuperpoweredAndroidAudioIO's instance with a device sample rate which is 48000, as I need live feedback of audio. I am creating AdvancedAudioPlayer's instance with a 48000 sample rate and Recording instance with a 48000 sample rate which is the device's output sample rate. The music file has an actual sample rate of 44100. 

**So my question is will the music will play at 48000Hz or at 44100Hz?**

Another question is that I play both recorded and music files simultaneously. The recording file has a sample rate of 48000, the music file has a sample rate of 44100. And the SuperpoweredAndroidAudioIO's sample rate is set to 48000. **So will both files play simultaneously in synchronization?**

**Comment by gaborszanto** [comment]
The AdvancedAudioPlayer will take care of sample rate conversion, it will always output audio in its "outputSamplerate" property.
