### ISSUE TITLE
Determinante Loop end when using loop between

### ISSUE THREAD

**Issue by ashojon** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#719]
Hi,
I refer to the issue #708. 
I am very fustrated, because I am not able to indicate exactly when a loop is ended when I use the "loop between" function.
I tried your suggtion to track the song position but was not succeful. 
Is it possiable to either add a API function for this or give me a snip of code to achive that. 
Thank you.

**Comment by gaborszanto** [comment]
You need to check the player's position in the audio processing callback. If it's lower than in the previous call to the audio processing callback, then you looped.
