### ISSUE TITLE
Example for SuperpoweredEffect in IOS.

### ISSUE THREAD

**Issue by iwarrior** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#721]
https://github.com/superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform/tree/master/Examples_Android/SuperpoweredEffect

Is there an example or method to use the above function in iOS?

It is input voice -> effect -> monitoring output

**Comment by gaborszanto** [comment]
No, but it's a trivial exercise to change any iOS example project for that.
