### ISSUE TITLE
StereoMixer produces invalid output with some (even) numbers of frames 

### ISSUE THREAD

**Issue by svenoaks** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#723]
StereoMixer will produce floats like:

> 2022-05-18 10:57:16.648 18331-29817/? V/CROSSEXAMPLE: INVALID OUTPUT 6.141433
> 2022-05-18 10:57:16.648 18331-29817/? V/CROSSEXAMPLE: INVALID OUTPUT 6.114010
> 2022-05-18 10:57:16.650 18331-29817/? V/CROSSEXAMPLE: INVALID OUTPUT 256.063416
> 2022-05-18 10:57:16.650 18331-29817/? V/CROSSEXAMPLE: INVALID OUTPUT 256.031616
> 2022-05-18 10:57:16.650 18331-29817/? V/CROSSEXAMPLE: INVALID OUTPUT 4294967296.000000
> 2022-05-18 10:57:16.650 18331-29817/? V/CROSSEXAMPLE: INVALID OUTPUT 4294967296.000000
> 2022-05-18 10:57:16.650 18331-29817/? V/CROSSEXAMPLE: INVALID OUTPUT 4294967296.000000
> 2022-05-18 10:57:16.650 18331-29817/? V/CROSSEXAMPLE: INVALID OUTPUT 4294967296.000000
> 2022-05-18 10:57:16.650 18331-29817/? V/CROSSEXAMPLE: INVALID OUTPUT 117832973025280.000000
> 2022-05-18 10:57:16.650 18331-29817/? V/CROSSEXAMPLE: INVALID OUTPUT 117833149186048.000000
> 2022-05-18 10:57:16.650 18331-29817/? V/CROSSEXAMPLE: INVALID OUTPUT 117701599035392.000000
> 2022-05-18 10:57:16.650 18331-29817/? V/CROSSEXAMPLE: INVALID OUTPUT 117833149186048.000000
> 2022-05-18 10:57:16.650 18331-29817/? V/CROSSEXAMPLE: INVALID OUTPUT 117833149186048.000000

> also some nan's.

with some numbers of input frames. 

This is from [code like this](https://github.com/svenoaks/Low-Latency-Android-Audio-iOS-Audio-Engine/blob/673d61f9e0ebe6c6b34647b0514470060f9a4023/Examples_Android/SuperpoweredCrossExample/app/src/main/cpp/CrossExample.cpp#L174):

```
  numberOfFrames = 4172;
    float outputBuffer1[numberOfFrames * 2];
    float outputBuffer2[numberOfFrames * 2];
    //float outputBuffer3[numberOfFrames * 2];
    bool silence = !playerA->processStereo(outputBuffer1, false, numberOfFrames, volA);
    if (playerB->processStereo(outputBuffer2, !silence, numberOfFrames, volB)) silence = false;

    if (!silence) {
        mixer->process(outputBuffer1, outputBuffer2, NULL, NULL, outputBuffer1, numberOfFrames);
        for (int i = 0; i < numberOfFrames * 2; ++i) {
            float n = outputBuffer1[i];
            if (isnan(n) || n > 1.0 || n < -1.0) {
                log_print(ANDROID_LOG_VERBOSE, "CROSSEXAMPLE", "INVALID OUTPUT %f", n);
            }
        }
    }
```

Same thing if a different buffer from the inputs is used for the output.

I'd appreciate a fast bug fix or at least document the constraints on the number of frames because it's putting the brakes on my white label project work.

**Comment by gaborszanto** [comment]
I found the problem. It works until 4096 frames, but if any if the buffers are NULL and frames are above 4096, this happens.

The next update will have the fix, but I can't promise any deadline for that.

**Comment by gaborszanto** [comment]
Fix released.
