### ISSUE TITLE
How to get MIC input and listen to the provided input at the same time from headphones/speakers on Android

### ISSUE THREAD

**Issue by shanalishams** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#724]

**Comment by shanalishams** [comment]
I am using following configuration for initializing the audio engine 

![image](https://user-images.githubusercontent.com/19967369/170843428-b01ab3b0-8ce8-4ef3-a762-0eae9acb510d.png)

**Comment by gaborszanto** [comment]
You need to focus on the audio processing callback. One of its arguments is the input buffer, it will contain the microphone input. Another argument is the output buffer. If you simply copy the input buffer's contents into the output buffer, you will hear it back.

**Comment by shanalishams** [comment]
In Android, this audio-processing callback has only an output buffer argument and no input argument so how I will copy the input buffer's content into the output buffer as there is no input buffer. Please look at the picture below to understand

![image](https://user-images.githubusercontent.com/19967369/170982218-c3f150a0-d7c0-489f-8db2-09870d4c849f.png)


And I am using the Volumn utility to capture mic audio like the following screenshot.

![image](https://user-images.githubusercontent.com/19967369/170982731-2560693b-afcd-4ef1-ba52-ffbd782100ea.png)

**Comment by shanalishams** [comment]
**Following is my full code snippet can you please tell me what wrong I am doing in the code please???**

![image](https://user-images.githubusercontent.com/19967369/171014714-ae097ef2-dde2-40ba-ac1f-e90699094446.png)

I am again copying the content of the stereo buffer to audio at the end.

I need to deliver a feature in development because of this issue I am stuck :(

**Comment by gaborszanto** [comment]
Your code snippet looks good. Maybe you forgot some basic Android stuff, such as asking for microphone permission in Java? Also check the manifest.

**Comment by shanalishams** [comment]
I was missing the microphone permission in the app once I enabled the microphone permission I was able to get my voice back from the speakers hence my issue is resolved. Thank you for actively coordinating with me on this.
