### ISSUE TITLE
192kHz playback on ios?

### ISSUE THREAD

**Issue by flagoworld** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#728]
Is there something I am missing to get 192kHz playback working on ios to a USB DAC? It sounds like audio data is getting cut off. Can sort of hear the audio but a lot of noise as well.

• setPreferredSampleRate to 192000
• DAC is showing 192kHz is coming from the phone
• output buffer number of frames in audioProcessing is 2048, which I believe is correct (44100kHz changes that to 512)
• looking at the data in the interleaved buffer after player->processStereo(), i see data filled out up to index 4095 (which should be correct, since 2048 frames * 2 channels per frame = 4096 floats)

**Comment by ivannador** [comment]
Hello! Thank you for reaching out.
What devices are you using? Is the audio correct when sample rate is set to 48kHz?

**Comment by flagoworld** [comment]
iPhone 13 Pro

Yes, 48khz works fine. Only having issues with 192khz.

Thanks

**Comment by flagoworld** [comment]
Oh ... the DAC I am using is a TOPPING D10s, sorry about that

**Comment by ivannador** [comment]
Thank you for your response!
We are looking into the issue.

**Comment by flagoworld** [comment]
Any updates? Thanks

**Comment by ivannador** [comment]
We are investigating the issue. Stay tuned for more info!

**Comment by flagoworld** [comment]
Update?

**Comment by ivannador** [comment]
We were unable to reproduce the issue so far, 192kHz playback works correctly on our side using a USB DAC with an iPhone.

- Were you using a sample app or custom code?
- Is it possible for you to test with a different USB device capable of 192kHz sample rate?
- Is it possible for you to test with a different iPhone?
- Is 96kHz also working correctly?
