### ISSUE TITLE
Add swift package manager support

### ISSUE THREAD

**Issue by brad-anytune** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#729]
Hi, as a consumer of superpowered SDK for iOS, i'd like to use Apple's officially supported Package Manager, Swift Package Manager to resolve Superpowered libraries.

**Comment by ivannador** [comment]
Hello!
Thank you for reaching out.
We made a note of your request. Stay tuned for more info.

**Comment by ivannador** [comment]
Closing as planned.
