### ISSUE TITLE
[iOS] Recorder saves files not correctly

### ISSUE THREAD

**Issue by AndrewRudyk** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#732]
I'm using Recorder for saving mic input in files.
As it's said in documentation, I create file path for "voiceRecording" for method "recorder->prepare" and create file path for "voiceTemp" for recorder initialization "new Superpowered::Recorder("voiceTemp.wav",  false);"

When "recorder->recordInterleaved(input, numberOfFrames);" launches, I see  "voiceTemp.wav" file  in Documents folder.
I stop recording using "recorder->stop()" and wait to see "voiceRecording.wav" in Documents folder.
It appears not always, but "voiceTemp.wav" file remains when "voiceRecording.wav" doesn't appear, and opposite.
This failure appears unpredictably - it can be first App launch, it can be start-stop recording.

I launch App in simulator and iPhone.

```objective-c
const char *test2Url;

static bool audioProcessing(void *clientdata, float *input, float *output, unsigned int numberOfFrames, unsigned int samplerate, uint64_t hostTime) {
    __unsafe_unretained SuperpoweredBridge *self = (__bridge SuperpoweredBridge *)clientdata;
     
    if (self->_recording && !self->recorderIsPrepared) {
        self->recorderIsPrepared = self->recorder->prepare(self->test2Url, samplerate, false, 0);
    }
    if (self->_recording) {
        self->recorder->recordInterleaved(input, numberOfFrames);
    }
}

- (void)startRecording {
    const char *tempUrl = createFileUrl("voiceTemp.wav");
    recorder = new Superpowered::Recorder(tempUrl);
    test2Url = createFileUrl("voiceRecording");
    _recording = true;
}

- (void)stopRecorder {
    if (self->recorder) recorder->stop();
    while (!recorder->isFinished()) NSLog(@"!!! %u", recorder->isFinished());
    _recording = false;
    recorderIsPrepared = false;
}
```

And samplerate setup isn't  convenient in "recorder->prepare(self->test2Url, samplerate, false, 0);"

**Comment by ivannador** [comment]
Hello! Thank you for reaching out.

You shouldn't call `prepare` in the real-time audio processing callback. You should prepare the recorder in a different thread, and the sample rate you set must be the same during the recording process.
Also please make sure that you prepare the recorder with the full filesystem path of the file and without the file extension. The temporary file should also be passed in as a full filesystem path, with the extension.

**Comment by AndrewRudyk** [comment]
The problem is "self->recorder->prepare" requires right samplerate for recording, but when I'm starting recording "audioProcessing" changes samplerate and I can get right samplerate only in this place

**Comment by ivannador** [comment]
You need to find a way to prepare the recorder after the sample rate is adjusted as calling prepare in the real-time thread is not the correct behavior.

**Comment by AndrewRudyk** [comment]
How can I do it if "audioProcessing" changes samplerate in process? 
And for iPhone 7 samplerate starts from 44100 Hz and iPhone 13 - 48000 Hz 
This is situation for microphone processing

**Comment by ivannador** [comment]
Changing sample rate is possible when different routes are used on iOS devices (Bluetooth headset, speaker, receiver, etc.).
The recorder input must have the same sample rate during the recording. I suggest using the Resampler class in the audio processing callback to account for the changing sample rate, and passing it's output to the recorder.

**Comment by ivannador** [comment]
@AndrewRudyk 

Did the suggestions solve the issue?

**Comment by AndrewRudyk** [comment]
Yes, I've got enough information. Thanks

**Comment by ivannador** [comment]
Closing as solved.
