### ISSUE TITLE
Errors while integrating with android

### ISSUE THREAD

**Issue by Maitreya-Bhatkhande** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#733]
`arguments '-DANDROID_PLATFORM=android-24', '-DANDROID_TOOLCHAIN=clang', '-DANDROID_ARM_NEON=TRUE', '-DANDROID_STL=c++_static', "-DPATH_TO_SUPERPOWERED:STRING=${superpowered_sdk_path}"
                cFlags '-O3', '-fsigned-char' // full optimization, char data type is signed
                cppFlags '-fsigned-char', "-I${superpowered_sdk_path}"`

these lines from build.gradle throw error while building project in android studio.
Looking forward for a quick response. :)

**Comment by ivannador** [comment]
Thank you for reaching out!
Please share the error logs.

**Comment by Maitreya-Bhatkhande** [comment]
[build-gradle.txt](https://github.com/superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform/files/9861550/build-gradle.txt)
**^^This is my build.gradle file^^**
When I uncomment 
`ndk {
        abiFilters 'armeabi-v7a', 'arm64-v8a', 'x86', 'x86_64'
    }`

It throws this error 
`A problem occurred evaluating project ':app'. > No signature of method: build_2eqx8m6jd0jvf9i04cy5iggms.android() is applicable for argument types: (build_2eqx8m6jd0jvf9i04cy5iggms$_run_closure1) values: [build_2eqx8m6jd0jvf9i04cy5iggms$_run_closure1@cce2277]`

Once I comment the above block and uncomment this
 `
externalNativeBuild {
        cmake {
            arguments '-DANDROID_PLATFORM=android-16', '-DANDROID_TOOLCHAIN=clang', '-DANDROID_ARM_NEON=TRUE', '-DANDROID_STL=c++_static', "-DPATH_TO_SUPERPOWERED:STRING=${superpowered_sdk_path}"
            cFlags '-O3', '-fsigned-char'
            cppFlags "-frtti -fexceptions", '-fsigned-char', "-I${superpowered_sdk_path}"
        }
    }`

It throws this error 
`A problem occurred evaluating project ':app'.> No signature of method: build_2eqx8m6jd0jvf9i04cy5iggms.android() is applicable for argument types: (build_2eqx8m6jd0jvf9i04cy5iggms$_run_closure1) values: [build_2eqx8m6jd0jvf9i04cy5iggms$_run_closure1@38a108d3]`

**Comment by ivannador** [comment]
Thanks for your response!

Superpowered 2.6.0 requires minimum SDK level of 24. You have to specify that and pass `'-DANDROID_PLATFORM=android-24'` also.
This version is built against NDK version `24.0.8215888`, so you have to use at least that version.

**Comment by Maitreya-Bhatkhande** [comment]
Thank You for the quick response, will try out that

**Comment by Maitreya-Bhatkhande** [comment]
Well, I changed the minimum sdk to 24 and `-DANDROID_PLATFORM=android-24`, also I degraded my ndk version to `24.0.8215888` but it is throwing exactly the same error for the same code blocks

**Comment by ivannador** [comment]
@Maitreya-Bhatkhande Did you manage to solve the issue?

**Comment by Maitreya-Bhatkhande** [comment]
Yes 👍 thank you for your quick help.
