### ISSUE TITLE
Undefined symbol: _OBJC_CLASS_$_SuperpoweredIOSAudioIO

### ISSUE THREAD

**Issue by realifieducf** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#734]
Hi, I'm trying to integrate your SDK into our iOS app to give it a try, and I'm getting the Undefined symbol: _OBJC_CLASS_$_SuperpoweredIOSAudioIO: d: symbol(s) not found for architecture arm64 error. I'm on an Apple M1, I've added all the libSuperPoweredAudio.xcframework as mentioned in your tutorial, as well as Foundation, Audiotoolbox, etc.. The headers are fine, I'm able to write code without it showing any error on the Editor, and correctly linking to classes when using command + click . I'm not sure what I'm doing wrong here.

**Comment by realifieducf** [comment]
Thanks for the reply! So, I've downloaded the latest sources from Github, and I'm running it on iOS devices, I've tried all kind of iPhones (8, XS, 12 and 14), and all of them had the same issue.

**Comment by realifieducf** [comment]
Update: I have been able to build it. Little suggestion: In your tutorial, you mention 

> To quickly integrate Superpowered with iOS audio you can add the lib/Superpowered/OpenSource/SuperpoweredIOSAudioIO.h and lib/Superpowered/OpenSource/SuperpoweredIOSAudioIO.mm files from the Superpowered SDK package to your project

This is a little confusing, it's worded as an optional suggestion when it's a requirement. Hopefully this can help someone else who might run into this issue.

**Comment by ivannador** [comment]
Thanks for the suggestion! Glad it works now!
