### ISSUE TITLE
Unable to record the voice and play it where as song is getting recorded and able to play

### ISSUE THREAD

**Issue by vijayakrishnav** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#738]
Hi Team,

In iOS Platform....
I am unable to play the voice when I use record functionality.
if I set yourVoiceVolume to 0 .4f it gives a loud sound. if I won't set this value recording the song is happening but our voice is not recording. Please help on priority.
 if (playing) {

          if (playingVoice) {
              yourVoiceVolume = 0.4f;
              Superpowered::Volume(stereoBuffer, stereoBuffer, 6.0f * yourVoiceVolume,
                                   6.0f * yourVoiceVolume,
                                   numberOfFramesUnsignedInt);
          }

**Comment by balazsbanto** [comment]
Hey vijayakrishnav,

Thanks for reaching out. 

Could you elaborate more please on the issue you are having and provide some steps to reproduce?

If I understand correctly you try to record speech and play it back and you can't hear the recorded voice? Do you hear just silence or the volume of the voice is too low? And it is working correctly when you do the same with music?

Which superpowered components are you using?

We would need more sample code in order to be able to reproduce the issue.

**Comment by vijayakrishnav** [comment]
- (bool)audioProcessing:(float *)output numFrames:(unsigned int)numberOfFrames samplerate:(unsigned int)samplerate {
    if (lyricCoachPlayer != nil && guideSingerPlayer != nil) {
    auto numberOfFramesUnsignedInt = (unsigned int) numberOfFrames;
    auto samplerRateUnsignedInt = (unsigned int) samplerate;
    lyricCoachPlayer->outputSamplerate = samplerRateUnsignedInt;
    guideSingerPlayer->outputSamplerate = samplerRateUnsignedInt;
    backingMusicPlayer->outputSamplerate = samplerRateUnsignedInt;
    guideSingerTransposedPlayer->outputSamplerate = samplerRateUnsignedInt;
    backingMusicTransposedPlayer->outputSamplerate = samplerRateUnsignedInt;
    stereoBuffer = output;
    if (recording) {
      
      recorder->recordInterleaved(stereoBuffer, numberOfFramesUnsignedInt);
    }
    
    if (playing) {
      
      if (playingVoice) {
        yourVoiceVolume = 0.4f;
        Superpowered::Volume(stereoBuffer, stereoBuffer, 6.0f * yourVoiceVolume,
                             6.0f * yourVoiceVolume,
                             numberOfFramesUnsignedInt);
      }
      
      lyricCoachPlayer->processStereo(stereoBuffer,playingVoice, numberOfFramesUnsignedInt,
                                      lyricCoachPlayerVolume);
      
      if (level == 0) {
        
        guideSingerPlayer->processStereo(stereoBuffer, true, numberOfFramesUnsignedInt,
                                         guideSingerPlayerVolume);
        backingMusicPlayer->processStereo(stereoBuffer, true, numberOfFramesUnsignedInt,
                                          backingMusicPlayerVolume);
      } else {
        guideSingerTransposedPlayer->processStereo(stereoBuffer, true,
                                                   numberOfFramesUnsignedInt,
                                                   guideSingerTransposedPlayerVolume);
        backingMusicTransposedPlayer->processStereo(stereoBuffer, true,
                                                    numberOfFramesUnsignedInt,
                                                    backingMusicTransposedPlayerVolume);
      }
      
    }
    
    return playing;
  }
  return  false;
  
}

**Comment by vijayakrishnav** [comment]
if I set yourVoiceVolume = 0.4f; it is giving loud noise but if I set to 0 then recording the song is happening without voice

**Comment by vijayakrishnav** [comment]
we want both recording song and voice to be played once we done with recording

**Comment by balazsbanto** [comment]
Thanks for the sample code. If understand you correctly I think you should put the recorder after you mix the input with the content of the players, like this:

```
if (playing) {
.......
}

// The recording should go after the mixing the input with the content of the players

if (recording) {
    recorder->recordInterleaved(stereoBuffer, numberOfFramesUnsignedInt);
}
```

Let me know if this helps!

**Comment by vijayakrishnav** [comment]
issue is same not fixed it's making loud noise

**Comment by balazsbanto** [comment]
Are you using the devices built-in microphone? Try using a headset with a microphone and check if it is the same.

**Comment by vijayakrishnav** [comment]
I have tried this, still the same.

**Comment by vijayakrishnav** [comment]
But whereas it is working in android platform, not in iOS, can you recheck my code snippet and let me know if any thing is missing from our side.

**Comment by balazsbanto** [comment]
Do you initialise your `SuperpoweredIOSAudioIO` with `AVAudioSessionCategoryPlayAndRecord`?
It should look something like this:

```
outputIO = [[SuperpoweredIOSAudioIO alloc]
                       initWithDelegate:(id<SuperpoweredIOSAudioIODelegate>)self
                       preferredBufferSize:12
                       preferredSamplerate:48000
                       audioSessionCategory:AVAudioSessionCategoryPlayAndRecord
                       channels:2
                       audioProcessingCallback:audioProcessing
                       clientdata:(__bridge void *)self];
```
                       
In order to provide more feedback, please share with us a fully working sample app where we can reproduce your issue.

**Comment by vijayakrishnav** [comment]
Hi can you share me the email so that I can share the source

**Comment by balazsbanto** [comment]
Hey, please send it to: support@superpowered.zendesk.com

**Comment by vijayakrishnav** [comment]
I have shared you via Email.Please check and do the needful.
