### ISSUE TITLE
No proper documentation can be found about this library

### ISSUE THREAD

**Issue by Maitreya-Bhatkhande** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#739]
I want to simply **loop an audio file (.wav) seamlessly on android** and I know this library is the solution to it. But I couldn't find any proper example implementing this feature. I checked **"crossexample"** and **"player"** folder of the repository in its Android section but couldn't find the code for looping effect. 
**Looking forward for help at the earliest.**

**Comment by balazsbanto** [comment]
Hey! You can find info about looping on our docsite: https://docs.superpowered.com/reference/latest/advanced-audio-player?lang=cpp

**Comment by Maitreya-Bhatkhande** [comment]
Thank you, that surely helped me out. I would recommend you to add this link in your repository's readme.

One more issue related to this is that there is a noticeable bump at the starting of the audio file while looping. I tried .ogg and .mp3 format but the bump still exists.  

Looking forward for your help.
