### ISSUE TITLE
[Android] Unable to record on some android devices 

### ISSUE THREAD

**Issue by nprapchat** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#742]
Hello Team,
in some of the android devices superpowered recorder not taking audio inputs, it's throwing `AudioRecorder: start() status -38` this error while call `(*recordInterface)->SetRecordState(recordInterface, SL_RECORDSTATE_RECORDING);` this line from `SuperpoweredAndroidAudioIO.cpp` class, can you guys please help me here.

**Comment by balazsbanto** [comment]
Hey,

This error message is not directly related to Superpowered.
The error could be caused by different things:
1. Could be that your app tries to open microphone while it is already reserved by some other process/object.
2. You may try to initialise with a sampleRate or a bufferSize that is not supported by the device.

**Comment by nprapchat** [comment]
Thank you @balazsbanto for your reply, can you please tell me what `status -38` this status code does mean, I have checked above two case you mentioned but it looks good on my end.

**Comment by balazsbanto** [comment]
This is not a Superpowered status code, it's a native Android one, and it means "INVALID_OPERATION". 
There are multiple questions related to this error code on stackoverflow, please check them and see if any of those relates to  your issue. E.g.:
https://stackoverflow.com/questions/20460892/audiorecord-start-status-38?noredirect=1&lq=1
https://stackoverflow.com/questions/61883488/audiorecord-start-status-38-in-cordova-android-application-only-in-samsung-s
https://stackoverflow.com/questions/70920043/audiothread-giving-e-audiorecord-start-status-38
https://stackoverflow.com/questions/50472966/android-audiorecord-error-starting-status-38
https://stackoverflow.com/questions/28204693/audiorecord-start-error-status-38

If the error still persists, please share with us how to reproduce this issue with our Recorder sample app, so we can provide more feedback.
https://github.com/superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform/tree/master/Examples_Android/SuperpoweredRecorder

**Comment by nprapchat** [comment]
I download Recorder sample app from superpowered sdk and it's throwing same error with that also. Can you please check it and let me know.

steps to reproduce:
run superpowered recorder project --> class `RecorderService.java` run native method `StartAudio()` --> in `RecorderExample.cpp` class on Initialize audio engine with audio callback function in it will throw this error after execution of this line in `(*recordInterface)->SetRecordState(recordInterface, SL_RECORDSTATE_RECORDING)` in `SuperpoweredAndroidAudioIO.cpp` class.

**Comment by balazsbanto** [comment]
Unfortunately I was not able to reproduce this issue with my test phones. Could you please share the following details in order to continue with the investigation?

1. The value of  `samplerate` and the `buffersize` passed to `StartAudio(samplerate, buffersize, intent.getIntExtra("fileDescriptor", 0));`
2. Device model used for testing
3. OS and API version of the phone
4. SuperpoweredSDK version used
5. Are you using an external microphone or the device's builtin microphone?

**Comment by nprapchat** [comment]
@balazsbanto Thank you your reply, recorder example working fine now, I am trying to update Superpowered SDK to version `2.6.0`, but getting this error while compile the app, Am I missing anything here?
<img width="1597" alt="Screenshot 2022-12-19 at 7 44 18 PM" src="https://user-images.githubusercontent.com/84467742/208446342-96dbb1e8-3c81-4147-9e37-7e1f4e2853db.png">

**Comment by balazsbanto** [comment]
@nprapchat please add the ndkVersion to your module level build.gradle(:app) files like this:
android {
........
      ndkVersion '24.0.8215888'
}
Make sure to remove this line  ndkPath "/Volumes/iMect/android/ndk/23.1.7779620/android-ndk-r23b" from the gradle file, which was accidentally left there.

It also seems that you build is trying to access two different ndkVersions.

**Comment by nprapchat** [comment]
`/Volumes/iMect/android/ndk/23.1.7779620/android-ndk-r23b` where can I find this in SDK?

**Comment by balazsbanto** [comment]
Depending on where you cloned the repo, line 34 :
../Examples_Android/SuperpoweredRecorder/app/build.gradle


Yes, your cmake version is fine.

**Comment by nprapchat** [comment]
`/Volumes/iMect/android/ndk/23.1.7779620/android-ndk-r23b` is this anywhere in `../Superpowered` bundle?

**Comment by balazsbanto** [comment]
Are you getting this error in your own app which integrates superpowered or the SuperpoweredRecorder sample app?

**Comment by nprapchat** [comment]
in my app in which I am updating superpowered sdk to latest version

**Comment by balazsbanto** [comment]
From the error code I can see that you have an error with "libRCStudioNative.so" which is not related to superpowered.
I can also see that somewhere you still reference the /Volumes/iMect/android/ndk/24.... , you should not have that absolute path in your code.

The error also references two different ndk versions 24 and 25.  Try to clean that up, so all your libs use the same ndkVersion.

Rebuilding your app in android studio may also help.

**Comment by nprapchat** [comment]
`/Volumes/iMect/android/ndk/24` I am not using this anywhere in my app, still it's throwing error after importing new superpowered bundle to my app

**Comment by balazsbanto** [comment]
If the `SuperpoweredRecorder` is working, try to compare its `build.gradle `and `CMakeLists.txt` with your own, and see where it does it differ. 
It may also be the case that some of you native libraries do not support the ndk version that you updated too.

I think this is not a Superpowered related issue anymore.

**Comment by nprapchat** [comment]
getting this error 
```
ld: error: undefined symbol: __write_chk
>>> referenced by unistd.h:206 (/Volumes/iMect/android/ndk/24.0.8215888/android-ndk-r24/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include/bits/fortify/unistd.h:206)
>>>               SuperpoweredHome.o:(copyfile(char const*, char const*)) in archive ../../Superpowered/libSuperpoweredAndroidarm64-v8a.a
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
```

**Comment by balazsbanto** [comment]
I think you are targeting the wrong android platfom (21), it should be 24 `'-DANDROID_PLATFORM=android-24'` . In the build.gradle file you should have something like this:

https://github.com/superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform/blob/master/Examples_Android/SuperpoweredRecorder/app/build.gradle

**Comment by nprapchat** [comment]
you make my day, thank you so much, it works
