### ISSUE TITLE
Sync 2 Players while one of them has been already started

### ISSUE THREAD

**Issue by ashojon** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#747]
Hi,
I try to start  and synchronize a second player to the first player which already started. Can't get them to synchronize.
Both Songs have the same length and BPM. I do not know the excat value of the BPM.

Here is my code.

static bool audioProcessing(
        void *__unused clientdata, // custom pointer
        short int *audio,           // output buffer
        int numberOfFrames,         // number of frames to process
        int samplerate              // current sample rate in Hz
) {
    firstPlayer->outputSamplerate = (unsigned int) samplerate;
    playerPercussion->outputSamplerate = (unsigned int) samplerate;
    firstPlayer->syncMode = secondPlayer->syncMode = Superpowered::AdvancedAudioPlayer::SyncMode_TempoAndBeat;
    // Jump to the first beat.
    firstPlayer->setPosition(playerMain->firstBeatMs, false, false);
    secondPlayer->setPosition(secondPlayer->firstBeatMs, false, false);
    firstPlayer->syncToBpm = secondPlayer->syncToBpm = firstPlayer->getCurrentBpm();
    secondPlayer->syncToMsElapsedSinceLastBeat = firstPlayer->getMsElapsedSinceLastBeat();

    float playerOutput[numberOfFrames * 2];

    bool silence = !firstPlayer->processStereo(playerOutput, false, numberOfFrames,
                                              volFirst);
    if (secondPlayer->processStereo(playerOutput, !silence, numberOfFrames,
                                        volSecond))
        silence = false;

    return !silence;
}

**Comment by ashojon** [comment]
Hey @ivannador, 
thank you for your reply. I changed my code according to your suggestion. Unfortunately it is still not synchronized.
Are you so nice and please have a look on my code? I am not sure what I am doing wrong

Note: playerMain is the first player and playerVariation2 is the second player.

void playMain(jboolean value) {
    playerMain->setPosition(0, false, false);
    playerMain->syncMode = playerVariation2->syncMode = Superpowered::AdvancedAudioPlayer::SyncMode_TempoAndBeat;

    playerMain->setPosition(playerMain->firstBeatMs, false, false);
    playerVariation2->setPosition(playerVariation2->firstBeatMs, false, false);
    playerMain->syncToBpm = playerVariation2->syncToBpm = playerMain->getCurrentBpm();
    playerVariation2->syncToMsElapsedSinceLastBeat = playerMain->getMsElapsedSinceLastBeat();

    if (value == true) {
        playerMain->loopOnEOF = true;
        playerMain->play();
    } else {
        playerMain->pause(0, 0);

    }
   
    Superpowered::CPU::setSustainedPerformanceMode(playerMain->isPlaying()); 
}

void playVariation2(jboolean value) {
   
    if (value == true) {
        playerVariation2->loopOnEOF = true;
        playerVariation2->playSynchronized();
    } else {
        playerVariation2->pause(0, 0);
    }

    Superpowered::CPU::setSustainedPerformanceMode(playerVariation2->isPlaying());

**Comment by ivannador** [comment]
Are you setting `originalBpm` and `firstBeatMs` values correctly?

**Comment by ashojon** [comment]
Unfortunately I don't know this values, so I don't set them

**Comment by ashojon** [comment]
But if the both song have the same length  (wave file) do I need to set the BPM? Because I know the length in ms

**Comment by ivannador** [comment]
You can use the Analyzer class to determine the BPM and the first beat milliseconds value, then you can use it correctly.

**Comment by ashojon** [comment]
Do you mean the "Superpowered::LiveAnalyzer" class? If yes would give an example how can do this? Thank you

**Comment by ivannador** [comment]
You could use the `Superpowered::Analyzer` class, no need for live analyzation. You could pass the songs through the analyzer before playback and set the player parameters with the analyzer results.

You can find an implementation example on the docs page.
https://docs.superpowered.com/reference/latest/analyzer?lang=cpp

**Comment by ivannador** [comment]
Closing as no further input from user.
