### ISSUE TITLE
How to get amplitudes of audio file

### ISSUE THREAD

**Issue by ilyas-shomat** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#750]
How I can get the audio file amplitudes to make a waveform in IOS like this

<img width="366" alt="Screen Shot 2023-03-02 at 18 14 28" src="https://user-images.githubusercontent.com/25116000/222425949-318e320a-3342-4c45-80c2-5e50f86d3be8.png">

**Comment by yoshi-hun** [comment]
Hello!
You could try it with the [`Waveform`](https://docs.superpowered.com/reference/latest/waveform?lang=cpp) class.
You can get the waveform data in 150/sec resolution. This means you can get one pixel for 6.66 ms each.
