### ISSUE TITLE
[Windows] Changing volume on the output in real-time

### ISSUE THREAD

**Issue by GhostVaibhav** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#751]
Hi Team,
For a couple of days, I'm stuck with changing the volume of the output stream in real time. It's not happening. Below is the snippet of code which I'm currently using -
```cpp
bool audioProcessing(void* clientdata, float* input, float* output, int numberOfFrames, int samplerate) {
	if (prev_v != cur_v) {
		Superpowered::VolumeAdd(output, output, prev_v, cur_v, numberOfFrames);
		prev_v = cur_v;
	}
	analyzer->process(output, numberOfFrames);
	bpm = analyzer->bpm;
	return true;
}
```
Where `cur_v` is representing the current volume and `prev_v` is representing the previous volume.
Also, for future reference, how would I be able to apply any effects on the output in real time?

**Comment by ivannador** [comment]
Hello!
You are using the `output` buffer in your code, but the audio data should be in the `input` buffer.
I think using `Superpowered::VolumeAdd(input, output, prev_v, cur_v, numberOfFrames);` would work.
After that you can use `output` in the analyzer, as `VolumeAdd` will copy `input` to `output` with gain applied.

You would use effects in the same `audioProcessing` callback, calling their `process` methods with the buffer.

**Comment by GhostVaibhav** [comment]
Thanks for the prompt reply but it's not working. I hear some output but it's very distorted. I also think that it's actually applying the volume on the microphone rather than the speaker. I have a fairly simple use case to only change the volume of my end device (like my headphones, speakers, etc.) using a slider in my GUI. The value of `cur_v` is updated as and when I move the slider.

**Comment by ivannador** [comment]
There is no mic or speaker volume in this sense, input buffer contains what is coming from the input and the output will be what's played on the speaker. `VolumeAdd` means `output = output + input * gain`, so the gain will be applied on the input. If you output buffer is empty, you can use the `Volume` method, which means `output = input * gain`.
What volume values are you using?
Do you hear perfectly normal audio when just `memcpy`ing input into output without any changes?

**Comment by GhostVaibhav** [comment]
My use case is to modify the output itself. For example, a YouTube video is playing. I want to change the volume of the video playback, acting like a middle man between the video playback and the speakers. I don't want to indulge with the microphone anyhow. As for your questions, yes the sound is coming just fine when doing `memcpy`.  But the volume is not affecting anything.

**Comment by ivannador** [comment]
For that you would have to route the Youtube audio output into the `audioProcessing` callback, so that the `input` buffer contains the Youtube audio data.
Think of this as a chain of processing where the `input` is coming in and the `output` is what's going out the speaker. Anything you do in-between will affect the signal, but you have to put it in the `output` buffer. If the mic signal is in the `input` buffer, then you will modify the mic signal.

These volume values are very high, think of it as a multiplier. If you multiply it by 100.f then you won't get a correct signal, it will be clipped all over the place. 0.f-1.f range would be lowering the volume, higher than that makes it louder. 2.f would be twice the amplitude and most likely that will clip also.

**Comment by GhostVaibhav** [comment]
I'm really glad that you are interested in understanding my problem, but here YouTube is just an example. I mean I want to process all the audio coming out of the speakers.

**Comment by ivannador** [comment]
You can only modify what's in the `input` buffer. If the system output is not in the `input` buffer, you can't modify it. If it is, then the `Volume` method can change it's volume.

**Comment by ivannador** [comment]
Sorry, I'm not familiar with the WASAPI at that level. If it is possible, you could tweak the `OpenSource/SuperpoweredWASAPIAudioIO` to your needs.
