### ISSUE TITLE
Feedback Voice not working

### ISSUE THREAD

**Issue by trupen-iOS** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#753]
Superpowered version:

**I have tried to implement feedback voice with recording, previously it was working fine and now it is not working**

`
static bool audioProcessing1(void *clientdata, float *inputBuffers, float *outputBuffers, unsigned int numberOfFrames, unsigned int samplerate, uint64_t hostTime) {

    float getBuffer[numberOfFrames * 2];
    Superpowered::Interleave(inputBuffers, inputBuffers, getBuffer, numberOfFrames);

    recorder->recordInterleaved(inputBuffers, numberOfFrames);
   
    Superpowered::Volume(inputBuffers, inputBuffers, currentVoiceFeedbackVolume, currentVoiceFeedbackVolume, numberOfFrames);
    Superpowered::DeInterleave(getBuffer, outputBuffers, outputBuffers, numberOfFrames);
    return true;
}
`

**Currently the feedback voice does sounds like robotic voice and can not hear anything but recording is working, when I hear recorded voice it is proper, but feedback voice is not.**

**Comment by ivannador** [comment]
Hello!
Assuming this is an iOS audio processing callback - the contents of `inputBuffers` are already interleaved, no need to interleave them. If you remove the `Interleave` and the `DeInterleave` and replace the second parameter in Volume with `outputBuffers`, you'll get the correct output.

**Comment by trupen-iOS** [comment]
Ok Thanks I will try the same
