### ISSUE TITLE
Time stretching issue with some specific files

### ISSUE THREAD

**Issue by Polovkin** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#755]
Superpowered version: 2.6.0

**Describe the bug**
We use Superpower for our experemintal iOS app. The main function is to change the playback speed in real-time. Recently, we encountered a problem where some files, when accelerated to the end of playback, are immediately played back with artifacts, even if the speed is returned to normal.

**Steps to Reproduce**
We have tried to replicate this issue on all platforms, including other applications that use Superpower. These tracks also exhibit the same issue. To reproduce the issue, it is sufficient to take the iOS example from [Superpowered Performance IOS Example](https://github.com/superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform/tree/master/Examples_iOS/SuperpoweredPerformance) and replace the standard track with the 
[problematic one](https://polovkin.github.io/static/audio/test.mp3).

**Expected behavior**
It is expected that all tracks should play back normally

**Actual behavior**
When launching the player, the track plays normally. However, if the playback speed is changed to any value of acceleration, artifacts appear in the track until the end of playback.

**Device information**
Please list which devices have this bug.
 - Device: Iphone 11 12 13 14,ios emulator, android emulator, superpower web
 - OS: Ios 15,16. android 10-12
 - Browser: Chrome

**Additional context**
Here's an example of artifacts in the web version of Superpowered. The artifacts are the same on other platforms. Simply changing the speed to any value will cause them to appear. The track begins playing at around 20 seconds.
https://polovkin.github.io

[Problem tracks attached](https://github.com/superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform/files/11463822/problem_tracks.zip)

**Comment by balazsbanto** [comment]
Hi,

Thank you for the well descriptive ticket, we appreciate it!

I tried to reproduce the artifacts that you are mentioning with the Superpowered Performance app and the web app that you nicely created, but I was not able to. To me it seems that the time stretching effect is applied correctly.

- Could you describe maybe in more detail the artifacts that you hear?  
- What do you exactly mean by "when accelerated to the end of playback"?
- Could you provide exact steps on how to reproduce this with the Superpowered Performance App?  Something like "load test.mp3 in the app seek to x.x seconds and enable time stretching with x.x playbackRate"

Maybe you could use the `SuperpoweredRecorder` to record one of the test tracks with the applied time stretching effect on, and point out the time internal where you hear the aforementioned artifacts.

**Comment by Polovkin** [comment]
Thank you for the response!

I cut out the silence in the track (Wagner - Siegfried’s March) so that the artifacts could be heard immediately. I made some changes to the [web version](https://polovkin.github.io/) - added descriptions and added a new track. Additionally, I added a recording using SuperpoweredRecord, where the artifacts are well audible.

1. The artifacts that I hear (and my team hears) are similar to micro-interruptions in the track. The Artifacts are particularly noticeable when playing the trumpet at the beginning of the track.
2. What I meant is that if you change the playback speed just once to any value > 1, these artifacts will be present until the end of the track.
3. I trimmed the silence in the track. The steps are as follows: replace the default track.mp3 in the iOS example with the problematic one . Press play and change the playback speed to any value greater than 1. 

Please make it louder if possible, and you will definitely hear distortions

**Comment by balazsbanto** [comment]
Hello,

We investigate the issue further, and unfortunately we cannot provide a quick fix for this. The time stretcher algorithm is quite complex,  and it will take a longer time to mitigate this. We will let you know when we will have a fix for this!

Sorry for the inconvenience, and thank you for your patience!

**Comment by Polovkin** [comment]
Thank you for your response! My team and I have spent a lot of time studying the issue, but we lack sufficient experience in such algorithms. I would be very interested to know what this could be in general.

If you manage to fix it, or if you already understand that this is something that cannot be fixed, could you briefly explain in which area the problem lies? Is it in the track? In the algorithm or something else?

Thank you!

**Comment by balazsbanto** [comment]
Unfortunately I can't share implementation details. Currently the algorithm does not handle correctly long instrumental notes, which is the case with classical tracks. 

We will get back to you once we fix this issue!

**Comment by Polovkin** [comment]
Actually, we're not interest in algorithm disclosure (sorry, for misunderstanding).
Please, help us to clarify on how to avoid these 'clipping' or artifacts in the input tracks: what exact parameters and metrics provoke this issues (e.g. frequencies, pitch-rate, MIDI-library that used to make an input file, etc.)?
So, could we avoid this issue by customizing the input files?

**Comment by balazsbanto** [comment]
Unfortunately you cannot avoid this issues for now, the clipping will occur in tracks with long notes, without transients.

**Comment by ivannador** [comment]
Closing this, fix will be provided in a future release.
