### ISSUE TITLE
Decoder prepends silence when decoding compressed files

### ISSUE THREAD

**Issue by JazariMusic** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#756]
Superpowered version: 2.5.1

**Describe the bug**
The SuperpoweredDecoder prepends about 48ms of silence plus pre-ringing to compressed audio files. This creates problems when trying to time align audio files of different types. 

**Steps to Reproduce**
1. In a DAW, create an audio track that begins with an impulsive event, like a kick or snare drum hit, right at the very first sample. Export the session as both a WAV file and a compressed file, either MP3 or M4A. 
2. Write a unit test that opens each file with a SuperpoweredDecoder. Call the Decoder's decode() function to fill a buffer with the first ~2400 frames of audio from each Decoder. Print the contents of each buffer to the console. Alternatively, decode the entirety of each file and persist to disk, then compare the decoded files in a sound editor. 

**Expected behavior**
I expect the percussive event that begins the uncompressed audio file to occur at the same time point in the decoded streams of each file. Of course there will be small differences in sample values between the compressed file and the WAV file, but events should happen at the same point in time. 

**Actual behavior**
The buffer that contains decoded data from compressed file has about 24ms of silence at the beginning, followed by about 24ms of low-level pre-ringing, and then about 48ms into the buffer, I see the actual percussion event. It should occur at the beginning. 

**Device information**
 - iPhone, Mac
 - iOS, MacOS
 - Browser NA
 - Version 2.5.1 (I think it has always been this way)

**Log messages**
Please share any log messages that may be relevant

**Additional context**
This is the test I used in Xcode compare decoded streams of an MP3 file and WAV exports of the same drum loop. Update the `path` variable to point at the appropriate file location. 
<img width="1057" alt="ACTUAL" src="https://github.com/superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform/assets/857401/986d2ef9-aa53-4c9c-9f96-4b41d0875346">
<img width="1063" alt="EXPECTED" src="https://github.com/superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform/assets/857401/63dc2922-1d82-49e6-a7c1-abfd88787f50">

```
- (void)testDecoder {
    //const char *track_filename = "drum_loop_48k-mp3.mp3";
    const char *track_filename = "drum_loop_48k.wav";
    
    copy_audio_resource_to_base_dir(track_filename);
    char *path;
    VOLOCO_UTIL_STRJOIN(path, base_dir, track_filename);

    Superpowered::Decoder *decoder = new Superpowered::Decoder();
    
    int result_code = decoder->open(path);
    XCTAssert(result_code == Superpowered::Decoder::OpenSuccess);
    decoder->setPositionPrecise(0);
    
    short int buffer[20000];
    long samples_read = decoder->decodeAudio(buffer, 2400);
    
    for(int n = 0; n < 2400; n++){
        printf("%d ,", buffer[n * 2]);
    }
}
```

**Comment by ivannador** [comment]
Hey JazariMusic,

Thanks for reaching out! We are looking into the issue you are experiencing.

Stay tuned for more info!

Best regards,
Superpowered Team

**Comment by balazsbanto** [comment]
Hey,

MP3 decoders and encoders typically append silence to the beginning of audio files for a specific reason related to the way the MP3 compression algorithm works. Maybe you can check out [this blogpost](https://medium.com/vimeo-engineering-blog/a-brief-history-of-gapless-audio-and-what-you-can-do-about-it-ea9e1c343215) for more in depth understanding. 
Are you sure your DAW didn't already appended the silence at the beginning of the track when you exported it?

To to mitigate this issues, you could use the [getAudioStartFrame](https://docs.superpowered.com/reference/latest/decoder?lang=cpp#:~:text=internal%20decoder%20error.-,getAudioStartFrame,METHOD,-Detects%20silence%20at) method of the `Decoder` class to detect the silence at the beginning, and synchronized based on that.

Hope this helps,
Superpowered Team

**Comment by JazariMusic** [comment]
Thanks for the explanation and the link to the article. I can come up with a workaround.
