### ISSUE TITLE
Running SuperpoweredPlayer on Samsung s8 got glitch from time to time

### ISSUE THREAD

**Issue by richardzhang0301** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#760]
Launch the original SuperpoweredPlayer demo from the latest commit from the master branch:
https://github.com/superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform/tree/f57e1a9472f4578ee0beb796902fb5493ef49a27

To Samsung s8

Got glitch (small popping) from time to time. (roughly every 10s - 30s once), feels like a perfromance issue, but hte CPU usage seems normal:
  PID USER         PR  NI VIRT  RES  SHR S[%CPU] %MEM     TIME+ ARGS            
 4742 oem_5004     20   0 4.3G 138M  78M S 28.0   4.1   0:11.15 com.samsung.ips+
  701 audioserver  20   0 125M 4.7M 3.0M S 22.6   0.1  14:54.64 audioserver
  653 audioserver  20   0  53M 3.2M 1.7M S 17.0   0.0   5:16.31 android.hardwar+
 6783 u0_a212      10 -10 3.8G 140M 110M S 11.6   4.1   0:09.59 com.superpowere+
 1514 system       18  -2 5.0G 254M 157M S  8.3   7.5 303:18.18 system_server
 6067 shell        20   0  23M 2.5M 1.3M S  6.0   0.0   0:04.96 adbd --root_sec+
 7255 shell        20   0  15M 5.3M 3.9M R  3.3   0.1   0:00.40 top
 3920 root         20   0    0    0    0 S  2.0   0.0   0:02.77 [kworker/u16:0]
 5930 root         20   0    0    0    0 S  1.3   0.0   0:02.19 [kworker/u16:16]
 4096 root         20   0    0    0    0 S  1.3   0.0   0:03.10 [kworker/u16:6]
28791 u0_a32       20   0 4.0G 178M 152M S  1.3   5.3   0:18.94 com.google.andr+
  957 wifi         20   0  20M 2.9M 2.7M S  1.3   0.0   2:23.10 wificond
 1235 root         20   0    0    0    0 S  1.0   0.0   0:04.36 [kworker/u16:8]
  567 logd         30  10  37M  16M 2.5M S  1.0   0.4  10:30.54 logd
  477 root         20   0    0    0    0 D  1.0   0.0   8:48.77 [msm-core:sampl+
 3503 root         20   0    0    0    0 S  0.6   0.0   0:00.17 [kworker/2:3]
25308 root          0 -20    0    0    0 S  0.6   0.0   0:12.27 [kworker/u17:1]
  665 system       RT   0 102M 2.7M 2.7M S  0.6   0.0   3:32.39 android.hardwar+
25764 root         20   0    0    0    0 S  0.3   0.0   0:03.78 [kworker/0:1]
25243 u0_a32       20   0 4.0G 195M 145M S  0.3   5.8   1:14.71 com.google.andr+

**Comment by balazsbanto** [comment]
Hey,

Thanks for reaching out! 

Please try increasing the buffer size and see if it helps. You can increase the buffer size by two in the `MainActivity.java` like this:
`NativeInit(samplerate, buffersize * 2, getCacheDir().getAbsolutePath()); // start audio engine
`
You can try even bigger sizes if the glitches persists.

Hope this helps,
Balazs

**Comment by richardzhang0301** [comment]
Thanks for the feedback. Tried increasing the buffer size, the issue still exists.
It seems that the issue is more likely to happen within few seconds after the screen is turned on or off. 
It is audiable both from the built-in speaker or 3.5mm output.
Here is a piece of recording from Samsung s8's 3.5mm output, the pop replicated at about 28.5s.
https://dcezofapvlc4i.cloudfront.net/pop.mp3

**Comment by gaborszanto** [comment]
Did you set the CPU mode to this? https://github.com/superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform/blob/f57e1a9472f4578ee0beb796902fb5493ef49a27/Examples_Android/SuperpoweredPlayer/app/src/main/cpp/PlayerExample.cpp#L105

**Comment by richardzhang0301** [comment]
Yep, in PlayerExample.cpp, this line exists:
extern "C" JNIEXPORT void
Java_com_superpowered_playerexample_MainActivity_TogglePlayback(JNIEnv * __unused env, jobject __unused obj) {
    player->togglePlayback();
    Superpowered::CPU::setSustainedPerformanceMode(player->isPlaying()); // prevent dropouts
}
