### ISSUE TITLE
Superpowered 2 Decoder::getAudioStartFrame() behaviour changed since Superpowered 1

### ISSUE THREAD

**Issue by AliMunchkin** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#764]
Superpowered version 2.5.1:

**Describe the bug**
Superpowered 2 `Decoder::getAudioStartFrame()` behaviour seems to have changed since Superpowered 1 `Decoder::getAudioStartSample()`.

Comparing a default call (with `thresholdDb = 0`), Superpowered 2 often returns larger detected silence than Superpowered 1.

However, if I provide `thresholdDb = -96` to Superpowered 2, I appear to get identical behaviour to a default call in Superpowered 1. This appears to fix the issue for us so far.

**Steps to Reproduce**
Compare calls to Superpowered 2 getAudioStartFrame() with Superpowered 1 getAudioStartSample().

**Expected behavior**
Identical behaviour between Superpowered 1 and 2 APIs.

**Actual behavior**
Different behaviour between Superpowered 1 and 2 APIs, unless an explicit silence threshold of -96dB is provided.

**Device information**
All devices tested with.

**Comment by AliMunchkin** [comment]
I forgot to mention that this issue only occurs with mp3 files which begin with a low noise level, in our case a section of background noise before the main vocal starts.

I'm happy to provide an example mp3 privately but I am not able to post it on here publicly.

**Comment by ivannador** [comment]
Hey @AliMunchkin,

Thanks for reaching out! We are looking into the issue, stay tuned for more info!

Best regards,
Superpowered Team

**Comment by balazsbanto** [comment]
Hi @AliMunchkin ,

We continuously try to improve our product with every new release, so there might be some minor differences between the results provided in the newer versions, hopefully in the right direction. 

There were indeed some changes in the `getAudioStartFrame` implementation. In the default case when you don't provide any ` thresholdDb ` the newer version is probably a bit less sensitive than the older version you are using. The older version was extremely sensitive in the default case and could detect noise as an audio "start," which might not be desirable.

Did you compare the results between the two mentioned versions? Which gave you more accurate results in your case?

Best,
Superpowered Team

**Comment by AliMunchkin** [comment]
@balazsbanto Thanks for the response.

We are experiencing an issue which has brought my attention back to this task.

As explained above, I was under the impression that using a threshold of -96dB with SP v2 `Decoder::getAudioStartFrame()` achieved identical behaviour to the SP v1 `Decoder::getAudioStartSample()` method.

However, we think we have recently experienced some use cases where the behaviour is different.

Our app uses multitrack stems, some of which start with long sections of background noise. For instance, a vocal stem where the vocal doesn’t come in immediately. With SP v1, the silence detection worked perfectly for us. But with the new implementation in SP v2, it’s no longer possible to achieve identical behaviour, so our app is affected.

#“The older version was extremely sensitive in the default case and could detect noise as an audio "start," which might not be desirable.”
I have a feeling, for our use case, we actually need it to detect noise as an audio start.
