### ISSUE TITLE
Bitcrusher bug

### ISSUE THREAD

**Issue by renezuidhof** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#767]
Superpowered version: 2.6.2 (commit d67e895ca31e9d42fd41ba56e38ab970da243cab)

**Describe the bug**
When using the bitcrusher effect, the effect stops working after enabling it for a second time.

**Steps to Reproduce**
I've used the SuperpoweredEffect project. Here I only changed the EffectExample.cpp file (
[EffectExample.txt](https://github.com/superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform/files/13329774/EffectExample.txt))

The changes I made:
1. Reverb is replaced with Bitcrusher.
2. `SuperpoweredAndroidAudioIO` and the bitcrusher is only initialized once.
3. When pressing the start/stop button the bitcrushers 'enabled' property is toggled. Instead of it being created and deleted.

**Expected behavior**
I expect the bitcrusher to be applied to the audio when pressing 'start' and be removed from the audio when pressing 'stop'.

**Actual behavior**
The first time pressing 'start' it works fine. The audio is heard with the effect applied to it. Also when pressing 'stop' the effect is removed. Now when pressing 'start' again I don't hear anything anymore.

**Device information**
Please list which devices have this bug.
 - Device: [Xiaomi Poco F2 Pro]
 - OS: Android 12

**Additional context**
In my own app once this problem occurs, I can change `frequency` and the problem is gone. Also, when the bitcrusher is set to another value (not the default of 8000) the effect is still applied but with wrong values once the effect is enabled for a second time.

**Comment by balazsbanto** [comment]
Hey @renezuidhof,

Thank you for the detailed description, we are looking into your issue!

Balazs,
Superpowered Team

**Comment by ivannador** [comment]
Hey @renezuidhof,

We can confirm that the Bitcrusher is indeed working incorrectly in this case. **The fix for this will be in our next release, coming soon.**
As a workaround until then, you could set an arbitrary frequency (or bits) value before the process call in your audioProcessing callback, just after enabling the effect. Then at the next process call set your desired value. The key is that the frequency value at enabling must differ from the value after that.

Best regards,
Ivan
Superpowered Team

**Comment by gaborszanto** [comment]
I see this issue is completed, but I don't see the fix in the source code... Where is it fixed?

**Comment by renezuidhof** [comment]
Thanks! I noticed that it needs two process calls indeed. For my app this would be quite a cumbersome workaround so I'll wait for the fix :)
