### ISSUE TITLE
Why is FLAC not supported?

### ISSUE THREAD

**Issue by flagoworld** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#770]
Just wondering.

**Comment by balazsbanto** [comment]
We currently do not have support for FLAC, but we are looking into adding this capability in a future update.

**Comment by anytuneapp** [comment]
We have had about a dozen customer request to support FLAC in the last year.   It would be a welcome addition for Android users.
