### ISSUE TITLE
Track end cut with Reverb (Echo)

### ISSUE THREAD

**Issue by drusak** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#775]
Hi

I have a question about extra end duration when applying Reverb (Echo) on input.
Assume the audio has duration 1000ms, I would like to apply Reverb (Echo) to it and save as wav. The problem is that these FX added extra samples (because of the delay) and thus output cut at end, so the duration is still 1000ms, but should be a bit bigger.
How can We implement that, e.g. to know extra time according to FX applied, or it should return false on FX::process call?

Currently it returned true on process even if I put NULL on input when player is not processing data
```
bool processed = player->processStereo(playbackBuffer, false, numberOfSamples, 1.f);
bool effectProcessed = effect->process(processed ? playbackBuffer : NULL, playbackBuffer, numberOfSamples);
```
effectProcessed is always true event if processed is false

Any help with this issue would be appreciated,
Thanks

**Comment by ivannador** [comment]
Hello,

The return value of process indicates that "the effect is included in the chain", i.e. it is enabled and processing. It won't indicate if the reverb tail ended.
I recommend disabling the effect when `processed` is false, then the `effectProcessed` will become false after the tail ended.
You can then stop the recording based on `effectProcessed`.

Hope this helps.

**Comment by drusak** [comment]
Thank you @ivannador, I will try this approach

**Comment by drusak** [comment]
Looks like it's working now and return false for FX when finished processing.
Thanks @ivannador

**Comment by ivannador** [comment]
Glad it got solved!
