### ISSUE TITLE
Problem when playing multiple files simultaneously

### ISSUE THREAD

**Issue by gugasv** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#780]
Superpowered version: latest

**Describe the bug**
Our app uses Superpowered to play multiple files simultaneously. Recently, we tested the app on some Google Pixel devices (Google Pixel 8 Pro and Google Pixel Fold), and sometimes, our player couldn't play the song (+1 files). We couldn't identify the problem yet because it doesn't occur constantly, so we think that it could be a problem when trying to open the files or maybe a concurrency problem. We currently use the library with the AAudio disabled because we face other problems when enabling it. 

We follow this flow to play multiple tracks simultaneously:

**Prepare**

1. Initialize the Superpowered when opening the app.
`Superpowered::Initialize(license_key)`
2. When the user opens a song, we create an instance of `SuperpoweredAndroidAudioIO`, created only once per session, so when the user skips to the next song we will reuse it.
3. Then, we create an instance of `AdvancedAudioPlayer` for each file/track and open the files. We also create a couple of instances of `StereoMixer`. Those players and mixers are stored on an auxiliary vector of tracks and mixers.

```cpp
void AppMixer::preparePlayer(bool enableInput) {
    if (audioIO != nullptr) {
        destroyAudioIO();
    }
    audioIO = new SuperpoweredAndroidAudioIO(
            (int) audioSampleRate,
            int(audioBufferSize),
            enableInput,
            true,
            enableInput ? recordingProcessing : audioProcessing,
            this,
            -1,
            SL_ANDROID_STREAM_MEDIA
    );
}
void AppMixer::prepare(string paths[], int size, float initialVolume) {
    if (audioIO == nullptr) {
        preparePlayer(false);
    }

    clearAuxVectors();

    // Make sure paths are sorted accordingly to the Mixer UI [ML]
    for (int i = 0; i < size; ++i) {
        auto player = new AdvancedAudioPlayer(audioSampleRate, 0);
        player->open(&paths[i][0]);
        auxPlayers.push_back(player);
        auxVolumes.push_back(initialVolume);
        // Here we are adding L/R for each player [ML]
        auxBalances.push_back(1.0);
        auxBalances.push_back(1.0);
    }

    setupMixers();
}
void AppMixer::setupMixers() {
    // Each mixer will have at least 3 players [ML]
    for (int i = 0; i <= auxPlayers.size() / PLAYERS_PER_MIXER; ++i) {
        auxMixers.push_back(new StereoMixer());
    }
}
```

**Process callback**

1. When the user plays the song, we call for each `AdvancedAudioPlayer` the `player→playSynchronizedToPosition()`.
    1. In the audio process callback, we verify if all the tracks have been loaded (`AdvancedAudioPlayer::*PlayerEvent_Opened*`). If so, we swap those players and mixers from the auxiliary vectors to the current one.
    2. If the files were not loaded, we verify and update our flag. `player→getLatestEvent()`
    3. If all files are loaded in the first loop, we set the player sync mode to `SyncMode_TempoAndBeat` and set the position to the beginning of the song.
    4. In the following loop, we sync the BPM of all the tracks based on the first track.
    5. Then, we process each track and mixer.
2. When the user clicks on pause, we pause all the tracks and update our pause flag, to skip the tracks and mixers process.

As described before, we think the problem could be when opening the file or a concurrency problem. Do you have suggestions on how to solve and/or improve the code?

We also aim to allow our users to play a song and record at the same time. We know that AAudio decreases latency, giving a better experience, but when we enable it, we have some concurrency problems, like running the process loop again while we are swapping the vectors.

In few words we need your support to:

- Solve the problem with the song no playing
- Solve the concurrency problem when AAudio is turned on

**Device information**
Please list which devices have this bug.
 - Device: Google Pixel 8 Pro and Google Pixel Fold
 - OS: Android 14

**Comment by balazsbanto** [comment]
Hey, let's continue our conversation here instead of on Zendesk.

 
I reviewed the provided code snippet but didn't spot any clear issues. To help us diagnose the problem further, could you please try to reproduce the issue using one of our public example apps? For instance, this example loads two audio files and mixes them together, and it also supports `AAudio` without issues:
 
https://github.com/superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform/tree/master/Examples_Android/SuperpoweredCrossExample
 
If you can replicate the issue in our sample app with minimal changes, it would be very helpful for us to pinpoint the problem.
 
Regards,
Balazs

**Comment by ivannador** [comment]
@gugasv Any updates from your side?
