### ISSUE TITLE
16 KB Support for Android 15 

### ISSUE THREAD

**Issue by HitRoxxx** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#785]
Hey there! Android 15 is rolling out a new 16 KB page size development mode and wants new apps to use it. It’d be super helpful if your SuperpoweredSDK supported this mode too, so developers don’t need to make extra efforts and updates. You can get more info [here](https://developer.android.com/guide/practices/page-sizes).
Also, is a version bump to Android 26 necessary for Superpowered SDK 2.6.8, or can we continue using Android 24 like with SDK 2.6.6?
Thanks!

**Comment by ivannador** [comment]
Hey @HitRoxxx 

Thanks for bringing this up!
We'll definitely look into recompiling Superpowered for 16 KB page size in the upcoming releases.

**Comment by HitRoxxx** [comment]
Also, is a version bump to Android 26 necessary for Superpowered SDK 2.6.8, or can we continue using Android 24 like with SDK 2.6.6 ?

**Comment by ivannador** [comment]
Yes, version 2.6.7 bumped the minSdkVersion to 26.

**Comment by ivannador** [comment]
Hey @HitRoxxx 

The next release will be built with 16 KB page size support. Expect it to drop in a week.

**Comment by ivannador** [comment]
The new release is out which is built with 16KB page size support. Closing this issue.
