### ISSUE TITLE
AndroidUSBAudio crashes

### ISSUE THREAD

**Issue by renezuidhof** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#789]
Superpowered version: 2.6.8 (commit: caf2102570ba86997cced5e47a6a9090031c166a)

**Describe the bug**
I can't get the `SuperpoweredUSBExample` to work. It runs, it detects the connected USB device and I can select different options regarding the in- and output. but nothing happens when I click `Start Loopback` or `Start Latency Measurement` or `Start sine wave`. If I leave it running it will most of the time crash randomly within a minute. If I press `stop` it will most of the time crash directly.

**Steps to Reproduce**
Run the `complexusb` or `simpleusb` example code. Connect a USB device and start and stop the loopback.

**Expected behavior**
Hearing the mic input through the speakers.

**Actual behavior**
Nothing happens. I added some logging to the `audioProcessing` function in `complexusb.cpp` and I can see that it is never called. It will be called once at the moment I press `stop` after which it will most of the time crash.

I also added logging after the call to `Superpowered::AndroidUSBAudio::startIO`, so I'm sure this is called.

**Device information**
 - Device: Google Pixel 8a and Xiaomi Poco F2 Pro (didn't try on any other devices)
 - OS: Android 14 for the Pixel

Tested with two USB devices: Focusrite 2i2 and a USB-C to 3.5mm jack. Both devices give the same result.

**Log messages**
I attached the Logcat results filtered on `com.superpowered.complexusb`. I added the `(TESTTEST)` logs myself.
[USBComplex.txt](https://github.com/user-attachments/files/17395206/USBComplex.txt)

**Additional context**
I always thought I had USB working in my app. At some point I checked the Superpowered issues and noticed `https://github.com/superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform/pull/737`. Apparently the USB code in my app never really worked (I really thought it did).

So I edited my code according to the changes in that commit and I can't get the USB connection to work, it just crashes. Therefor I checked to see if I could get the example projects to work. That's how I ended up here.

**Comment by ivannador** [comment]
Hey @renezuidhof,

The new Superpowered release is out, which contains the fix for this issue. Please test and report back.

**Comment by renezuidhof** [comment]
I just tested it with the SuperpoweredUSBExample and it seems to work great! Thanks for the fix

**Comment by renezuidhof** [comment]
I think the example projects needs a little change. When using it like it is the IDE gives me a warning (Mutable implicit PendingIntent will throw an exception, follow either of these recommendations: for an existing PendingIntent use FLAG_NO_CREATE and for a new PendingIntent either make it immutable or make the Intent within explicit) when using this:
```
val permissionIntent = PendingIntent.getBroadcast(context, 0, Intent(constants.ACTION_USB_PERMISSION), PendingIntent.FLAG_MUTABLE)
```

Changing it to this works and does not give me the warning.
```
val intent = Intent(constants.ACTION_USB_PERMISSION)
intent.putExtra(UsbManager.EXTRA_PERMISSION_GRANTED, false)
intent.setPackage(context.packageName)

val permissionIntent = PendingIntent.getBroadcast(context, 0, intent, PendingIntent.FLAG_MUTABLE)
```

**Comment by ivannador** [comment]
Hey @renezuidhof, thanks for pointing that out. Feel free to open a PR for it if you already have to change.
